### ISSUE TITLE
Support Markdown text/images in Tips

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#10]
Render all text in the Tips page with MarkdownElement, and the Tips content should be a rich text editor that converts to Markdown formatted text, including uploading and converting images to inline base64. (Ideally it could also support embedded html, just like actual Markdown text, but let me know if this is not feasible.)

@sarithapillai8 Please investigate and let me know if you have any questions?

**Comment by sijugeorge-zco** [comment]
@avaidyam 
We have added Markdown Element to the contents on the Tips Details page. 
Do we need to add the Markdown Element to the title on the Tips Details page?
We are using this https://github.com/remarkjs/react-markdown
Please see this [https://commonmark.org/help/](https://commonmark.org/help/) to format text

**Comment by avaidyam** [comment]
No, it should only be for the contents of the tip. Great!
