### ISSUE TITLE
Use a locale map for translation short-codes instead of hardcoding locale names

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#102]
Right now the locale short-codes `en-US`, `hi-IN`, and `es-ES` are hard-coded in the `LAMP-dashboard` source. Please add this file (`locale_map.json`) to instead lookup short-codes to names (i.e. `hi-IN` → `Hindi` or `es-ES` → `Spanish (Spain)`).

[locale_map.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5858691/locale_map.json.txt)

**Comment by sijugeorge-zco** [comment]
@avaidyam 
On the Login page language dropdown, all the languages will be loaded from the JSON file you provided (as attached image).
The dropdown value will be displayed in the format from the JSON _native (english)_, Eg: _Español (Spanish)_
We have changed the folders from en_US to en-US , hi_IN to hi-IN etc. 
Also for '_javascript-time-ago_' we have added switch conditions to support languages.
![screencapture-localhost-3000-1611570860350](https://user-images.githubusercontent.com/63731044/105695737-6dc6ae80-5f28-11eb-8f5b-3134e69849ef.png)

**Comment by avaidyam** [comment]
@sijugeorge-zco Wow, this is fantastic! Two minor points: 
1. If the `native` string `==` the `english` string, then please hide the `english` string to reduce the redundancy. (i.e. `English (English)` → `English`).
2. Dynamically filter this list to only show translations where they are available. Right now, we only support `en-US`, `es-ES`, and `hi-IN`.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
For DBT, i've created separated files for languages and defined translations and generated build. After that the bas64 of that build is included on the Lamp-Dashboard and while running i'm getting the below error

**Comment by sijugeorge-zco** [comment]
@avaidyam 
For DBT, i've created separated files for languages and defined translations and generated build. After that the bas64 of that build is included on the Lamp-Dashboard and while running i'm getting the below error:
_Access to fetch at 'http://localhost:3000/dbt_locales/en/translation.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._ 

Due to this error , language translation are not loaded now. 
Earlier we were loading all the languages in a single file which was working.

**Comment by avaidyam** [comment]
For the DBT and other activities, it may be best to keep it all in one integrated file then and avoid any remote loading.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
OK Sure. For the DBT and Games, i'll keep all the translations on the single file as it was before.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
When we changed language of browser(chrome) to hindi it is showing as **hi** , so as you suggested if we give only **hi-IN** it won't load default. We need to add conditions like **["hi", "hi-IN", "hi-in"]**  that should be hardcoded also same case for English having **en** , **en-US** etc.
Please suggest.

**Comment by avaidyam** [comment]
For automatic detection, take the `"hi"` and match it to the first possible language code (i.e. `matched_codes = language_codes.filter(code => code.startsWith(detectedLanguage))` - if the array has length `0`, then default to `en-US`, otherwise use `matched_codes[0]`).

**Comment by sijugeorge-zco** [comment]
@avaidyam 
But on dropdown we are setting values like "en-US" not "en" so it will not set as selected default.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
But on dropdown we are setting values like "**en-US**" not "**en**" so it will not set as selected default.
Either we need to change dropdown value of English from "**en-US**" to "**en**" and same to others(after checking)

**Comment by sijugeorge-zco** [comment]
@avaidyam 
When we made **Hindi** the default language on browser(Chrome), the navigator.language is returning only **hi** not **hi-IN**, so it will only select default **en-US** on our LAMP Login language dropdown. 
Also we could find only one hindi language on the language settings list(Settings>>Advanced>>Language) when we checked on Chrome.
Do we need to change anything, please confirm.

**Comment by avaidyam** [comment]
@sijugeorge-zco Please use the logic I specified in my comment above for this. It should take the `hi` and match it to the first relevant locale code, `hi-IN`. Otherwise there is nothing special to be done for this functionality.
