### ISSUE TITLE
On dashboard, the bar of "patients/activities" across the bottom blocks the last participant on the list unless you expand your screen

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#103]
> **Collaborator**: When I'm on dashboard and the bar of "patients/activities" is across the bottom, it blocks the last participant on my list. I can't scroll down and click on them because of the bar. If I widen my screen enough it's fine, but I thought it was worth submitting as a bug because it doesn't seem like this should be happening. I don't know if you can tell that well from the photo, but you can kind of see the top of the yellow indicator bubble.
> ![image](https://user-images.githubusercontent.com/1361003/105995544-1edb5f00-6077-11eb-812a-c661175caf7c.png)

**Comment by sarithapillai8** [comment]
![scroll](https://user-images.githubusercontent.com/63710347/106771790-5e9cda80-6665-11eb-8e88-c1d2b7ab5eee.png)


We are not able to find the issue.

**Comment by avaidyam** [comment]
@sarithapillai8 Thanks for the screenshot confirmation. Can we presume that migrating away from `material-table` should resolve issues like this and related scrolling/visibility issues as well?

**Comment by sarithapillai8** [comment]
@avaidyam 
Yes. We will be showing the list with pagination, so hopefully those issues will be resolved.
