### ISSUE TITLE
Show a placeholder if no activities are provided for a tab

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#11]
Instead of a blank Manage tab, for example, show a message "There are no Manage activities available." with a gray "error_outline" material icon.

**Comment by avaidyam** [comment]
@sarithapillai8 I can’t seem to see this in the staging yet - has it been implemented, or do we need to update the staging environment to check this out?

**Comment by sarithapillai8** [comment]
@avaidyam 
This update is already in staging. Could you please check after clearing cache? I updated the staging with command and checked.
