### ISSUE TITLE
CouchDB to MongoDB conversion  in repositories

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#110]
The repositories should be tweaked to handle mongo db too.

The Mongoose package will be used for database operations in mongo dB.
An env variable called db_driver will be used to identify the db. It will checked and fetch data from the particular db. This will be done in the repositories.
eg:
If(process.env.db_driver===couch){
C/R/U/D on couchdb
}else{
C/R/U/D on mongodb
}

**Comment by avaidyam** [comment]
@Linoy339 Can you more specifically outline the changes to be made? Thanks!

**Comment by Linoy339** [comment]
@avaidyam . We have completed testing and went well with functionality .But, we faced some memory leak issue. We will be fixing it and pushing it on Monday.

**Comment by Linoy339** [comment]
@avaidyam . Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/54](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/54)

**Comment by Linoy339** [comment]
@avaidyam .Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/55](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/55)

**Comment by avaidyam** [comment]
Thanks @Linoy339 - could you close the prior PR? My team will review and set up the current PR and merge it quickly.

**Comment by Linoy339** [comment]
@avaidyam . Its done
