### ISSUE TITLE
Lamp API optimisation 

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#111]
New apis  to be implemented :
1)While participant list gets loaded:
Researcher_lookup_participants: This will be a new api where we fetch researcher settings(tags),study, participants list with participant settings(tags) based on study, sensor_event, activity_event. This api will be designed to accept a limit of maximum 100(which means 100 or less than 100 participants will be fetched at  a time) and if limit is given as input to this api, it should not exceed 100. If so, default pagination would be used. The response format almost looks like:
{
researcher_id: "a",
researcher_settings:[..],
studies:[...],
activity_event:[...],
sensor_event:[..],
participants:{ [P1]:{},[P2]:{},[P3]:{} }

}

2)While activity list gets loaded:
Researcher_lookup_activity:This will be a new api where we fetch activities together with activity_spec. This api will be designed to accept a limit of maximum 100(which means 100 or less than 100 activities will be fetched at  a time) and if limit is given as input to this api, it should not exceed 100. If so, default pagination would be used. 
There would be new functions to be implemented in corresponding repositories and the existing repository functions won't be changed for these. We will do it in both couch db and mongo db.

This is the present plan. We will update here if any addition/changes are there

**Comment by avaidyam** [comment]
@Linoy339 Can you more specifically outline the changes to be made? Thanks!

**Comment by Linoy339** [comment]
@aditya. As per the discussion, Can you please check this and merge in staging environment to test?
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/61](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/61)

**Comment by avaidyam** [comment]
This item appears to be completed already, so closing this issue now.
