### ISSUE TITLE
Application is slow to load pages and possible missing attachment API is blocking the request

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#113]
Some of the requests takes about 12 - 16 seconds to load data and view the page content from mindLAMP dashboard, while looking at the browser network log most of the time they are waiting for attachment API requests. I have attached screenshots, network logs and API Server logs.

We increased the RAM size in our CentOS server to 8 GB and 4 CPUs, we are still noticing mindLAMP dashboard application is slow in response to view the data.

I am accessing the mindLAMP app from within corporate network using the actual server 
[Report_Issue.pdf](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933221/Report_Issue.pdf)
[_lamp_server.1.hi3iax1xeg3f956dtls74pl33_logs (1).txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933223/_lamp_server.1.hi3iax1xeg3f956dtls74pl33_logs.1.txt)

name as the domain name in the mindLAMP dashboard using Chrome Browser. I have high performance computer with good network speed.

Based on recommendation from Aditya, reporting as an issue. Please find the attachment of logs.

**Comment by avaidyam** [comment]
@jeydude From looking at an excerpt of the logs, it seems like there was a brief hiccup of ~10 seconds (exactly) that caused response time to slip. 
```
GET /researcher 304 - 17.188 ms
GET /researcher 304 - 10010.332 ms
GET /researcher/3cxja7qyss87e59egqp5/study 304 - 12901.561 ms
GET /participant/U9224035406/sensor_event?origin=lamp.analytics 304 - 12479.337 ms
PUT /type/3cxja7qyss87e59egqp5/attachment/lamp.selectedStudies/me 200 - 12916.575 ms
GET /type/3cxja7qyss87e59egqp5/attachment/lamp.selectedStudies 404 - 12930.377 ms
GET /researcher/3cxja7qyss87e59egqp5/study 304 - 19.454 ms
GET /type/U9224035406/attachment/lamp.messaging 404 - 12524.528 ms
```

Could you also attach logs from the CouchDB database and double check your firewall settings again? The API Server is not supposed to send `HTTP 304` responses, so I wonder if certain HTTP headers are being ignored/skipped by your firewall.

**Comment by jeydude** [comment]
Please find the couchdb log
[_lamp_database.1.joxd5ctj5oxzl6nvt0zu3kx2a_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933392/_lamp_database.1.joxd5ctj5oxzl6nvt0zu3kx2a_logs.txt)

**Comment by avaidyam** [comment]
Could you share a combination of the logs from both the server and database during a time frame in which you test the dashboard to load the patient data? Also, is there a load balancer or proxy (i.e. nginx) in front of the API Server?

**Comment by jeydude** [comment]
We are using traefik.

I just tested it, I have attached API server log, CouchDB log, cache log and traefik log with my latest log.
[_lamp_cache.1.zedkpk6c1su3j8u733vzr6d64_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933454/_lamp_cache.1.zedkpk6c1su3j8u733vzr6d64_logs.txt)
[_router_traefik.1.pbjmuxel55xqkg1a0gaa3wc6q_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933455/_router_traefik.1.pbjmuxel55xqkg1a0gaa3wc6q_logs.txt)
[_lamp_database.1.joxd5ctj5oxzl6nvt0zu3kx2a_logs (1).txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933456/_lamp_database.1.joxd5ctj5oxzl6nvt0zu3kx2a_logs.1.txt)
[_lamp_server.1.hi3iax1xeg3f956dtls74pl33_logs (2).txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5933457/_lamp_server.1.hi3iax1xeg3f956dtls74pl33_logs.2.txt)

**Comment by avaidyam** [comment]
Just to clarify, which version of the server image are you using? (Specific tag or the SHA of the docker image would be helpful!)

**Comment by jeydude** [comment]
Here is the yaml file I am using for mindLAMP Stack

version: '3.7'
services:
  server:
    image: bidmcdigitalpsychiatry/lamp-server:2020
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    environment:
      HTTPS: 'off'
      ROOT_KEY: '<ROOT KEY>'
      CDB: 'http://admin:<PASSWORD>@database:5984/'
      PUSH_API_GATEWAY: 'https://app-gateway.lamp.digital/'
      PUSH_API_KEY: '<PUSH KEY>'
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      labels:
         traefik.enable: 'true'
         traefik.http.routers.lamp_server.entryPoints: 'websecure'
         traefik.http.routers.lamp_server.rule: 'Host(`<HOST NAME>`)'
         traefik.http.routers.lamp_server.tls.certresolver: 'default'
         traefik.http.services.lamp_server.loadbalancer.server.port: 3000
      placement:
        constraints:
          - node.role == manager 
  database:
    image: mlpcouchdb
    healthcheck:
      test: curl --fail --silent http://localhost:5984/_up || exit 1
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: '<PASSWORD>'
    volumes:
      - /apps/mindLAMP/data/couchdb:/opt/couchdb/data
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
    ports:
    - "4369:4369/tcp"
    - "5984:5984/tcp"
    - "9100:9100/tcp"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lamp_database.entryPoints: 'websecure'
      traefik.http.routers.lamp_database.rule: 'Host(`<HOST NAME>`)'
      traefik.http.routers.lamp_database.tls.certresolver: 'default'
      traefik.http.services.lamp_database.loadbalancer.server.port: 5984
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
    
    Here is the screenshot of the design documents from activity database
    
![image](https://user-images.githubusercontent.com/841011/107058360-21863480-679a-11eb-8925-3f43f43caf03.png)

**Comment by avaidyam** [comment]
@jeydude Could you insert the following design document into the `activity` database using the CouchDB admin UI? 
```json
{
	"_id": "_design/id-timestamp-index",
	"language": "query",
	"views": {
		"id-timestamp": {
			"map": {
				"fields": {
					"_id": "asc",
					"timestamp": "asc"
				},
				"partial_filter_selector": {}
			},
			"reduce": "_count",
			"options": {
				"def": {
					"fields": [
						"_id",
						"timestamp"
					]
				}
			}
		}
	}
}
```

Furthermore, please change the Docker image reference `bidmcdigitalpsychiatry/lamp-server:2020` to `bidmcdigitalpsychiatry/lamp-server:2021`. Then please re-run the test and share logs/timings.

**Comment by jeydude** [comment]
Thanks for the latest image reference. I have updated to bidmcdigitalpsychiatry/lamp-server:2021.
Redeployed the lamp stack. I have inserted the activity design document into couchdb using admin UI.

Please find the attached logs files.
[_lamp_database.1.mnuxp88gzctuw8mxla3nwszyf_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5935039/_lamp_database.1.mnuxp88gzctuw8mxla3nwszyf_logs.txt)
[_lamp_server.1.wc56fji6lvcuffxeoxwfoygpq_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5935040/_lamp_server.1.wc56fji6lvcuffxeoxwfoygpq_logs.txt)

Here are the couchdb databases design documents.

![image](https://user-images.githubusercontent.com/841011/107084092-3247a200-67bc-11eb-9197-cc012cba8cee.png)

![image](https://user-images.githubusercontent.com/841011/107084079-2cea5780-67bc-11eb-9e1f-dea48be23b7b.png)

![image](https://user-images.githubusercontent.com/841011/107084059-278d0d00-67bc-11eb-95b8-274e2299567b.png)

![image](https://user-images.githubusercontent.com/841011/107084049-22c85900-67bc-11eb-8927-278fbc4e5680.png)

![image](https://user-images.githubusercontent.com/841011/107084036-1d6b0e80-67bc-11eb-8d96-5242f76d7216.png)

![image](https://user-images.githubusercontent.com/841011/107084004-16dc9700-67bc-11eb-8946-9c50d7cd5f39.png)

![image](https://user-images.githubusercontent.com/841011/107083987-117f4c80-67bc-11eb-92ae-aece1a2edff4.png)

![image](https://user-images.githubusercontent.com/841011/107083974-0af0d500-67bc-11eb-8bca-9984dab95e0f.png)

Please let me know if you need anything else. Thanks!

**Comment by avaidyam** [comment]
@jeydude Thanks so much - this is a good amount of information and our dev team (@Linoy339) can investigate it further. It seems like there's a 10 second arbitrary slow-down somewhere between CouchDB and the API Server.

**Comment by jeydude** [comment]
I will have to update my production server with new API server reference and new activity design document. Please let me know if anything is missing with design documents. I can insert them. Thanks!
