### ISSUE TITLE
App must be responsible for scheduling the notifications If there is no network access.

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#115]
Get the schedules from Activity API, and scheduling local notifications.
- Call Activity API daily and get the schedules. Remove all scheduled local notifications and schedule again.

**Comment by amaljofyzco** [comment]
Hi Aditya,

In Android, if we need to do the local scheduling of Activity, the logic what i am planning is different from that of iOS.

Problem in android is, in notification class we can't directly specify the date for scheduling. So the only possible way is to **create a Room Dao for storing the Activity details** and by using the **os Alarm Manager** feature for getting the corresponding trigger using the **Broadcast Receiver**.

Once a **Broadcast Receiver** is fired, we need to cross check with the DB entry to fetch the details of the particular schedule and throw a notification.

Another issue is Android support notification is as Int Datatype. (Jijo already conveyed it).

I am also expecting more complexity in handling local and remote notifications. 

I am planning to do with above logic in andorid, if you have any suggections please we can discuss on that also.

Thanks Amal

**Comment by avaidyam** [comment]
@jijopulikkottil 

> we couldn't find a way to schedule local notification using cron string. We can parse the Activity API response and can schedule notifications. There is some more work to schedule everyXhour and using the minutes from the "time" field.

Sure, this makes sense. 

> For remote and local notification, we can use same identifier, so that the one overwrite the other one (local notification overwrites with remote and vice versa). to do that, API team should give the notification_id with each schedule.

This makes sense as well. 

> Also for repeated notifications, the previous notification will be replaced (if exist in notification center) by latest one. So we don't need to expire the notifications except for the case "repeat_interval": "none"

This seems good as it'll prevent spamming notifications to the user for the same survey. 

> [There is some complexity to remove local notification (suppose local notification is not delivered yet) when remote notification arrives. If we remove the pending local notification which may have repeat type.. then we will lose upcoming local notifications]

Perhaps schedule all local notifications as individual ones to avoid breaking repeating schedules? 

@amaljofyzco 

> Problem in android is, in notification class we can't directly specify the date for scheduling. So the only possible way is to create a Room Dao for storing the Activity details and by using the os Alarm Manager feature for getting the corresponding trigger using the Broadcast Receiver. Once a Broadcast Receiver is fired, we need to cross check with the DB entry to fetch the details of the particular schedule and throw a notification.

This is expected and this strategy makes sense.  

> Another issue is Android support notification is as Int Datatype. (Jijo already conveyed it). I am also expecting more complexity in handling local and remote notifications. I am planning to do with above logic in andorid, if you have any suggections please we can discuss on that also.

Sure, if anything comes up, please share it here so we can come up with an optimal solution.

**Comment by jijopulikkottil** [comment]
> Perhaps schedule all local notifications as individual ones to avoid breaking repeating schedules? - @avaidyam  Then we have to use different identifier to make individual, but this will stop the behaviour of overwriting/replacing the previous one.

**Comment by avaidyam** [comment]
@jijopulikkottil Give it a shot with the easier approach first, and if it poses too many issues then we can change directions later?

**Comment by jijopulikkottil** [comment]
Yes. just discussed the expecting behaviour. Let us implement and verify first.

**Comment by jijopulikkottil** [comment]
@avaidyam @Linoy339  Can we remove the `settings` block from the Activity API response:

```
{
            "id": "h6xerq2nytxegr35bmhv",
            "schedule": [
                {
                    "start_date": "2021-02-02T17:25:30.819Z",
                    "time": "2021-02-02T17:25:30.819Z",
                    "repeat_interval": "custom",
                    "custom_time": [
                        "2021-02-02T17:30:43.084Z"
                    ]
                }
            ],
            "_deleted": false,
            "settings": [
                {
                    "audio": null,
                    "audio_name": null
                }
            ],
            "spec": "lamp.breathe",
            "name": "zcolinrm1"
        }
```

As it may contain audio data, the response data size is too big and app is getting memory issues.

**Comment by Linoy339** [comment]
@avaidyam . Can you suggest on it. It seems, we cannot remove settings from this api, as its used in some places.
Can we have another api which excludes settings .

**Comment by jijopulikkottil** [comment]
What about adding parameter in request to identify the call from mobile app to ignore `settings`

**Comment by avaidyam** [comment]
@Linoy339 The `_deleted` parameter is not supposed to be exposed by the API to the client. Let's add a query parameter to the `list` and `view` methods on `Activity`/`Sensor`/`ActivitySpec`/`SensorSpec` called `ignore_binary`. If this parameter is set to `true`, replace the `settings` object on `Activity`/`Sensor` with `null`, and replace the `executable` and `icon` fields on `ActivitySpec` with `null`. (This needs to be supported across CouchDB and MongoDB adapters.)

@jijopulikkottil This way your client code will set this `ignore_binary` flag to `true` and can filter out the base64-encoded data across the API.

**Comment by Linoy339** [comment]
@aditya. The _deleted flag is not there. We kept it for some experimental purpose. It won't be there in api response

**Comment by Linoy339** [comment]
@avaidyam .
Two known issues are there with this approach

1.Old activity schedules does not support local notification, as they do not poses notification ids
solution for 1:create an initial script to generate notification ids for all activity schedules

2.Whenever there is an update of any schedules of a particular activity, notification ids gets regenerated which
will not inform the device for change.
Solution for 2: Whenever there is an update, we can send a silent push notification with a  parameter
so the app can call activity api again to restore the schedules.

**Comment by Linoy339** [comment]
Please find
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/59](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/59).
Can you make it in staging only, as we can test it and merge into production?

**Comment by Linoy339** [comment]
@avaidyam. This includes soft delete feature in MongoDB too.
