### ISSUE TITLE
Mark email address field as an "email" input type to prevent auto-capitalization

### ISSUE THREAD

**Issue by jeydude1** [BIDMCDigitalPsychiatry/LAMP-platform#117]
Can you make the username or email address field in the mindLAMP login screen case-insensitive? Currently login username is case sensitive so if the study participant used a mindLAMP mobile app they might enter Upper/lowercase.

**Comment by avaidyam** [comment]
[From **RFC 5421**](https://tools.ietf.org/html/rfc5321):
> ... implementations MUST take care to preserve the case of mailbox local-parts. In particular, for some hosts, the user "smith" is different from the user "Smith". Mailbox domains follow normal DNS rules and are hence not case sensitive.

Furthermore, the Credential object in the LAMP Platform can signify more than a user-facing credential (email + password) such as an API Key (access key + secret key) which *ARE* care-sensitive. If I understand your issue description correctly, on a mobile device, auto-capitalization applies to the email field which makes it difficult to enter the correct email address?

**Comment by jeydude1** [comment]
Yes, that's correct Aditya, in mobile phones auto-capitalization is enabled by default that will allow mistakes for some of the non-technical study participants.

**Comment by avaidyam** [comment]
@sarithapillai8 To resolve this issue it seems we need to [mark the email address field as an email input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) to prevent autocapitalization.
