### ISSUE TITLE
Cortex visualization

### ISSUE THREAD

**Issue by jeydude1** [BIDMCDigitalPsychiatry/LAMP-platform#118]
We need Cortex visualization that are available in https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex - this Cortex documentation does not have instructions about how to generate different graphs and instructions about attaching them to patient/study participants. It will be nice to have them.

Aditya explained some of the sensor data graph that can be added to the mindLAMP dashboard in Prevent/Cortex section. Can you share instructions to get Cortex working in our local server environment.

I have used following command to get the code into 
```
pip install git+https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex.git#egg=LAMP-cortex
```

Use this code to get the sensor data:
```
import LAMP
from lamp_cortex.participant_ext import ParticipantExt
from lamp_cortex.study_ext import StudyExt

LAMP.connect("admin", " < Admin PASSWORD > ",
             " <API URL > ")
print('connected')
# Get Participant object
participant= ParticipantExt('<PATIENTID>')
print('got participant')
# Generate Sensor Data graph
participant.sensor_events()
print('done with sensor events')
```

Received following error while executing above code

```
E:\Program Files\Python387\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
```

Not sure, if above code is enough to get the sensor data visualization under Cortex section of Prevent screen, can you share instructions/code to generate Cortex for sensor data summary and push into patient dashboard Prevent screen?

**Comment by jeydude1** [comment]
@ryan-hays and @rydmel any update on documentation and generating Cortex visualization?

**Comment by avaidyam** [comment]
@jeydude1 We should have news and further documentation mid-next-week. @ryan-hays can respond here once that's ready and available.
