### ISSUE TITLE
Analytics events on how long users spend on each tab/looking at data

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#12]
Each time a tab is opened by a patient in the app, we should emit a "lamp.analytics" event with the parameter "type" = "open_page" and "page" = "learn"/"assess"/"manage"/"prevent"/"conversations" (based on which page was actually opened). Then, the last tab opened should be saved in **localStorage**. 

Any thoughts ﻿@michaelmenon?

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please specifiy the format for the data to be saved? Do we need to log for each menu (Feed, Learn, Assess, Prevent and Manage) or every activity page?

**Comment by avaidyam** [comment]
I specified above, but here is a code example: 
```typescript
await LAMP.SensorEvent.create(participant_id, {
    "timestamp": new Date().getTime(),
    "sensor": "lamp.analytics",
    "data": {
        "type": "open_page",
        "page": "conversations"
    }
})
```
This should only be for the following pages:
- Feed
- Learn
- Assess
- Manage
- Prevent
- Conversations

**Comment by sarithapillai8** [comment]
@avaidyam 
You have specified to save last tab in the localStorage and save sensor event for each tab open. So don't we need duration value in sensor event? otherwise why do we need to save localstorage?

**Comment by avaidyam** [comment]
`SensorEvent` objects do not have a `duration` field. You're thinking of `ActivityEvent` objects. The reason it's helpful to save the last tab in `localStorage` is so when the user reopens the app, it goes to the place they were last in. The analytics events are helpful for us to know which tabs were most opened or used. Specifically we want to know when conversations were opened/viewed as well.

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please check the PR and let me know if the implementation is to be changed?
