### ISSUE TITLE
Unable to find Steps data in the Cortex section of the Prevent tab on iPhone 

### ISSUE THREAD

**Issue by kkadapa** [BIDMCDigitalPsychiatry/LAMP-platform#123]
We were unable to see the steps bubble in the Cortex section of the Prevent tab iPhone 8 and iPhoneX. 

Please see the below screenshots, both I and another user installed Production MindLamp App from AppStore and have Step's data available in the database.

Please let us know if you need any additional information.

![image (5)](https://user-images.githubusercontent.com/6679852/108523584-16ec9480-729c-11eb-9df1-fdc29d4bcf00.png)
![image (4)](https://user-images.githubusercontent.com/6679852/108523589-181dc180-729c-11eb-8d4b-d6afaf236e28.png)
![image (3)](https://user-images.githubusercontent.com/6679852/108523593-194eee80-729c-11eb-9dfb-7011032f8f30.png)

**Comment by avaidyam** [comment]
This seems to be an issue identified by @jeydude1 and his team as well -- there is a request limit of 1000 most recent sensor data points for optimization purposes. If step count was not part of the most recently uploaded batch of data, or there is too much data being collected for an individual, the step count bubble does not show up. 

The specific code is [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/master/src/components/Prevent.tsx#L333) and [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/9beed4cd3ca648f863e4df21f903e5bd37e9ec34/src/components/ParticipantData.tsx#L120).

**Comment by kkadapa** [comment]
Hello, @sarithapillai8 Could you kindly let us know if this issue is fixed or is it a low priority?

**Comment by avaidyam** [comment]
@kkadapa This will be resolved with the next staging release in mid-March. We'll respond here with specifics at that time!

**Comment by kkadapa** [comment]
Hello @avaidyam, Just following up to see if there are any updates on resolving this issue?

**Comment by kkadapa** [comment]
Hello, we just got notified from the latest newsletter that these issues are ready. Could you kindly clarify?
[Mar-Apr Newsletter 6-2.pdf](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6314741/Mar-Apr.Newsletter.6-2.pdf)

**Comment by avaidyam** [comment]
@kkadapa unfortunately our mid-March release was delayed but these changes will be rolling out by next Friday. //cc @jtorous @rbilden @michaelmenon

**Comment by kkadapa** [comment]
Hi @avaidyam When I go to https://dashboard.lamp.digital/#/ and **Try it** as **Researcher** it shows the below loading screen same happens when I connect to our QA environment backend. 

According to the new update/release what exactly needs to be changed in the backend for the Steps Sensor to work? and Once the Researcher/Clinician configures the Sensors (steps) will they be available to the Patients/Users on the mobile apps Prevent Tab, Cortex section after 12 hours?

![image](https://user-images.githubusercontent.com/6679852/116125167-2967bd80-a693-11eb-91b0-870bcd7f5908.png)

**Comment by avaidyam** [comment]
@kkadapa [As indicated in the release notes/latest news post](https://docs.lamp.digital/blog#frontend), you need to upgrade your server image to the latest `:2021` image, and then it should work correctly.

**Comment by kkadapa** [comment]
Thansk @avaidyam. We already had 2021 but just had to clear browser cache. I followed as outlined in this issue to manually add Steps Document to the sensor_spec database. https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/119

![image](https://user-images.githubusercontent.com/6679852/116498364-9471e980-a877-11eb-8fde-b9e7105a2ccc.png)


Please see below, When I click on the Cortex section in the Prevent tab it's throwing errors

https://user-images.githubusercontent.com/6679852/116498296-6be9ef80-a877-11eb-82f3-dad7fd4d7579.MOV

**Comment by kkadapa** [comment]
@avaidyam Do we need to open a new issue to track the UI glitch? Can we expect to see Steps data once the issue is fixed?

**Comment by kkadapa** [comment]
Hi @avaidyam Just following up to see if there are any updates regarding the issue. Please let us know if you need any further information. Thanks!

**Comment by jtorous** [comment]
Hi Karthik,

We don't have the funds to build it quickly. Other teams have pulled the
step data from the database and built a simple dashboard around that which
may be the fast solution. The good news is the step count data is collected
and stored, so this is the last step of how to display it! The photo below
is an example from a different team.

Thanks,
John

[image: Screen Shot 2021-05-07 at 9.04.18 AM.png]

**Comment by kkadapa** [comment]
Appreciate your response Dr Tourous! @jtorous I am unable to see the screenshot I only see "[image: Screen Shot 2021-05-07 at 9.04.18 AM.png]" Can you kindly upload the image again?

Did other teams displayed the steps on the Cortex section of the iOS/Android Mobile Apps or did they use some Tableau or some BI tool to just display the data?

**Comment by jtorous** [comment]
Hi,

The screenshot was just another team that built a custom web viewer that
pulls directly from the database. That seems to quickest solution as when
we do it for LAMP it has to work on iOS, Android, and web which we will get
to but a higher bar. Thus the one of web view is the  fastest way to get to
the goal today.

Thanks,
John
