### ISSUE TITLE
The "source" parameter should be used across all HealthKit and Google Fit sensors

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#126]

**Comment by avaidyam** [comment]
The value for `source` should come from [`sourceRevision` on iOS](https://developer.apple.com/documentation/healthkit/hkobject/1615483-sourcerevision) and [`originDataSourceId` on Android](https://developers.google.com/fit/scenarios/read-sleep-data) 
//cc @amaljofyzco

**Comment by jijopulikkottil** [comment]
iOS code is pushed. @amaljofyzco please change this task status when Android is done.
