### ISSUE TITLE
Add 'duration' for the sensor event lamp.sleep

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#127]

**Comment by jijopulikkottil** [comment]
please see the sample data for 3 minutes in bed and 1 minute sleep.

{
            "timestamp": 1614059640000,
            "sensor": "lamp.sleep",
            "data": {
                "value": 0,
                "source": "com.apple.Health",
                "type": "in_bed",
                "duration": 180000
            }
},
{
            "timestamp": 1614059580000,
            "sensor": "lamp.sleep",
            "data": {
                "value": 1,
                "source": "com.apple.Health",
                "type": "asleep",
                "duration": 60000
            }
}

Available 'type' values are  0 "in_bed" , 1 "asleep", 2 "awake" 
@avaidyam please confirm

@amaljofyzco hope android doesn't have the sleep data.

**Comment by avaidyam** [comment]
@jijopulikkottil This looks good. It looks like HealthKit (and Google Fit) have overlapping discrete segments, which is something for data scientists to resolve when analyzing the sleep data; nothing for you to adjust here. It looks like `type` and `value` mean the same thing - if so, just use the `value` field with the string representation that you propose is in the `type` field? 

![](https://docs-assets.developer.apple.com/published/ae8867d461/record_sleep_data_2x_3a78f928-8d73-41f1-87d5-9fec91ade7b3.png)

**Comment by jijopulikkottil** [comment]
As we are using common class for sending sensor data, the `value` parameter is `number` type. (also the `value` property in HealthKit samples are integer). Thats why we kept the `value` as type number. Can we use new param `value_text` ? or we can use the same `value` with type text for `lamp.sleep` as you suggested. no issues. Which ever is easier for data scientists to resolve.

**Comment by avaidyam** [comment]
That seems like a good idea, @jijopulikkottil - let's use `value` for the integer type, and `representation` (since `value_text` does not really explain the meaning of the field) for the string type. It should be easy to dynamically get the correct string representation from the enums.

**Comment by jeydude1** [comment]
@avaidyam, not sure if you can capture from HealthKit
1. Bed-In Time
2. Awake
3. Deep sleep
4. REM sleep
5. Light sleep
6. Bed-Out Time
I will be useful to get those data as well.

**Comment by jtorous** [comment]
We do not ask for this yet but can in the near future with an update.

-John

**Comment by jeydude1** [comment]
Also include heart rate variability HRV data along with HR data in future, i was told some of the researchers wants HRV data.

**Comment by avaidyam** [comment]
@jeydude1 It looks like HealthKit can only provide the following states: `in_bed`, `asleep`, and `awake`, with the starting timestamp and duration. (See the figure below for an explanation.)
![image](https://user-images.githubusercontent.com/1361003/109499072-62542f00-7a62-11eb-9570-dcb8f2764c5e.png)

The sleep phase (light, deep, REM) are not possible on the iOS side, but we do capture these phases on the Android side **only if the wearable device or smartphone sleep tracking app supports it.** By default, only **Fossil Gen 5** watches appear to support sleep tracking with this level of detail at a glance. 

Furthermore, we should be capturing HRV through `heartRateVariabilitySDNN` on iOS via HealthKit in the upcoming beta release. This is likely only supported if the Apple Watch itself supports it, however.
