### ISSUE TITLE
Better repository adapter resolution to prevent crashes and remain compatible with existing deployments

### ISSUE THREAD

**Issue by jeydude1** [BIDMCDigitalPsychiatry/LAMP-platform#128]
Hi Aditya,

Not sure is it OK to use 
```
image: bidmcdigitalpsychiatry/lamp-server:latest 
``` 
```
Initializing LAMP API server...

  (node:1) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency

  (Use `node --trace-warnings ...` to show where the warning was created)

  Server routing initialized.

  Clean all queues...

  CLEANING ALL QUEUE

  Connected to Nats Pub Server

  Connected to Nats Sub Server

  DONE--CLEANING ALL QUEUE

  Initializing schedulers...

Initialization complete.

(node:1) UnhandledPromiseRejectionWarning: MongooseError: Operation `activity.find()` buffering timed out after 10000ms

    at Timeout.<anonymous> (/usr/src/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)

    at listOnTimeout (internal/timers.js:554:17)

    at processTimers (internal/timers.js:497:7)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

GET / 200 - 10.437 ms

GET / 200 - 7.129 ms

```

Not sure if I need mention any Mongo DB references instead of Couch DB, please let me know.

**Comment by Linoy339** [comment]
@jeydude1 . Please put a variable named DB_DRIVER in your env :
DB_DRIVER = couchdb

**Comment by jeydude1** [comment]
Thanks, i have added that, able to access CouchDB.

**Comment by avaidyam** [comment]
@Linoy339 Let's change the driver discovery environment variables to make it easily compatible with existing deployments.
1. Check the environment variable `DB` first, else check `CDB` for a valid string.
1. If the string begins with `mongo://` it implies switching to the Mongo repository adapter. 
1. If the string begins with `http://` or `https://` it implies switching to the CouchDB repository adapter. 
1. Else, if something else, like `mssql://` or something, throw an error for a missing repository adapter and shut down.

**Comment by Linoy339** [comment]
@avaidyam . We can remove DB_DRIVER. from env
1. Can you explain the point no 1?
 
2.Is the connection string for both mongo and couchdb to be a part of  the variable CDB?:
There would be only one variable named **CDB** which contains either mongo or couch connection string . If this string begins with mongo://, it implies switching to the Mongo repository adapter. If the string begins with http:// or https://, it implies switching to the CouchDB repository adapter. Else, if something else, like mssql:// or something, throw an error for a missing repository adapter
OR
There would be only one variable named **DB** which contains either mongo or couch connection string . If this string begins with mongo://, it implies switching to the Mongo repository adapter. If the string begins with http:// or https://, it implies switching to the CouchDB repository adapter. Else, if something else, like mssql:// or something, throw an error for a missing repository adapter

**Comment by avaidyam** [comment]
@Linoy339 
1. If the `DB` env is defined, use that. If not, check if `CDB` is defined instead. If neither are defined, throw an error that no adapter/DB connection is configured. 
1. The connection string for EITHER Mongo or Couch should be part of the one env `DB` (and fallback to `CDB` if `DB` is not defined).

**Comment by Linoy339** [comment]
Okay. Got it. Thank you

**Comment by Linoy339** [comment]
@avaidyam . The above change is done.
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/58](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/58)
