### ISSUE TITLE
lamp.analytics to be used to keep data collection logs

### ISSUE THREAD

**Issue by ZCOEngineer** [BIDMCDigitalPsychiatry/LAMP-platform#129]
Use `lamp.analytics` with `type = log` to keep logs indexed by patient ID

**Comment by jijopulikkottil** [comment]
```
      {
            "timestamp": 1614755610657,
            "sensor": "lamp.analytics",
            "data": {
                "action": "log",
                "message": "GPS is disabled.",
                "user_agent": "2021.1.21, iPhone, 14.3",
                "device_type": "iOS"
            }
        }
```
This is a sample.

**Comment by avaidyam** [comment]
@jijopulikkottil Let's change the `user_agent` string format like so: `AppName AppVersion; OSName OSVersion; DeviceType DeviceModel`. For example, `NativeCore 2021.1.21; iOS 14.3; iPhone A1921". Is the `device_type` field still required anywhere or would it make sense to remove it? (cc @Linoy339)

**Comment by jijopulikkottil** [comment]
@avaidyam  So for android and iOS, the `appname` should be `NativeCore`!  ok.

**Comment by jijopulikkottil** [comment]
For iOS, we can't get the model number. Instead we can get the system info. We can see the mappings [here](https://gist.github.com/adamawolf/3048717) 

`"user_agent": "NativeCore 2021.1.21; iOS 14.3; iPhone iPhone8,1"`
