### ISSUE TITLE
TestFlight build is crashing in the background

### ISSUE THREAD

**Issue by ZCOEngineer** [BIDMCDigitalPsychiatry/LAMP-platform#130]
[Problem]
TestFlight build is crashing in the background

**Comment by jijopulikkottil** [comment]
@avaidyam  We used test flight build and unable to reproduce the crash. All crashes coming from 3 devices (2 iPhone8 and 1 iPhone XR ).
We checked the crash log, and replaced the background timer implementation in another way. I can make PR today so you can submit to test flight and can be test by those same devices/users.

**Comment by avaidyam** [comment]
@jijopulikkottil Please do - thank you! (cc @jlavoie9)
