### ISSUE TITLE
Compatibility mode to collect all sensor data for legacy server configurations

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#131]
if the sensor_spec list comes up empty, please fallback to collecting ALL the data like the code used to work

**Comment by jijopulikkottil** [comment]
Following are the complete list of sensor names:
`"lamp.gps", "lamp.activity_recognition", "lamp.telephony", "lamp.screen_state", "lamp.nearby_device", "lamp.steps", "lamp.device_motion", "lamp.accelerometer", "lamp.analytics", "lamp.sleep", "lamp.heart_rate", "lamp.blood_pressure", "lamp.respiratory_rate", "lamp.body_temperature", "lamp.oxygen_saturation", "lamp.blood_glucose", "lamp.nutrition", "lamp.segment"`

**Comment by avaidyam** [comment]
@jijopulikkottil Do you have JSON Schema that describes the data format for each of these?

**Comment by jijopulikkottil** [comment]
Similar to [this](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/119#issuecomment-786641294) . This is the data extracted from the staging. But this is incomplete and also need some corrections. I can update this document and can send next day if you want this format.

**Comment by avaidyam** [comment]
Here's an updated document that removes the CouchDB specific document stuff. This is just an array of JSON Schemas now. Could you update this document to correctly match the sensor data being collected? (i.e. I filled out `lamp.gps` some time ago with the details, following the same format will be helpful.)

[sensor_spec.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6051613/sensor_spec.json.txt)

**Comment by jijopulikkottil** [comment]
Updated the document. @avaidyam  @amaljofyzco please verify it.
[sensor_spec.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6061582/sensor_spec.json.txt)

1. Hope we don’t need `units` for any sensors.

2.  We can replace the property name `content` as “payload” for `lamp.analytics` with push notification (`action = notification`)

2. We are getting diastolic and systolic from two samples. So there are two `source` So can we add two source property for `blood_pressure`. Like `source_diastolic` and `source_systolic` ?

3. We had not included `battery_level` with `lamp.screen_state` . We can include with next build.

**Comment by avaidyam** [comment]
1. [We should be able to get the units for an `HKSample` it seems.](https://developer.apple.com/documentation/healthkit/hkquantitysample)
1. It seems fine either way, `content` or `payload` seem equally descriptive. 
1. Let's use this kind of structure for `blood_pressure`: 
```js
{
  timestamp: ...,
  sensor: ...,
  data: {
    systolic: {
      value: 120,
      units: "mmHg",
      source: "com.apple.Health.123"
    },
    diastolic: {
      value: 80,
      units: "mmHg",
      source: "com.apple.Health.123"
    }
  }
}
```
1. That makes sense, thanks. 
1. Yes, in addition to `value`, `units`, and `source`, you could use `meal_time` with possible values `preprandial` (before meal) and `postprandial` (after meal).

**Comment by jijopulikkottil** [comment]
2- we can keep the same `content`
iOS code is committed. @amaljofyzco please change this task status when you finish.
