### ISSUE TITLE
Translation Required 

### ISSUE THREAD

**Issue by sijugeorge-zco** [BIDMCDigitalPsychiatry/LAMP-platform#138]
Hindi and Spanish translation required for the Attached file.

_Note:_
The texts to be translated are on the right side(_value_) of the _key:value_ pair on the attachment.

[translation_changes.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6210517/translation_changes.json.txt)

**Comment by sijugeorge-zco** [comment]
@avaidyam 
We have changed the term "_study_" to "_group_" and "_patient_" to "_user_" throughout the application an will update  only after we get the new texts and translated.

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - see attached for Hindi translation. Thanks! fyi @avaidyam 

[Translation_changes_Azaz_April_13.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6304850/Translation_changes_Azaz_April_13.txt)

**Comment by sijugeorge-zco** [comment]
@avaidyam 
We need translated strings (for Spanish & Hindi) for the attached file.

[translation_spanish_and_hindi_required.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6516900/translation_spanish_and_hindi_required.txt)

**Comment by tlakhtak** [comment]
Attached are the translated strings for Hindi.

[translation_hindi_required_24May2021_AK.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6578467/translation_hindi_required_24May2021_AK.txt)

**Comment by sijugeorge-zco** [comment]
@tlakhtak 

Please find the texts to be translated in HINDI.

Translations are required for strings ( on the right side of the _key : value_ pair) on the attached JSON file.

[Hindi_Transaltion_Needed_07012021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6749008/Hindi_Transaltion_Needed_07012021.txt)

**Comment by sijugeorge-zco** [comment]
@avaidyam @SuruPa00 @tlakhtak 

Can you please update us the above translations for HINDI.

**Comment by sijugeorge-zco** [comment]
@SuruPa00  @tlakhtak 

Please find the strings(_attachments_) that needed translation for both **HINDI** and **SPANISH**.

[Researcher_Hindi_and_Spanish_translation_needed_07202021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6848124/Researcher_Hindi_and_Spanish_translation_needed_07202021.txt)
[Manage_Prevent_Hindi_and_Spanish_translation_needed_07202021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6848126/Manage_Prevent_Hindi_and_Spanish_translation_needed_07202021.txt)
[Learn_Hindi_and_Spanish_translation_needed_07202021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6848127/Learn_Hindi_and_Spanish_translation_needed_07202021.txt)
[Activity_Hindi_and_Spanish_translation_needed_07202021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6848128/Activity_Hindi_and_Spanish_translation_needed_07202021.txt)
[Survey_Hindi_and_Spanish_translation_needed_07202021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6848129/Survey_Hindi_and_Spanish_translation_needed_07202021.txt)

**Comment by tlakhtak** [comment]
[Hindi_Transaltion_Needed_AK_07012021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6848159/Hindi_Transaltion_Needed_AK_07012021.txt)

We'll work on the others, thanks

**Comment by tlakhtak** [comment]
Hi, we would like to have the app available to translate in French as well - can we use the files listed here to provide to translators, or are they no longer up to date?

**Comment by SuruPa00** [comment]
@sijugeorge-zco following the previous comment, can you confirm if there are further files to translate so we can move forward with a French translation? If there are more, please attach them here.

**Comment by avaidyam** [comment]
@michaelmenon @ZCOEngineer Can you share the updated translation files to work off of for French and [Italian](https://mindlamp.discourse.group/t/italian-language/479/2)?

**Comment by sarithapillai8** [comment]
[translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7819580/translations.txt)
@avaidyam Please find the latest file we are using in dashboard now.

**Comment by sarithapillai8** [comment]
@avaidyam This is still assigned to me. We are waiting for the translation files.

**Comment by avaidyam** [comment]
We haven't received anything yet. When we do I'll reopen this issue.
