### ISSUE TITLE
DBT Diary Card Updates

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#14]
1. Need to add two questions to page 7 underneath "Did you have an urge to quit therapy this week?" 
    1. "Did the skills help?" (Yes/No)
    1. "Did you have an urge to commit suicide this week?" (Rating scale: 0-5)
    1. "Did you have the urge to die?" (Rating scale: 0-5)
1. Also, please make the configuration for target behavior units a custom text field instead of "Times"/"Hours"/"Yes". It was a typo/mistake in the original version that only those three radio button options were there.

Action items from today's meeting (cc @Elena):
---
**For the DBT Diary Card code:**
1. Remove the "Weekly overview" page from DBT Diary Card.
1. [Restore the Skills data.](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commit/9fd8e34615b0c95b473a39c47e7a54b9842f14c2)
1. Move the "Did the skills help?" question to right after page 5.
1. Add a radio button for "zero" for each rating scale.
1. Remove the ability to "de-select" a rating scale radio button. 
1. It should not be possible to advance to the next page if you did not click a rating for all items. 
**For the Survey code (in the Dashboard code):**
1. Add "Short Answer" option which will be a single line text field, not a text box.
1. Add "Rating" option which will be the rating scale as it appears in the DBT Diary Card. 
Any questions @sarithapillai8 @michaelmenon? Also, please let us know the expected effort on this as soon as possible! 

Basecamp Conversation
---
> @sarithapillai8: I have updated these changes in staging. Could you please confirm if the changes are as expected. Note: Fixed the back button issue and aligned the question to center as Tim suggested.
> 
> @michaelmenon: Thanks for the details, I will talk to team and we will update an eta for these items by Monday.
>
> @sarithapillai8 Restore the Skills data. - this is done. 
> 1. Remove the ability to "de-select" a rating scale radio button . 
> 1. It should not be possible to advance to the next page if you did not click a rating for all items. 
> 
> I am confused with the above changes. If there is a validation required in rating to proceed to next, why do we need an option to de-select the rating?
>
> @avaidyam: You are correct: There should **NOT** be an option to de-select the rating. We **DO** need validation to ensure that all questions have been selected to continue to the next page. 
>
> @sarithapillai8: Okay. Got it. Do we need a special activity creation screen for weekly overview or is there any restriction required to have single kind of survey weekly overview survey? Note: **The requested changes can be updated by next Wednesday(18/11/2020).** Thank you.
> 
> @avaidyam: No restrictions or special creation screens. 👍
>

**Comment by avaidyam** [comment]
@sarithapillai8 Minor change request! 
1. Right now when creating a Target Behavior it shows a dialog with a text field for "Behavior name" and has 4 options: "Times", "Hours", "Yes", and "Custom". Only when selecting "Custom" does a new text field for "Custom unit" come up. 
    1. We would like to change it to be this: "Behavior name" (text field, required) + "Unit name" (text field with autocomplete, required). 
    1. If both fields are not filled out, the "ADD" button should be disabled. 
    1. [For info on implementing autocompletion for the text field, see this link](https://material-ui.com/components/autocomplete/#combo-box). For the "Unit name" autocompletion, it should have the options "Times", "Hours", and "Minutes".

**Comment by avaidyam** [comment]
@sarithapillai8 The changes I listed above for the creation UI were not implemented yet - moving this back to In Progress.

**Comment by avaidyam** [comment]
@sarithapillai8 It's not yet possible to create a **Rating** question type. I see this error in the console: 
```
TypeError: t.map is not a function. (In 't.map((function(e){return null===e||void 0===e?void 0:e.value}))', 't.map' is undefined)
```
Furthermore, as mentioned before the **Rating** question type is supposed to still have an array of options just like the **Slider** question type; the length of the array is the number of rating bubbles visible. 

---

Also, I made this comment on the appropriate Pull Request, but I will include it here as well for reference:
> When testing out typing custom units for the DBT Diary Card, the UI crashes to a white screen and there's this error in the console:
> ```
> TypeError: null is not an object (evaluating 'c.toLowerCase')
> ```

**Comment by sarithapillai8** [comment]
@avaidyam 
Rating type was not specified with options and I thought it is to be with 0 to some number. It was told to have a similar view for the rating we have in DBT. Actually what do you want to include with this options? If any text is entered as options, how can we  render through the radio buttons? And where do we need to show the descriptions?

I am not getting error with both rating and custom unit implementation. Could you please confirm that you cleared cache ? I have updated the build file to handle the data on back button tap, otherwise I didn't get issues.

**Comment by avaidyam** [comment]
@sarithapillai8 
Right - it should have the same UI as it did when it was a part of DBT Diary Card. There is unfortunately no point to an options array, except the length of that array should be used for the number of radio buttons to display in the UI. **Upon selecting a radio button,** perhaps a good design is to show the Value underneath the buttons, and the Description as a subtitle underneath the Value text. 

Let me check again after clearing cache and using incognito mode and report back. To my knowledge I was testing with the latest master branch. If all else is good to go and production-ready then we can push the `LAMP-activities` changes as well.

**Comment by sarithapillai8** [comment]
@avaidyam 
I can keep the options array. but to display the value underneath the button will be difficult with the design. We already have such kind of design with normal radio buttons. That is why I put the filed for maximum rating to find the number of radio buttons. Please confirm.

**Comment by avaidyam** [comment]
@sarithapillai8 
> to display the value underneath the button will be difficult with the design
How so? I imagine it could look and work just like the slider question type does? If I set `options = [-10, -5, 0, 5, 10]`, the rating scale numbers should be those values. Once I select a rating, that option's description should appear in light gray subtitle text underneath the rating scale.
