### ISSUE TITLE
Sensor configuration parameters

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#145]
Now that the current beta code correctly verifies which sensors it must collect/upload data from, the higher frequency sensors such as `lamp.device_motion` and `lamp.gps` should also support the following parameters:
1. `frequency` (units: `Hz`): The frequency at which to poll the sensor for data. 
2. `cellular_upload` (boolean): If `true`, the sensor should upload data on a cellular/LTE connection **in addition to WiFi.** Defaults to `false`.

**Comment by jijopulikkottil** [comment]
@avaidyam you mean those parameters will be the part of sensor-spec (api /participant/{participant_id}/sensor) for higher frequency sensors and app will collect/upload data as per the parameter value. Please confirm.

**Comment by avaidyam** [comment]
@jijopulikkottil Yes - it will be part of the **Sensor API** (`/sensor/*`), not **SensorSpec API** (`/sensor_spec/*`). @saranya-sajeev Can you confirm your understanding is the same?

**Comment by saranya-sajeev** [comment]
Yes Aditya.

**Comment by jijopulikkottil** [comment]
@avaidyam  Yes. So it's an addition to the task https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/92 .
1. Currently `lamp.gps` not following any frequency, instead we are observing the location changes and collect it when it fires. So we should change this behaviour and have to get the location based on frequency.. right ?
2. Also for `cellular_upload`, currently we are posting sensor data without checking the connectivity(wifi or cellular). So we should change it to like upload sensor events only if Wifi (`cellular_upload` = false). And it should be the default case. ok. And if `cellular_upload` is true, we don't need to check the connectivity type (as we are doing now).

**Comment by avaidyam** [comment]
@jijopulikkottil 

> Currently lamp.gps not following any frequency, instead we are observing the location changes and collect it when it fires. 

Hmm, this is not the behavior we were expecting but this is probably better and may mean we do not want to change it. @jlavoie9 @ryan-hays can you double check on this and confirm? 

> Also for cellular_upload, currently we are posting sensor data without checking the connectivity(wifi or cellular). So we should change it to like upload sensor events only if Wifi (cellular_upload = false). 

Yes, the default value for `cellular_upload` should be `true` then, and if it is set to `false`, we should only upload data on WiFi.

**Comment by jlavoie9** [comment]
> @jijopulikkottil
> 
> > Currently lamp.gps not following any frequency, instead we are observing the location changes and collect it when it fires.
> 
> Hmm, this is not the behavior we were expecting but this is probably better and may mean we do not want to change it. @jlavoie9 @ryan-hays can you double check on this and confirm?

@avaidyam If we only collect when the location changes, it would be important to record a duration as well. Without a recorded duration we won't be able to determine the difference between a stationary participant and a participant with missing data.

**Comment by jijopulikkottil** [comment]
@avaidyam , we can consider the field 'frequency' comes inside for specs "lamp.gps", "lamp.device_motion" and "lamp.accelerometer".
sample:    
```
{
        "id": "cnyem460gynjcn7gfnaw",
        "timestamp": 1620375978767,
        "spec": "lamp.gps",
        "name": "Sensor 4",
        "frequency": 1
  }
```

How we need to handle the param 'cellular_upload'? for individual sensors or for all ? Hope it will be applicable for all sensors, so the parameter comes outside the sensors array. Please comment.

**Comment by avaidyam** [comment]
@jijopulikkottil Cellular upload should be considered at a per-sensor level. Furthermore, the correct `Sensor` object definition is as follows (`frequency` should be part of the `settings` object):
```json
{
        "id": "cnyem460gynjcn7gfnaw",
        "timestamp": 1620375978767,
        "spec": "lamp.gps",
        "name": "Sensor 4",
        "settings": {
                 "frequency": 1,
                 "cellular_upload": true
        }
}
```

If there are **significant** challenges in implementing this, please prepare those so we can discuss them in this week's meeting.

**Comment by jijopulikkottil** [comment]
Yes, It has some challenges. We should keep each sensor data in individual files.

**Comment by avaidyam** [comment]
For now, an alternate solution is to auto-enable `cellular_upload` for ALL sensors if AT LEAST ONE sensor has it enabled. If this approach is easier to get started with, then it is easier to keep a backlog issue describing this challenge and add a disclaimer to the documentation about this behavior (which I will do).

**Comment by jijopulikkottil** [comment]
Yes, that is easier. We can continue with that approach.

**Comment by jijopulikkottil** [comment]
For iOS,
1. As we are fetching lamp.device_motion and lamp.accelerometer data using same motion handler, we have to use same frequency if both exist. So if both exist and have different frequency, then we will use frequency of lamp.device_motion. hope this is fine.

2. We have to set a maximum (also the default) threshold frequency. so for lamp.gps, can we set frequency 1 ? So if user set a frequency 2 or 3, then we will use 1. (`min(1, user defined)`)

3. for lamp.accelerometer, lamp.device_motion, currently the default is 5. we can consider it as maximum threshold frequency. So if user set 6 or 7, then we will take 5. (`min(5, user defined)`)

@avaidyam let me know if need any changes.
----
Hope the threshold (also the default) frequency will be different on Android device @saranya-sajeev

**Comment by avaidyam** [comment]
> we have to use same frequency if both exist. So if both exist and have different frequency, then we will use frequency of lamp.device_motion. hope this is fine

Yes -- this is perfectly fine, but instead, please use the **highest frequency between the two.**

> We have to set a maximum (also the default) threshold frequency. so for lamp.gps, can we set frequency 1 ? [...] for lamp.accelerometer, lamp.device_motion, currently the default is 5. we can consider it as maximum threshold frequency

Sure, but please make sure this maximum is defined by Apple/Google as a hardware or software limitation. If the clinician requests 100 Hz and the hardware supports it, it should be collected at that rate.

> Hope the threshold (also the default) frequency will be different on Android device

The maximum threshold should not be different across iOS and Android. If 100 Hz is the maximum, but the device cannot support it, then the collection should occur at the actual maximum collection frequency of the device.

**Comment by jijopulikkottil** [comment]
@avaidyam  Can we set frequency in staging dashboard or is the related server task not done ?

**Comment by avaidyam** [comment]
@jijopulikkottil To do so you will need to call the API method using cURL on the command line or some similar approach. The frontend task was not completed.

**Comment by jijopulikkottil** [comment]
@avaidyam could you provide the cURL with parameter

**Comment by avaidyam** [comment]
[It would be the sensor update call detailed here.](https://docs.lamp.digital/api/update-a-sensor)

**Comment by saranya-sajeev** [comment]
Maximum value for frequency that Android app can accept is 1.

**Comment by avaidyam** [comment]
@jijopulikkottil @saranya-sajeev Has this feature been implemented **in production on both** iOS and Android now?

**Comment by jijopulikkottil** [comment]
iOS -> Yes. 
Hope it is implemented in Android too. @saranya-sajeev  can confirm.

**Comment by avaidyam** [comment]
@jijopulikkottil Can you also confirm that the behavior in #426 is implemented? I believe this behavior is specific to iOS since you have to keep the GPS sensor always-on to keep the app alive in the background. 

> * If no sensors are created in a study/user, no sensor data is collected from
any sensor.
> * When no GPS sensor is created, IF it has to be collected no matter what (to keep the app alive in the background), make it so that the frequency is very low and the data is NOT uploaded to the server.
> * These updates will render lamp.none useless, but this is fine and this can be deleted after we test all the collection is working as intended.

**Comment by jijopulikkottil** [comment]
> - If no sensors are created in a study/user, no sensor data is collected from any sensor.

If no sensors are created in a study/user, then we will collect all sensors. If we specify "lamp.none" only, then we will collect no sensor.

> - When no GPS sensor is created, IF it has to be collected no matter what (to keep the app alive in the background), make it so that the frequency is very low and the data is NOT uploaded to the server.

Yes, all are correct except we are not setting low frequency if no GPS. 
[You are correct, we can set low frequency if GPS sensor is not added]

> - These updates will render lamp.none useless, but this is fine and this can be deleted after we test all the collection is working as intended.

You mean, we have to change the implementation like If no sensors are added, then we should not collect any sensors. right ? [yes, If we implement so, lamp.none will be useless]

**Comment by avaidyam** [comment]
> If no sensors are created in a study/user, then we will collect all sensors. If we specify "lamp.none" only, then we will collect no sensor.

No, this was never the correct implementation - please delete `lamp.none` entirely. If there are no sensors for a user, no sensor data should be collected. 

> Yes, all are correct except we are not setting low frequency if no GPS. [You are correct, we can set low frequency if GPS sensor is not added]

Good, so even if `lamp.gps` is not declared in the user's sensor list, the GPS sensor should run in the background in a very low Hz.

> You mean, we have to change the implementation like If no sensors are added, then we should not collect any sensors. right ? [yes, If we implement so, lamp.none will be useless]

Yes, and please delete `lamp.none` entirely.

**Comment by saranya-sajeev** [comment]
> 
> 
> @jijopulikkottil @saranya-sajeev Has this feature been implemented **in production on both** iOS and Android now?

It is implemented in Android too.

**Comment by avaidyam** [comment]
Thanks for the update! Is it implemented exactly the same way?

**Comment by saranya-sajeev** [comment]
Yes same as in iOS
