### ISSUE TITLE
Manage Credentials for Administrators

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#146]
The `Manage Credentials` menu must be available in the blue top bar for Administrators and must ONLY allow editing the System Administrator credentials, whose `origin` field will be `null` (not a string value). The latest staging server should support these operations.

**Comment by sarithapillai8** [comment]
Please find the PR with fix - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/210
