### ISSUE TITLE
Edit/delete studies dialog in UI

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#15]
Basecamp Conversation
---
> **Collaborator**: Patient name not updating correctly. If we change researcher name is not updated and when i create a patient the study name is the first created.
>
> @sarithapillai8: The description is not clear. Could you please provide some account/new account so that we can have multiple researchers? Currently we only have option for creating studies. Do we need option for updating studies? Researcher update functionality is existing one if it was there. we didn't change anything on researchers list.
> 
> @avaidyam: I think the issue is they are not able to rename/delete studies. This may be a feature request instead then. Let me check with them first.
>
> @sarithapillai8: We don't have study listing now. So how do you expect to implement this edit/delete of studies? Can we have a separate tab for studies to manage them?
>
> @avaidyam: Let me mock it up for you later today, but I think it makes sense as a dialog that is opened from a menu.
>
> @sarithapillai8: do you mean to load the studies in a list with edit delete option in the dialog?
>
> @avaidyam: Yes, exactly -- this dialog can be opened from a button anywhere reasonable on the page. If you think you've got the idea, would you still like me to mock it up for you or would you be able to proceed?
>

**Comment by sarithapillai8** [comment]
@avaidyam 
On deleting study, do we need to delete all the related patients and activities data or will those automatically be deleted?

**Comment by avaidyam** [comment]
@sarithapillai8 Should be automatically handled if you delete the study!

**Comment by sarithapillai8** [comment]
@avaidyam 
So do  you want to delete those related records with different API calls or is that part of delete study API?

**Comment by avaidyam** [comment]
It's part of the Study deletion API already so nothing else to handle.
