### ISSUE TITLE
Disconnect ActivityScheduler from LAMP-server and bring to LAMP-worker repository

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#150]
Activity Scheduler which is used for scheduling notifications via redis has to be a part of Lamp-worker

Solution:

- Remove the Activity Scheduler job and related queues from LAMP-server
- Bring the necessary repo functions to LAMP-worker
- Use Nats pub-sub to listen to the activity update, activity delete, login and logout api. The data just published will be subscribed by LAMP-worker (for a particular topic eg:SCHEDULE_UPDATE.SCHEDULE_DELETE etc)

**Comment by avaidyam** [comment]
> (for a particular topic eg:SCHEDULE_UPDATE.SCHEDULE_DELETE etc)
@Linoy339 Within `LAMP-server`, please re-use existing NATS topics that are based on the API data types (`researcher`, `study`, `activity`, `activity_event`, etc.) and do not create new ones just for `LAMP-worker`.

**Comment by Linoy339** [comment]
Okay. Understood @avaidyam

**Comment by avaidyam** [comment]
@Linoy339 As a heads up for this work item, please use `LAMP-js` to connect to the LAMP server and do not copy over any repository files. (The same usage/API as in `LAMP-dashboard`.)

```
npm i lamp-core
import LAMP from "lamp-core"
LAMP.connect({ accessKey: "test", secretKey: "test", serverAddress: "test.com" })
```

**Comment by Linoy339** [comment]
@avaidyam . Okay

**Comment by Linoy339** [comment]
@avaidyam . Just to confirm:
Along with publishing activity api changes, we have to do the following too:
In the LAMP-server start,
   Instead of calling ActivityScheduler(), we have to fetch activities for valid studies,
   and  publish activity_id. 
   LAMP-worker will be consuming the activity_id via nats. Then, using lamp-core, it will be 
   fetching activity schedules, there by updating every schedules in redis (aws elastic cache) 
   used by LAMP-worker

**Comment by avaidyam** [comment]
@Linoy339 No - `LAMP-server` will not be doing this, only `LAMP-worker`:
1.`LAMP-worker` starts up...
1. Use `LAMP-js` to query API server for active Researchers
    1. Loop through Researchers and query for active Studies
        1. Loop through active Studies and query for Activities
            1. Check whether the activity ID and schedule are already in the scheduler cache
                1. If they are, continue.
                1. If not, add the scheduler cache.
            1. Record the activity ID as visited in a list
1. Remove all cached schedules that were not recorded as visited. 
1. Register a listener (from `LAMP-worker`) for `activity.*` to capture all Activity create/update/delete events.
    1. On create: add ID to scheduler cache.
    2. On update: modify schedule for ID in scheduler cache.
    3. On delete: remove ID from scheduler cache.
1. Register a listener for `participant.*` to capture all Participant create/delete events.
    1. On create: add ID to scheduler cache.
    2. On delete: remove ID from scheduler cache.

This way we are not trying to dump the entire cache and process 5000+ activities all at once each time the `LAMP-worker` (or `LAMP-server`) reloads/starts.

**Comment by Linoy339** [comment]
Okay. Got it @avaidyam . LAMP-server will not be doing this, only LAMP-worker.

Actually, Point No 1 is done. But, Instead of updating the existing schedule, we are removing and inserting it again.
The activity get function in the Activity repository has been tweaked to get with no binary data 
from the query level itself, if ignore_binary is true, so that the function is 
optimized enough  not end up in buffer allocation error
So ,if we rewrite the above :


1. LAMP-worker starts up...
  1.Use LAMP-js to query API server for active Researchers
    -Loop through Researchers and query for active Studies
    -Loop through active Studies and query for Activities
    -Remove the activity ID from cache if existing and reschedule it with the present schedules
  2.Register a listener (from LAMP-worker) for activity.* to capture all Activity create/update/delete events
    -when an activity id gets published, this get removed from scheduler and gets added to the scheduler cache again.

**Comment by avaidyam** [comment]
That makes sense! I think we're on the same page about the implementation, then. 👍

**Comment by Linoy339** [comment]
Okay. 👍

**Comment by Linoy339** [comment]
Sorry. Above should be written as :

LAMP-worker starts up...
**1. Firstly, clear all Schedules from redis cache**
2.Use LAMP-js to query API server for active Researchers
-Loop through Researchers and query for active Studies
-Loop through active Studies and query for Activities
-Take those activities with valid schedules and add to scheduler
3.Register a listener (from LAMP-worker) for activity.* to capture all Activity create/update/delete events
-when an activity id gets published, this get removed from scheduler and gets added to the scheduler cache again.

**Comment by Linoy339** [comment]
👍

**Comment by avaidyam** [comment]
I see - so the difference here is two things:
1. You are not keeping a visited ID list and then removing stale entries afterward, because you are clearing the whole schedule cache at the start and rebuilding it. (That should still be fine for now.)
1. You are not registering a listener for participant IDs, I assume because you are just fetching the list dynamically when the schedule fires instead. (This is a better approach.)

Thanks for the clarification.

**Comment by Linoy339** [comment]
Yes. That's right @avaidyam . 
,

**Comment by Linoy339** [comment]
@avaidyam : Just to know: While we conect using LAMP.connect() in LAMP-worker, do we have to use the admin credentials of LampServer?
There is a need for it to encrypt using crypto js  or any other tool, as it need not to be exposed in Lamp-worker(.env). Right?

**Comment by avaidyam** [comment]
@Linoy339 The parameters for `LAMP.connect()` are access key (`LAMP_ACCESS_KEY`), secret key (`LAMP_SECRET_KEY`), and server address (`LAMP_SERVER_ADDRESS`). These should all be pulled from the environment itself. As you correctly state, they should not be encrypted or anything else. 👍

**Comment by Linoy339** [comment]
Okay. Got it

**Comment by Linoy339** [comment]
@avaidyam 
Can we use like this :
await LAMP.Auth.set_identity({id:accessKey,password:secretKey,serverAddress:server_url})
const researchers =  await LAMP.Researcher.all()

**Comment by avaidyam** [comment]
@Linoy339 Instead of the `set_identity` function you should use `await LAMP.connect(...)` (the same parameters). Otherwise, that is correct.

**Comment by Linoy339** [comment]
Thanks @avaidyam .

**Comment by Linoy339** [comment]
Also, Can we include ignore_binary parameter in allByStudy() which is a method in Activity.service and Sensor.service of Lamp-core?
i.e, can we give a PR for the above in LAMP-core?

**Comment by avaidyam** [comment]
Yes, you can make a PR on `LAMP-js` (the JS API) with this change.

**Comment by Linoy339** [comment]
Okay. I will do that now

**Comment by Linoy339** [comment]
Can you confirm the repository:

https://github.com/BIDMCDigitalPsychiatry/LAMP-js ?

**Comment by avaidyam** [comment]
Yes, that's correct.

**Comment by Linoy339** [comment]
@avaidyam . Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-js/pull/1](https://github.com/BIDMCDigitalPsychiatry/LAMP-js/pull/1)

**Comment by avaidyam** [comment]
To verify that this works for your needs, please `npm install git+https://github.com/BIDMCDigitalPsychiatry/LAMP-js.git`.

**Comment by Linoy339** [comment]
Okay. Thank you

**Comment by Linoy339** [comment]
And this will install latest lamp-core..right?

**Comment by avaidyam** [comment]
Yes.

**Comment by Linoy339** [comment]
Okay. I will test it after doing that.

**Comment by Linoy339** [comment]
@avaidyam . Just to confirm: Can we remove the scheduling part and related queues from LAMP-server completely?
(because LAMP-worker takes the responsibility of the same)

**Comment by avaidyam** [comment]
Yes, please remove it entirely from the server. The collaborators will be informed of this change before deploying any update.

**Comment by Linoy339** [comment]
Okay. Thanks

**Comment by Linoy339** [comment]
@avaidyam . Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/2](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/2)

**Comment by avaidyam** [comment]
@Linoy339 I've merged the PR, but I still see several places (mostly in `app.ts`) with code referencing a direct database connection -- this needs to be refactored to correctly use the LAMP-core package as you've done with the notification scheduling code. Thanks!

**Comment by Linoy339** [comment]
@avaidyam . We do this inorder to take data from scriptpaths database,  which we created to store tokens and scripts.
As you said, we may have to store it in tags then. Do we need to proceed like that?

**Comment by Linoy339** [comment]
Okay.
We will do the above change and push together with LAMP-server changes by tomorrow

**Comment by Linoy339** [comment]
@avaidyam . Just to confirm:  RIght now, the script paths(.zip) are saved in a folder  called uploads in LAMP-worker. This also need to get saved in tag database(as value). Right?

**Comment by avaidyam** [comment]
@Linoy339 Yes, the zip file should converted to base64 to save it directly.

**Comment by Linoy339** [comment]
Okay. 
So, This will be the api to save the token :
https://api.lamp.digital/type/type/7s9ts30kq0w67tdg1qhe/attachment/study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by/me
and the data saved would be 
_id:60a765103a2802fcfcd1e1e7,
_parent:"7s9ts30kq0w67tdg1qhe",
key:"study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by",
type:"me",
_deleted:false,
value:""UEsDBBQAAAAIAEaPclLjtyaAFAAAABIAAAAQAAAAcmVxdWlyZW1lbnRzLnR4dMsoKSko1..."

(7s9ts30kq0w67tdg1qhe-researcher_id)

**Comment by avaidyam** [comment]
No, the key is incorrect. The key is user-defined and for now you should change it to be "lamp.automation" temporarily. The value is correct but may benefit from being a data-url. For example, `data:application/python;base64,UEsDBBQAAAA...." because it allows you to encode the MIME type metadata in-line.

**Comment by Linoy339** [comment]
OKay..Can you please tell where to save token ("study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by",)?

**Comment by avaidyam** [comment]
If you mean that this is the trigger that causes the script to run, you could plug it into the data-url like so:
```
data:application/python;trigger=study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by;base64,UEsDBBQAAAA....
```

**Comment by michaelmenon** [comment]
@avaidyam saving zip file as binary data to DB is not a good idea .

There are two options for this :
 1) Either save the zip to AWS s3 and save the file path total db
2) Save the zip to a server folder and mount that as a volume with the docker container and save the path to tag DB.

Which one should we follow. Saving in AWS s3 would be the best option.

**Comment by avaidyam** [comment]
@michaelmenon Yes, it's clear this is not the best approach but it is the fastest approach. Once this initial version is complete and tested, we can revisit the implementation.

**Comment by Linoy339** [comment]
Thanks for confirming @avaidyam . We will do this way .

Coming to the storage of token("study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by").
1)If we do as said above,  Fetching of data from tag database for a particular token becomes complicated, as the token is mixed in value field .
In the above case we need to query with _parent:researcher_id, key:"lamp.automation". Here, there would be  multiple records with binary data and it would be complicated to fetch (may results in buffer allocation error).
(Please note that we have faced issues while retrieving activities without ignore_binary earlier).

If its stored in key, we can easily fetch the data individually, like we can fetch with _parent:researcher_id, key:"study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by" which gives only 1 data.


2) Regarding the Data Url, we assume only zip file will be uploaded. The reason is that the file uploading will have dependencies. Inorder to include these, we can use zip file, as zip file can be created with the script file with these dependencies all together. The zip usually includes script file, requirements.txt(if any), version.txt(if in case of python, need to identify whether the version is pyhon3 or python2). 
 So to conclude, a zip file in our case can have script  file(.js,.py) alone 
 or script  file(.js,.py) with requirements.txt(eg:node-fetch,https...) and  version.txt(in case of python, we need to identify whether the version is pyhon3 or python2 ) 
 or script  file(.js,.py) with requirements.txt(eg:node-fetch,https...) 
 or script  file(.js,.py) with version.txt(in case of python, we need to identify whether the version is pyhon3 or python2 )

**Comment by avaidyam** [comment]
> If its stored in key, we can easily fetch the data individually, like we can fetch with _parent:researcher_id, key:"study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by" which gives only 1 data.

@Linoy339 This makes sense; please prefix it like so: `lamp.automation.study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by` just for clarity and that should work fine. 

> version.txt(if in case of python, need to identify whether the version is pyhon3 or python2)

We do not and should not support Python 2, so we should eliminate the need for a `version.txt` at all.  Otherwise this approach looks good!

**Comment by Linoy339** [comment]
Will prefix  as lamp.automation.study.cadn2efwhrxkppq9tn9t.activity.pqhm5zd2rbgpt5bjx5by
version.txt will be ignored
Thanks @avaidyam for confirming this.

**Comment by Linoy339** [comment]
@avaidyam .
Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/3](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/3)

**Comment by Linoy339** [comment]
@avaidyam . There was a minor fix. Can you please check this:
[https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/4](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/4)

**Comment by Linoy339** [comment]
@avaidyam . Can you please check [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/102](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/102)

This is regarding the  removal of ActivityScheduler  queues.
