### ISSUE TITLE
Not getting sleep duration value from android app

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#153]
We are using developer team APK file for Android device, we are not getting sleep data.

Here is the sleep data we see in our couchdb
```
"data": [
  {
"timestamp": 1618240969253,
"sensor": "lamp.sleep",
"data": {
"value": 0
}
}
```

**Comment by avaidyam** [comment]
@jeydude [It looks like this PR](https://github.com/BIDMCDigitalPsychiatry/LAMP-core-android/pull/15) might solve the issue you need. It should take a few minutes (up to an hour) to pass through Google Play Store review and land in beta.

**Comment by saranya-sajeev** [comment]
Google fit connection issue in play store 
[MindLamp_04302021.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6406624/MindLamp_04302021.zip)
beta may be fixed only after completing the verification. You can check in the attached build.

**Comment by jeydude** [comment]
Thanks @saranya-sajeev and @avaidyam, we will try the apk file and let you know. Thanks for the apk file!

**Comment by jeydude** [comment]
@saranya-sajeev, we got the sleep data only for one day after that we are not getting

here is one of the android user data with latest timestamp. User is actively using the wearable, apps.
![image](https://user-images.githubusercontent.com/841011/117187754-ddf39480-ada1-11eb-8782-802f202e7165.png)

**Comment by saranya-sajeev** [comment]
Is sleep data showing in Google fit for other days?

**Comment by jeydude** [comment]
We can see the sleep data in Google Fit for all the days but not in mindLAMP database. We are using your APK file - MindLamp_04302021.zip for android. 

Attached Log file here, I do not see any error with sending sensor data. 
[LampLog-09082021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6435316/LampLog-09082021.txt)

Let me know if you need anything else. Thanks!

**Comment by saranya-sajeev** [comment]
Ok I will check.
