### ISSUE TITLE
Changing the Mongoose to native Mongo driver of node js.

### ISSUE THREAD

**Issue by ZCOEngineer** [BIDMCDigitalPsychiatry/LAMP-platform#155]
**Describe the bug**
use native drivers for MongoDB node js driver.
https://docs.mongodb.com/drivers/node/fundamentals/connection/

**Comment by Linoy339** [comment]
Please find :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/89](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/89)
