### ISSUE TITLE
Implement Cortex Features

### ISSUE THREAD

**Issue by jlavoie9** [BIDMCDigitalPsychiatry/LAMP-platform#157]
# Primary Feature Tracker

## Screen Active

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested
### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:
### Misc.
Any other notes/issues with this feature

## Significant Locations

| Assigned To |
|-|
| @rydmel  |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`: 'U3365978523' 
- Params `(start, end, resolution)`:
### Misc.
Any other notes/issues with this feature

## Sleep Periods

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Survey Scores

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Trips

| Assigned To |
|-|
| @rydmel  |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

# Secondary Feature Tracker

## Active Duration

| Assigned To |
|-|
|@rydmel  |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Call Degree

| Assigned To |
|-|
| @jlavoie9   |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Call Duration

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Call Frequency
| Assigned To |
|-|
| |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Call Number

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## FastDTW

| Assigned To |
|-|
| @rydmel  |

### Status:
- [x] Code Exists
- [x] Code Refactored
- [x] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature:
-this should be deleted and will just be in similarity measures

## Entropy

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Fragmentation

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Frechet

| Assigned To |
|-|
| @rydmel  |

### Status:
- [x] Code Exists
- [x] Code Refactored
- [x] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature
- this should probably be deleted since it's in similarity measures

## Hometime

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Screen Duration

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Sedentary Duration

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Similarity Measures

| Assigned To |
|-|
| @rydmel  |

### Status:
- [x] Code Exists
- [x] Code Refactored
- [x] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Sleep Duration

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## SMS Number

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Survey Results

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Trip Distance

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

## Trip Duration

| Assigned To |
|-|
| @jlavoie9 |

### Status:
- [ ] Code Exists
- [ ] Code Refactored
- [ ] Code Tested

### Testing info:
Find a good testing participant for this feature
- Participant`(id)`:
- Params `(start, end, resolution)`:

### Misc.
Any other notes/issues with this feature

# Additional Issues:
Add any other general cortex issues 
- Need a flag so that unsaved features (ex: similarity measures) are only calculated when requested
- Need a flag that allows specific features not to be saved
- I think the window is not inclusive of end time, which is a bit unnatural

**Comment by avaidyam** [comment]
I just tested surveys and it worked fine! (No test case yet though - will edit that in later.) (This is also a test comment.)

**Comment by ryan-hays** [comment]
Should we be doing implementation tracking here or in 'Projects/LAMP Cortex'?

**Comment by jlavoie9** [comment]
> Should we be doing implementation tracking here or in 'Projects/LAMP Cortex'?

Here is better, I can delete 'Projects/LAMP Cortex' because projects didn't leave us space for the testing details like there is here

**Comment by avaidyam** [comment]
Yup I think this issue is for individual components/features and the LAMP Cortex project will be for broader things (this issue should be part of that tracker, nested, basically).
