### ISSUE TITLE
Event querying upper limit 

### ISSUE THREAD

**Issue by jlavoie9** [BIDMCDigitalPsychiatry/LAMP-platform#158]
**Describe the bug**
When querying SensorEvents, CouchDB upper limit was not inclusive, but now with MongoDB , the upper limit is inclusive:

**To Reproduce**
### With CouchDB:
```
LAMP.connect(os.environ['LAMP_ACCESS_KEY'], os.environ['LAMP_SECRET_KEY'],'api2.lamp.digital')
LAMP.SensorEvent.all_by_participant('U5456960690',origin='lamp.accelerometer',to=1603910639535)
```
 **Returns:**
`{'data': []}`

### With MongoDB:
```
LAMP.connect(os.environ['LAMP_ACCESS_KEY'], os.environ['LAMP_SECRET_KEY'],'api.lamp.digital')
LAMP.SensorEvent.all_by_participant('U5456960690',origin='lamp.accelerometer',to=1605129652233)
```
**Returns:**
```
 {'data': [{'timestamp': 1605129652233,
   'sensor': 'lamp.accelerometer',
   'data': {'x': 0.01031494140625,
    'y': 0.003021240234375,
    'z': -0.9908294677734375}}]}
```

**Expected behavior**
Should return the empty list as CouchDB did

**Comment by Linoy339** [comment]
@avaidyam . Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/83](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/83)

**Comment by avaidyam** [comment]
@jlavoie9 When you confirm that this behavior fixed I can close the issue. Thanks!
