### ISSUE TITLE
Cortex dependency integration into Dockerfile

### ISSUE THREAD

**Issue by ryan-hays** [BIDMCDigitalPsychiatry/LAMP-platform#159]
Some dependencies needed for LAMP-cortex are "lost" in the LAMP-ide when the docker compose file is updated. All dependencies are listed in the `LAMP-cortex/setup.py`; can we either dynamically pull those dependencies and add them to the Dockerfile, or manually keep them updated?

**Comment by avaidyam** [comment]
[Can you create a `requirements.txt` file for LAMP-cortex?](https://realpython.com/lessons/using-requirement-files/) This would likely solve the issue from the `LAMP-cortex` side (and we can resolve the `LAMP-ide` issue separately too).

**Comment by ryan-hays** [comment]
> [Can you create a `requirements.txt` file for LAMP-cortex?](https://realpython.com/lessons/using-requirement-files/) This would likely solve the issue from the `LAMP-cortex` side (and we can resolve the `LAMP-ide` issue separately too).

`requirements.txt` is now in `master`

**Comment by avaidyam** [comment]
Thanks!! Let's leave this open for next week so we can fix the IDE issue too!
