### ISSUE TITLE
SensorEvent batch update inorder to reduce the frequent database write 

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#160]
The sensor events comes in large size in frequent intervals and writing to database these kind of data is becoming complicated

Solution Proposed: Write to redis until certain number gets exceeded for the sensor events(for example, say 50000). When the number of events gets exceeded, write to database from redis store via a queue. 
Lamp. Analytics is excluded in this, as it comes in smaller number. Also, it need to be saved immediately

**Comment by Linoy339** [comment]
@avaidyam . Please find[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/82]( https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/82)

**Comment by avaidyam** [comment]
@Linoy339 @michaelmenon Remaining issues: 
1. Retrieving sensor event data should first query the cache to see if it can fill `limit` events from there, and if not, then check the database. 
2. If Redis is not configured then fall-back to the original straight-to-database behavior.

**Comment by avaidyam** [comment]
A significant issue (memory leak) is now propping up: 

```
<--- Last few GCs --->

[1:0x55c0fb532f40]   429476 ms: Mark-sweep 1986.9 (2073.3) -> 1971.3 (2068.0) MB, 1337.3 / 0.0 ms  (average mu = 0.170, current mu = 0.061) allocation failure scavenge might not succeed

[1:0x55c0fb532f40]   430844 ms: Mark-sweep 1988.6 (2068.3) -> 1973.3 (2072.0) MB, 1280.8 / 0.0 ms  (average mu = 0.120, current mu = 0.064) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by Linoy339** [comment]
@avaidyam . It seems like the large amount of data wrtes(at present, it is 50000) causing the issue, 'JavaScript heap out of memory'.
Can you please reduce its number, which can be done in src/utils/queue/BulkDataWrite.ts

**Comment by michaelmenon** [comment]
@Linoy339  how are we writing to DB are you taking the whole 50K from queue in memory and try gin to write ? Then this issue will come. that is not the correct way. write in batch I mean take data in small batches from the Redis queue and write it to DB.

**Comment by avaidyam** [comment]
@Linoy339 I agree with @michaelmenon - the 50k number needs to be **raised, not reduced**. Right now  50k events fill up in about five seconds. There's a memory leak somewhere that needs to be addressed it seems.

**Comment by michaelmenon** [comment]
Yes we need to take 500 items at one time and write back to DB and loop on this until the whole Queue is not written back to DB. Taking 50k at once in heap memory will cause out of memory crash.

**Comment by Linoy339** [comment]
@avaidyam. We need to tweak the code liitle bit. We will test it and give a PR by tomorrow.

> @Linoy339 @michaelmenon Remaining issues:
> 
> 1. Retrieving sensor event data should first query the cache to see if it can fill `limit` events from there, and if not, then check the database.:Can you confirm: The api, participant/:participant_id/sensor_event should be tweaked to give priority to cache instead of database. If so, the data should not be saved in the cache with format which we have done now. Instead, we have to save it with the key as participant_id(for example, U1234567789:sensor_event). 
> 2. If Redis is not configured then fall-back to the original straight-to-database behavior: This can be done.

**Comment by Linoy339** [comment]
If Redis is not configured then fall-back to the original straight-to-database behavior:

If this happens, notifications also won't work. Right?
   Do we need to implement a common solution for all(eg: make a flag cache_enabled in .env and make use of the redis cache, if its true. If done like this, we might have to check everywhere we use redis cache mechanism that include notification firing too.)? 
  
  Can you suggest ?

**Comment by Linoy339** [comment]
@avaidyam . Got it.
But, a concern of publishing large sensor_event data in nats server is there. 
As  we are keeping  a separate redis instance in Lamp-server too, we can overcome that which we believe.

**Comment by avaidyam** [comment]
Should it overwhelm NATS, we can artificially rate-limit or size-limit it somehow. (i.e. if Patient X uploads 500 sensors events of type `lamp.gps`, only push the very last `lamp.gps` event instead.)

**Comment by avaidyam** [comment]
Hmm, I'm not quite following. It's my understanding that this is the workflow: 
1. Data enters the `SensorEventService.create()` function.
1. IF caching enabled (i.e. `REDIS_HOST` env exists):
    1. Push all data to Redis (`BulkDataWrite`). 
    1. If number of cached events > threshold, spawn background process/thread.
        1. Flush Redis cache to database. (May take ~1500ms.)
        1. Notify NATS subscribers of latest events.
1. ELSE: 
    1. Push data to database directly.
    1. Notify NATS subscribers of latest events.
1. Return success to API client. (Entire request should always take ~5ms or less if caching enabled.)

**Comment by Linoy339** [comment]
Okay. Got it.
I was in a confusion of dumping these bulk events  to database from Lamp-worker side. 
Now its  clear. So, its only the latest data to go to nats consumer, which make a good solution.

Thanks @avaidyam

**Comment by avaidyam** [comment]
@Linoy339 That's correct, glad to help! The `LAMP-server` (API Server) component will still basically be in charge of database/caching, vending the API, and allowing listeners to be notified of data changes. The `LAMP-worker` component will use the API and listen to changes to (1) update push notification schedules, (2) invoke automations code.
