### ISSUE TITLE
Cortex documentation

### ISSUE THREAD

**Issue by Ashermind** [BIDMCDigitalPsychiatry/LAMP-platform#161]
**Problem:**
I am well aware that Cortex is in alpha stages of development but I find the documentation lacking.

**Solution**
I would like to see a bit more in depth documentation of current Cortex, even if not finished yet. The current "theoretical" overview of features in docs.lamp.digital nor the README on github seems to provide enough information for usage without the need to dig in the source code of the package.
It is not a feature I find particularly important, but it would most certainly be nice to have.

**Comment by avaidyam** [comment]
@Ashermind We've just made our first (beta) release of Cortex! [You can find the documentation here.](https://docs.lamp.digital/cortex_example) Please let us know (or make a pull request) if you have any documentation suggestions.
