### ISSUE TITLE
BETA application is crashing on iOS devices

### ISSUE THREAD

**Issue by Ashermind** [BIDMCDigitalPsychiatry/LAMP-platform#162]
**Describe the bug**
The beta app is crashing on iOS mobile devices.

**To Reproduce**
1. Install the app via TestFlight app
2. Run the application
3. Log in
4. The app crashes by itself

**Expected behavior**
The app should be working without these crashes.

**Smartphone 1:**
 - Device: iPhone 11 pro
 - OS: iOS 14.4.2
 - App Version: 2021.1.21 (257)
 
 **Smartphone 2:**
 - Device: iPhone 12 pro
 - OS: iOS 14.4.2
 - App Version: 2021.1.21 (257)
 
 **Smartphone 3:**
 - Device: iPhone Xr
 - OS: iOS 14.4.2 
 - App Version: 2021.1.21 (257)

**Comment by jijopulikkottil** [comment]
I think the crash started with the builds which using new API library which use Combine framework. I will investigate and update.

**Comment by avaidyam** [comment]
@jijopulikkottil Thanks for the investigation! Please ping us back here when you find the source of the crashes!

**Comment by jijopulikkottil** [comment]
here is a related discussion https://forums.swift.org/t/easy-to-reproduce-combine-crash-involving-future-and-concurrency-memory-leak/36334.

**Comment by jijopulikkottil** [comment]
@Ashermind We have done some improvements. Could you please check with new beta build (265).

**Comment by Ashermind** [comment]
@jijopulikkottil The app is stable but we have another issue.
bidmcdigitalpsychiatry/lamp-server:2021@sha256:d29f8a21b4ce8579b5d1538e5010755b7fb671f4e7f674de0e1c78d2ef56e334
