### ISSUE TITLE
Breathe with audio ends abruptly and also logs out the user

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#17]
Basecamp Conversation
---
> **Collaborator**: If an audio file is provided, the duration of the breathing exercise should match the length of that audio file. The breathing exercise is also taking the user back to the home screen instead of the screen they were previously at before opening the activity.
>
> @sarithapillai8: **This can be updated by Monday after QA.**

**Comment by avaidyam** [comment]
@sarithapillai8 While testing in staging, I notice that the Breathe activity timer is still 2min (static) even if an audio file is provided, and when doing the meditation, it cuts off at this 2min mark.

**Comment by sarithapillai8** [comment]
@avaidyam 
Ok sorry I misunderstood the requirement. We can update.

**Comment by avaidyam** [comment]
@sarithapillai8 Great! To re-iterate:
1. Breathe shall have two settings: (1) the audio upload/url, and (2) duration in minutes.
1. When Breathe is loaded: 
    1. If audio is provided, then the length of the audio is used as the timer.
    1. If no audio is provided (`null` value), then the `duration` parameter its used as the timer.
    1. If no audio is provided, and no `duration` parameter is provided (both `null`), then default to a 2 minute timer.
