### ISSUE TITLE
Assess icons and descriptions not displaying 

### ISSUE THREAD

**Issue by jlavoie9** [BIDMCDigitalPsychiatry/LAMP-platform#170]
The first time the Assess page loads in the app the icon and description from `lamp.dashboard.activity_details` are not loaded. You have to click out to another tab, then click back to Assess for the icons and description to display properly. 

This is  important since we need to use the description to give instructions to the participant before they complete the activity. Currently, we have no way of telling whether the participant saw the instructions or not. See below video for example.

https://user-images.githubusercontent.com/67972674/115598400-635a4d80-a2a8-11eb-8255-6dff894016ff.mp4

**Comment by avaidyam** [comment]
It seems like it's an error for the dashboard to check `activity_details` tag and it should instead be using `activity.description` or `activity.icon`, etc.
