### ISSUE TITLE
App is automatically logging out when closed

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#171]
> Issue - The app logs out immediately when the App is closed. 
Background - I am using an android mobile phone -(Moto g6, Android 
version-9) and currently I am using it for research purposes. 
I have been given a username and password(with lamp domain eg: 
xyz@lamp.com)
and after I login after sometime, if I open the app again, I 
automatically just logout from the app.
![image](https://user-images.githubusercontent.com/82968538/115600135-563e5e00-a2aa-11eb-9665-280e0d0a83ce.png)

Also occurs on samsung s10e.

**Comment by SuruPa00** [comment]
@ZCOEngineer  was this issue ever looked at?

**Comment by saranya-sajeev** [comment]
@SuruPa00 Issue is not reproduced here. Could you please check in latest beta build?

**Comment by avaidyam** [comment]
@saranya-sajeev @sarithapillai8 @jijopulikkottil @ZCOEngineer  @michaelmenon 

This issue has been reproduced MANY times and our team has seen this issue happen to patients with our own eyes in many cases. We have closed many duplicate issues and redirected those to this issue. Please continue to reproduce the issue - it WILL happen at one point or another. **If I have logged in at all on dashboard or in iOS/Android apps, I should NOT see the login screen ever again until I have manually chosen to log out.** We need to squash this issue for good once and for all.

**Comment by saranya-sajeev** [comment]
Is this issue exists in all platforms or only in Android?

**Comment by ZCOEngineer** [comment]
@saranya-sajeev, @jijopulikkottil This is happening randomly on both iOS and Android. So lets check both platforms.

**Comment by jijopulikkottil** [comment]
@SuruPa00 We are trying to reproduce it. Hope the issue is getting with production server and using the app in app-store.
On mobile app, it will send a "logout" lamp.analytics event when receive a logout action. So could you provide login details of a user who got this issue to check sensor events.

**Comment by jijopulikkottil** [comment]
To reproduce the issue, could you give us a credentials of existing participant (or create new one under same researcher and study) which we experience the logout issue ?

**Comment by saranya-sajeev** [comment]
@SuruPa00 is user logging in to the demo account after exiting from the app in this case?

**Comment by SuruPa00** [comment]
@saranya-sajeev i believe the account was a normal one, not a demo, and @jijopulikkottil  this was an external collaborator so i will reach out and get back to you about creating a test user under their study

**Comment by ZCOEngineer** [comment]
@SuruPa00 could you also see if the logout issue is still there?

**Comment by SuruPa00** [comment]
@ZCOEngineer yes will test and check w the people who reported the issue!
