### ISSUE TITLE
Notification icon on app won't go away

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#172]
> There is a notification icon on the app that I cannot be removed. It says 1. I open the app and there seems to be nothing to do in it and even when I close out there is still a notification on the app.

**Comment by avaidyam** [comment]
If this is an Android device, this is not a bug. Android requires mindLAMP to display a persistent (non-dismissible) notification that informs the user that data collection is ongoing in the background.
