### ISSUE TITLE
LAMP thinks its Sunday when its actually Friday

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#173]
> not clear why there is a large circle on Sunday, this was taken on a Friday
![image](https://user-images.githubusercontent.com/82968538/115599925-21320b80-a2aa-11eb-9d64-62626b818966.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
We are not able to reproduce this. We tried changing timezone also. Could you please confirm ?
