### ISSUE TITLE
Custom icons are compressed and pixellated if uploading an SVG file

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#18]
Please make sure that if the user uploads an SVG icon we are not compressing it somehow or minimizing its size. SVG icons are very small and always crisp and do not need compression, but PNG icons are where we should continue to compress the image.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
For Tips only the icons are compressed(except SVG) and the tip details are not compressed.
All the rest of the Activities are also compressed(except SVG).
