### ISSUE TITLE
Badge for completing a survey does not show up when you access the survey from the Feed

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#183]
> When I complete the survey from the push notification pipeline (instead 
of navigating from the app directly), once I respond to the last 
question and hit submit, the screen remains on the page with the last 
question. When I hit the back button (top left arrow), I was taken to 
the blank login page, so it was unclear whether my responses saved. 
Other times when I hit the back button, I was taken to the mindLAMP home
 page (I didn't notate whether this was the feed or the assess tab). 
Either way, it would be preferable to see the badge and be automatically
 routed to the home page after hitting submit, and avoid having to hit 
that back button. 
(this does not appear to happen when I initiate the survey from assess 
tab directly - after I hit submit I see the badge saying "nice work!" 
and am led back to the assess tab)

**Comment by SuruPa00** [comment]
this issue has since been resolved
