### ISSUE TITLE
Seems to be a leftover schedule for activities from 1969?

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#185]
> This is honestly such a small issue, but whenever I create an activity group, there's always a schedule that shows up from 1969. It might not matter because it is set on do not repeat, but it seems weird.
![image](https://user-images.githubusercontent.com/82968538/115604070-eed6dd00-a2ae-11eb-87e5-24a40902c90a.png)

**Comment by sarithapillai8** [comment]
@avaidyam 
Updated the group activity creation  without schedule - 
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/213
