### ISSUE TITLE
When you're importing an activity, if the file is too large there needs to be a pop-up telling you so you know why it won't upload

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#190]
> When you try to "import activity" into mindLAMP, it will not go. It seems like the issue is that you're trying to upload too many things, but the issue is there is no pop-up or anything that says like "file too large" it just looks like nothing happened. I think even just adding that pop-up would be helpful because it took me a while to understand why the activities weren't being uploaded.

**Comment by SuruPa00** [comment]
this issue has been updated
