### ISSUE TITLE
Icons for surveys show up in "Assess" but not in the Feed

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#192]
> icon shows up under assess but not when task is assigned in feed
![image](https://user-images.githubusercontent.com/82968538/115605639-be903e00-a2b0-11eb-8cd1-f551f48aaaae.png)
![image](https://user-images.githubusercontent.com/82968538/115605646-c223c500-a2b0-11eb-92cf-793052b7639f.png)

**Comment by avaidyam** [comment]
Duplicate of #170!
