### ISSUE TITLE
Question description and option description fields displaying incorrectly

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#194]
> This applies to the slider question format. Since the question options 
> are restricted to numerical, I tried to use the "Question Description" 
> field to elaborate. However, when I do this, the survey displays 
> incorrect text on the user view (on the survey editing screen within my 
> researcher dashboard, I wrote "0: low; 1: medium; 2: high" under 
> Question Description; but on the phone view of the survey, I just see 
> "(0 being 0, 2 being 2)". 
> 
> If I try to leverage the "Option Description" field but leave the 
> Question Description blank, on the user end it looks like the Question 
> Description pulls from the first and last option description; but the 
> additional text below the slider only includes 3/4 options descriptions 
> and the text under "your response" does not fit in the window.

> ![image](https://user-images.githubusercontent.com/82968538/115606974-5e9a9700-a2b2-11eb-9d5a-02f16f8b4317.png)

> ![image](https://user-images.githubusercontent.com/82968538/115606992-64907800-a2b2-11eb-8b27-e75b221cb315.png)

> ![image](https://user-images.githubusercontent.com/82968538/115607007-6a865900-a2b2-11eb-8105-99fe9c2eed61.png)

> ![image](https://user-images.githubusercontent.com/82968538/115607025-6f4b0d00-a2b2-11eb-86b8-969957885e11.png)

**Comment by SuruPa00** [comment]
This issue is no longer relevant/has not appeared
