### ISSUE TITLE
App crashes when attempting to log in (Androids)

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#202]
> mindLAMP application is not able to login, it crashes while trying to login the android devices we have tried few android devices (Samsung, HTC, Moto).
![image](https://user-images.githubusercontent.com/82968538/115608268-0d8ba280-a2b4-11eb-9cce-0b4ad096d872.png)

**Comment by jeydude** [comment]
Hi, That's my android phone screen, can you remove it. Thanks!

**Comment by avaidyam** [comment]
@jeydude I have removed the first screenshot, and the second screenshot contains no identifiable content. Thanks for letting us know!

**Comment by avaidyam** [comment]
This is resolved in recent beta versions and will be publicly released soon.
