### ISSUE TITLE
"Back" and "Submit" buttons overlap on long surveys

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#203]
> A colleague reports that with a long survey question the "back" and "submit" buttons are overlapping the answer options (see screenshot).
![image](https://user-images.githubusercontent.com/82968538/115608425-3ca21400-a2b4-11eb-9262-1c0b0d8c8d5b.png)

**Comment by avaidyam** [comment]
Duplicate of #98!
