### ISSUE TITLE
Android user unable to log in

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#208]
> Participant on an android is not able to log in.
![image](https://user-images.githubusercontent.com/82968538/115609347-6a3b8d00-a2b5-11eb-9cab-3c244c7193d0.png)
![image](https://user-images.githubusercontent.com/82968538/115609384-758eb880-a2b5-11eb-98c3-2ac1a5337bf8.png)

**Comment by avaidyam** [comment]
Potential duplicate of #202 and should be resolved.
