### ISSUE TITLE
Survey screen jumping back to top before you can hit "not at all"

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#21]
> We try scrolling upward which shows the option briefly, but it just jumps right back making it difficult for the participant to select “not at all”. I have included a video. Is there a way to prevent the screen from jumping back if the person scrolls down? (see video below)

**Comment by michaelmenon** [comment]
This needs to be closed for now until we get the screenshot or vide of the issue
