### ISSUE TITLE
Graphs aren't formatted correctly when viewing from Prevent tab in app

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#210]
> When I go to prevent in the app and view data for my DBT Diary Card, it opens to a graph zoomed in. I can't see any of the other graphs and the formatting is way off
![image](https://user-images.githubusercontent.com/82968538/115609794-fe0d5900-a2b5-11eb-9a70-a3aa2de31272.png)

**Comment by avaidyam** [comment]
Duplicate of #416!
