### ISSUE TITLE
Sometimes, 1 message will be sent MANY times (both TO and FROM app)

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#213]
> so, this has also happened to me, but i thought i was doing something wrong. but it seems like sometimes when you send a message it sends MANY times. See the pic.
>
> U5708776312
>
>![image](https://user-images.githubusercontent.com/82968538/115610612-1c278900-a2b7-11eb-8ff1-b1796444dc5b.png)

**Comment by SuruPa00** [comment]
This issue is no longer present
