### ISSUE TITLE
Very slow when logging in

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#22]
This sounds like it could be similar to the Manage tab issue we had before where the spinner was never cancelled once data was loaded.

> **Collaborator**: We’ve noticed that sometimes, logging in to Mind Lamp 2, there will be a significant loading time. We will get this screen below for several minutes at a time… and sometimes you have to close the app entirely because it seems as if its “timed out”

![image](https://user-images.githubusercontent.com/1361003/98567948-8a830c80-227e-11eb-833b-030c3ccda0a6.png)

Basecamp Conversation
---
> @michaelmenon: Can we check if its just a simple issue of spinner not getting cancelled ? please confirm.
> 
> @avaidyam: Unfortunately they did not give any console logs/other diagnostic info...
>

**Comment by michaelmenon** [comment]
We can close this issue for now and reopen once we get more info or if it happens again

**Comment by jennymelcher** [comment]
It seems like the new update has brought back extremely long loading times on the dashboard. For a project with about 250 users, the dashboard has been loading for 25 minutes and still is not done loading. This probably needs more investigation because it makes the dashboard hard to use.

**Comment by avaidyam** [comment]
@jennymelcher It looks like the issue has been resolved in staging and will soon be in production so I’ll close this again for now. 
@michaelmenon I think for our next major sprint we should add #16 as a major focus to resolve these recurring issues.
