### ISSUE TITLE
How to add Smartphone Cognitive Tests to a study?

### ISSUE THREAD

**Issue by nsrilakshmi96** [BIDMCDigitalPsychiatry/LAMP-platform#220]

**Comment by rbilden** [comment]
Hi @nsrilakshmi96 here is the link to an article that should help: https://docs.lamp.digital/create_activities
Please check out [docs.lamp.digital](docs.lamp.digital) for more "how to" information!

**Comment by nsrilakshmi96** [comment]
Hi @rbilden, thank you for your response. I don't see the cognitive tests to add an activity in the dashboard. I have attached a screenshot for your reference. 
![Capture](https://user-images.githubusercontent.com/46331228/115951826-7d8e6880-a500-11eb-9374-9ee1896e29b6.PNG)

**Comment by rbilden** [comment]
@nsrilakshmi96 can you scroll down once you open that menu? The activities should be below "Smartphone Cognitive Tests." If not, then this is a bug and you can submit a bug report here: https://docs.lamp.digital/bug

**Comment by avaidyam** [comment]
@nsrilakshmi96 Is this a self-hosted server? (i.e. not `api.lamp.digital`)

**Comment by nsrilakshmi96** [comment]
@avaidyam Yes, this is a self-hosted server.

**Comment by avaidyam** [comment]
@nsrilakshmi96 If you have access to the database, please try calling this command: 

```bash
curl -XPOST https://admin:YOUR_PASSWORD@YOUR_DATABASE_URL/activity_spec/_bulk_docs -H 'Content-Type: application/json' --data "{"_docs":[{"_id":"lamp.3d_figure_copy"},{"_id":"lamp.balloon_risk"},{"_id":"lamp.breathe"},{"_id":"lamp.cats_and_dogs"},{"_id":"lamp.cats_and_dogs_new"},{"_id":"lamp.dbt_diary_card"},{"_id":"lamp.digit_span"},{"_id":"lamp.group"},{"_id":"lamp.jewels_a"},{"_id":"lamp.jewels_b"},{"_id":"lamp.journal"},{"_id":"lamp.nback"},{"_id":"lamp.nback_new"},{"_id":"lamp.pop_the_bubbles"},{"_id":"lamp.scratch_image"},{"_id":"lamp.serial7s"},{"_id":"lamp.simple_memory"},{"_id":"lamp.spatial_span"},{"_id":"lamp.spin_wheel"},{"_id":"lamp.survey"},{"_id":"lamp.temporal_order"},{"_id":"lamp.tips"},{"_id":"lamp.trails_b"},{"_id":"lamp.trails_b_dot_touch"},{"_id":"lamp.trails_b_new"},{"_id":"lamp.visual_association"}]}"
```

**Comment by nsrilakshmi96** [comment]
@avaidyam the underscore before docs gives an error in the curl command saying 'post body must include docs parameters', after removing the underscore, curl command ran. I am now able to see Smartphone Cognitive Tasks in the dashboard. Thank you!

**Comment by avaidyam** [comment]
@nsrilakshmi96 Fantastic - great debugging skills! I've updated my original comment and removed the underscore.

This appears to be a similar duplicate of #119 except affecting Activity configuration and not Sensor configuration. (This is also a pretty minor item and will be resolved in the next major release.)
