### ISSUE TITLE
Daily streak resets and question numbers missing

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#222]
> The days resume from day 1 or day 2, even on 8th or 9th day of taking the survey. And, the question number is not displayed.
An NIH patient also had the same issue of question numbers not showing up
![image](https://user-images.githubusercontent.com/82968538/116083633-d712a680-a66a-11eb-8475-35801db97f48.png)
![image](https://user-images.githubusercontent.com/82968538/116083643-dbd75a80-a66a-11eb-8312-871fa57c0b27.png)

**Comment by SuruPa00** [comment]
This bug appears to be resolved
