### ISSUE TITLE
Missing Jewels numbers 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#223]
> Cannot see the number "4" in a pair, as per the rules of the game "Jewel B"; therefore, cannot complete the game.
![image](https://user-images.githubusercontent.com/82968538/116083829-1640f780-a66b-11eb-80f3-4d5309476ba8.png)

**Comment by avaidyam** [comment]
Duplicate of #96.
