### ISSUE TITLE
Streak discrepancies across jewels A and B in Hindi 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#224]
> For "Jewels B", it showed Day-1 when I used the app in Hindi after game completion, but for "Jewels A" and the two surveys, it showed "Day-4"
![image](https://user-images.githubusercontent.com/82968538/116083975-45efff80-a66b-11eb-9653-2336e63ac4f8.png)
![image](https://user-images.githubusercontent.com/82968538/116083983-49838680-a66b-11eb-9f04-04cb5df8ebb8.png)

**Comment by avaidyam** [comment]
Duplicate of #105 and #222.
