### ISSUE TITLE
DBT Appearance and Survey Functionality Issues

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#227]
> The Diary Card under "Assess" looks off. Also, some of the functionality is off: e.g. can't press some of the radio buttons. After restarted the app several times, it looked how it was supposed to one time. However, on trying again multiple times, seeing the same errors as in the attached screenshots.
![image](https://user-images.githubusercontent.com/82968538/116405216-651e9680-a7fd-11eb-9830-905a0ed065cc.png)
![image](https://user-images.githubusercontent.com/82968538/116405228-694ab400-a7fd-11eb-9305-408a7957acf6.png)
![image](https://user-images.githubusercontent.com/82968538/116405245-6d76d180-a7fd-11eb-9388-5bfddbfa90f3.png)
![image](https://user-images.githubusercontent.com/82968538/116405264-736cb280-a7fd-11eb-90b3-19c6c856516a.png)
![image](https://user-images.githubusercontent.com/82968538/116405287-79fb2a00-a7fd-11eb-8e03-cdaefcd6fd71.png)
![image](https://user-images.githubusercontent.com/82968538/116405300-7e274780-a7fd-11eb-8cab-7eb1818ec374.png)
![image](https://user-images.githubusercontent.com/82968538/116405317-82536500-a7fd-11eb-80ad-09aac62bc356.png)
![image](https://user-images.githubusercontent.com/82968538/116405327-867f8280-a7fd-11eb-985f-f73287dad515.png)
![image](https://user-images.githubusercontent.com/82968538/116405344-8aaba000-a7fd-11eb-95a4-477154fb979b.png)
![image](https://user-images.githubusercontent.com/82968538/116405389-972ff880-a7fd-11eb-8983-4ef3b414bfcd.png)
![image](https://user-images.githubusercontent.com/82968538/116405362-8f705400-a7fd-11eb-929b-48515a5c28d1.png)

**Comment by avaidyam** [comment]
This was resolved.
