### ISSUE TITLE
Cortex caching implementation

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#234]
The proposed implementation for the Cortex caching system is as follows:

### Overview
![Untitled](https://user-images.githubusercontent.com/1361003/116569299-41c81a00-a8d7-11eb-9e56-9855df4424eb.png)
* The blue boxes represent already-cached calls to a Cortex feature function, and the gray boxes represent un-cached calls to a Cortex feature function. 
* The check-mark indicates that the feature function has already processed data and the cache was able to retrieve the data immediately without re-running the feature function code. 
* The refresh icon indicates that the cache for this feature function did not exist before, but the feature function code is being run now and the resulting data is being cached upon completion. 
* The waiting icon (three dots) indicates that this feature function did not have cached data before, and an identical copy is currently executing; upon completion of that separate already-executing invocation of the function, that invocation's resulting cache is used.

### Details
1. We will use Pickle files (example below) to transiently cache native Python objects to disk as part of the `_feature_types.py` code. 
    ```python
    import pickle
    try:
        df = pickle.load(open("_cache.pickle", "rb"))
    except (OSError, IOError) as e:
        df = cortex_function_call_goes_here(**kwargs)
        pickle.dump(foo, open("_cache.pickle", "wb"))
    ```
2. Caching will be implemented for `raw`, `primary`, and `secondary` features and will be optional.
3. The cache location should be determined by the `CORTEX_CACHE_DIR` environment variable, which should default to `~/.local/cortex/`. 
    * If this is changed to `/data/cortex_cache/`, for example, for a multi-user system, all users of that system that run and work with cortex data can share the cache.
4. Cache files will be named like so: `{feature name}_{id}_{start}_{end}_{param1}_{param2}.pickle`, where `param1`/`param2` indicate the list of parameters provided to that specific invocation of the feature function.
5. [Optionally use `compress_pickle` instead](https://lucianopaz.github.io/compress_pickle/html/) to save disk space if it becomes an issue in the future.
6. When a feature function is to be executed, the wrapping decorator will first check if the matching cache exists, and load that. If not, the function is invoked and the cache is generated afterwards. 
    - The decorator code will create and hold a **file lock** for the cache before the function is even called.
    - If two invocations occur simultaneously, the second invocation will be be forced to wait until the file lock is released by the first invocation.
    - At this point, the first invocation has returned the newly-cached data, and the second invocation will ALSO return the newly-cached data.

### Advanced
1. Cache management functions will be provided to work directly with pickle files or import/export a bundle of pickles together.
    1. `cache_clear(...)`: Deletes a cache file matching the exact id and parameter set combination or patterns (i.e. delete ONLY all GPS feature caches).
    2. `export(...)`: Bundles the entire cache directory into a single Tar file and use GZ to highly compress it (`.tar.gz` file), but rename this file to `.lamp`.
    3. `import(...)`: Imports a `.lamp` file by unpacking the caches within the file into the current cache directory.

### Example

```python
from cortex import gps

# This first invocation will be executed and data is fetched from the API directly.
df1 = gps("U1234", 1619600000000, 1619700000000)
# The data has already been cached for us by the feature decorators as: gps_U1234_1619600000000_1619700000000.pickle

# This second invocation will NOT actually be executed, as the pickle file exists, so it will be read from instead.
df2 = gps("U1234", 1619600000000, 1619700000000)
assert df1 == df2, "These DFs should be identical!"

# Now with the addition of fake_param, Cortex believes this to be semantically different data.
df3 = gps("U1234", 1619600000000, 1619700000000, fake_param=100)
# The data is newly cached for us by the feature decorators as: gps_U1234_1619600000000_1619700000000_100.pickle (notice the "_100" appended!)

assert df1 != df3, "These DFs should be different!"
```

**Comment by avaidyam** [comment]
@jlavoie9 mentioned the following:
> We should ideally be able to determine if a larger cache exists than the one we are seeking for (i.e. if the `start` of the cache is earlier and `end` is later) and be able to pull out a sub-piece of the cache instead of performing an exact match. Furthermore, we can go in the opposite direction and stitch together two smaller cache chunks and perform an API call on the missing block in between (which itself can then be cached).

**Comment by ryan-hays** [comment]
Basic items (1), (2), and (3) have been [implemented as of this PR](https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex/pull/23)

**Comment by ryan-hays** [comment]
I am implementing `compress_pickle` to allow for `raw_feature` results to be cached in uncompressed (`.pkl`) or compressed (`gzip`, `bz2`, etc) form.

Currently we are saving uncompressed pickles with the extension `.cortex`. Should we keep this ambiguous extension, or should we specify the (un)compression method by the extension?

**Comment by avaidyam** [comment]
We can follow the existing convention of `.tar.gz`, etc. like so: 
  * `.cortex`: Uncompressed.
  * `.cortex.gz2`: Compressed using GZip.
  * etc...

**Comment by ryan-hays** [comment]
All functionality except for basic point #6 is implemented with pull request [`advanced_caching`](https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex/pull/25). I am going to close this issue, and we can open a new one in the future for #6 and/or more testing if necessary
