### ISSUE TITLE
Cortex main function

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#235]
Currently, each feature function must be run for each unique Participant ID with the same parameter set. Instead, a helper function (called `run` or `main`, etc.) can instead automate this and provide a much friendlier interface to using Cortex:

```python
import cortex
cortex.run("some study ID", ["hometime", ["significant_locations", { some_params }], ...], 1619600000000, 1619600000000)
```

1. First, the function will generate an ID list.
    1. If provided a single string, check the type of the object.
        1. If Participant, the ID list is an array of that ID only.
        2. If Study, the ID list is the list of Participant IDs under the Study.
        3. If Researcher, the ID list is a list of all Participant IDs under all Studies under that Researcher.
    2. If provided an array of strings, use the array as the ID list itself.
2. Next, loop over the zipped list of `(ID, Feature)` in parallel to execute.
3. Finally, stitch the results together as a single pandas data frame.

In addition, the `run` function should allow setting the start/end/resolution parameters using strings instead of a milliseconds integer. [This library should help with parsing that.](https://github.com/wroberts/pytimeparse)

**Comment by jlavoie9** [comment]
This function also needs to automatically get the start and end time for a participant if none are provided. These default start and end should just be the first and last events found for a participant

**Comment by ryan-hays** [comment]
Let's implement this in branch [`run`](https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex/tree/run)

**Comment by avaidyam** [comment]
I also think we should ensure the following with the new `run` function:
1. `cortex.run` should return a `pd.DataFrame` for convenience (or a list of data frames? but that seems quite unpythonic and cumbersome).
2. `cortex.plot` could be a convenience function that passes its `kwargs` to `cortex.run` but wraps the returned `df` in an `alt.Chart(...)` which could pretty simply allow syntax like this:
    `cortex.plot('MY_RESEARCHER_ID', ['survey_results']).mark_line().encode(x='timestamp', y='score', color='id')`
    This would generate an interactive/brushable multi-line plot of survey results over time across all participants in a study with a legend indicating color → ID.

---

**FYI:** I've shared the following Python pseudo-code with @lukeoftheshire which he'll be working to implement as part of the `run` branch:

```py
def unpack_ids(id_set):
    """
    This function should unpack a provided ID or list of IDs into
    a list of Participant IDs.
    """
    
    if type(id_set) == string:
        # Call the LAMP API to find out what type of ID it is
        
        # We passed in a Researcher ID
        if id_set is Researcher:
            # Get all Study IDs for the Researcher ID
            # Get all Participant IDs for all Study IDs
            pass
        
        # We passed in a Study ID
        elif id_set is Study:
            # Get all Participant IDs for the Study ID
            pass
        
        # We passed in a single Participant ID
        elif id_set is Participant:
            # Return a list of exactly the one Participant ID
            return [id_set]
​
    # We passed in a list of Participant IDs
    elif type(id_set) == list:
        # Return the list of Participant IDs itself
        return id_set
```

**Comment by ryan-hays** [comment]
@lukeoftheshire Can you add logging statements to `generate_ids` and later to `run`? 

E.g. `log.info("Unpacked Researcher id " + id + " to a list of " + str(len(generate_ids(id))) + " participants.")`

**Comment by lukeoftheshire** [comment]
Done! I added logging for each of the four conditions, and fixed a typo. It should be added to the 'run' branch.

**Comment by avaidyam** [comment]
@ryan-hays I think this is done, but can you double check against `LAMP-cortex` code?
