### ISSUE TITLE
Mandatory response before preceding

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#237]
> All questions should be mandatory in PHQ-9 and sleep questionnaire. Right now, one can proceed ahead even without answering any particular question

**Comment by avaidyam** [comment]
This was actually the original behavior of surveys from mindLAMP v1 and early v2. This was modified (for MAPNET reasons) but should likely be a parameter for each survey question (`required: boolean`) to selectively enable it.

**Comment by avaidyam** [comment]
Duplicate of #427 and #385.
