### ISSUE TITLE
Back button logs out the user

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#238]
> This is a long-standing challenge in the app that by clicking the "back button" on the phone (which users usually do), we exit the app and have to re-log in.

**Comment by avaidyam** [comment]
@tlakhtak There seem to be several duplicates: #212, #193, #184, and #171. Let's close all the others and redirect them to #171?

**Comment by tlakhtak** [comment]
#212 is unrelated, other are merged to #171

**Comment by tlakhtak** [comment]
Closed because duplicate to #171
