### ISSUE TITLE
Dashboard buttons missing for some participants

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#241]
> When participant name or email is too long, buttons to access their profile/data are not visible![image](https://user-images.githubusercontent.com/82968538/117026750-090ab500-acca-11eb-8bea-3a72b880244a.png)![image](https://user-images.githubusercontent.com/82968538/117026706-0019e380-acca-11eb-9580-342ed19fcaf4.png)
![image](https://user-images.githubusercontent.com/82968538/117026725-04de9780-acca-11eb-8fe2-8269410c01ea.png)

**Comment by sarithapillai8** [comment]
Which device you are checking this? For us when the names are long, it is going new line, not affecting buttons.

**Comment by tlakhtak** [comment]
On the dashboard on Chrome, using a 13-inch Macbook Air. On our end, issue persists - since in some cases they are emails, the full text shifts to the next line but still shifts buttons: see image
![image](https://user-images.githubusercontent.com/82968538/123108045-101b8d00-d408-11eb-86ed-8f0a572b2473.png)
