### ISSUE TITLE
SMS/Text message information

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#242]
Is it possible to receive SMS/Text message information. Datetime of the message, sent/received, etc?

**Comment by avaidyam** [comment]
Yes, this is already possible and is documented. Mileage may vary by device and operating system version as Apple/Google have been making it harder to get this data in the past few years.

**Comment by jeydude** [comment]
Thanks @avaidyam, to receive sms, do i need to include lamp.sms as part of the sensor_spec?, if yes, could you share the sensor_spec for sms. Thanks!

**Comment by avaidyam** [comment]
[This is the projected list of SensorSpec IDs.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/92#issuecomment-770976348) You should be able to add any/all of them to test with!

**Comment by jeydude** [comment]
Thanks!
