### ISSUE TITLE
Open API definition missing new APIs?

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#243]
@avaidyam, I have noticed few new Endpoints/APIs that are called in the mindLAMP dashboard. But they are not listed in the [Open API 3.0.3 definition](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/blob/master/openapi.yml) - 

Here are some the new Endpoints/APIs that are called in the mindLAMP dashboard:
```
https://<HOSTED API SERVER>/researcher/7vs81xf3w38dec5dsd64/_lookup/participant
https://<HOSTED API SERVER>/study/bze1t66jkra2ngdtzrv2/_lookup/participant/mode/2
https://<HOSTED API SERVER>/researcher/7vs81xf3w38dec5dsd64/_lookup/activity
https://<HOSTED API SERVER>/researcher/7vs81xf3w38dec5dsd64/_lookup/sensor
```

can you please update newly added endpoints/apis to the Open API schema definition? Thanks!

**Comment by avaidyam** [comment]
@jeydude Thanks for the heads up - these were introduced in the recent production release and should not be part of the official API. **They will be removed in the next production release and should not be used as official public API.** My team can temporarily document them for your security firewall use-case.

**Comment by avaidyam** [comment]
@jeydude This is not due to the API definition -- this is probably related to #123 or #133. However, the development team is working to add an OpenAPI definition for these two methods.

**Comment by jeydude** [comment]
Thanks @avaidyam, let us know once you have 

```
https://<HOSTED API SERVER>/researcher/7vs81xf3w38dec5dsd64/_lookup/participant
https://<HOSTED API SERVER>/study/bze1t66jkra2ngdtzrv2/_lookup/participant/mode/2
https://<HOSTED API SERVER>/researcher/7vs81xf3w38dec5dsd64/_lookup/activity
https://<HOSTED API SERVER>/researcher/7vs81xf3w38dec5dsd64/_lookup/sensor
```
or any other missing APIs in the mindLAMP Open API 3.0.3 added to the YAML/JSON file.  Thanks!

**Comment by avaidyam** [comment]
@jeydude Here is the modified specification for temporary use with Akana (please remove the `.txt` extension):  [openapi_modified_akana.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6451639/openapi_modified_akana.json.txt)

**Comment by jeydude** [comment]
Thanks @avaidyam, I will use this and update our API system. Thanks for your help!

**Comment by jeydude** [comment]
Please try the new json file with https://editor.swagger.io/, getting some errors, please fix them and I will use the latest. Thanks @avaidyam

**Comment by avaidyam** [comment]
It's now updated (the original comment has also been updated): [openapi_modified_akana.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6452430/openapi_modified_akana.json.txt)

**Comment by jeydude** [comment]
Thanks, looks good.

**Comment by jeydude** [comment]
@avaidyam We noticed mindLAMP dashboard application is still calling below which is missing with your Open API definition.
"/type/{id}/attachment"
"/type/{id}/attachment/{attachment_key}"

after adding these two API from the old definition, now it is working.

Please consider to include above APIs definition as part of your Open API definition. Thanks!

**Comment by jeydude** [comment]
@avaidyam, I am getting more and more API error due to mismatch with Open API definition and API calls from latest mindLAMP dashboard application, please make sure to include all the latest APIs in Open API definition. 
 
Here are some of the errors due to mismatch with Open API definition, I did not test each functionality of the mindlamp dashboard application, if I test them I am sure I will have more list of errors, please update the Open API definition to match with your latest mindLAMP dashboard application calls. Once you have the final open API definition, please share it. Thanks a lot!


HTTP   Method | URL | Error
-- | -- | --
DELETE | https://<HOSTED API   SERVER>/participant/U7097351426 | 500
PUT | https://<HOSTED API   SERVER>/type/U7097351426/attachment/lamp.name/me | CORS
Options | https://<HOSTED API   SERVER>/type/U7097351426/attachment/lamp.name/me | 404
POST | https://<HOSTED API   SERVER>/type/U0465708292/credential | CORS
Options | https://<HOSTED API   SERVER>/type/U0465708292/credential | 404
