### ISSUE TITLE
Self password change - Researcher/Patient

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#249]
How do I update my password, if I login as researcher or as a patient?

I am not seeing manage credential option in the dashboard app.

![image](https://user-images.githubusercontent.com/841011/117877681-77231f00-b26a-11eb-8ba5-e5573e8b02e8.png)

**Comment by avaidyam** [comment]
This was a security and compliance change. Patients must ask their clinicians and clinicians must ask their system administrators for a password reset.
