### ISSUE TITLE
Implement Cortex raw features for WiFi/Bluetooth and Sleep

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#250]
We should implement `lamp.wifi`, `lamp.bluetooth`, and `lamp.sleep` raw features. One item of note is to clearly differentiate how the "raw feature sleep" is HealthKit/Fit derived and not the same as our "secondary feature sleep". Furthermore, we should add additional info to the documentation around Bluetooth/WiFi address + RSSI:

> RSSI is a term used to measure the relative quality of a received signal to a client device, but has no absolute value. […] Cisco, for example, uses a 0-100 scale, while Atheros uses 0-60. It’s all up to the manufacturer (which is why RSSI is a relative index), but you can infer that the higher the RSSI value is, the better the signal is. […] There’s a lot of math we could get into, but basically, the closer to 0 dBm, the better the signal is.
> [-- Source](https://www.metageek.com/training/resources/understanding-rssi.html)

<img width="660" alt="Screen Shot 2021-05-12 at 11 01 50 AM" src="https://user-images.githubusercontent.com/1361003/118000625-fe789d00-b313-11eb-8bef-7407ceee8ad1.png">

### Raw Bluetooth Example

```
 {'timestamp': 1616172913842,
   'sensor': 'lamp.bluetooth',
   'data': {'bt_rssi': -88,
    'bt_address': 'CCF087D3-A0FC-0FDF-D7F9-1285211653FB'}},
  {'timestamp': 1616172858929,
   'sensor': 'lamp.bluetooth',
   'data': {'bt_rssi': -91,
    'bt_address': 'CCF087D3-A0FC-0FDF-D7F9-1285211653FB'}},
  {'timestamp': 1616170339651,
   'sensor': 'lamp.bluetooth',
   'data': {'bt_rssi': -98,
    'bt_address': 'CCF087D3-A0FC-0FDF-D7F9-1285211653FB'}},
  {'timestamp': 1616022127303,
   'sensor': 'lamp.bluetooth',
   'data': {'bt_rssi': -94,
    'bt_address': 'CCF087D3-A0FC-0FDF-D7F9-1285211653FB'}},
  {'timestamp': 1616022112113,
   'sensor': 'lamp.bluetooth',
   'data': {'bt_rssi': -95,
    'bt_address': 'CCF087D3-A0FC-0FDF-D7F9-1285211653FB'}}
```

### Visualized Example

(Sample code to generate a plot of number of unique addresses encountered per day per patient.)

```python
import cortex
import altair as alt 

# Generate an Altair chart with Cortex data source:
alt.Chart(

    # Obtain patient U123's bluetooth data.
    cortex.run("U123", ["bluetooth"])

        # Resample (aggregate/group-by) the data per-day.
        .resample('D')

        # Count the number of unique entries (address) encountered per day.
        .nunique()

        # Revert the df index to a column for Altair to access it.
        .reset_index())

# Encode "timestamp vs. address (unique count)" as a line plot.
.mark_line().encode(x='timestamp', y='address')
```

<img width="653" alt="Screen Shot 2021-05-12 at 11 21 51 AM" src="https://user-images.githubusercontent.com/1361003/118000939-439ccf00-b314-11eb-93e6-c95a539ec349.png">

**Comment by ryan-hays** [comment]
`lamp.wifi` and `lamp.bluetooth` were implemented and added as of PR [`add_raw`](https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex/pull/24)

**Comment by avaidyam** [comment]
Ah oops - I closed this without the corresponding documentation update being completed. Sorry, reopening!

**Comment by ryan-hays** [comment]
`lamp.sleep` was implemented and added with PR [`healthkit_gfit_sleep`](https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex/pull/31).

However, currently it is ambiguously getting data from the `lamp.sleep` sensor. We might consider doing some preprocessing 
of the data before returning based on the Healthkit/Fit data types.

**Comment by ryan-hays** [comment]
@rydmel When you are done documenting the wifi and bluetooth, open a PR in `LAMP-platforms`

**Comment by avaidyam** [comment]
@rydmel While I see that [you've updated the documentation](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/commit/55e9653f71764b9e694a67262a4b92700e11af65), it does not cover the info listed in the issue body above. Could you add that detail as well?

**Comment by avaidyam** [comment]
Thanks for the fixes @rydmel!
