### ISSUE TITLE
Not collecting passive data from Android and iOS devices (latest releases)

### ISSUE THREAD

**Issue by Ashermind** [BIDMCDigitalPsychiatry/LAMP-platform#252]
**Description of the issue**
1. We redeployed lamp backend on our server using Portainer
2. Ourbackend image is the latest 2021 release.
3. We added sensorspec manually into the couch db.
![image](https://user-images.githubusercontent.com/46451717/118287942-36c6d980-b4d4-11eb-821f-8c686ba9b599.png)
4. We created new patients and started testing 5 devices (2 iOS, 3 Andoird)
    All of the devices have the latest BETA or TestFlight apps from stores.
    All of the mindlamp2 apps have enabled permissions and disabled any and all battery saving options.
    All of our devices have installed google fit and/or the iOS health equivalent.
5. We are able to collect active data such as questionnaires and messaging with the "researcher", but we were not able to collect any sensor data even after adding the sensors to the study and restarting and or reinstalling the app multiple times.

I personally was able to send a small chunk of data to server yesterday while I was tinkering and reinstalling, closing and opening the app. Unfortunatelly I do not know what were the circumstances at that time.
Here is a proof:
![image](https://user-images.githubusercontent.com/46451717/118288621-e13efc80-b4d4-11eb-99ba-1178fa69cfbc.png)

Therefore I assume the backend is set up as it should be, the data is readable after export but it is unusable because it is just a few entries.

Other devices did not send any data at all.

We are not sure how to reproduce this bug but it seems comon at least for us, we do not know how to avoid or mitigate this.

I had already asked in another issue thread if the Google Fit is mandatory and if it really has to be installed prior the installation of mindlamp2 or not (yesterday I tried uninstalling and installing both in different succesion).

**Desktop:**
 - Server image: bidmcdigitalpsychiatry/lamp-server:2021@sha256:d29f8a21b4ce8579b5d1538e5010755b7fb671f4e7f674de0e1c78d2ef56e334

**Smartphone:**
 - Devices Apple: Apple iPhone 11 Pro,  Apple iPhone 8 Plus, Apple iPhone 12
 - Devices Android: Realme 7 Pro, Samsung S8+,

Note: We are not sure where is the problem located and whether we have missed some crucial step in docs.lamp.digital and forums, but I believe we did everything as we were supposed. We would really be glad to be able to collect passive data from devices by next week and we would like to continue for a month not only to test the new version of mindlamp but also because of our studies.

Ondrej Sakači

**Comment by jijopulikkottil** [comment]
@Ashermind 
Could you just verify that the sensor json by executing this API using basic auth.
https://api.lamp.digital/participant/{participantid}/sensor The part 'api.lamp.digital' might be different for your instance.
(let us know if you need any help to execute the API)

And please copy-paste the response (partially or fully) here.

**Comment by Ashermind** [comment]
@jijopulikkottil 
Ok I used it like this:
https://SERVER.URL/participant/{participant_id}/device_motion

And got:
{
  "message": "404.api-endpoint-unimplemented"
}

So I guess there might be problem on the server side afterall.

**Comment by jeydude** [comment]
@Ashermind, 

try https://<SERVER.URL>/participant/<YOUR PARTICIPANT ID>/sensor_event?origin=lamp.accelerometer

Hope it works for you.

**Comment by jijopulikkottil** [comment]
"/sensor_event" API is for listing the collected sensor data.
To see the configured sensors, we have to use "/sensor" end point.

**Comment by Ashermind** [comment]
@jeydude  Thank you I did not pass the credentials.

The /sensor gives this response:
```
{
  "data": [
    {
      "id": "nmrqsjpfenkhf1n7zsa0",
      "timestamp": 1620926591147,
      "spec": "lamp.device_motion",
      "name": "DevMotion",
      "settings": {}
    },
    {
      "id": "gyz5w8ekt2hepvxkx9yk",
      "timestamp": 1620926656395,
      "spec": "lamp.gps",
      "name": "GPS",
      "settings": {}
    },
    {
      "id": "n4rr085pgyn40yzbfpcn",
      "timestamp": 1620926667867,
      "spec": "lamp.screen_state",
      "name": "ScreenState",
      "settings": {}
    },
    {
      "id": "ae85r0rtxrx03n4zs7nb",
      "timestamp": 1620927082152,
      "spec": "lamp.nearby_device",
      "name": "NearbyDevice",
      "settings": {}
    },
    {
      "id": "akhbvptz1nvvspx6esf4",
      "timestamp": 1620927106219,
      "spec": "lamp.telephony",
      "name": "Telephony",
      "settings": {}
    },
    {
      "id": "30tf2wdm1er098fhpxav",
      "timestamp": 1620927114353,
      "spec": "lamp.steps",
      "name": "Steps",
      "settings": {}
    },
    {
      "id": "sx5p7sprss9fekx2qrty",
      "timestamp": 1620927137353,
      "spec": "lamp.analytics",
      "name": "Analytics",
      "settings": {}
    },
    {
      "id": "v8a7ehymvx5ahh70jz5a",
      "timestamp": 1620993832252,
      "spec": "lamp.steps",
      "name": "Steps",
      "settings": {}
    }
  ]
}
```
While /sensor_event?origin=lamp.accelerometer returns:
```
{
  "data": []
}
```

**Comment by jeydude** [comment]
@Ashermind 

I did not see lamp.accelerometer in your sensor list, try adding accelerometer sensor to one of your patient profile.

If you are using CouchDB as your database, check your CouchDB--> sensor_event database, that will tell you what data you are collecting and when.

Check your design documents in each couchdb database. I have design documents for all the database except activity_spec database. In past, I missed design documents for some database that caused issue to us.

Check your APP Server log to see if you are seeing any error or not.

Check your permission with your phone.  If you are using Android phone and test version of mindLAMP app, try to logout and login we noticed with test version of android app if you re-login we get some of missing sensor data.

If you are using iPhone and TestFlight version of mindLAMP app. We are getting accelerometer, analytics, heart_rate, steps, device_motion, telephony. We are not getting gps, screen_state and sleep sensor data. We have reported the issue with  @jijopulikkottil.

**Comment by jijopulikkottil** [comment]
@jeydude  

> "We are not getting gps, screen_state and sleep sensor data."

 With new build, we are collecting gps every second (earlier we collect it if there is any change in location). We have also done some improvement with lamp.sleep. so it should work. About  'lamp.screen_state', are you getting no data ? It seems to be working when I test here. Please verify all. If you are configured 'sensor', then please check the these items are present.

**Comment by avaidyam** [comment]
> we are collecting gps every second
Please adjust the behavior so if `frequency` is not set, it collects data with location change only, and that if if `frequency` is set, it should obey that instead of just once a second.

**Comment by jeydude** [comment]
@jijopulikkottil after April 26, I am still missing lamp.gps and lamp.screen_state data. Will wait for the new build.

**Comment by jijopulikkottil** [comment]
@avaidyam fixed location sensor. @jeydude We have done some improvements. Please verify with new build which is going to publish.

**Comment by jeydude** [comment]
Any information on the production releases to Apple Store or Android Play Store?

**Comment by avaidyam** [comment]
@jeydude We are preparing to submit both iOS and Android to production before the end of the month. We're unsure how long the review process will take but [we'll make a news post about it in our forum too](https://mindlamp.discourse.group).
