### ISSUE TITLE
Update documentation with Sensor and Cortex examples

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#270]
The below is the full list of supported `SensorSpec`s:
```
lamp.gps
lamp.analytics
lamp.device_motion
lamp.steps
lamp.nearby_device
lamp.telephony
lamp.screen_state
lamp.segment
lamp.sleep
lamp.nutrition
lamp.blood_glucose
lamp.blood_pressure
lamp.oxygen_saturation
lamp.body_temperature
lamp.heart_rate
lamp.respiratory_rate
lamp.accelerometer
lamp.activity_recognition
```

We should ensure that API or Cortex examples are provided for each of the above in addition to the existing parameter and description info.

**Comment by dcurrey88** [comment]
Closing this issue as it looks like these exist here: https://docs.lamp.digital/data_science/data_types
