### ISSUE TITLE
SVG/Vector art icon for mindLAMP

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#273]
Currently, the mindLAMP app icon is a fixed size (512x512) PNG icon; it should be converted to an SVG icon for both iOS and Android, [but also as a Favicon for the dashboard](http://thenewcode.com/28/Making-And-Deploying-SVG-Favicons).

**Comment by avaidyam** [comment]
The icon has been converted to an SVG. @sarithapillai8 @saranya-sajeev @jijopulikkottil Please update all references across Web/iOS/Android to use this SVG file **(no PNG assets should be used at all anymore - [including `ic_launcher`](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive), etc.)**. 

[mindLAMP.svg.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7563928/mindLAMP.svg.zip) //cc @tlakhtak

**Comment by jijopulikkottil** [comment]
@avaidyam In splash screen, currently the logo is svg. Not sure to use svg as app icon. will investigate it.

**Comment by avaidyam** [comment]
It should be possible to use an SVG in the XCassets file and have XCode generate the proper PNG file sizes automatically for you. We just don't want to be managing raster graphics assets (Pangs, JPGs, eyc.) anymore unless they're screenshots.

**Comment by jijopulikkottil** [comment]
@avaidyam for iOS, in Xcode, we couldn't find a way to provide SVG as app icon.

**Comment by saranya-sajeev** [comment]
@avaidyam SVG icon integration completed for Android and it is pushed to beta.
