### ISSUE TITLE
Error while entering RATING Survey questions

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#276]
While entering RATING Survey questions, got below error
![image](https://user-images.githubusercontent.com/841011/119572811-f2132c00-bd78-11eb-8650-75aa8e981056.png)

To reproduce this issue, **enter only the description value** under the Add option. Don't enter anything on the question option, leave it blank and click Add option, if you do this one or two times, you should be able to reproduce the error in the dashboard app.
![image](https://user-images.githubusercontent.com/841011/119572937-225aca80-bd79-11eb-9b0a-b5f304b6ebc3.png)

And user is not able to select RATING  survey questions answer via iphone/android phone. It works in web browser though.

**Comment by sarithapillai8** [comment]
Fixed with PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/247

**Comment by sarithapillai8** [comment]
Fixed with PR - BIDMCDigitalPsychiatry/LAMP-dashboard#247
