### ISSUE TITLE
App crashes when location service is not turned on - iOS

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#277]
I had disabled the location service for some other purpose, while location service was not turned ON, I tried to open the mindLAMP testflight version of iOS app, it was crashing.

Once location service turned ON, testflight version of iOS app worked fine.

**Comment by avaidyam** [comment]
@jeydude [The documentation specifically states that all sensor-related permissions MUST be enabled regardless of what data is being collected by mindLAMP.](https://docs.lamp.digital/app/#android)
