### ISSUE TITLE
Including image in the survey question

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#278]
Is there any way to include image in the survey/activities question page? Sometimes while asking survey question we wanted to include a image also. If this feature is not there, then it will be nice have that features.

**Comment by avaidyam** [comment]
@jeydude [It should now be possible to use Markdown formatting with Survey text](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/384), so you could try embedding an external image via URL or a data-url to embed a small SVG or PNG file. (This is not an officially supported feature, but it should work!)
