### ISSUE TITLE
Survey bundle restarting from beginning

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#282]
> Multiple users report issues that either the morning and afternoon batch of surveys do not register as complete - user is redirected to start the survey over and over again. 

Some users reported facing this issue when using the notifications to go to the survey, and are able to bypass by using the dashboard directly.

**Comment by sarithapillai8** [comment]
Production release done with fixes :
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/releases/tag/2021.6.11
