### ISSUE TITLE
Black or White screen after log-in attempt

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#283]
> User is not able to log in, continuously - instead of successful log in and dashboard, user sees black or white screen.

**Comment by sarithapillai8** [comment]
We are not able reproduce this one. Could you please provide more details and also confirm if it was any network glitch?

**Comment by tlakhtak** [comment]
this is a persistent issue for a user, U8924256758.

**Comment by tlakhtak** [comment]
@sarithapillai8  this issue also occurred for a different user, U8974761142

**Comment by michaelmenon** [comment]
Thanks this issue is fixed in staging we are trying to push this to production but some other update are being tested in staging by @avaidyam , so only after that completes we can push the fix for this to Production. Will let you know as soon as we could push the fix for this to production.
