### ISSUE TITLE
App stalls when using Jewels, shows loading screen

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#284]
> When trying to use Jewels during the mornings, app crashes or gets stuck on a loading screen.

**Comment by sarithapillai8** [comment]
We are not able reproduce this one..

**Comment by michaelmenon** [comment]
@tlakhtak can you post a video of the issue as its not reproducible at our end. Also browser details on which you are testing. Is it easily reproducible at your end or is it an issue with slow network at your end ?

**Comment by tlakhtak** [comment]
I am also unable to reproduce on my end. For now, we can ignore this issue.
