### ISSUE TITLE
Unable to see the saved alias upon login

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#287]
> Unable to see the saved de-identified numbers of patients on the list upon login
>
> It initially saves when you hit the check button but then as soon as you leave the page goers back to the original LAMP generated number. This will make it impossible for clinicians who are doing scales after my assessment to recognize the correct number and delay data collection on the patient(s)

> ![image](https://user-images.githubusercontent.com/82968538/120812191-c29fb480-c51a-11eb-9354-50aace7a0763.png)

**Comment by sarithapillai8** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/254
Updated in production
