### ISSUE TITLE
Missing key-value pair in survey result data

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#288]
> Occasionally, the value key will not be stored for an individual question in a survey, meaning that participant response data does not exist. All the following screenshots come from College Study data. This seems to occur more frequently when duration is high (100,000+), but can also occur when duration is low( <10,000).
>
> This appears to only happen to the 'value' key - i.e. other values are never missing.
>
> Example 1: 
> ![image](https://user-images.githubusercontent.com/82968538/120820169-4b6e1e80-c522-11eb-94dc-8aab607ef741.png)
>
> Example 2: Missing data occurs for different questions, but not for every participant
> ![image](https://user-images.githubusercontent.com/82968538/120820192-5032d280-c522-11eb-9d04-96e2dc15f0f4.png)
>
> Example 3: The following provides an activity id where this occurred.
>![image](https://user-images.githubusercontent.com/82968538/120820305-6a6cb080-c522-11eb-9e4f-fefe055e93af.png)
>
>Example 4: The following provides an example of normal data objects(top,bottom) compared with one where the 'value' key is missing (middle)
>![image](https://user-images.githubusercontent.com/82968538/120820571-aa339800-c522-11eb-9cb0-ba839c850ea1.png)
>
>Example 5: This bug can occur multiple times within a single survey, although this is rare.
>![image](https://user-images.githubusercontent.com/82968538/120820627-b7508700-c522-11eb-8515-aa33bf4cb3e0.png)

**Comment by sarithapillai8** [comment]
Could you please provide researcher/activity/participant details on this?

**Comment by tlakhtak** [comment]
Activity is both Daily and Weekly surveys in Researcher 'dnbd16yj2zkegk67aqm8'. Issue persisted for multiple participants.

**Comment by sarithapillai8** [comment]
Those surveys having some missing question types. Can you confirm the surveys are correctly updated and recheck?

**Comment by lukeoftheshire** [comment]
We are having trouble finding the surveys without question types. Could you please provide an id corresponding to one of the surveys with missing types?

**Comment by sarithapillai8** [comment]
Please check daily survey - There are no selections on type of question : The data is like below :
Array(11)
0:
duration: 6097
item: "I felt down today"
level: null
type: null
value: "0"
__proto__: Object
1:
duration: 16472
item: "Today I feel little interest or pleasure"
level: null
type: null
value: "2"
__proto__: Object
2:
duration: 26361
item: "I felt anxious today"
level: null
type: null
value: "1"
__proto__: Object
3:
duration: 68499
item: "Today I have trouble relaxing"
level: null
type: null
value: "0"
__proto__: Object
4:
duration: 54941
item: "Today my thoughts felt jumbled and confused"
level: null
type: null
value: "0"

While running the survey, the default 'likert' type taken there.

If we can edit the survey and test with one participant we can debug it. We are not able to reproduce it in our test data. Also could you please let me know how the survey was created and identify if it came from import functionality.

**Comment by lukeoftheshire** [comment]
Thank you for the clarification. Per the [LAMP documentation](https://docs.lamp.digital/data_science/data_types) I believe level and type should be null in _result_ data, which this appears to be as it contains duration info. In the survey _specification_ type is correctly set to 'likert' - see below:
'settings': [{'text': 'I felt down today',
    'type': 'likert',
    'options': None},
   {'text': 'Today I feel little interest or pleasure',
    'type': 'likert',
    'options': None},
   {'text': 'I felt anxious today', 'type': 'likert', 'options': None},
   {'text': 'Today I have trouble relaxing',
    'type': 'likert',
    'options': None},
   {'text': 'Today my thoughts felt jumbled and confused',
    'type': 'likert',
    'options': None},
   {'text': "Today I heard voices that others apparently couldn't hear",
    'type': 'likert',
    'options': None},
   {'text': 'I felt stressed today', 'type': 'likert', 'options': None},
   {'text': 'I was able to function well today',
    'type': 'likert',
    'options': None},
   {'text': 'Today I could handle what came my way',
    'type': 'likert',
    'options': None},
   {'text': 'Today I felt that others have it in for me.',
    'type': 'likert',
    'options': None},
   {'text': 'I felt that others could read my thoughts today',
    'type': 'likert',
    'options': None}]},
    
 The survey was likely created through import functionality - but as the specification appears to be correct hopefully this is not an issue. For the same reason, if it is possible to investigate this issue without altering the survey that would be preferable.

**Comment by sarithapillai8** [comment]
Can we have a test participant to debug this issue?

**Comment by lukeoftheshire** [comment]
Yes, but please use the staging database to do so - this will prevent testing data from being mixed in with user data that will be analyzed later.

**Comment by sarithapillai8** [comment]
We tried importing the surveys and tried submitting for a test participant. We are not able to reproduce this in any way. Can you please provide any information for this?
@avaidyam Is it possible to try this from your side?

**Comment by lukeoftheshire** [comment]
Thank you for trying to replicate the bug - we have found it difficult to reproduce as well, as it does not occur every time a survey is submitted. 

Over the course of approximately 1300 weekly survey submissions in the college study group we noticed only 38 duplicate surveys across 31 participants, so the rate is not high. Nonetheless, this duplicate data can be found in the database. The following _non-exhaustive_ list of participants with duplicate data may be useful:
U8915884744(activity id - jesqkrzxfxk8ncmxgf02)
U0668545528(activity id - jesqkrzxfxk8ncmxgf02)
U157365160 (activity id - jesqkrzxfxk8ncmxgf02)
U9187733591 (multiple duplicates - activity id - 9qpwcdy7cqcaecmxn910)
U9608481542(activity id - 9qpwcdy7cqcaecmxn910)
U4755427211 (activity id - 9qpwcdy7cqcaecmxn910)
U0853096147 (activity id - 9qpwcdy7cqcaecmxn910)
U8312925877 (activity id - 9qpwcdy7cqcaecmxn910)
U3731398114(multiple duplicates - activity id 6vkbs78wtps0thj8m6e)
U8044797014(multiple duplicates - activity id p6vkbs78wtps0thj8m6e)
U2725359023(multiple duplicates - activity id va0h841mh48f9e6kp5k5
U8559533112(id va0h841mh48f9e6kp5k5)
U4241916648(id va0h841mh48f9e6kp5k5)
U2636091422(id va0h841mh48f9e6kp5k5

Activity IDs for duplicate weekly surveys are:
jesqkrzxfxk8ncmxgf02
9qpwcdy7cqcaecmxn910
p6vkbs78wtps0thj8m6e
va0h841mh48f9e6kp5k5

As you can see, this occurs across multiple participants and in all four college study weekly surveys. I hope this information is helpful - please let me know what else would help you.

**Comment by michaelmenon** [comment]
thanks for the details , we will check on the data and let you know on this.
