### ISSUE TITLE
Games not loading for afternoon batch of activities

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#293]
> When clicking on the afternoon notification, the surveys are displayed and then the box game. Right after completing the box game, the next 3 games will not load, there is just a blank screen (should be box game pro, jewels, and jewels pro after that). This occurs when accessing from the notification and also when going into the app and clicking on "afternoon notifications'. This is only happening for the afternoon notification we have set up, not the morning one.

> https://sendvid.com/mtkckf85

**Comment by sarithapillai8** [comment]
We are not able reproduce this one. Could you specify the games that were not loaded, and the batch tried to debug?

**Comment by sarithapillai8** [comment]
Updated the fix in production
