### ISSUE TITLE
Breathe activities with URL

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#295]
> In the "breathe" manage activity, there is a space to upload a URL (i.e. from youtube) for audio, but that functionality does not actually exist. Can this be fixed? OR can you find a fix for this issue (take away the option, provide a description of links that WILL vs will NOT work).

**Comment by SuruPa00** [comment]
This is now a reoccurring issue and should be worked on when possible - see example issue of video below:
https://user-images.githubusercontent.com/86117379/130467943-2c4e9f62-7ce8-49dd-a25e-9fe8d31435fb.mov

**Comment by sarithapillai8** [comment]
@avaidyam This is implemented with Audio element and it is expected to work with mp3/ogg/wav formats. 
We have checked with this kind of URLs there:
https://www.kozco.com/tech/piano2.wav
https://www.kozco.com/tech/LRMonoPhase4.mp3

**Comment by avaidyam** [comment]
Looking at the original request, it seems like the collaborator that submitted this has a misunderstanding: 

> space to upload a URL (i.e. from youtube) for audio

We don't support YouTube URLs for audio in the Breathe activities. I'll close this issue - sorry for the confusion @sarithapillai8!
