### ISSUE TITLE
Breathe activities error message

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#298]
>Cannot edit any breathe activities - displays error message instead. Can create new breathe activity.
>![image](https://user-images.githubusercontent.com/82968538/121943193-f21ea000-cd16-11eb-884f-cdaf0467e141.png)

**Comment by sarithapillai8** [comment]
Please provide more detail if this is something related to any specific study or specific breathe activity.

**Comment by tlakhtak** [comment]
Some Breathe activities which can be imported successfully, used successfully on the dashboard, but cannot be edited.

**Comment by sarithapillai8** [comment]
We are not able to reproduce this issue. Could you please specify anyone which we can try?

**Comment by sarithapillai8** [comment]
Issue fixed in PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/246
