### ISSUE TITLE
Detect Low Power Mode

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#3]
[See this discussion post for details.](https://github.com/orgs/BIDMCDigitalPsychiatry/teams/native-core/discussions/1)

**Comment by michaelmenon** [comment]
This can be closed as this will be implemented with this ticket 
 https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/40

**Comment by SuruPa00** [comment]
can it be added so that low power mode is a sensor within lamp.analytics? this way, it can be detected for future data collection issues if a device was on low power mode or not

**Comment by avaidyam** [comment]
@jijopulikkottil [Here is example code that can be used to listen to low power mode notifications.](https://www.hackingwithswift.com/example-code/system/how-to-detect-low-power-mode-is-enabled) The fact that LPM was turned on or off should be conveyed as a `lamp.analytics` event.

**Comment by jijopulikkottil** [comment]
We can observe change in low power mode and can send the sensor event if device is connected to internet.
Do we need to store the request if no connectivity and send when connected ?

```
{
            "sensor": "lamp.analytics",
            "data": {
                "device_type": "iOS",
                "value": 1, // 1 = device is in low power mode, otherwise 0.
                "user_agent": "NativeCore 2021.1.21; iOS 14.3; iPhone iPhone8,1",
                "action": "lowpowermode"
            },
            "timestamp": 1630688499345
}
```

**Comment by SuruPa00** [comment]
@jijopulikkottil yes to storing the request if no connectivity and send when connected

**Comment by jijopulikkottil** [comment]
Ok, we can store the above analytics data to sync later.
We are syncing(sending to server) stored requests only when low power mode is turned off. So the stored analytics data sync only when device is connected and lower-mode is turned off.

Let me know if need any changes.

**Comment by SuruPa00** [comment]
@jijopulikkottil is this still being implemented or is it completed

**Comment by jijopulikkottil** [comment]
@SuruPa00 It is completed. Testing is In-Progress

**Comment by avaidyam** [comment]
@jijopulikkottil Can you share what the data would look like? 
@saranya-sajeev Is this also implemented on Android?

**Comment by jijopulikkottil** [comment]
@avaidyam same as https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/3#issuecomment-912683563

**Comment by saranya-sajeev** [comment]
@avaidyam it is not  implemented in Android. We are not getting low power mode callbacks when tested.

**Comment by avaidyam** [comment]
[Please implement it ASAP.](https://stackoverflow.com/questions/4139149/android-power-save-mode-listener)

**Comment by saranya-sajeev** [comment]
@avaidyam In Android , low power mode call back is not firing.

**Comment by avaidyam** [comment]
Are you using the `ACTION_POWER_SAVE_MODE_CHANGED` broadcast intent?

**Comment by saranya-sajeev** [comment]
@avaidyam yes

**Comment by avaidyam** [comment]
It doesn't seem like you've added this to `AndroidManifest.xml`:

```
<receiver android:name=".observers.PowerSaveModeReceiver">
    <intent-filter>
        <action android:name="android.os.action.POWER_SAVE_MODE_CHANGED"/> 
    </intent-filter>
</receiver>
```

Can you confirm that it's set up this way and then test it?

**Comment by saranya-sajeev** [comment]
@avaidyam it is also tried and not worked.

**Comment by avaidyam** [comment]
[Please take a look at this procedure to test low power mode (battery saver mode) on Android 9+.](https://stackoverflow.com/questions/48932479/ways-to-test-power-save-mode-changed-action-power-save-mode-changed-receiver) There's a number of other ways to implement this too and as long as it works on most major devices (i.e. Google Pixel, Samsung Galaxy S series) we can consider it implemented.

**Comment by saranya-sajeev** [comment]
@avaidyam When we checked in Galaxy M31, we are receiving the callback. May be it depends on the manufactures. 
 We will integrate low power mode event in the android app and the event will be sent if it available in the phone .

**Comment by avaidyam** [comment]
@saranya-sajeev Can you confirm the data is being [posted in the same way that @jijopulikkottil has implemented?](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/3#issuecomment-912683563)

**Comment by saranya-sajeev** [comment]
@avaidyam sure.

**Comment by saranya-sajeev** [comment]
@avaidyam low power mode data is posted in the same way as in ios. Sample data post from Android is as below.

"data": {
        "device_type": "Android",
        "value": 1,
        "user_agent": "NativeCore 2021.10.25;samsung;SM-M215F",
        "action": "lowpowermode"
      },
      "sensor": "lamp.analytics",
      "timestamp": 1643630153968
    }

**Comment by avaidyam** [comment]
Is this now in beta for QA testing?

**Comment by saranya-sajeev** [comment]
No we will push it today.

**Comment by saranya-sajeev** [comment]
@avaidyam Low power mode integration pushed to beta.

**Comment by dcurrey88** [comment]
This issue appears to be resolved in staging. I see low power mode analytics events in both iOS and Android.

```
{'sensor': 'lamp.analytics',
  'data': {'device_type': 'iOS',
   'value': 1,
   'user_agent': 'NativeCore 2022.2.28; iOS 15.3.1; iPhone iPhone10,4',
   'action': 'lowpowermode'},
{'device_type': 'Android',
   'value': 0,
   'user_agent': 'NativeCore 2022.0.27; Android 10; OnePlus; HD1905',
   'action': 'lowpowermode'}
```
