### ISSUE TITLE
Journal data is not correctly formatted

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#30]
Here is what it looks like right now:
```json
{
      "timestamp": 1604430446324,
      "duration": 0,
      "activity": "arqpbxkp91sabbt1drrj",
      "static_data": {
        "journalText": "some text here",
        "feedback": "Bad"
      },
      "temporal_slices": {}
    }
```

1. Every activity should have a timer running for how long was spent in that activity that reports a value for `duration`, this code should be part of the dashboard itself and not part of the activity code that is running in the `iframe`.
1. Please rename `journalText` to `text`. 
1. Please rename `feedback` to `sentiment` and change its response `Yes` to `good` and `Bad` to `bad`.

**Comment by sarithapillai8** [comment]
@avaidyam 
The data format changed and so prevent will have issues with old data.

**Comment by avaidyam** [comment]
Once you make this change in staging I can go through and manually patch the old items in the database.
