### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#300]
Our collaborators observed many missing or half-translated sections on text native to the app.
![image](https://user-images.githubusercontent.com/82968538/122307470-0eb20800-ced0-11eb-8748-269041b7e5ec.png)
![image](https://user-images.githubusercontent.com/82968538/122307488-1376bc00-ced0-11eb-8977-33d9eb37ba36.png)
![image](https://user-images.githubusercontent.com/82968538/122307505-1a9dca00-ced0-11eb-9486-ebeea38e0261.png)
![image](https://user-images.githubusercontent.com/82968538/122307527-24bfc880-ced0-11eb-898d-e7ec8c8a607e.png)
![image](https://user-images.githubusercontent.com/82968538/122307538-29847c80-ced0-11eb-9785-d4332f2cfa4b.png)
![image](https://user-images.githubusercontent.com/82968538/122307547-2e493080-ced0-11eb-96be-19075f7b51eb.png)
![image](https://user-images.githubusercontent.com/82968538/122307555-32754e00-ced0-11eb-97db-08e401b680d0.png)
![image](https://user-images.githubusercontent.com/82968538/122307572-37d29880-ced0-11eb-8eff-e810c2fc29e4.png)
![image](https://user-images.githubusercontent.com/82968538/122307602-4751e180-ced0-11eb-8862-4b53bcaceb0e.png)
![image](https://user-images.githubusercontent.com/82968538/122307623-4f118600-ced0-11eb-9a51-a479a7c2c207.png)
![image](https://user-images.githubusercontent.com/82968538/122307634-546ed080-ced0-11eb-98c3-0164094bdc4b.png)
![image](https://user-images.githubusercontent.com/82968538/122307654-63558300-ced0-11eb-9a5b-f91c25dca906.png)
![image](https://user-images.githubusercontent.com/82968538/122307662-681a3700-ced0-11eb-8629-f612992e36e1.png)
![image](https://user-images.githubusercontent.com/82968538/122307668-6badbe00-ced0-11eb-882c-54b2b10cef6f.png)
![image](https://user-images.githubusercontent.com/82968538/122307682-710b0880-ced0-11eb-9e1b-a33c3003d72b.png)
![image](https://user-images.githubusercontent.com/82968538/122307701-7a947080-ced0-11eb-8945-0ffd023e4c32.png)
![image](https://user-images.githubusercontent.com/82968538/122307711-7f592480-ced0-11eb-9987-7f7a8cbb2433.png)
![image](https://user-images.githubusercontent.com/82968538/122307719-82ecab80-ced0-11eb-833f-5bdafd18cd37.png)
![image](https://user-images.githubusercontent.com/82968538/122307728-86803280-ced0-11eb-97dd-8babc88651c3.png)
![image](https://user-images.githubusercontent.com/82968538/122307734-8aac5000-ced0-11eb-9b5c-68824521af6b.png)
![image](https://user-images.githubusercontent.com/82968538/122307750-8ed86d80-ced0-11eb-9e05-f7cf6be0b8fc.png)
![image](https://user-images.githubusercontent.com/82968538/122307765-93048b00-ced0-11eb-85dd-50f53f3173c4.png)
![image](https://user-images.githubusercontent.com/82968538/122307784-98fa6c00-ced0-11eb-93b2-46a88a92266c.png)
![image](https://user-images.githubusercontent.com/82968538/122307797-9dbf2000-ced0-11eb-9137-b778f061f49d.png)
![image](https://user-images.githubusercontent.com/82968538/122307807-a152a700-ced0-11eb-9c4e-fd0b2914cc8d.png)

**Comment by sijugeorge-zco** [comment]
@tlakhtak 

Do we need translations for these events _(attached Image)_, since they are SENSOR events ?

![SensorEvents](https://user-images.githubusercontent.com/63731044/122912729-47415e00-d376-11eb-9ae6-e5b81644bc1b.png)

Hindi Translations are needed( _generate translations for right side value for each key on the attachment_ ) for the attached file (_Hindi_Transaltion_Needed_06222021.txt_) 

[Hindi_Transaltion_Needed_06222021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6693680/Hindi_Transaltion_Needed_06222021.txt)

**Comment by tlakhtak** [comment]
For now SENSOR translation is not required

**Comment by tlakhtak** [comment]
[Hindi_Transaltion_Needed_06222021.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6716287/Hindi_Transaltion_Needed_06222021.txt)
Completed translations.

**Comment by tlakhtak** [comment]
Is there any more text that requires Hindi translations?

Additionally, we would also like to proceed with Kannada translations. Please provide documents for which to provide translations.

**Comment by michaelmenon** [comment]
@tlakhtak can we create a new feature request ticket for this. not sure this we should continue this on this issue thread which was closed.

**Comment by tlakhtak** [comment]
#347 added as a new issue.
