### ISSUE TITLE
Create Survey Link

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#305]
> It would be helpful to have a public survey link feature on the lamp platform akin to REDCap's. That way, a direct link to a survey can be sent out for testing rather than having people go through the log in process and navigating to the survey on their own.

**Comment by michaelmenon** [comment]
Need to discuss internally with LAMP team to include this feature. Will update.

**Comment by michaelmenon** [comment]
@avaidyam let us know if this needs to be included.

**Comment by avaidyam** [comment]
@michaelmenon As @ZCOEngineer was not assigned, it is not included for work.

**Comment by michaelmenon** [comment]
ok thanks for the confirmation
