### ISSUE TITLE
Participant Log In Error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#306]
> Participant tried to login on iPhone using their temporary email (U8974761142@lamp.com) and password (U8974761142). Pop up appeared mentioning "incorrect username, password, or server address" and "invalid id or password". The same thing happened when I tried to log in using these credentials on my chrome browser. No credentials showed up when I logged in as an admin and selected the key next to their name.

> 
![image](https://user-images.githubusercontent.com/86117379/123842777-27aeb600-d8df-11eb-9b42-b0e7c0e25e04.png)

**Comment by sarithapillai8** [comment]
Could you please confirm that this user created with group creation?
