### ISSUE TITLE
Survey notification does not work for some schedules

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#309]
> Scheduling surveys to occur "Two times every month" does not appear to work. Surveys do not appear in the Feed section. This is true on phones and via a browser.

**Comment by Linoy339** [comment]
@tlakhtak Could you please attach a screenshot of particular schedule?

**Comment by tlakhtak** [comment]
Collaborators want to be able to schedule survey notifications for every two weeks from start date, rather than on two fixed days every month. Can this be added as a feature?

**Comment by sarithapillai8** [comment]
@tlakhtak 
Yes we can add this as feature.  Do you need this as new schedule type or change the current implementation of 'Two times every month'?

**Comment by tlakhtak** [comment]
We would need this as a new schedule type

**Comment by sarithapillai8** [comment]
@avaidyam Please confirm if we can proceed with implementing this. New feature requests were in hold.

**Comment by Linoy339** [comment]
@SuruPa00. The related changes has  been done and released in LAMP-worker

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production.
