### ISSUE TITLE
Block passive data from the LAMP database for one or more participants

### ISSUE THREAD

**Issue by er42** [BIDMCDigitalPsychiatry/LAMP-platform#312]
Maybe this is a naive question, but is there a way to block `SensorEvent` data from being saved in the LAMP database for one or more participants? If not, this would be a very useful feature (either for specific sensors, or for all sensors).

**Comment by avaidyam** [comment]
By removing all Sensors in a Study, the Participants in that study should no longer be collecting any passive data. You can also pick and choose the Sensors to collect data from.

**Comment by er42** [comment]
Hi @avaidyam -- thanks for the quick response! 

We had actually specified only one sensor (`lamp.gps`) for the study, but we are receiving data from various others (including accelerometer, gyroscope, etc.). Is there a way we can prevent this?

**Comment by avaidyam** [comment]
@er42 This feature is enabled in the beta build and will soon go live for everyone!

**Comment by er42** [comment]
I see -- is there an ETA of when the new production build will be released?

**Comment by avaidyam** [comment]
I think @SuruPa00 might have more info on that this week or next! We'll update here as well when it's released.

**Comment by er42** [comment]
Great -- thanks!

**Comment by er42** [comment]
Just following up on this -- we've been testing out the new release of the iOS app and the feature to select only specific sensors seems to be working for it. 

However, on the Android beta build (installed via the google play store), we are still getting data from various other sensors.  Is that expected? Is there another android beta version available that allows more control over sensor selection?

**Comment by SuruPa00** [comment]
Hi there! So the android app is still currently in the process of being pushed to latest build (which the iOS version is currently using), so there may be differences between the two right now. We hope to have this issue solved in the next week or two!

**Comment by er42** [comment]
Ok, thanks for the update! We'll be glad to test out the new android build once it's available.

**Comment by er42** [comment]
Hi @SuruPa00, is there any news yet on when this functionality will be available in the android app (either the beta or production version)?

**Comment by SuruPa00** [comment]
@er42 The android update process ended up being a bit more complicated than expected but we did just submit the last piece needed for it to go through this past week, so hopefully within the next week!

**Comment by er42** [comment]
@SuruPa00 Just checking in... any news on the status of the android update? Thanks!
