### ISSUE TITLE
Back button and instructions missing for Jewels A&B and Spatial Span

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#313]
Patients do not know how to play the games, and have to exit the app and restart to return to main menu from Spatial Span or jewels A and B cognitive tests. 

> ![image](https://user-images.githubusercontent.com/82968538/124189792-4653af00-da8f-11eb-887d-af72492c4eb3.png)
> ![image](https://user-images.githubusercontent.com/82968538/124189808-4c499000-da8f-11eb-9488-7ad63b5b04cd.png)
>![image](https://user-images.githubusercontent.com/82968538/124189828-523f7100-da8f-11eb-86b2-cc8c68399c97.png)

**Comment by sarithapillai8** [comment]
We didn't add instructions. If you need this changes, please make a feature request. @avaidyam  Please confirm.

**Comment by tlakhtak** [comment]
Seems like instructions shown in activity descriptions were not appearing on the front page for a collaborator, but our team and their team cannot reproduce now
