### ISSUE TITLE
Clicking on a notification takes you to a blank page and not the activity

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#32]
> **Collaborator 1**:
> ![image](https://user-images.githubusercontent.com/1361003/98839529-a370f680-2413-11eb-9dc3-cf8dccd17f49.png)
>
> **Collaborator 2**: When clicking on a notification, the mindLAMP app opens up but just shows a blank screen and does not go to the surveys
> 
> **Collaborator 3**: When clicking on a notification for the mind lamp 2 app, it just goes to a blank screen. Although the notifications are coming up in the phone's notification centre they are not working with the app and bringing the user to the surveys and cognitive tests they are supposed to complete.
> 

@Linoy339 I know you had mentioned that the push notification code is sending URLs in the form `https://{DASHBOARD_URL}/#/participant/{PARTICIPANT_ID}/activity/{ACTIVITY_ID}/`.
@sarithapillai8 Is the UI code handling this behavior correctly? 

@Linoy339 @jijopulikkottil Ideally we actually want to be sending only the fragment of the page URL like so: `/participant/{PARTICIPANT_ID}/activity/{ACTIVITY_ID}/` and the native app should be loading the web view that has already been authenticated and appending this to the base URL. Is that behavior something we can switch to?

**Comment by jijopulikkottil** [comment]
Here also we can set the 'LAMP._auth' to the `sessionStorage` and can load the notification page (activity url) on the second `WKWebview` as it is doing now with existing build. right ?

**Comment by avaidyam** [comment]
Yes, this issue may be a duplicate of the other issue then.
