### ISSUE TITLE
Data inside survey missing

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#320]
> Displaying data in some questions within survey but not all. See screenshot where data is missing.
![v143w4Sj_o](https://user-images.githubusercontent.com/86117379/125623069-05c764b6-94a7-4030-bf90-569aefd219c4.jpg)

**Comment by sarithapillai8** [comment]
@SuruPa00 
Could please specifically point out what is actually missing?
