### ISSUE TITLE
URGENT - All activities not loading

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#321]
Morning of July 16 2021, all activities on dashboard return loading screen and cannot be used. Dashboard is available and loads fine but no activities can be used. Server running LAMP is still working fine.

**Comment by tlakhtak** [comment]
Seems to have just resolved - what might have been the issue? @ZCOEngineer

**Comment by jtorous** [comment]
There was are error in the built tag our team reverted as a fix . We are not sure why this tag was incorrect. 

John
