### ISSUE TITLE
URGENT: Notifications for scheduled activities appear at incorrect times, don't lead to activities

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#326]
> I scheduled 5 different surveys to start next week M-F on a weekly schedule at 9 am. Everyone (3 people testing the app) then received a notification at 9 am today (Friday) that ALL the surveys were due. However when I click on the notification nothing happens, presumably because I cannot do the survey yet. Seems like notifications are showing up on the day created, rather than the day they are scheduled to appear.

This issue was happening on an Android Pixel 5, and an iPhone XS in the Researcher group ```3a8bgz4z43t02q64k75f```. I could not replicate this on my own with a testing account using the exact same schedule of activities in the same group and while the testing account was receiving the correct schedule on my end, the other accounts still received the incorrect schedule. They tried making another testing account as well but that also showed the wrong schedule.

**Comment by Linoy339** [comment]
@tlakhtak . We were not considering the start date  here, so the notification gets fired before.
We will give a fix for this

**Comment by SuruPa00** [comment]
@ZCOEngineer @Linoy339 any update on this?

**Comment by Linoy339** [comment]
@SuruPa00 . Yes, this has been fixed in LAMP-worker. 
We are trying to deploy Lamp-worker. When it comes up, it will be resolved

**Comment by SuruPa00** [comment]
@Linoy339 sorry if i misunderstood, does that mean this bug has been fixed and should no longer be occurring?

**Comment by Linoy339** [comment]
@SuruPa00 . The resolution has been done and  moved to staging. 
This need to move to production for the issue  to be fixed. Before, we need to test the same  in the staging environment. But now, we face some issue in deploying it in staging server. We are looking into it. We will let you know  ASAP
