### ISSUE TITLE
Unable to log in as a researcher to dashboard

### ISSUE THREAD

**Issue by Ashermind** [BIDMCDigitalPsychiatry/LAMP-platform#327]
**Describe the bug**
After the redeployment of the lamp platform and creating researcher in the dashboard, I am unable to open him or log in as him. Instead I am stuck on the loading screen.

**Expected behavior**
I except to open or log into empty patient page, where I would like to create patient accounts for usage and testing.

**Screenshot**
![Screenshot_2021-07-26_03-42-20](https://user-images.githubusercontent.com/46451717/126922113-6692732d-7152-4f82-84bb-a8e28f3370bc.png)

**Database logs**
Lamp_database.1.zxm5j6qs21cy@tuplak    | [notice] 2021-07-26T01:28:18.353692Z nonode@nohost <0.6581.120> 6df77f0454 database:5984 10.0.1.5 admin HEAD /participant/09nn0c5vhp62xqh5k06j 404 ok 1
Lamp_database.1.zxm5j6qs21cy@tuplak    | [notice] 2021-07-26T01:28:18.357110Z nonode@nohost <0.6585.120> 9585d636b4 database:5984 10.0.1.5 admin HEAD /researcher/09nn0c5vhp62xqh5k06j 200 ok 1
Lamp_database.1.zxm5j6qs21cy@tuplak    | [notice] 2021-07-26T01:28:18.384373Z nonode@nohost <0.32622.119> 8242be1c7b database:5984 10.0.1.5 admin POST /credential/_find 200 ok 3
Lamp_database.1.zxm5j6qs21cy@tuplak    | [notice] 2021-07-26T01:28:18.387783Z nonode@nohost <0.6586.120> 68cc680185 database:5984 10.0.1.5 admin POST /researcher/_find 200 ok 2
Lamp_database.1.zxm5j6qs21cy@tuplak    | [notice] 2021-07-26T01:28:18.527091Z nonode@nohost <0.32621.119> 4bf5344ede database:5984 10.0.1.5 admin POST /credential/_find 200 ok 3
Lamp_database.1.zxm5j6qs21cy@tuplak    | [notice] 2021-07-26T01:28:18.530829Z nonode@nohost <0.6584.120> d48fa57dc4 database:5984 10.0.1.5 admin POST /study/_find 200 ok 2

**Server:**
- Image: bidmcdigitalpsychiatry/lamp-server:2021 (fresh redeployement last Tuesday 2021 08. 20.).
- OS: # 1 SMP Debian 4.19.181-1 (2021-03-19)
- Kernel: 4.19.0-16-amd64

**Comment by SuruPa00** [comment]
Hi @Ashermind, is this issue still persisting? If so, let me know!

**Comment by Ashermind** [comment]
> Hi @Ashermind, is this issue still persisting? If so, let me know!

Before I check it, should we try updating?

**Comment by SuruPa00** [comment]
Yes! Try updating and seeing if the issue is still persisting. There have been some updates in the past few weeks that may solved your issue. Else, we can look into it further!
