### ISSUE TITLE
Modify settings for Jewels game modes and merge variants

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#33]
> **Collaborator**: we cannot understand how the levels in the jewels games work, we always manage to play the beginner. It is connected by chance to a specific number of plays.

Right now there are 4 sets of parameters, `beginner`, `intermediate`, `advanced` and `expert` (or similar names), and two variants `A` and `B` for the Jewels game. In mindLAMP 1, the Jewels game would change the difficulty mode based on previous scores, but this functionality is not automatic or supported in mindLAMP 2, so it makes no sense to have multiple confusing.

1. Merge the code for both `Jewels A` and `Jewels B` into one codebase to keep things simple.
1. Add a `variant` parameter to the `settings` that can be either `Trails A` or `Trails B` -- based on which the code will change what types of Jewels are displayed.
1. Add a `mode` parameter to the `settings` that can be one of `beginner`, `intermediate`, `advanced` and `expert` -- this will tell the code what settings/mode to use. [There is already a static compile-time variable for this](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/a9c3f9322050ae1d03dd307f0cb178a9956789e6/JewelsPro/src/components/jewels/Jewels.tsx#L65) that could just be updated to instead check for a `mode` and if not found or invalid, default to `mode=1`.

**Comment by sarithapillai8** [comment]
@avaidyam 
Which activity spec should be used for both games?

**Comment by avaidyam** [comment]
Either activity spec should work temporarily (i.e. both have the same parameters, but the default variant for A is "trails_a" and for B it's "trails_b"), then we can pick one to hide later.

**Comment by sarithapillai8** [comment]
@avaidyam 
I have updated the pull request with the above default settings.

**Comment by avaidyam** [comment]
@sarithapillai8 Does this also add the `mode` settings variable as well? Or just `variant`?
