### ISSUE TITLE
DBT Diary Card Graph in Prevent has NaN x-axis

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#330]
> I am using the MindLAMP 2 app on iOS 14.7 when I get this error. I click on the Prevent tab. Under Activity I click on "DBT Diary Card". When I view the visualizations for "Emotions" , Urges (effective), Urges (ineffective), Actions (Timeline) the x-axis shows "NaN" instead of dates. (See screenshots MindLAMP iOS 1 of 4 - MindLAMP iOS 4 of 4). I do not see this error when I view the DBT diary card visualizations on a web browser (Edge and Chrome). The x axis shows dates and plots my DBT diary card responses over time. (See screenshots MindLAMP Browser 1 of 3 - MindLAMP Browser 3 of 3)

Mobile 

![MindLAMP iOS 1 of 4](https://user-images.githubusercontent.com/86117379/127202706-9921d879-3bef-4315-a94a-37c3ceeab88b.PNG)
![MindLAMP iOS 2 of 4](https://user-images.githubusercontent.com/86117379/127202710-9e111b8f-e1ab-4380-a5aa-34e5d60a8aa9.PNG)
![MindLAMP iOS 3 of 4](https://user-images.githubusercontent.com/86117379/127202711-c977fdf7-7677-400c-88fc-8f3392457e77.PNG)
![MindLAMP iOS 4 of 4](https://user-images.githubusercontent.com/86117379/127202718-baa1ac53-4af6-4e39-9b8d-9836b23ed139.PNG)

Browser

![MindLAMP Browser 1 of 3](https://user-images.githubusercontent.com/86117379/127202824-37fbc95e-c109-40b4-ad65-06a7d60eec3b.png)
![MindLAMP Browser 2 of 3](https://user-images.githubusercontent.com/86117379/127202826-5a13b362-c788-4b7e-b0dd-3f99eb179590.png)
![MindLAMP Browser 3 of 3](https://user-images.githubusercontent.com/86117379/127202822-820887c4-73b6-49a7-9b39-72bb671f9ec6.png)

**Comment by sarithapillai8** [comment]
Issue fixed and updated in production. 
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/278
