### ISSUE TITLE
LAMP-worker causing docker container terminations

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#331]
Shortly after creating a new docker container using the LAMP-worker image, the container crashes. Initially, the container terminates with no exit code, but then quickly terminates again with exit code 137. This repeats, but at no time is the container stable for longer than 5 minutes.

Here are the logs for one iteration of this loop:
```
locked job on activity_scheduler,
participantslength 0,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given 022szr8y2v4kqr09y46m,
Saving to redis,
Processing 1 activities for push notifications.,
Preparing to fetch activities,
activity_id given 2gefteve45gkk1a67y80,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given 0h1ch1a00fj5n6yjdjsy,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 3,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given 43w7df4nnseh3mfc49ha,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 0,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given xapxxrbv220bjrra36hf,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 0,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given 2yphpangaebzxh12d1qh,
Saving to redis,
Processing 1 activities for push notifications.,
Preparing to fetch activities,
activity_id given 0q6trf6nj2c722mz6t38,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given bkj0d2djetqgm88fzwea,
Saving to redis,
Processing 1 activities for push notifications.,
Preparing to fetch activities,
activity_id given hc2t5hhrn9yz38dd1kf9,
Saving to redis,
Processing 1 activities for push notifications.,
Preparing to fetch activities,
activity_id given cp74pxwhkwaj6c4yargt,
Saving to redis,
Processing 1 activities for push notifications.,
Preparing to fetch activities,
activity_id given d8jcjd9j2t9btkjqyqts,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
locked job on activity_scheduler,
participantslength 1,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
Preparing to fetch activities,
activity_id given 42bbcpyp11f8pygk18pc,
Saving to redis,
Processing 1 activities for push notifications.,
locked job on activity_scheduler,
participantslength 13,
Saving to Redis completed....,
release lock  on success  activity_scheduler,
```
These were the final logs before a termination.

The logs are quite variable - at one point these messages related to queues appeared. During one iteration the only logs that appeared had to due with the queue - see below.
<img width="245" alt="Screen Shot 2021-07-28 at 2 47 25 PM" src="https://user-images.githubusercontent.com/34659264/127382501-0c2e9c8c-bdc8-46fe-b4d8-489011121ec2.png">
 
<img width="441" alt="Screen Shot 2021-07-28 at 3 01 01 PM" src="https://user-images.githubusercontent.com/34659264/127382331-63e97d31-0234-4b80-8865-79686d77421b.png">

Please let us know if there is additional information we can provide regarding this issue.

**Comment by Linoy339** [comment]
Can you provide the docker file?

**Comment by Linoy339** [comment]
@SuruPa00 
https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/blob/master/Dockerfile
Is this one which you are using?

**Comment by lukeoftheshire** [comment]
Yes, that is the dockerfile.

**Comment by Linoy339** [comment]
I was able to run with this docker file in my  local machine and its still running.
Is the container available in portainer(https://console.lamp.digital)? If yes, can you please mention the container name?

**Comment by lukeoftheshire** [comment]
I have just re-added a single container with the name lamp_staging_worker .

**Comment by Linoy339** [comment]
@lukeoftheshire .
Can you please check with memory
usually exited with 137  denotes  Out of memory

**Comment by lukeoftheshire** [comment]
Hi @Linoy339 

Thank you for looking into this. We haven't placed any particular memory constraints on the docker container, but we will continue looking. As we investigate, would you be able to provide the memory specs of your local machine, and/or the amount of memory we should reserve to run the worker?

**Comment by Linoy339** [comment]
Mine is with 8gb. But my db size is less compared to LAMP-server db. 
I think 4 gb would  be sufficient. Can you check with @avaidyam for this?

**Comment by avaidyam** [comment]
We should have 32GB available on `node-02` @lukeoftheshire so it shouldn't have been a problem? @Linoy339 Why is there such high memory usage to begin with? Is it something we can reduce or would that take more effort in the long term?

**Comment by Linoy339** [comment]
@avaidyam . I have run the same docker file here and its running well.  It is not getting stopped till now.

As the message from  your container logs was -  "exited with 137". I just guessed with out of memory.
Still, we are not sure of how it ran across this problem

**Comment by avaidyam** [comment]
Can you add more logging to it across the whole codebase? (Same for LAMP-server eventually). I suspect it may be the same `UnhandledPromiseRejection` issue or something similar that occurs in Node 14+.

**Comment by lukeoftheshire** [comment]
Yes, I think something else is happening in additon to our (potential) memory problem. As Adiya mentioned, node-02 is provisioned with 32GB of memory. Additionally, `top` didn't show any big memory usage at any point before the container failed.

As I initally alluded to, the container is first stopping twice (with no error code) before it terminates with code 137. Could these first two terminations have any meaning?

**Comment by Linoy339** [comment]
@lukeoftheshire @avaidyam . Let us check in deeper and let you know

**Comment by Linoy339** [comment]
@lukeoftheshire . Can I deploy in node-02?

**Comment by lukeoftheshire** [comment]
Sure!

**Comment by Linoy339** [comment]
@lukeoftheshire . Can you please add network "lamp_staging_default" to  container - "lamp_worker_01". It seems, I am uinable to do it

**Comment by Linoy339** [comment]
@lukeoftheshire . Can you merge [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/12](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/12) 
and try deploying and let us know the container name.

**Comment by Linoy339** [comment]
@lukeoftheshire . Can you deploy now?

**Comment by lukeoftheshire** [comment]
Yes! I have updated the image and redeployed. As before, the container is from the service lamp_staging_worker

**Comment by Linoy339** [comment]
@lukeoftheshire . Can you please change the port in .env(say 3001 instead of 3000) and redeploy it?

**Comment by lukeoftheshire** [comment]
I have updated the port to 3001 and redeployed

**Comment by Linoy339** [comment]
Can You update the variable SCHEDULER to off in env and redeploy?

**Comment by lukeoftheshire** [comment]
Done

**Comment by Linoy339** [comment]
Can you merge [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/13](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/13)

and remove DOCKER_IMAGE from env and redeploy?

**Comment by lukeoftheshire** [comment]
Done and done!

**Comment by Linoy339** [comment]
Can you check the container health :
https://console.lamp.digital/#!/4/docker/containers/388c3f4568fb354bf0b1e594a044508cffba5da36ebc6a70784d0a7a1d0ace9b?nodeName=node-02.lamp.digital?
It says :
Connecting to localhost:3000 (127.0.0.1:3000) wget: can't connect to remote host (127.0.0.1): Connection refused ?
Is there any network properties to be enabled?

**Comment by lukeoftheshire** [comment]
I see both lamp_staging_default and public as available networks

Additionally, the following logs appear in the logs:
```    
Running with schedulers disabled.
Initiating nats server
topic published activity_event
topic published activity
topic published participant
topic published researcher
topic published sensor_event
topic published sensor
topic published study```

**Comment by Linoy339** [comment]
Please merge this too 
https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/14
and redeploy .

**Comment by lukeoftheshire** [comment]
Merged and redeployed.
To note, all previous changes, (port, scheduler, etc.) are still in effect.

**Comment by Linoy339** [comment]
Can you make it as earlier?
PORT 3000
SCHEDULER ON

**Comment by lukeoftheshire** [comment]
The PORT and SCHEDULER variables have been reset as specified

**Comment by Linoy339** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/15

please merge and redeploy

**Comment by lukeoftheshire** [comment]
Done.

Of note, the log appears to have changed to :
```Connecting to localhost:3000 (127.0.0.1:3000) wget: server returned error: HTTP/1.1 404 Not Found```

**Comment by Linoy339** [comment]
I am not sure on this. Let me check once again and come back. It seems to be an issue with network or dns, which I am not sure about.
Can you check from your end on the network ?

**Comment by Linoy339** [comment]
@lukeoftheshire . It seems like Lamp-worker and api-staging server is using the redis container of production .

Please find the error in api-staging while we post the sensor_event:
POST /participant/U0899474655/sensor_event 200 - 2.746 ms,
Error: getaddrinfo ENOTFOUND message_queue,
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {,
  errno: -3008,,
  code: 'ENOTFOUND',,
  syscall: 'getaddrinfo',,
  hostname: 'message_queue',
},

We think, In both env of  Lamp-worker and api-staging server, we should fill REDIS_HOST from lamp_staging_default network.
Now, redis container from lamp_default is used.

Please correct it

**Comment by Linoy339** [comment]
@lukeoftheshire . I have created a container named "lamp_staging_worker01".
It is running. But, found that there is some issue while connecting to redis. Here, I face a problem of connecting to proper network. I was able to connect to public, but not to lamp_staging_default  network.
Can you please connect it to lamp_staging_default  network also?

**Comment by Linoy339** [comment]
@lukeoftheshire . or else you can simply stop the container -"lamp_staging_worker01" and start a new one.
Please let us know if done

**Comment by lukeoftheshire** [comment]
I have spun up a new container from the service specification, which should have access to the lamp_staging_default. It still has the name lamp_staging_worker

Two things I noticed as I did so:
1. When I manually stopped the running 'lamp_staging_worker1" container through portainer, it terminated in the same way that the other container did - two terminations with no error code and then a termination with error code *137*.
2. I noticed some env variables in the lamp_staging_worker that were not in the original dockerfile. I have added those to the service so they should now be present.

**Comment by Linoy339** [comment]
Can you please merge this:

[https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/19](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/19)

and redeploy?

**Comment by lukeoftheshire** [comment]
Merged and redeployed

**Comment by Linoy339** [comment]
Thanks @lukeoftheshire

**Comment by Linoy339** [comment]
@lukeoftheshire .Please merge [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/20](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/20)

**Comment by Linoy339** [comment]
@luke. We have merged it. 
Can you please deploy it for once now and also make sure that the container doesn't get removed
even if it get failed or stopped

**Comment by Linoy339** [comment]
Hi @lukeoftheshire . The stack has been updated and redeployed. Its working as expected.
The reason of termination was that the stack was provided with an unwanted health check. LAMP-worker is not to be exposed and its for internal purpose which it subscribe to nats server. We believe, this was copied from api-staging server. 
Also, we have removed the host rule (traefik.http.routers.lamp_worker_staging.rule: 'Host(`api-staging.lamp.digital`)') from LAMP-worker stack, which is unnecessary.

We will test it now  and let you know soon

**Comment by lukeoftheshire** [comment]
Hi @Linoy339 ! Thank you for your hard work on this. How did the test go? Do you think we are ready to deploy this to the staging server again? If so, what steps can we take on our end to help you/get set up?

**Comment by Linoy339** [comment]
Hi @lukeoftheshire . Its already in staging and we have tested it in staging and is working as expected. As we said above, the termination happened because the stack was provided with an unwanted health check.
We aleady asked @SuruPa00 for the testing from your end. If everything goes well, we can move to production.

**Comment by lukeoftheshire** [comment]
This looks good per some testing and reviews from other members of the team - I think we are ready to push this to production!

Thank you all very much for your hard work on this issue!

**Comment by Linoy339** [comment]
Thanks @lukeoftheshire . We can push to production ASAP
