### ISSUE TITLE
URGENT: Not collecting passive data

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#332]
> A participant in the digital clinic (U5059078716) has not been getting passive data for a couple of weeks now. They report that their phone may have died in the past couple of weeks but they did not delete and re-download the app. They have been taking surveys. Reports sometimes having phone on low power mode, but not always.

See permissions page below:
![image0](https://user-images.githubusercontent.com/86117379/127665233-be7e4f6a-e06a-46b5-99bd-918dd12d1132.png)

**Comment by zcoaskchemicals** [comment]
It seems the data has not been captured because the phone was off , could you check if the data is coming now after the phone is switched on. Can you ask the user to login to the app once.  Also low power mode also disables GPS and other sensor data. I will double check on this and let you know.

**Comment by michaelmenon** [comment]
It seems the data has not been captured because the phone was off , could you check if the data is coming now after the phone is switched on. Can you ask the user to login to the app once. Also low power mode also disables GPS and other sensor data. I will double check on this and let you know.

**Comment by jijopulikkottil** [comment]
@SuruPa00 We will not sync data to server in low power mode. That might be the reason.
