### ISSUE TITLE
Reminders not working on dashboard

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#333]
> For participant U5059078716, scheduled activity reminders are not showing on the feed despite being set in settings.
<img width="300" alt="Screen_Shot_2021-07-30_at_10 33 44_AM" src="https://user-images.githubusercontent.com/86117379/127692011-ab0fcb88-d351-416f-b2e5-fc60c9818e36.png">
<img width="300" alt="Screen_Shot_2021-07-30_at_10 33 21_AM" src="https://user-images.githubusercontent.com/86117379/127692017-6333fe07-6055-4340-a935-399a25ce65af.png">

**Comment by sarithapillai8** [comment]
Fix updated in this PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/281
We moved the fix in staging. Once QA done, we can move this to production.

**Comment by sarithapillai8** [comment]
Updated in production
