### ISSUE TITLE
Issues having multiple dashboard tabs open

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#334]
**Describe the bug**
Impossible to have 2 different dashboard tabs open without glitches. One of the tabs imports the participants from the other tab even if you are looking at different studies.

**Expected behavior**
Should be able to have multiple tabs open at once with different researchers or participants open.

**Comment by sarithapillai8** [comment]
@avaidyam @SuruPa00 
Please provide more details for this issue. It seems working from two tabs. Where did you see the issue?

**Comment by dcurrey88** [comment]
If I go onto one tab on one researcher and another tab on a different researcher the first tab will show all participants from both the first and second researcher. They will show up under the filter, and if you toggle to the activities page and back to users they will show there as well.

**Comment by SuruPa00** [comment]
This issue is no longer appearing and appears to be fixed
