### ISSUE TITLE
Filtering participants persists across sessions

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#335]
**Describe the bug**:
Certain users in researchers become filtered out and then we have to manually filter them back in at the top to see them.

**Comment by sarithapillai8** [comment]
@avaidyam  @SuruPa00  
Could you please provide more details on this? If this is about study filter, then the expected behavior is saving selected studies in tag and loading details based on that. When manually change, this tag info will be updated and details will be loaded accordingly.

**Comment by avaidyam** [comment]
Filters should no longer be using Tags; clinicians want these to NOT be shared across devices.

**Comment by sarithapillai8** [comment]
@avaidyam 
The filtering of activities, sensors, participants are using study filter. Do you remove that entirely? If so, could you please update this as feature task as it is not a bug then. This is working as expected with our current implementation.

**Comment by avaidyam** [comment]
No, we do not want to remove the filters, but change the implementation to use localStorage instead of Tags.

**Comment by sarithapillai8** [comment]
@avaidyam 
Sorry, This is not clear. I understood the change to replace the tags with localStorage. But how that achieve the change requested in the task description?

**Comment by avaidyam** [comment]
Switching to localStorage should solve this problem, caused by filters being set on one device and also appearing for the same account on another device.

**Comment by sarithapillai8** [comment]
Ok. Got it. Thanks.

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in dashboard-staging. QA completed. Production can be updated with User hierarchy changes.

**Comment by sarithapillai8** [comment]
@SuruPa00 

Updated in production. Please check
