### ISSUE TITLE
Breathe activities audio does not work

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#337]
**Describe the bug**:
Breathe activities have a slot to put a link to audio, but this does not actually function.

**Comment by sarithapillai8** [comment]
@avaidyam 
We could not reproduce this. Could you please confirm?

**Comment by dcurrey88** [comment]
@sarithapillai8 You are correct, it is now working on our end. I will close this issue.
