### ISSUE TITLE
Clicking on an activity should take you there

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#339]
**Describe the bug**:
When users click on activities in the feed, it does NOT take them to the activity.

**Comment by sarithapillai8** [comment]
@avaidyam @SuruPa00 
Could you please provide the details? We have some time restrictions for accessing the activities from feed.  For eg : Hourly activities can have multiple rows in feed, and only upcoming ones can be accessed. Like that we have different schedule based restrictions. So could you please confirm this is not the case?

**Comment by avaidyam** [comment]
That is the correct behavior; @dcurrey88 are you referring to how past/inactive schedules look the same as future/active schedules?

**Comment by dcurrey88** [comment]
@sarithapillai8 Users should not be able to click on activities from the past, but currently the feed will never take you to an activity, regardless of the time when its scheduled.

**Comment by SuruPa00** [comment]
This issue is no longer appearing
