### ISSUE TITLE
Activities become de-selected when accessing the next page

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#343]
**Describe the bug**
When selecting activities under the “activities” page from a researcher account, if you change the page to see the next part of the list, the activities that you have already selected often become de-selected.

**Comment by sarithapillai8** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/commit/74820f0627385a0378a8b728af339436fb0c9f5b - Updated in dashboard-staging

**Comment by sarithapillai8** [comment]
@SuruPa00
Updated in production.
