### ISSUE TITLE
Journal survey crashing

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#346]
Participant U5059078716 inside the TECC study has reported the journal survey to be crashing once they type around 100 characters. Additionally is it possible to make a longer textbox than 300 characters?

**Comment by sarithapillai8** [comment]
@SuruPa00 
Could you suggest what is the limit you need for the text then? Also we are not able to reproduce this with 100 characters. Could you provide any screenshot or video with issue?

**Comment by SuruPa00** [comment]
Hi @sarithapillai8, could we make the textbox have a limit of 800 characters?

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
The changes are updated in production.
