### ISSUE TITLE
Kannada Translations

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#347]
Our collaborators would like to implement Kannada translations on the app. Please provide text for us to get translated.

**Comment by michaelmenon** [comment]
Ok great thanks for creating this as a new ticket, we will get back on the strings asap

**Comment by sijugeorge-zco** [comment]
@tlakhtak

Please find the texts to be translated to Kannada.

Please use the **right side values** of each texts on the attached files.


[JewelsPro_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967675/JewelsPro_translations.txt)
[Journal_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967676/Journal_translations.txt)
[MedicationTracker_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967677/MedicationTracker_translations.txt)
[PopTheBubbles_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967678/PopTheBubbles_translations.txt)
[ScratchImage_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967679/ScratchImage_translations.txt)
[Survey_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967680/Survey_translations.txt)
[Tips_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967681/Tips_translations.txt)
[VoiceRecording_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967682/VoiceRecording_translations.txt)
[BoxGame_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967666/BoxGame_translations.txt)
[CatsAndDogs_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967668/CatsAndDogs_translations.txt)
[Dashboard_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967671/Dashboard_translations.txt)
[DBT_DiaryCard_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967672/DBT_DiaryCard_translations.txt)
[Goals_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967673/Goals_translations.txt)
[HopeBox_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967674/HopeBox_translations.txt)
[BalloonRisk_translations.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6967664/BalloonRisk_translations.txt)

**Comment by avaidyam** [comment]
Let's move this discussion to #138 to keep all the translation files and comments in sync.
