### ISSUE TITLE
Welcome Note about version upon login

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#348]
We would like a minor feature that lets a user know when they login if they are not using the latest version of LAMP. When someone logs in and they are using an outdated version of LAMP, they would be notified with perhaps a pop-up or another way to say "Note: This is NOT the latest version of LAMP".  or "Note: This is the latest version of LAMP." if they are using the latest up to date version.

**Comment by sarithapillai8** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/287 - Updated
