### ISSUE TITLE
Change sorting order for Activities and Patient lists

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#35]
> **Collaborator**: Activities (on the dashboard) show up in a random, different order each time the researcher logs in. When I look at an activity list for a researcher on the dashboard, the activities are not displayed in the same order every time. Even refreshing the page changes which studies appear at the top. This makes it hard to get used to. 

I think we should change the sorting order to sort by `Study.name` (ascending/A-Z) and THEN `Participant.id` (ascending/0-9). That would solve this issue.

**Comment by sarithapillai8** [comment]
@avaidyam 
FYI - we are sorting activities by study.name followed by activity.title.
