### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#350]
User U7744128165 has reported the app crashing itself or sometimes crashing the entire app on a Samsung Note 10 running on Android Version 10.

**Comment by saranya-sajeev** [comment]
Hi @SuruPa00 
Is t possible to get more details on this? If the user can share the steps to reproduce the issue it will be very helpful for us to figure out the issue.

**Comment by SuruPa00** [comment]
Hi @saranya-sajeev, after uninstalling and redownloading the app, the crashing has ceased for now. For now, we should be fine and do not need it be looked into further.
