### ISSUE TITLE
DBT Diary Card Fixes

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#352]
- Add “amount” as an option for measurement under Actions in addition to the existing options of times, minutes, hours.

- The labels for target behavior should read Effective Target Behaviors and Ineffective Target Behaviors. Please add the word effective to the header for target behavior to differentiate between effective and ineffective target behaviors. Please see below.
![target](https://user-images.githubusercontent.com/86117379/128919950-7ecd7cf6-be49-4de5-9879-28d44f00a4e8.png)

-The actions timeline still plots effective/ineffective actions together, these need to be separated by color to denote the difference between the data points- please see below:
![actions](https://user-images.githubusercontent.com/86117379/128920017-acc7e444-94cd-4228-b9aa-f0cfea19ab94.png)

**Comment by sarithapillai8** [comment]
Updated the changes in production - BIDMCDigitalPsychiatry/issue-352
