### ISSUE TITLE
GoogleFit Connectivity Issues

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#354]
> Despite new update, beta version of the app is still reporting GoogleFit connectivity issues. mindLAMP is running on a different server than ours. Log displaying the error is attached here.

> [LampLog.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6969716/LampLog.txt)

**Comment by saranya-sajeev** [comment]
@SuruPa00 We are analyzing the Google fit issue, it is still not resolved. Google fit access is working fine for users those already gave consent to access Google fit data. Issue is with new users.  We are working on this issue.

**Comment by saranya-sajeev** [comment]
@SuruPa00 We have created a sample for checking Google fit issue. What we observed is that , in the  OAuth Consent screen of Google Cloud Console, we can select the **Publishing Status**. Currently our app's publishing status is **In Production**.
Another option is **Testing**. 

**In Production:**
Once you set your app status as "In production," your app will be available to anyone with a Google Account. Depending on how you configure your OAuth screen, you may have to submit your app for verification .

 **Testing:**
If your app is still being tested and built, you can set your status to "testing". In this state, you can test your app with a limited number of users.

For **Testing**, Google fit sign in will work only for the test accounts we have added in Google Cloud Console. I have added two test accounts for the sample app and OAuth Consent screen shown to that users. After changing the publishing status to **In Production**, the consent screen not shown even for the test accounts.  So my assumption is that apps that are in **In Production** status must complete verification to work the Google fit login.

**Comment by saranya-sajeev** [comment]
Could you please achange **"Publishing status"** to **Testing** in OAuth Consent Screen of Google Cloud Console and then you can add a test user. Then follow below steps

    

1. Add the test account on Android phone
2.     Launch mindLamp app.
3.     App will show a pop up to choose an account to continue, select the test account added in Google Cloud Console.
4.     App consent screen will show.
Then you can create the video and reapply for verification.

**Comment by SuruPa00** [comment]
@saranya-sajeev would changing the app status to testing affect users who are currently using the app? since we have many android users who are currently in use of the app, we want to make sure users are not negatively impacted

**Comment by saranya-sajeev** [comment]
@SuruPa00 For users those already gave consent to access google fit data, will not affect.

**Comment by SuruPa00** [comment]
@saranya-sajeev we just followed the instructions you provided, but no app consent screen appeared, any suggestions on next steps? we have a video, but it does not show the information we need since no screen came up with the listing of the permissions we are requesting did not display.

**Comment by saranya-sajeev** [comment]
@SuruPa00 have you changed the publishing status to Testing in Console https://console.cloud.google.com/apis/credentials/consent?authuser=1&folder=&organizationId=&project=api-6882780734960683553-445906 ?

**Comment by SuruPa00** [comment]
@saranya-sajeev yes, we did - we then added a test user with an email account, logged in using that email account and a dummy lamp user, and still did not see any screen - i can turn it back to testing if you need

**Comment by saranya-sajeev** [comment]
@SuruPa00 When I have checked in the developer account, the publishing status is still in Production.
![GoogleCloudConsoleImage](https://user-images.githubusercontent.com/81216000/130627151-86ed07fc-5ed3-4b27-8492-fc478d27356f.png)

**Comment by SuruPa00** [comment]
@saranya-sajeev just set it back to testing

**Comment by saranya-sajeev** [comment]
@SuruPa00 Ok. I will add my account as tester and let you know.

**Comment by saranya-sajeev** [comment]
![GoogleFitConsentScreen](https://user-images.githubusercontent.com/81216000/130629039-ed088516-8fb7-41d7-9d9e-eed093a7eb8c.png)

**Comment by saranya-sajeev** [comment]
Consent screen is showing for the beta build.

**Comment by SuruPa00** [comment]
any updates since submitting this video @saranya-sajeev

**Comment by saranya-sajeev** [comment]
@SuruPa00 You can submit the video and reapply for verification.

**Comment by SuruPa00** [comment]
@saranya-sajeev we have now been successfully verified, so lets move on to update android asap

**Comment by saranya-sajeev** [comment]
ok suraj we will push the app to production

**Comment by saranya-sajeev** [comment]
@SuruPa00 Could you please create a video and share the link as described in the issue https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/353. After providing the link we can move beta build to production.

**Comment by SuruPa00** [comment]
@saranya-sajeev can the same video you made not work? it showcases location is being accessed and the gps data shows the use of it in the visual

**Comment by saranya-sajeev** [comment]
@SuruPa00 Please find the location video shared at https://www.dropbox.com/s/vafytj6c1ruu7zs/mindLampLocationvideo.mp4?dl=0 Please upload to Youtube and share the link.

**Comment by saranya-sajeev** [comment]
@SuruPa00 We have uploaded the video and submitted app to production. It is currently in Review status.

**Comment by ZCOEngineer** [comment]
@SuruPa00 No Thanks Suraj, we uploaded it to youtube and created the link

**Comment by ZCOEngineer** [comment]
@SuruPa00, @avaidyam 
Android app was rejected with the below reason

`Feature does not meet requirements for background location accessBased on our review, your declared feature does not meet the requirements for background location access. Please remove the background location permission requested and submit an update to your app. When declaring a feature for background location access, please note the following: Your selected feature should deliver clear value to the user and be important to the core functionality, or main purpose of the app. Without this core feature, the app is “broken” or rendered unusable. You should also consider if users would expect the app to access their location in the background, and if you can deliver the same experience without accessing location in the background.`

**I remember Aditya mentioning about contacts in apple and google, will it help to get pass this? or shall we discuss on any change for resubmission?**

**Comment by avaidyam** [comment]
We need and require background location data. My team can investigate this and reply to Google.

**Comment by michaelmenon** [comment]
Thanks @avaidyam

**Comment by SuruPa00** [comment]
@ZCOEngineer is this feedback message in the cloud console? if so, where can i find it?

**Comment by saranya-sajeev** [comment]
@SuruPa00 They have sent the details as mail to jtorous@gmail.com also there is an option in Google Play Console to view the mail content. 
Please find below steps to view the mail content on Google Play Console
1. Login in to Google Play console
2. Select mindLamp 2 from All Apps page
3. Dashboard will show update status as update rejected. There is an option to "Go To Policy Status", tap on it.
4. From the policy status page tap on the right arrow to view details.
5. There is an option to view email, tap on it. It will show the details.

**Comment by SuruPa00** [comment]
@SuruPa00 submitted the appeal yesterday, will update you when i receive feedback

**Comment by saranya-sajeev** [comment]
@SuruPa00 ok thanks for the update.
