### ISSUE TITLE
Group Duplication Errors

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#355]
> When using the 'Duplicate Group' feature when creating new user and new group, images for Activities do not carryover to the new group.  
Example below - see the jewels icons being entirely empty

![Image from iOS](https://user-images.githubusercontent.com/86117379/129386159-f1acbb4c-ed8f-47f8-8233-92238dadd568.png)

**Comment by Linoy339** [comment]
@SuruPa00. This is fixed in staging and will be available in production as soon as we plan a release

**Comment by SuruPa00** [comment]
@Linoy339 just check in on this and looks good - push asap

**Comment by Linoy339** [comment]
@SuruPa00. As per the discussion, we can move to production after getting verification regarding LAMP-worker functionality
There has been a crash after deploying it((https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/331).).We fixed it.
So, we can push altogether after the verification from your side.

**Comment by SuruPa00** [comment]
@Linoy339 #331 has been tested and can be pushed, please push this fix as well

**Comment by Linoy339** [comment]
Okay @SuruPa00

**Comment by Linoy339** [comment]
@SuruPa00 . Sure.

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in dashboard-staging. QA completed. Production can be updated with User hierarchy changes.

**Comment by SuruPa00** [comment]
@saranya-sajeev seems to still not be working and is continuing to have that problem. See attached [video](
https://user-images.githubusercontent.com/86117379/131385725-effa87bf-077a-4495-bc2c-ab83ab0c32cc.mov)

**Comment by Linoy339** [comment]
@SuruPa00 . Its not pushed to production. Please check with api-staging.
As discussed, we will be moving to production after User hierarchy fixes

**Comment by Linoy339** [comment]
This is pushed to production @SuruPa00
