### ISSUE TITLE
Select All and Deselect All Filter Button

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#356]
In the dashboard, once we enter a researcher group, can we make it so that (1) we are able to have no studies selected - you can see the error in unselecting everything comes up in the bottom left; and (2) can we have a new set of two buttons where i have circled in red in the screenshot - one to say "deselect all" and one to say "select all" so that the filters do not have to be individually clicked through 1-by-1 if someone wants to start again with filters or just select everyone. I suggest this be done by moving the current filterable groups down one row (as if there were 2 rows) and keeping the select all and deselect all buttons in one row to avoid crowding/confusion. Let me know if there are any better suggestions.

![image](https://user-images.githubusercontent.com/86117379/129607420-fc2d0f97-9799-4de4-b7f0-9e5bd49da1d0.png)

**Comment by michaelmenon** [comment]
Thanks we will check and get back on the time required asap.

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in dashboard-staging. QA completed. Production can be updated with User hierarchy changes.

**Comment by sijugeorge-zco** [comment]
@SuruPa00 

We have updated the changes as below :

If the researcher clicks _Deselect All_ the studies **OR** no studies are selected and Logged Out and then Logged In again, the user will _Select All_ the studies as default.

After creating a study, the created study will automatically be selected on the filter (even if _Duplicate From_ is not selected  **OR** _Create a new user under this group_ not selected).

Please confirm if any other changes to be done.

**Comment by SuruPa00** [comment]
@sijugeorge-zco can this be pushed asap?

**Comment by sijugeorge-zco** [comment]
@SuruPa00 

We had already pushed this code on [**dashboard-staging**](https://dashboard-staging.lamp.digital/) earlier and its working.

Please let us know any other changes needed for filtering.

**Comment by sarithapillai8** [comment]
@SuruPa00
Updated in production.

**Comment by SuruPa00** [comment]
@saranya-sajeev im looking in production and this is not appearing, is there any reason why this may be?

**Comment by sarithapillai8** [comment]
@SuruPa00 
Could you please clear the cache and recheck?
