### ISSUE TITLE
Download a csv containing all participant activity data for a research study

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#358]
Currently, downloading participant raw data directly from the LAMP website is difficult - it would be nice to have a single easy-to-use button that enables data download

To fix this issue, we will add a button to the data portal that allows a user to download a CSV containing raw activity data.

**Comment by avaidyam** [comment]
@lukeoftheshire [Here's the old version of this feature from the legacy dashboard code.](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/commit/e75293f91e39e23f11abb5bb9570006c444d1dd4) We should also be merging all the data across participants into one big CSV with de-obfuscated IDs (Activity ID → name of activity), suitable for Excel import or similar.
