### ISSUE TITLE
Dates (months) are abbreviated inconsistently in charts in the Prevent tab

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#36]
> **Collaborator**: "Oct" for October , "November" for November in the prevent page. Looks weird, especially in the app when it goes off the page, although dashboard is shown here.
![image](https://user-images.githubusercontent.com/1361003/98842644-dddc9280-2417-11eb-8c19-6f9d9c7de1bc.png)

If this is in the old graphing code let me know, @sarithapillai8, as it may not make sense to work on this bug in that case as we want to completely overhaul that code.

**Comment by sarithapillai8** [comment]
@avaidyam 
This is from the old code. Please let me know if I need to spend time on this.

**Comment by avaidyam** [comment]
Nope - if this is from the old graphs, we can ignore it!
