### ISSUE TITLE
Jewels levels

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#363]
> 1) Despite the settings having specifications for how to set up multiple levels (ex. the number of jewels that should increase per level), you can only play 1 level of Jewels at a time. Previously, #218 we were told that this must be requested as a feature - however, it appears as though the settings to do so are there, and it is actually a bug: 2) What do the X changes in level count, X diamond count, Y changes in level count, and Y shape count settings do? Currently, cannot observe any change in the game when altering these settings. 3) How is Jewels scored?

**Comment by sarithapillai8** [comment]
@SuruPa00 
1)  There are settings in the activity creation screen as we are just populating the fields with the settings. It was asked to do the level changes later. And it never came up as priority , that is why we commented to change the task to feature one. We can work on it after user hierarchy changes if it is a priority one. 
2) These parameters are not yet implemented as we didn't implement levels. The expected functionality is as follows :- 
Increase Jewels count to “x_diamond_count” while reach “x_changes_in_level_count”  level.
Increase Jewels shape count to “y_shape_count” while reach “y_changes_in_level_count”  level.
3) The equation used is :-
score = (largest correct jewel number tapped / (total tap count + 1)) * 100

**Comment by SuruPa00** [comment]
@sarithapillai8 please work on this after hierarchy changes - this should be a priority since jewels functioning properly is required for proper data collection. Thanks

**Comment by sarithapillai8** [comment]
@SuruPa00 
Jewels- levels (for both jewels a & b) changes updated in dashboard staging. Could you please check and let me know if any further changes required?

**Comment by sarithapillai8** [comment]
Updated in production. 
https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commit/dbd470ed4d87a30f4326059015dea4df74f15af9

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
In the last meeting , the requirement for jewels levels is expected to be similar to box game. Box game works like -  each time the game opens with 1st level. In jewels - We are updating levels based on the bonus points accumulated until previous game. So could you confirm - the game will start with the level calculated from the total bonus points earned? The old version was not going to previous levels. So please confirm.

**Comment by tlakhtak** [comment]
We would like levels to start from the 1st level every time, and then progress to the 2nd level on completion like Spatial Span. We can ignore bonus point-based progression.

**Comment by SuruPa00** [comment]
@sarithapillai8 do we have an update of the eta on this?

**Comment by ZCOEngineer** [comment]
@SuruPa00 development is complete and we have started QA. if everything goes well then we can release this early next week.

**Comment by SuruPa00** [comment]
@ZCOEngineer ok please try to release this by tuesday, thanks

**Comment by sarithapillai8** [comment]
@SuruPa00 
We have updated this on dashboard staging. Please check and let us know if this is ready to be released.

**Comment by SuruPa00** [comment]
@sarithapillai8 Thanks for your hard work on this!
