### ISSUE TITLE
User Hierarchy Changes

### ISSUE THREAD

**Issue by sarithapillai8** [BIDMCDigitalPsychiatry/LAMP-platform#368]
**System admin :**

Current list of researchers will be changed like : Extra column showing type of user and list will include researchers, user admins and clinician admins. 
When system admin try to add users - there will be 3 user types listed in the drop-down to identify which user to be created. 
Assuming the same API for creating researchers can be used with some extra field for user type.  

 **User Admin:**

Similar to researcher list with - but the list will contain clinicians with study(researcher group) in one column they assigned. 
Adding clinician will ask for study(researcher group) to be selected. 
Studies tab from current researchers will be moved to this place as new tab. 

**Clinician admin:**

Similar to researchers list view, but with clinicians in the list. They can impersonate as any clinician. There will be option to impersonate as each clinician.

 
**Clinicians:**

Similar to researcher view, but with single study.
The dropdown for the 'Add' button will be removed and it will allow patient addition under the study of clinician
They can impersonate as patient.
Activities/sensors/studies will be hidden
 

**Researchers :**

Keeping the current view,

**Comment by SuruPa00** [comment]
@sarithapillai8 when i try to create clinicians inside the first group created inside my test useradmin account (named uadmin), i can create clinicans. When i create a new study inside that uadmin user (named uadmin2), when i create a clinician and assign them to the that new uadmin2 group, they do not show up in the list of clinicians in the uadmin account. 

Additionally, when I create clinicians, sometimes they create a new researcher group? This should not be happening. 

Lastly, when I enter a clinical admin account ( a test account named cadmin), i get a list of clinicians. How can i delete from this list of clinicans? There are also clinicians showing up in this list that i created with a different user admin account. 

Can you check on these issues and double check account creating is working in order?

**Comment by michaelmenon** [comment]
Thanks @SuruPa00 will check and post our comments asap.

**Comment by sarithapillai8** [comment]
@SuruPa00 
Do the uadmins can see the studies and clinicians created under different uadmins and manage them all? I was managing it like different group of admins managing different set of studies and clinicians. Please confirm, I can change accordingly. 

I will check with what happening with clinician creation.
 
Clinical admins are supposed to manage all the clinicians under different studies. So listed all. No manage option is there for clinical admin as it was said that they cannnot manage any clinicians, they can only impersonate as different clinicians. They can access different studies through different clinicians. Do they need to manage clinicians? What I understood is -  only uadmins are supposed to manage clinicians.

**Comment by sarithapillai8** [comment]
@SuruPa00 
The issues you mentioned are updated in code repo. Dashboard staging is not getting updated because some issues.  Once it is fixed, you can check the changes there using api-staging server.

**Comment by avaidyam** [comment]
@sarithapillai8 I believe your original interpretation is correct - we will double check with the client. It also came to our attention today that the Manage Credentials option for admins is not correctly functioning - the `origin` of the Credential object **MUST** be `null`, not `"admin"`.

**Comment by sarithapillai8** [comment]
@avaidyam 
Manage Credentials option for admins is not correctly functioning - the origin of the Credential object MUST be null, not "admin"
 : - With this do you want to change this for super admin only or for all the admins including clinical admin and user admin? And could you also please confirm this change is to remove the permissions changes we did in API level?

**Comment by sarithapillai8** [comment]
@SuruPa00  @avaidyam @michaelmenon 
All the updates are ready for testing in dashboard-staging. Auto-update issue seems fixed.

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
Could you please confirm all the user admins can see all the clinicians and studies? The API for fetching all the studies not working and studies can be fetched researcher based. So please confirm on this, so that we can work on API changes.
@michaelmenon

**Comment by avaidyam** [comment]
@sarithapillai8 The change for `origin = null` is for ANY administrator type. Can you share what API level changes happened for this feature? There should not have been any; this implementation should have been *entirely frontend only*. Going forward as well, we do not want any API changes for any feature.

**Comment by sarithapillai8** [comment]
@SuruPa00 user admins can see all the clinicians created by all user admins now. But they can see the studies they created. Not the ones other user admins created and they cannot create clinicians under a study created by another user admin. This is already implemented in dashboard-staging. The studies can  be fetched based on the creator. @avaidyam  already commented no api changes to be done on this. So this is the only possible way of implementation. If any alternative way , please suggest.
@avaidyam 
The api changes we did for permissions. If we change origin = null, hope we can get rid of that too. But please confirm on the comment above. If we want to fetch studies by researchers in a loop, we can do. But confirm studies will be managed by the created users only.

**Comment by avaidyam** [comment]
@sarithapillai8 Just to clarify - user admins and practice lead should be identical in all cases except how the dashboard admin page works for them. User admins can manage credentials and create clinics/researchers BUT NOT ENTER THEM, and practice leads should be able to view all clinics/researchers BUT NOT CREATE/DELETE THEM (or manage credentials). In the API level, system administrators, user administrators, and practice leads are ALL the same - just an "admin" (aka `origin = null`) level credential. 

I don't see how this should be changing the way studies or clinics/researchers are fetched at all?

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please go through all the comments above. I have detailed everything. https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/368#issuecomment-906601074.
Also could you please confirm if there any api for fetching all the studies at admin level without looping through users? Studies were created for researchers, both admins are created as researchers and handled them as admins. This is to manage maximum changes only from front end.There is no option to create an admin from front end now. This was already commented above. We can set origin null for admins, and get rid of permission changes we did.

**Comment by sarithapillai8** [comment]
@avaidyam 
We are not able to change origin=null condition for user and clinical admins. 
There is a validation in the service which do not allow typeId null condition- 
https://github.com/BIDMCDigitalPsychiatry/LAMP-js/blob/a9fde0d7779231a67bbc12324406b9cf2da4608a/src/service/Credential.service.ts#L21.
Please do let me know, how to proceed.

**Comment by avaidyam** [comment]
Discussion moved to #378.
