### ISSUE TITLE
"Notification Expired!" after swiping on a notification and then being logged out

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#37]
> **Collaborator 1**: I swiped into a notification and it said "Notification expired!" and logged me out of my account. I was logged into the [REDACTED] study and i presume this notification was meant to be telling me about a [scheduled activity], but I have no idea.
> ![image](https://user-images.githubusercontent.com/1361003/98842751-06fd2300-2418-11eb-8abd-51ee164070fb.png)
>
> **Collaborator 2**: Subject [REDACTED] keeps getting logged out of the app and has to re-log in following notification prompt of a survey.
>

The notification should be removed from the Notification Center if it's expired, this is not intended behavior. Also, there are far too many cases where people have reported being logged out. @jijopulikkottil how is the iOS code storing credentials?

**Comment by jijopulikkottil** [comment]
I will check if we can auto remove the notification when its expired!
_how is the iOS code storing credentials?_ - we are storing it in UserDefaults. And clearing only when logout.

**Comment by avaidyam** [comment]
If the credentials are being stored in `UserDefaults`, why does the `WebView` UI keep showing the login screen? I believe the  `WebView` is saving the credentials too, into `localStorage`. Does that data stay preserved across all `WebView` instances in the app?

**Comment by jijopulikkottil** [comment]
logout issue -> After a successful login, and on a second launch, user always landed to login screen ? Or landed to login screen when tap on a notification ?

And Is this issue reporting only from last week (I mean with last build) ?
[With last build, we have explicitly set the storage for WKWebViewCOnfiguration ( configuration.websiteDataStore = WKWebsiteDataStore.default() ) ]

--I am not getting this auto logout issue with iPhone6s.

**Comment by avaidyam** [comment]
1. They land on the login screen after tapping on a notification. 
1. Do you mean last week's staging/TestFlight build or the production build?

**Comment by jijopulikkottil** [comment]
1. ok, and are they able to go back to home screen by tapping the back button ( back arrow in left top) ? I asked because, when we tap on notification, first it loads the login page and then navigate to the specific activity screen automatically.

2.  testflight build on Nov 6.

**Comment by avaidyam** [comment]
1. They are able to return to the mindLAMP app when tapping the back button. When a notification with a page action is tapped it is supposed to take the page fragment from the notification: `/participant/123/activity/456` (example) and then append it to the dashboard URL that was set for the app like so: `https://{DASHBOARD_URL}/#/{PAGE_FRAGMENT}` and load that in the WebView. 
    1. Furthermore, when tapping a link it's not supposed to leave the app you were already in, it's supposed to show a notification overlay above the app you are already in, just like the Mail or Messages app do. This was explicitly defined in earlier Basecamp messages as well, see the "Custom Views provided by the Notification Content Extension" part here: 
    - ![](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/advanced-user-notifications-images/customui01.png)
2. Got it, I'll check with the collaborator to see if this is the version they were using.

**Comment by jijopulikkottil** [comment]
1. One more clarification, when we build the url from page fragment, we have to append the URL_TOKEN (base64 of username:password:serveraddress). right?.  So the full URL will be https://{DASHBOARD_URL}/#/{PAGE_FRAGMENT}?a={URL_TOKEN}. please confirm

1.i) yes, we have done this customisation. we will show the page if user long press the notification banner.

**Comment by avaidyam** [comment]
1. No, do not do this. I think it's because you add this now that it's confusing the frontend code and causing it to reset the credentials each time. If already logged in, the credentials are saved in localStorage and as long as the localStorage is shared across all app `WebView`s, you should be fine. Please test this on your end. 
    1. If they long-press the notification banner, it loads in the notification content extension? Then if they short-tap the notification banner, it should open the app itself and load the page inside of the main WebView, not have a separate WebView tab with a Back button that leads to the main WebView.

**Comment by jijopulikkottil** [comment]
1. ok. I think we need to do some additional code to share the local storage among wkwebviews of same app.
1.i) _If they long-press the notification banner, it loads in the notification content extension?_ - No, in the notification extension, the app data is not available by default. So we can't append url-token.

_"if they short-tap the notification banner, it should open the app itself and load the page inside of the main WebView_" - Yes we can try this first. or can try (1) share the local storage among wkwebviews and open the page in another webview.

**Comment by jijopulikkottil** [comment]
Hope we need to work on this "The notification should be removed from the Notification Center if it's expired". One method is to send again a silent push notification using the same apns-id in the header. Or we can try to remove within the app by retrieving the apns-id and running a thread.

**Comment by avaidyam** [comment]
1. You will probably need to [set a global singleton `WKProcessPool`](https://developer.apple.com/documentation/webkit/wkprocesspool) and use it when constructing `WKWebView`s.
    1. I don't understand why this is a limitation, can you explain in a bit more detail?
    1. I think it may make sense to try sharing the `localStorage` first and see if that resolves the issue.
1. [For removing remote notifications, see this reference.](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649500-removedeliverednotifications) [You may need to set this up inside of an `UNNotificationServiceExtension`.](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension/1648229-didreceive)

**Comment by jijopulikkottil** [comment]
1. I tried using a singleton process-pool, but it is not sharing the same webview session when load activity-page in another webview. 
i) no limitation, as we are using 'notification content extension' to display the webpage outside the app, we need to share the base64token using app group capability.
ii) yes, but it doesn't work by sharing the process-pool or sharing the websiteDatastore. I think it might be work if we were using cookies..Are we using cookies ?

# it will work if we load the notification's page url on main webview.

2. To removing remote notifications, we should pass 'apns-collapse-id' (e.g "apns-collapse-id": "**118**") in request header. Also please pass the same id for "notificationId" in our payload. 
e.g
'{"aps":{"alert":"Hello world!","badge":0,"sound":"default","mutable-content":1,"content-available":1},"notificationId":"**118**","expiry":20000,"page":"/participant/U7007185831/activity/8ezktf28twj47ktakf02"}'

so we can retrieve the id easily from notification content and can set a timer for "expiry" interval to remove the same notification.

**Comment by avaidyam** [comment]
1. @jijopulikkottil This is an interesting problem to tackle --  I haven't been able to figure out a solution. The reason this is happening is likely because extensions are run out-of-process through the XPC framework, and thus the `WKProcessPool` is not the same one as the one created within the app's process. This means you're right - we'll likely have to use some kind of app-group capability to synchronize things. [We're not using Cookies in the UI code but you could add some code to do this as part of the Native Core.](https://medium.com/@mahithegeek/sharing-cookies-in-ios-nshttpcookiestorage-part-2-ee466c17e96) 
    1. On login event, set the auth token as a shared cookie.
    1. On logout event, clear the auth token shared cookie.
    1. When loading a new WKWebView, inject a JS user script to do the following: 
        1. If `localStorage` does not contain the auth token, set the value.
        1. If `localStorage` DOES contain the auth token already, do nothing.
2. @Linoy339 - are we able to pass the `apns-collapse-id` parameter in this way? If so, @jijopulikkottil is it already implemented in such a way that it can auto-remove the notification after `expiry` then?

**Comment by jijopulikkottil** [comment]
1. Even within the app, suppose we login on one `WKWebview`, and if we try to open an activity page on another `WKWebview` , it is asking credentials. Tried to use shared `WKProcessPool` and `localStorage`. but didn't work.

  If we add cookies from the app side, can the webpage use this cookie for authenticate when we open an activity page from a second wkwebview ? What will be the key-values we have to store?

2. It is not implemented in the existing testflight build. Its coding is completed.

**Comment by avaidyam** [comment]
@jijopulikkottil 
1. Right - as I explained above, `WKProcessPool` won't work in app extensions it seems. Meaning we have to use the cookie method.
2. The UI code does not use cookies at all, so until it does support it, you will need to use cookies to shuffle the auth token around and use a `WKUserScript` to convert the token into a localStorage item (the key used by the UI code is `LAMP._auth`) as I described in my comment above. Does that make sense?
3. Can you let me know when it's pushed (and move this issue to the `Completed (Staging)` category).

**Comment by jijopulikkottil** [comment]
In web, we are using session storage for keeping  "LAMP._auth" dictionary. (I search it in the local storage first).

> "WKProcessPool won't work in app extensions it seems"
Yes, what I was trying to tell is, sharing `WKProcessPool` didn't work even with in the app for two `WKWebview`.

In our main web view, I tried to retrieve LAMP._auth from session storage, but we are getting nothing

```
func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {

        let script = "sessionStorage.getItem(\"LAMP._auth\")"
        wkWebView.evaluateJavaScript(script) { (authDict, error) in
            print("LAMP._auth = \(authDict)") //prints null
        }
}
```
----
I tried [to set the LAMP._auth key to the session storage](https://stackoverflow.com/questions/44896823/is-there-a-way-to-set-local-storage-in-wkwebview)  , set value like {"id":"U7007185831@lamp.com","password":"12345", "serverAddress" :"api.lamp.digital"}  and load an activity url (https://dashboard.lamp.digital/#/participant/U7007185831/activity/8ezktf28twj47ktakf02) of same user. But it landed to login page instead of activity.

Note sure what I am missing here.. will check again..

**Comment by avaidyam** [comment]
@jijopulikkottil 
1. This is interesting -- can you try to create a small Swift Playground and share it here so we can see what the issue is? This might be an Apple issue...
2. Can you share a small Swift Playground project with this (the session storage + local storage + user script loader) so I can test on my end? Make sure you are setting **localStorage** so the UI code can see it. The format appears to be: 
```js
JSON.stringify({
        id: ...
        password: ...
        serverAddress: ... 
})
```

**Comment by jijopulikkottil** [comment]
@avaidyam Its worked after a few tries. So setting key-value to session storage is fine now.  Shared the playground. First it will landed to login page, then automatically redirected to activity page after 2-4 seconds. (similar behaviour of appending URL token).
[MyPlayground.playground.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5568283/MyPlayground.playground.zip)

**Comment by avaidyam** [comment]
Interesting - unsure what the issue might be.... do you know why there's a 2-4 second delay there perhaps? (And thanks for the playground so I can test it too!)

**Comment by jijopulikkottil** [comment]
The notification content displayed outside the app is not full screen, so our activity page is broken. Even if we apply scrolling on this survey page, it will be difficult to manage. Because if we swipe on that popup, it will be dismissed.
![IMG_8159](https://user-images.githubusercontent.com/63795052/99826325-38938e00-2b7e-11eb-98ef-3f0751698d9a.PNG)

**Comment by avaidyam** [comment]
@jijopulikkottil [Have you made sure to follow Apple's guidelines correctly? (See the "Support Interactive Controls" section here.)](https://developer.apple.com/documentation/usernotificationsui/customizing_the_appearance_of_notifications) According to Apple you must specify `UNNotificationExtensionUserInteractionEnabled=YES` under `NSExtensionAttributes` in the notification extension's `Info.plist`.

**Comment by jijopulikkottil** [comment]
Yes, I had enabled user interaction. Issues are fixed now by customizing the content height.
![IMG_8244](https://user-images.githubusercontent.com/63795052/99943459-5851ce80-2d97-11eb-8b99-c9831f566c08.PNG)

**Comment by avaidyam** [comment]
@jijopulikkottil 
1. Great - I think it makes sense to make the view as close to full screen as possible by setting the `contentHeight` to `screen.height - ((padding * 3) + close_button_height)` after replacing the pixel heights for those variables. 
2. Though I think you're on the right track, this implementation doesn't sound robust:
    > When ever receive a notification, we are starting a thread
    
    Instead, use a background timer or something similar that schedules with the OS directly, so the app can be awoken correctly in all scenarios.

**Comment by jijopulikkottil** [comment]
1. The close button and padding spaces are not available. We can set `contentHeight` as `screen.height - x` where x will be a constant affordable for all devices. Otherwise we can try to set it proportionally and using the scale factor.
2.  I will check is there a way to schedule with the OS. One thing is local notification, but it is not supported silent one.

**Comment by avaidyam** [comment]
@jijopulikkottil 
1. Let's use a static fixed value as you suggest. That's a great idea. 
1. That's alright - I think any approach we can take is a good one for this. Do you think we should branch it off onto a new issue?

**Comment by jijopulikkottil** [comment]
1. It's done.
2. 
> Do you think we should branch it off onto a new issue?

 Yes, please.

**Comment by avaidyam** [comment]
@jijopulikkottil Could you go ahead and make a new issue?

**Comment by jijopulikkottil** [comment]
created new [issue](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/52) . Is it only visible to me?.. looking for a way to add participant!. Also unable to set project.

**Comment by avaidyam** [comment]
@jijopulikkottil I see it, no worries!

**Comment by jijopulikkottil** [comment]
In iOS, the notification expire issue is still open, because sometimes the `didReceiveRemoteNotification` is not invoked even the app is running in background. We can investigate it on the [new thread](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/52)

**Comment by avaidyam** [comment]
@jijopulikkottil Thanks, this is helpful, we can investigate that separate bug in the new issue. @amaljofyzco are these changes done on the Android side as well? I didn't see a PR for them.

**Comment by amaljofyzco** [comment]
![Uploading Screenshot 2020-12-03 at 10.51.05 AM.png…]()
Could you check it now?

**Comment by amaljofyzco** [comment]
> @jijopulikkottil Thanks, this is helpful, we can investigate that separate bug in the new issue. @amaljofyzco are these changes done on the Android side as well? I didn't see a PR for them.

Notification auto expiry done in android also, provided we need to get expiry obj in ms in the notification payload.
Made PR request could you check now

**Comment by avaidyam** [comment]
Thanks, just merged it!
