### ISSUE TITLE
Import activity file size causes error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#373]
When you import a json file from exporting activities, nothing happens when the file size seems to be too big (can upload kb of activities, but not jsons that are a few mb or higher) - since participants are having larger mb jsons imported now, this is an important issue to fix. Once this is fixed, can it be smoothly pushed to production without waiting on other pieces after our team tests it?

**Comment by michaelmenon** [comment]
ok thanks @SuruPa00 . will check the design. seems like we need to change it to have big files imported in chunks. Will update asap.

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
There is a limit restriction 5MB  for file to import. Could you confirm whether we have to increase the limit to 10MB - 15MB and or show the current limit information in the import screen?

**Comment by SuruPa00** [comment]
Increase to 15 MB and make a note somewhere that shows the limit information on the import screen.

**Comment by sarithapillai8** [comment]
@SuruPa00 
Updated in dashboard-staging.

**Comment by SuruPa00** [comment]
@sarithapillai8 is it possible to raise the MB limit to 25MB? If so, please do that. If not, can you push this production without waiting for user hierarchy to push?

**Comment by sarithapillai8** [comment]
@SuruPa00 
This can be done. But there will be a noticeable delay in importing large files. If no problem with that, we can do. Please confirm.

**Comment by SuruPa00** [comment]
@sarithapillai8  this is fine, as most files will be 15MB and under, but the availability of larger files is convenient. Go ahead and raise the limit then.

**Comment by sarithapillai8** [comment]
@SuruPa00
Updated in production.
