### ISSUE TITLE
Cluster got shut down 

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#375]
node-01.lamp.digital got down for some reasons. @avaidyam @SuruPa00 Could you please look into it ASAP?
We need to look after the redis misconfigure issues after this cluster becomes active

**Comment by lukeoftheshire** [comment]
Hi @Linoy339 - thank you for letting us know about this! We have rebooted node-01 and I have confirmed that things are working as normal (for now). I will be keeping an eye on it throughout the day but please let us know if it goes down again.

**Comment by Linoy339** [comment]
Thanks @lukeoftheshire .

**Comment by Linoy339** [comment]
@lukeoftheshire .
Nats was down 2 days before. Now it looks like redis is also down in production.

Can you please check and bring those up. Also, please check the server for any space issues.

**Comment by lukeoftheshire** [comment]
Hi @Linoy339 - thank you for telling us about this issue. I have confirmed that redis has not exceeded its imposed 4 gb limit (as of last check, it was at about 3.85/4). However, it appears that three instances of lamp-worker have been spun up, each consuming about 7 gb of memory, leading to 100% usage which could be causing your issues. We are actively investigating this and I will update this topic when I have more info.

**Comment by Linoy339** [comment]
Yes @lukeoftheshire . Let us know if any thing from your side

**Comment by lukeoftheshire** [comment]
Hi @Linoy339 yes I can confirm there were multiple instances of those  - I am unsure as why this might happen, so please let me know if you have any ideas how this could have happened. Thank you for letting me know about it! I have removed any extraneous versions and (as of this comment) there should be only one of each of those running.
