### ISSUE TITLE
Deleting a single activity deletes all activities

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#379]
When viewing a participant's activities and sensors, when you go to delete an activity from that participant, sometimes all of the activities are deleted.

**Comment by sarithapillai8** [comment]
@SuruPa00 
Not able to reproduce this issue. are you sure not all activities are selected or do you mean it getting deleted for all participants under the study which we show in the warning?

**Comment by dcurrey88** [comment]
@sarithapillai8 Only one activity is selected, I press delete, and then all activities are deleted under the study after the warning is shown. This does not happen every time I delete an activity, but has happened several times recently.
