### ISSUE TITLE
Notifications bubble for Conversations does not change

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#38]
> **Collaborator**: Notifications for new messages doesn't go away after you check the message. The notification for messages doesn't go away even if I've already viewed the message. I feel like this is a problem because people won't check for new messages once they realize it could be the one they've already viewed.
> ![image](https://user-images.githubusercontent.com/1361003/98843276-bafeae00-2418-11eb-91ba-09d47c0e1b4d.png)

Do you think there's a quick solution for this? Or would it rely on something like #12 to be implemented first (so we can keep track of when the last time the person viewed the conversation to clear out the bubble)?

**Comment by sarithapillai8** [comment]
@avaidyam 
Currently we don't have an option to mark as read or to update the read status. So could you please let me know how do you want to implement this?

**Comment by avaidyam** [comment]
I think once #12 is implemented there'll be a timestamp to compare against to see if there needs to be an unread indicator or not. Let's keep this open until that item is completed.

**Comment by sarithapillai8** [comment]
Ok. But with the timestamp, how can we identify if that message is read by the participant?

**Comment by avaidyam** [comment]
One idea: if the latest analytics event for the conversations tab being opened occurred at `timestamp = X`, and the latest message occurred at `timestamp = Y`, the unread indicator should be shown if and only if `X < Y`.

**Comment by sarithapillai8** [comment]
@avaidyam 
But there is one issue. We have list of messages grouped by one sender in initial page, and on clicking each the user can see all the messages. So even if the conversation page is open. the detail page might not have been opened. Or do we need to save separate analytics event for detail page also?

**Comment by avaidyam** [comment]
No need - the unread indicator can just be a dot that applies to ANY conversation. We can improve the implementation later if we need more granularity, I think.

**Comment by sarithapillai8** [comment]
@avaidyam 
FYI This can be done after implementing https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/12. Not sure if possible as part of Bug bash.
