### ISSUE TITLE
LAMP-worker Docker support

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#380]
Currently, the `DOCKER_ADDR` environment variable for `LAMP-worker` does not allow using a socket path (i.e. `/var/run/docker.sock`). If no `DOCKER_ADDR` is provided, the default socket path should be used instead.

**Comment by Linoy339** [comment]
@avaidyam. Can you describe more on this, as I am not clear ?

**Comment by avaidyam** [comment]
How can I specify `/var/run/docker.sock` (which is the default location of Docker's socket) to `LAMP-worker`? I cannot.

**Comment by Linoy339** [comment]
Okay. Just to clarify: Inside Lamp-worker, there should be a docker support inorder to run our script. Right?

**Comment by avaidyam** [comment]
Yes... is that not how it is currently implemented? I see Docker being used right now. We want to keep using Docker.

**Comment by Linoy339** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/blob/master/src/helpers/ScriptRunner.ts#L4
The docker initialization   starts here (whenever a script comes in).  Can you help me out on default docker address to be given here?

**Comment by avaidyam** [comment]
If I set `DOCKER_ADDR` to `/var/run/docker.sock` or leave it undefined, what happens here? This is the issue. 

1. `/var/run/docker.sock` should be the default value if no other `DOCKER_ADDR` is defined. 
2. If I manually specify a socket path like `/var/run/docker.sock` this code will not work.

These edge cases (and many more) are not handled correctly.

**Comment by Linoy339** [comment]
> Yes... is that not how it is currently implemented? I see Docker being used right now. We want to keep using Docker.

Yes. It is implemented like that.
Basic working is as follows:
1)Lamp-worker image should have docker support inside(i.e docker inside docker)
2)When a script comes in, Lamp-worker initializes the docker which is inside the LAMP-worker and this docker should have a default docker address to communicate, and it can be 127.0.0.1:2375 or /var/run/docker.sock. Please correct me if I am wrong.
3)The docker engine inside LAMP-worker should pull some image(only once and if already pulled, we can use that image ) in order to run the script file which comes in.

Can you clarify the flow here?

**Comment by avaidyam** [comment]
1. Docker does not run inside of Docker. What is happening is that the host machine's Docker daemon socket is being shared with the container. None of the file system within the container is accessible outside of the container and thus is not visible to the host machine's Docker daemon. 
2. No, it should be that `DOCKER_ADDR` allows the user to change where this Docker socket is found. If not provided then assume the default socket path (in `/var/run/docker.sock`). This is how the container will connect to the host machine's Docker daemon. 
3. There is no Docker engine inside of the container. We are "borrowing" it from the host machine. Otherwise, yes, we request the host machine to pull and use a predefined Docker image. Then we run the script inside of that.

**Comment by Linoy339** [comment]
Okay. Its like docker container(LAMP_worker) is accessing the host machine and pull a custom predefined image from host  to run our scripts.
Is that right?

**Comment by avaidyam** [comment]
Yes, that is correct. [For more information, see this Docker article.](https://www.docker.com/blog/building-serverless-apps-with-docker/)

**Comment by Linoy339** [comment]
Thanks @avaidyam .

So In my understanding, we need to use DOCKER_ADDR from the env variable and if its not given or undefined, we have to use the default socket address (/var/run/docker.sock) which should not be exposed in env

Only change is that we have to have a check for DOCKER_ADDR whether it is defined or not. If defined, lets take it or else we can use default socket address.

We do not need to do anything in the code to make host as docker engine support, as it should be made while we create the stack.

Can you confirm this?

**Comment by avaidyam** [comment]
Yes that is correct.

**Comment by Linoy339** [comment]
Thanks for the clarification @avaidyam

**Comment by avaidyam** [comment]
Discussion moved to #382.
