### ISSUE TITLE
Automations do not work due to LAMP-worker issues

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#383]
Due to issues #380 and #382, Automation scripts cannot (and will not) run currently through LAMP-worker. Because all LAMP backend code is executed within an isolated Docker container, the file system of one container is not accessible to another container **or the Docker host** (which would be a massive security vulnerability). As a result of saving automations code into local ZIP files (#382), even if the LAMP-worker could interact with the Docker host (which it cannot, as a result of #380) the host cannot mount the ZIP files into a child container and thus automation code does not run.

**Comment by Linoy339** [comment]
@avaidyam .[https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/380](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/380)  : For this, we need to check the DOCKER_ADDR whether it is defined or not. If defined, lets take it or else we can use default socket address.

[https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/382](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/382) :For this, we need to avoid using filesystem in LAMP-worker container. Instead, use the base64 encoded script file(zip) to run directly inside the container. 

[https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/381](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/381):For this, we will remove all logs that logs for each nats publish. We will keep only the relevant (i.e for triggering an automation script)

**Comment by avaidyam** [comment]
Discussion moved to #382.
