### ISSUE TITLE
Survey text Markdown support

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#384]
Survey text (across question text, option text, descriptions, etc) should support Markdown. Most of the legwork was done already through `react-markdown` [as implemented in Tips and updated recently](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commit/9e3476f33047bcc400b13d26590da0875683edf3#diff-5a122eba93c60c2575b97147a802046529a08b791db130014d4c43986ca5b320R154). However, **even with this implementation, there is missing `gfm` and `emoji` plugin support.**

**Comment by sarithapillai8** [comment]
@avaidyam 
Survey changes will require minimum 2 days to finish. I hope you need the markdown for all the possible texts in survey. So it will need some time. 
**Note** : We have restored gfm/emoji for tips in dashboard-staging.

**Comment by avaidyam** [comment]
@sarithapillai8 Yes, this makes sense. In general for the future, any clinician/researcher-customizable text must support Markdown.

**Comment by sarithapillai8** [comment]
@avaidyam 
This task was specifically saying about survey. Do you want this change to be effected on all activity titles and descriptions and other settings across all the activities? If so we need some more time to finish. If survey one is important we can update it in 2days, and work on others later after other urgent fixes.

**Comment by avaidyam** [comment]
Survey only, but as a general note when creating new activities, please keep this in mind.

**Comment by sarithapillai8** [comment]
Ok got it @avaidyam

**Comment by sarithapillai8** [comment]
@avaidyam @SuruPa00 @michaelmenon @ZCOEngineer 
This is updated in production.

**Comment by SuruPa00** [comment]
@sarithapillai8 checked and looks good - thanks for this
