### ISSUE TITLE
Fix addEventListener/postMessage for Goals and Medications

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#386]
Currently, [Medications](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/master/MedicationTracker/src/components/MedicationTracker.tsx) and [Goals](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/master/Goals/src/components/Goals.tsx) do not respond to Activity loading events like other activities (i.e. [Journal code example here](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/8d6f6baae33b84f4ad5125cf563a833445cacf04/Journal/src/components/JournalEntries.tsx#L139)). This makes it impossible to create an ActivitySpec and mount these two activities in the dashboard currently.

**Comment by SuruPa00** [comment]
@sarithapillai8 hi, do we have an update on this? if not, could we add this as something to work on in parallel with other tasks soon

**Comment by sarithapillai8** [comment]
@SuruPa00 we haven't started on it yet. After jewels levels we can focus on this.

**Comment by sarithapillai8** [comment]
@avaidyam @SuruPa00 Could you provide more details on the settings values for these? These are now just converted wo separate application. Can we just use like everything from settings?

**Comment by avaidyam** [comment]
For right now, it doesn't actually matter what settings values are present -- you can use anything that makes sense to remove any kind of placeholder text.

**Comment by sarithapillai8** [comment]
![image](https://user-images.githubusercontent.com/63710347/152334406-79840fa8-7b27-4369-beac-ce3ed88f75b0.png)
This is the screen for new goal. Could you please provide how this should be considered for ActivityEvent ?
![image](https://user-images.githubusercontent.com/63710347/152334441-8809041e-53ae-4d42-9739-f5df2aa355b3.png)
Similarly for medications.

**Comment by avaidyam** [comment]
This page should be scrapped. The configuration for medications and goals is the same JSON Schema Form setup as is present for Surveys or Tips. These pages do not produce ActivityEvents.

**Comment by sarithapillai8** [comment]
@avaidyam Could you please provide more details?

**Comment by avaidyam** [comment]
> We did the design in this way and development started after demo and moved to LAMP-activities.

Correct - there was a misunderstanding very early on with the implementation of this feature. 

> but this is not the activity creator screen, this is the activity screen expected like a survey attending screen 

This screen is supposed to be clinician-facing for configuring the medications/goals, just like surveys/tips/etc. This is not a patient-facing screen. 

The patient-facing side is the one that allows them to mark off the medication as taken or goal as completed.

| Create/edit - clinician-facing | View/complete - patient-facing |
|-|-|
| ![image](https://user-images.githubusercontent.com/1361003/152580659-9998c872-7fb6-4b8e-910e-49f4ac5e174d.png) | ![image](https://user-images.githubusercontent.com/1361003/152580627-460ddaa8-949a-489c-9abd-38155478210c.png) |
| ![image](https://user-images.githubusercontent.com/1361003/152580824-6c97f7f7-2785-47ce-bb3b-d79fc08d66f2.png) | ![image](https://user-images.githubusercontent.com/1361003/152580879-af4533d0-e0d7-46ce-b58d-f54400a156c0.png) |
 
(Please note that the "My Goals" page above should not be used. Each Goal or Medication is its own icon on the Home Screen.

**Comment by sarithapillai8** [comment]
Please correct me if I am wrong: 

- So  with medications, it will be like add medicine name activity title, dosage in settings. With activity schedule option we can schedule and it will come in feed section. As we do with tips, this will also show in any tab, and user can submit it like 'Mark complete'.
- Similarly, Goals can be created as activities, like medications.

I am changing this to feature as this is a change, not a bug.

**Comment by sarithapillai8** [comment]
@avaidyam 
So By default , the medications and Goal activities will have the 'None' selection for tab. The researcher can still change that setting like other activities, right? 
For Goals, do you prefer to have any specific settings parameters like dosage for medications?

**Comment by avaidyam** [comment]
@sarithapillai8 No, they will have the `manage` tab by default (as should be specified in the ActivitySpec). Yes, the clinician can always change the tab to whatever they like or remove it entirely. 

Please use the existing settings parameters for Goals. It should be the goal name, the units (string), and the amount (number). For example: Drink water, "times", 3. 

Can you share screenshots here of what the medications and goals settings pages looked like before vs. now after being converted to JSON Schema Forms?

**Comment by sarithapillai8** [comment]
>Please use the existing settings parameters for Goals. It should be the goal name, the units (string), and the amount (number). For example: Drink water, "times", 3.

isn't Goal name actually the activity name?
I understood about units and amount. 
Daily, times etc need to be set through schedule or these are just texts?

>Can you share screenshots here of what the medications and goals settings pages looked like before vs. now after being converted to JSON Schema Forms?

We don't have any configuration page goals and medications now. It was expected to use like journals without any specific settings.

**Comment by avaidyam** [comment]
> isn't Goal name actually the activity name?

Yes, and the activity icon should be the goal's icon too. 

> Daily, times etc need to be set through schedule or these are just texts?

The goal "Drink 24 ounces of water twice daily" would become:
1. Title = "Drink water"
1. Icon = a water bottle or so
1. Description = "Remember to stay hydrated!"
1. Settings =

**Comment by sarithapillai8** [comment]
@avaidyam 
We have updated the changes in dashboard-staging. Could you or your team please review and suggest changes if any?

**Comment by sarithapillai8** [comment]
@avaidyam Yes the changes are updated in dashboard-staging. The activity specs are available through api-staging.

**Comment by avaidyam** [comment]
They don't seem to be working - the `Save` button never enables. 

<img width="1006" alt="Screen Shot 2022-03-16 at 13 44 46" src="https://user-images.githubusercontent.com/1361003/158654121-0fe3f5e2-9a41-44be-b6e1-4295122a68fd.png">

**Comment by sarithapillai8** [comment]
Where this was tested? There are unit and value settings for both activities. Can you confirm this is tested in dashboard-staging with api-staging login?

**Comment by sarithapillai8** [comment]
@avaidyam Sorry there was a bug related to loading settings. There are two mandatory settings(unit and value) for goals/medications. Could you please recheck?

**Comment by sarithapillai8** [comment]
@avaidyam If any changes required. Please let us know.

**Comment by lukeoftheshire** [comment]
On Android, Goals and Medication activities don't load. Instead, I only see white screens:
![Screenshot_20220412-141217](https://user-images.githubusercontent.com/34659264/163027314-85435926-e545-4abc-ac40-79a13917a476.jpg)
![Screenshot_20220412-140729](https://user-images.githubusercontent.com/34659264/163027318-2932ca3a-d7b5-48fb-bc17-0224027158e9.jpg)

Here are the Activities:
```
[{'id': 'n09yf33ppryt2qacp4qj',
  'spec': 'lamp.goals',
  'name': 'Goal Test 1',
  'settings': {'unit': '1', 'value': 1},
  'schedule': [],
  'category': ['manage']},
 {'id': '46baaqk5n0bpspj78msf',
  'spec': 'lamp.medications',
  'name': 'Medication Test 1',
  'settings': {'unit': 'Units', 'value': 2},
  'schedule': [],
  'category': ['manage']}]
```

**Comment by avaidyam** [comment]
@lukeoftheshire (or @dcurrey88) Does this occur on iOS as well?

**Comment by michaelmenon** [comment]
Just to confirm is this in Android beta ?

**Comment by dcurrey88** [comment]
> @lukeoftheshire (or @dcurrey88) Does this occur on iOS as well?

This occurs on iOS as well.

**Comment by michaelmenon** [comment]
ok we will check on the iOS TestFlight beta build ?

**Comment by evinkalengaden** [comment]
We have accessed the existing Goals and also tried on creating new GOAL as specified in the conversation above. We are not able to reproduce. Please find the attachment.

**Comment by sarithapillai8** [comment]
@lukeoftheshire @avaidyam @michaelmenon
Updates are available in staging build and they seems working. Please find the attached video. Beta/TestFlight builds are pointed to production build where the dashboard updates are not available. Could you confirm on this?

https://user-images.githubusercontent.com/63710347/163177117-dba1e77a-7c62-40c1-a363-fe23aa938650.MP4

**Comment by lukeoftheshire** [comment]
Ah, I see! I didn't know that, so this one is on me! Thanks to both of you for testing this and letting me know. This'll be helpful for future testing.

**Comment by avaidyam** [comment]
@michaelmenon I'm confused. I thought your team had already completed an internal end-to-end QA testing round? If that was the case, why were these aspects not tested on PC browser vs. Android/iOS beta builds too?

**Comment by sarithapillai8** [comment]
@avaidyam Our QA was testing in internally created staging builds that are pointing to staging. Not in beta/TestFlight.

**Comment by michaelmenon** [comment]
Hi @avaidyam  yes our team did the testing and I think you are not getting my point here. The current beta iOS/Android is pointing to production dashboard and not to the staging dashboard which is fully tested. The production still does not have the staging updates. Our team did test the Android/iOS pointing to staging. If that was you are asking.

**Comment by avaidyam** [comment]
I see what you mean - can we have your team also QA test every issue on the browser AND iOS+Android beta going forward? The beta builds should always point to dashboard-staging.

**Comment by michaelmenon** [comment]
Sure Aditya, just to confirm we had already tested on Android/iOS pointed to staging and will do again. But we will update the beta build again pointed to beta so that your team can test as well.

**Comment by evinkalengaden** [comment]
The iOS beta build (Pointed to staging) is **Ready for test** in TestFlight. We have tested the build and its working fine.

@avaidyam @michaelmenon @lukeoftheshire

**Comment by lukeoftheshire** [comment]
QA tested, looks good on Android!
