### ISSUE TITLE
Feed Activities Error

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#387]
When trying to access activities through the feed, the following error shows both on Chrome and on a Android phone.
![Screenshot_20210924-093439_mindLAMP](https://user-images.githubusercontent.com/82968538/134694304-07e07ffc-e1b1-4aed-92e9-9ab5372daf2e.jpg)
<img width="1440" alt="Screen Shot 2021-09-24 at 9 41 22 AM" src="https://user-images.githubusercontent.com/82968538/134694329-ac4f9b3d-5061-4c41-a991-35f700d2c6e3.png">

**Comment by ZCOEngineer** [comment]
@tlakhtak we shall check on this.

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production. Please check.

**Comment by SuruPa00** [comment]
@sarithapillai8 seems to be working after checking - thank you!
