### ISSUE TITLE
Scoring Issues on Translated Prevent Page

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#388]
When using Hindi version of the app, despite answers displaying in Hindi, Prevent page shows scores for answers in English. Hindi response just show a flat line, not reflecting new responses to survey questions.

https://user-images.githubusercontent.com/82968538/134701931-0695a738-8890-4c06-8314-779d508f9923.mp4

**Comment by ZCOEngineer** [comment]
@tlakhtak We shall check into this

**Comment by sarithapillai8** [comment]
@tlakhtak @SuruPa00 
We are not getting this issue. Tried translations and got same result on graph. Please see the attached screenshots.
![Capture](https://user-images.githubusercontent.com/63710347/135233547-a80b9868-e7ea-4875-a6e6-df01217909e0.PNG)
![Capture1](https://user-images.githubusercontent.com/63710347/135233554-6a4f8719-8a39-466a-a609-f0d9ffa513d8.PNG)

If you can provide the credentials, we can check into this in detail.

**Comment by tlakhtak** [comment]
rescred@lamp.com
redcred

**Comment by sarithapillai8** [comment]
@tlakhtak 
This is updated in production
