### ISSUE TITLE
Integrate Activity Recognition API on iOS and Android

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#39]
* [On iOS we should be using `CMMotionActivityManager.startActivityUpdates(to:withHandler:)` to collect this data.](https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager)
* [On Android, we should be using `ActivityTransitionRequest.requestActivityTransitionUpdates()` to collect this data. ](https://developer.android.com/codelabs/activity-recognition-transition#0)

This data MUST be collected continuously in the background to whatever extent possible. Let me know if there are any questions on the task!

**Comment by jijopulikkottil** [comment]
sensor name = "lamp.activity"
schema of `data`

    "data": {
            "activity": {
                "running": false,
                "cycling": false,
                "automotive": false,
                "stationary": true,
                "unknown": false,
                "walking": false,
                “on_foot”: false (Android only)
            }
        }

we are also getting "confidence". In Android it is percentage, But in iOS it is 0-low, 1-medium, 2-high.

please confirm the schema

**Comment by avaidyam** [comment]
@jijopulikkottil This is great, following the actual sensor spec, this is how it should look when uploaded:
```json
"data": {
  "running": false,
  "cycling": false,
  "in_car": false,
  "stationary": true,
  "unknown": false,
  "walking": false,
  “on_foot”: false,
  “confidence”: 0.87
}
```
Primarily, the `automotive` activity is renamed to `in_car`, and the `confidence` parameter is a floating point percentage. For iOS, use `low (0) = 0.0`, `medium (1) = 0.5`, and `high (2) = 1.0` to convert values and it should work well. The `spec` should be `lamp.activity_recognition` instead, to better match the Apple/Android names and docs.

@amaljofyzco Is this the same representation/data for Android as well?

**Comment by amaljofyzco** [comment]
> @jijopulikkottil This is great, following the actual sensor spec, this is how it should look when uploaded:
> 
> ```json
> "data": {
>   "running": false,
>   "cycling": false,
>   "in_car": false,
>   "stationary": true,
>   "unknown": false,
>   "walking": false,
>   “on_foot”: false,
>   “confidence”: 0.87
> }
> ```
> 
> Primarily, the `automotive` activity is renamed to `in_car`, and the `confidence` parameter is a floating point percentage. For iOS, use `low (0) = 0.0`, `medium (1) = 0.5`, and `high (2) = 1.0` to convert values and it should work well. The `spec` should be `lamp.activity_recognition` instead, to better match the Apple/Android names and docs.
> 
> @amaljofyzco Is this the same representation/data for Android as well?

same representation is for android except confidence is not available.

**Comment by avaidyam** [comment]
@jijopulikkottil I saw your PR for this, but @amaljofyzco did you have a PR for the Android code as well? Also,

> we are also getting "confidence". In Android it is percentage, But in iOS it is 0-low, 1-medium, 2-high.

Is this not actually the case @amaljofyzco?

**Comment by amaljofyzco** [comment]
> @jijopulikkottil I saw your PR for this, but @amaljofyzco did you have a PR for the Android code as well? Also,
> 
> > we are also getting "confidence". In Android it is percentage, But in iOS it is 0-low, 1-medium, 2-high.
> 
> Is this not actually the case @amaljofyzco?

No Aditya, In Activity Recognition Transition API we are getting the activity-type and transition-type.

Confidence value is returned in ActivityRecognitionApi [https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionApi](url)
Which is currently deprecated. When we replied on this its done by mistake.

**Comment by avaidyam** [comment]
@amaljofyzco I have merged it but [could you also add support for the sampling API?](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionApi) @jijopulikkottil Is there an equivalent sampling API for iOS?
