### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#392]
> I've the mindLAMP app in my phone and I've noticed that when I've not used the app for a couple of days and then open the app, all the notifications which were scheduled between the last time I opened the app to the latest scheduled notification gets sent all at the same time. Other than morning, evening and cognitive games, all the other activities are scheduled weekly. And if I do clear the notifications, it reappears after an hour.  

![Screenshot_20210929-195627_mindLAMP](https://user-images.githubusercontent.com/86117379/135335296-824e6cec-cfb4-459d-b72f-bfe33b7038c4.jpg)
![Screenshot_20210929-195640_mindLAMP](https://user-images.githubusercontent.com/86117379/135335300-31788888-579c-45ab-a1d7-d29550afde83.jpg)
![Screenshot_20210929-195657_mindLAMP](https://user-images.githubusercontent.com/86117379/135335301-5a300aab-b805-451e-92f3-45457ebf599b.jpg)

**Comment by saranya-sajeev** [comment]
@SuruPa00 We are using Android work Manager for scheduling local notifications. Work Manager makes sure the scheduled task executes again even if the app is restarted.

**Comment by saranya-sajeev** [comment]
That means  if the app is not available at the scheduled time, work manager will show all the notifications when the app comes alive.

**Comment by SuruPa00** [comment]
@saranya-sajeev i see, is it possible to have this reconfigured so this does not happen? it bodes for a bad ui/ux experience from the reports of our users - we should have the notifications only appearing at the appropriately scheduled times

**Comment by saranya-sajeev** [comment]
We will check and update you.

**Comment by SuruPa00** [comment]
Is there an update on this?
