### ISSUE TITLE
Feed activities can't be clicked before scheduled time

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#393]
Users that go into the feed cannot click on a survey / activity ahead of the scheduled notification time. Users are meant to be able to enter the feed and complete the activities as they see fit.

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please confirm on this? We did it like it should not be clickable before the scheduled time.

**Comment by SuruPa00** [comment]
@sarithapillai8 this should clickable at anytime now, so if there any changes that need to be made to do that please do

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
We implemented different conditions to control the clickable behavior of the feed items. For eg, with the repeat interval 3hour, we restricted the item like it can be clicked in between the 3hour gap comparing to current time. So there were a lot of checking 
 for each repeat interval. It was implemented as Aditya said. So please confirm you want to remove all these conditions for all the repeat intervals.

**Comment by avaidyam** [comment]
@sarithapillai8 We'd like to keep the current implementation - thanks for bringing this up and reminding us about our prior discussion! 

---

_**Sidenote for others stumbling across this GitHub issue:** If we allowed patients to disregard their notification schedule, there really would not be a point to the notification schedule, breaking the notion of ecological (i.e. "in the field where the patient is") momentary (i.e. "brief, in the moment the patient needs to respond") assessment (i.e. "surveys") (EMA) that we rely on mindLAMP for._

_**If the patient really does need to take the survey independently of notification schedule, the clinician should enable the activity to appear in the Learn tab, where they can take it without being restricted by existing schedule.** If the clinician does NOT want to allow patients to take surveys outside of notification schedules, they should hide the survey from all tabs -- see #165._

**Comment by SuruPa00** [comment]
As discussed, this functionality will be kept for now till further notice
