### ISSUE TITLE
Sensor Configuration UI Issue

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#394]
> When on the "sensors" tab, after clicking "+Add", I filled in the group and the name fields, but the dropdown for sensor spec is blank and remains in red font. 

![asSplWFw_o](https://user-images.githubusercontent.com/86117379/135852564-4b50c818-94f1-42cf-a0a7-4905c1f5b4cd.png)

**Comment by avaidyam** [comment]
This occurs if the API Server was not configured properly (i.e. no SensorSpecs were installed by the IT team, for example). This isn't a bug with LAMP itself.
