### ISSUE TITLE
New Labels for Prevent Tab and Researchers View

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#395]
A minor change I expect, but please change the "Prevent" tab to be renamed to "Portal" and make sure the label in the tab itself (and any other relevant place) says "Portal" instead of "Prevent". Additionally, in admin view please change "Researchers" to "Investigators"

**Comment by sarithapillai8** [comment]
@SuruPa00 
This updated in production.
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/373
