### ISSUE TITLE
Removing sensors on dashboard will not stop data collection

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#396]
> If I remove the sensors on the dashboard, passive data will still be collected. For example, for U6809902742, data collection was turned off last week, but GPS data was collected yesterday.

**Comment by SuruPa00** [comment]
@jijopulikkottil updated, let me know if theres anything else you need

**Comment by SuruPa00** [comment]
@jijopulikkottil did you mean to delete these sensors and readd them? just did that, but let me know if you meant something else

**Comment by jijopulikkottil** [comment]
@SuruPa00 yes, I meant the same.

Could you do one more thing ? please [close app](https://support.apple.com/en-us/HT201330) from background and reopen the app. And please update here when you are done.

**Comment by jijopulikkottil** [comment]
This is another case - @Linoy339 Could you please check the sensor spec in production is updated or not? because when @SuruPa00 remove all  and added again, the old sensor identifiers are still there. ["lamp.accelerometer.motion" and lamp.device_state]

**Comment by SuruPa00** [comment]
@jijopulikkottil no worries, I just killed the app from the background and reopened. Let me know if you need any more steps!

**Comment by jijopulikkottil** [comment]
Hi @Linoy339 Please update the sensor spec. I have updated the content (see attached file) received by https://api.lamp.digital/sensor_spec 
Unused sensors are marked as Red, and new sensors are marked as Green.
[sensorSpec_20211020.odt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7388733/sensorSpec_20211020.odt)

**Comment by jijopulikkottil** [comment]
@SuruPa00 Sensor spec updated in production. 
Also the issue fixed and the latest iOS build is in test flight now. We can release it tomorrow after beta testing.

Currently the refresh interval for sensor configuration is 2 hours. i.e It will take about 2 hours to update the app If we remove or add sensors on admin console. [it won't refresh with new sensors if the device is in low power mode].

Let us know if we need to change the refresh-interval

FYI- The refresh interval of activity (Activity API to reset local notification) is 12 hours.

**Comment by jijopulikkottil** [comment]
@SuruPa00 Shall we release the beta build 2021.10.20 (296) ?

**Comment by SuruPa00** [comment]
@jijopulikkottil yes please push
