### ISSUE TITLE
DBT Diary Card Skills Visualization in Portal Tab

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#398]
As per  LA's request, we would like a grid-based visualization for when people view the DBT diary card in the portal tab. We want this to be formatted as the days of the week on the top row, with color coding based on skill groups that have been done. Additionally, skills that have not been used should be greyed out and the skills that are used should be signified with a check mark in their box and be associated with the color of that skill group. A rough mock-up of what we ideally want is present in a screenshot from Excel. For example, if no skill is done, the entire grid will stay grey (except for the labels of the skills that), and each skill that is completed for the week will cause the row of that skill to be colored with the associated label color.

Skills completed w some uncompleted - 
![image](https://user-images.githubusercontent.com/86117379/136265552-82edf692-eb33-4801-82df-7482707a461a.png)

No skills completed - 
![image](https://user-images.githubusercontent.com/86117379/136265635-2db57a8f-225a-43c9-96bd-5a0fd8f34fdd.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 

Just confirming - With the current design the skills are shown with collapsible list. So only this section need to be converted to grid design as provided.
Do we need to change this only for LA using any flag or env settings?

**Comment by SuruPa00** [comment]
@sarithapillai8 this looks good, but see screenshot below because the vertical gridlines arent appearing for the first row of each section 
![image](https://user-images.githubusercontent.com/86117379/137978077-8f0429a6-f7e2-4e5e-a86e-61a6e1479a75.png)

**Comment by SuruPa00** [comment]
Additionally, can you add 2 new smaller features for this grid card. Can you add an "Expand all" option that opens each section that then becomes "Collapse all" to collapse each section. Then, can you also have a box next to that which says "Filter checked" that filters for only the rows that are colored in because they have a check mark. Visually, this would show up as an expand all button, the filter box, and then the date range selector. Let me know if that makes sense or if you have any questions.

**Comment by sarithapillai8** [comment]
@SuruPa00 
I have managed opening multiple panels through the accordion component. Do you still want to change it to checkbox design? Please have a look. If needed we need to create custom component to handle this.

**Comment by SuruPa00** [comment]
@sarithapillai8 this looks good, can you also change "Filter Checked" to "Show Only Skills Used"

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is also updated.
