### ISSUE TITLE
Use an optional environment variable to rename the Researchers/Investigators/Programs tab in admin

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#399]
We are currently receiving multiple requests to rename what used to be the "Researchers" tab and is now the Investigators/Programs tab. See https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/395#issue-1015140647 for an example. Additionally, we anticipate future users of LAMP may want to rename this tab, and we want to avoid this becoming an ongoing issue.

To solve this issue, can we use an optional environment variable ("REACT_APP_LAMP_RESEARCHER_ALIAS") to rename the researchers tab to a string at build time? Ideally, if no environment variable is not defined, the name will default to "Researchers". This should preserve the standard functionality of LAMP for the average user but also accomodate users who want a different UI.

**Comment by sarithapillai8** [comment]
@lukeoftheshire 
Updated in dashboard-staging as suggested. If env file is there in root folder and there is value for REACT_APP_LAMP_RESEARCHER_ALIAS, it will be using for 'Researchers' text.

**Comment by sarithapillai8** [comment]
@lukeoftheshire 
Thank you.
Reverted the change and updated in staging. Released other changes to production after reverting this change.
