### ISSUE TITLE
Support offline caching of sensor data 

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#40]
If there is no network connection or insufficient battery level to upload data, it must be cached and collected until the requirements are met again.

**Comment by avaidyam** [comment]
@jijopulikkottil I saw your PR for this, but @amaljofyzco did you have a PR for the Android code as well?

**Comment by amaljofyzco** [comment]
> @jijopulikkottil I saw your PR for this, but @amaljofyzco did you have a PR for the Android code as well?

sorry @avaidyam I forget to hit compare and pull request button yesterday.
