### ISSUE TITLE
Alphabetical filtering and sort option

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#400]
We want it so the filter list in the the deselect/select users area to be alphabetized in both the 'users' tab and the 'activities' tab. Can we also have it so that the list of users in the users tab are alphabetical? Additionally, we have a sort button added next to the filter button that alphabetizes from A-Z by default and when clicked, reverse alphabetizes from Z-A. Lastly, when you add an activity, the list of users/groups that show up are in no particular order, can that be alphabetized as well? Essentially, alphabetization will make ordering easier.

**Comment by ZCOEngineer** [comment]
@SuruPa00 We shall work on this after current priority items

**Comment by sarithapillai8** [comment]
@SuruPa00 
Do we have to change the sorting of the activities/users under a studies based on this sorting selection()A-Z & Z-A?

**Comment by sarithapillai8** [comment]
@SuruPa00 
Do we need to change the order of listing in activities/users based on study sorting or keep the A-Z sorting all the time? Also users are sorted by id, not name ; as names are not available all the time, they are saved as attachments.

**Comment by SuruPa00** [comment]
@sarithapillai8 make it A-Z based on the study

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production.

**Comment by SuruPa00** [comment]
@sarithapillai8 thanks for the update. I'm checking on it in production and while the AZ button is there, when I click it, nothing is happening. Additionally, loading the list of users takes far too long. As of right now, each user is loaded 1 by 1, which makes it very inefficient to access users in large studies, I've asked for this fix in #414 as well. Can both these issues be looked into?

**Comment by sarithapillai8** [comment]
@SuruPa00 
I am not able to reproduce the issue. Please see the attached, Could you please attach any recording to understand the issue?
https://user-images.githubusercontent.com/63710347/144014805-ac48bf7b-22dc-44b3-bab7-be2d510f8fe7.mp4

**Comment by SuruPa00** [comment]
@sarithapillai8 here is a screen recording of the issue - please also note the extremely long loading times

https://user-images.githubusercontent.com/86117379/144055384-a3888842-0886-4d6d-a100-7b1381d7382f.mp4

**Comment by SuruPa00** [comment]
@sarithapillai8 I see, can this be changed so that all studies are loaded at once? put this in staging so that I can compare loading times to see which is preferred

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is not a minor change. Our staging is updated with the change for https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/427#issuecomment-982728054 and vulnerability fixes. So once we release those, I can update staging with this of you want. And the loading time will be too long if we need to load all the data after fetching everything, and it was like this before. That was why while optimizing, we changed like this after several discussions to speed these things up.

**Comment by avaidyam** [comment]
@sarithapillai8 Let's test the performance of this method (loading it all at once) in staging. There may be a simple solution here, but we should see how slow or fast it is first. //cc @lukeoftheshire

**Comment by lukeoftheshire** [comment]
In case it helps, @sarithapillai8, I happen to have a JSONata query that can be made through LAMP.API.query command that loads a list of studies as objects, each containing a "participants" key that is a list of participants w/ ids and names. The exact command would be:
```
LAMP.API.query('($studyList := $LAMP.Study.list('RESEARCHER_ID');
          $list := $map($studyList,function($study){{'name': $study.name,'id':$study.id,
                                                        'participants':[$map($LAMP.Participant.list($study.id).id,function($id){{'name': $LAMP.Tag.get($id,'lamp.name'),'id':$id}})]}})
    )')
 ```


 
 Where only RESEARCHER_ID  needs to be replaced. I've tested this on my end and it does appear to load pretty quickly:

<img width="693" alt="Screen Shot 2021-12-01 at 1 18 25 PM" src="https://user-images.githubusercontent.com/34659264/144297336-605fea4a-9542-4dca-8f0e-027c6becaca9.png">

This image above comes from me running the query through the data portal, but I think running through the API may be even quicker. This took only about 3.8s for TECC Lite, which is probably our most study-heavy test currently. There is also a pretty significant advantage in that it drastically reduces the number of calls necessary (currently I think the dashboard is making multiple calls per particpant).

**Comment by sarithapillai8** [comment]
@avaidyam @lukeoftheshire 
Thanks for the details. I can check and will let you know.

**Comment by sarithapillai8** [comment]
@avaidyam @lukeoftheshire 
We are not familiar with LAMP.API.query methods. Can you provide some documentation? We can try fetching basic details of participants, activities and sensors in single/multiple queries.

**Comment by lukeoftheshire** [comment]
Hi @sarithapillai8 

Absolutely! LAMP.API.query takes, as an input, a string which it then attempts to run as a JSONata query on the lamp server. JSONata is a language with a variety of handy methods for transforming and working with JSON data. You can find some information on JSONata here: https://docs.lamp.digital/data_science/jsonata . Additionally, the LAMP implementation of JSONata includes most(if not all) of the normal LAMP API (also listed on that page). 

A basic query to list all studies for a researcher, for example might look like: `$LAMP.Study.list(researcher_id)`, which would return an array of all studies associated with a particular researcher. 

What makes JSONata particularly nice is that you can use multi-line queries to do quick edits to your data before returning it. For example, in the query above (reproduced here):
```
($studyList := $LAMP.Study.list('RESEARCHER_ID');
 $list := $map($studyList,function($study){{'name': $study.name,'id':$study.id,
                                                        'participants':[$map($LAMP.Participant.list($study.id).id,function($id){{'name': $LAMP.Tag.get($id,'lamp.name'),'id':$id}})]}})
)
```

I first get a list of all studies, then iterate over them with a map function to get participant details for each. I can do all this with one API call and let the server handle the rest, which prevents me from having to deal with, for example, multiple promises to get a single participant's data.

You can also run queries on the LAMP Data Portal accessed through the dashboard, by toggling to Terminal Mode - see documentation for that here: https://docs.lamp.digital/data_science/data_portal#terminal-mode

I hope this helps - please let me know what additional info I can give you about this.

**Comment by sarithapillai8** [comment]
@SuruPa00 
The changes are updated in staging for testing purpose. Please don't do any release, as our master branch is now updated with these changes.  If everything looks fine, we can release after QA confirms.

**Comment by divyav2020** [comment]
We have updated the build in Dashboard staging
