### ISSUE TITLE
Push Notifications Code Issue

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#401]
> I’ve managed to use the following code to get pushed notifications:
> 
> sensor_events = LAMP.SensorEvent.all_by_participant(participant_id, origin=“lamp.analytics”)[‘data’]
> 
> notifications = [i[‘data’] for i in sensor_events if i[‘data’].get(‘action’) is not None and i[‘data’].get(‘action’) == ‘notification’]
> 
> However, it doesn’t seem to record every single notification that is sent – for example I can’t see any of the notifications sent today (6th October 2021) when testing – the last notification I can see was on the 29th September:
> 
> {‘timestamp’: 1632931564754, ‘sensor’: ‘lamp.analytics’, ‘data’: {‘action’: ‘notification’, ‘device_type’: ‘iOS’, ‘user_agent’: ‘NativeCore 2021.7.6; iOS 14.4; iPhone iPhone10,3’, ‘content’: {‘expiry’: 86400000, ‘aps’: {‘content-available’: 1, ‘alert’: 'Activity for next week: 1. run for 30 mins; 2. jump 20 times; 3. swim for 40 mins; 4. sprint 3 times; 5. sit for 3 mins, 6. walk for 30 mins; 7. sleep for 60 mins; 8. deep breath for 2 mins; 9. stand for 10 mins; 10. drink water 200ml. ', ‘mutable-content’: 1, ‘badge’: 0, ‘sound’: ‘default’}, ‘actions’: [], ‘notificationId’: 'Activity for next week: 1. run for 30 mins; 2. jump 20 times; 3. swim for 40 mins; 4. sprint 3 times; 5. sit for 3 mins, 6. walk for 30 mins; 7. sleep for 60 mins; 8. deep breath for 2 mins; 9. stand for 10 mins; 10. drink water 200ml. '}}}

> 
> I’ve also tried filtering by timestamp with “_from” and “to” inside that LAMP.SensorEvent.all_by_participant() function but to no avail.
> 
> Thanks very much and look forward to hearing from you.

**Comment by avaidyam** [comment]
@jijopulikkottil It seems like recording notification receipts is not working - can you confirm if there's any issue with that?

**Comment by jijopulikkottil** [comment]
@SuruPa00 @avaidyam 
When we test, server fails to send remote push notification after a day or two days. (we couldn't notice it because of local notification). Discussed with @Linoy339 and he found that an issue of getting token due to newly added Analytic actions. So I can continue testing the issue of 'recording notification receipts' after this server fix.

**Comment by jijopulikkottil** [comment]
@Linoy339 Tested on staging after server update and it is working fine. App is getting push notifications and sending analytic events to server.
@SuruPa00 So iOS app will works fine after the production server update. App update is not needed.
