### ISSUE TITLE
Android service permissions screen is not functioning properly

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#402]
We are having reports of Android users running into issues with the service permissions screen when they download mindLAMP. Once they accept service permissions, the box closes out and simply appears again, which does not let them proceed to the login screen and just keeps looping. See if this issue can be looked at soon as possible, as it is preventing new patients from joining studies properly. 

![image](https://user-images.githubusercontent.com/86117379/136583713-12318d23-f578-4cdb-8ff3-3e5d78faa976.png)

**Comment by saranya-sajeev** [comment]
@SuruPa00 I will check the issue.
