### ISSUE TITLE
Time Picker Survey Option

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#404]
Can we have a new survey question type called time picker where there are three inputs set up as 3 different boxes, 

The first one being a box that can have manual entries in the form of XX where only numbers can be inputted to indicate the hour (07, 14, 22) and then one box for XX for minutes (36, 55), and the last picking a box that only has two selectable options of AM or PM. Please have entries limited to the range for that metric (minutes should only be able to be 00-60)

Can we have the entries recorded as military time, but add an additional option that somewhere that allows a toggle between military time and standard time. You can have this as a box before the hour box as well. Set the toggle default as Standard Time (which should restrict hour entries to 00-12) and if the toggle is set to military time, change the hour range to 00-24 and grey out the AM/PM box. 

Let me know if you need any clarification!

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in production.

**Comment by SuruPa00** [comment]
@sarithapillai8 Thanks for this, it is working from the dashboard as intended. Can you make it though so that when the data is called, everything is returned in military time regardless of whether from the UI, AM PM or Military Time was selected?
