### ISSUE TITLE
iOS/Android DeviceMotion data not identical

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#408]
When scheduling an activity, what is the intended purpose for the custom times box? We can already schedule on a custom time based on the "Time" box in the scheduling popup. Can you give a use case for when we would use the custom times box as well?

additionally, what are gps.contextual and accelerometer.motion used for? if we are not collecting those as something extra on top of original gps and accelerometer, let me know.  We are considering deleting those if they have not been yet.

**Comment by avaidyam** [comment]
@SuruPa00 `lamp.gps.contextual` is a hold-over from mindLAMP v1 that contains social and environmental context that the user fills out as a pseudo-survey. This has not existed in mindLAMP for years now, so you can ignore this.

@jijopulikkottil Since `lamp.device_motion` has the same accelerometer data WITH additional gyro/motion/gravity data, do you think it is feasible to remove `lamp.accelerometer` in the near future? 

@saranya-sajeev Is `lamp.device_motion` implemented the exact same way on Android as @jijopulikkottil has done on iOS?

**Comment by jijopulikkottil** [comment]
@avaidyam 
In iOS,  lamp.device_moton data is from [CMDeviceMotion](https://developer.apple.com/documentation/coremotion/cmdevicemotion). So the "motion" data is the [user acceleration](https://developer.apple.com/documentation/coremotion/cmdevicemotion/1616149-useracceleration) 

lamp.accelerometer data is from [CMMotionManager](https://developer.apple.com/documentation/coremotion/cmmotionmanager) [accelerometerData](https://developer.apple.com/documentation/coremotion/cmmotionmanager/1615992-accelerometerdata)

--------
Below is the sample data at same timestamp

```
      {
           "sensor": "lamp.accelerometer",
            "data": {
                "x": -0.0554046630859375,
                "y": 0.018218994140625,
                "z": -0.9925689697265625
            },
            "timestamp": 1631497628750
        }
```

 ```
   {
            "sensor": "lamp.device_motion",
            "data": {
                "motion": {
                    "x": 0.00033351778984069824,
                    "y": -0.0010437443852424622,
                    "z": 0.006497621536254883
                },
                "magnetic": {
                    "x": -18.154403686523438,
                    "y": 33.973846435546875,
                    "z": -0.9541015625
                },
                "attitude": {
                    "x": -0.05516539220931536,
                    "y": -0.01872964326149722,
                    "z": -1.5837174388747068
                },
                "gravity": {
                    "x": -0.05512774735689161,
                    "y": 0.018728548660874367,
                    "z": -0.9983036518096924
                },
                "rotation": {
                    "x": -0.0034970194101333605,
                    "y": 0.0007610619068145754,
                    "z": 0.0003306157886981964
                }
            },
            "timestamp": 1631497628750
        }
```

**Comment by avaidyam** [comment]
@jijopulikkottil Great - this makes sense. 

@saranya-sajeev Are `lamp.device_motion` and `lamp.accelerometer` implemented the same way on Android? [It looks like only `lamp.accelerometer` is.](https://github.com/BIDMCDigitalPsychiatry/LAMP-kotlin/blob/master/lamp_kotlin/src/main/java/digital/lamp/lamp_kotlin/sensor_core/Accelerometer.kt) You may need to manually assemble a `DeviceMotion` equivalent using `Sensor.TYPE_LINEAR_ACCELERATION`, `Sensor.TYPE_GYROSCOPE`, `Sensor.TYPE_GRAVITY`, `Sensor.TYPE_ORIENTATION`, `Sensor.TYPE_MAGNETIC_FIELD`, and `Sensor.TYPE_ROTATION_VECTOR`.

---

**NOTE for readers:** `CMAccelerometerData` is the raw, unfiltered data, and `CMDeviceMotion` is the result of sensor fusion and filtering to provide a better view of the device in 3D space.

**Comment by saranya-sajeev** [comment]
@avaidyam In android we are sending single sensor data for lamp.device_motion as below and not as a group.

{
      "data": {
        "motion": {
          "x": -0.035913024097681046,
          "y": -0.05985504388809204,
          "z": 10.079588890075684
        }
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1637219902287
    },
    {
      "data": {
        "gravity": {
          "x": -0.0006108652451075613,
          "y": 0,
          "z": -0.0006108652451075613
        }
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1637219902267
    },
    {
      "data": {
        "rotation": {
          "x": -0.0033568383660167456,
          "y": 0.0012234500609338284,
          "z": 0.027474381029605865
        }
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1637219902127
    },

**Comment by avaidyam** [comment]
@saranya-sajeev Please update it ASAP to the same format as iOS. Is `lamp.accelerometer` uploaded too? Can you link the source code for both sensors here?

**Comment by saranya-sajeev** [comment]
@avaidyam In Android there is a SensorEventListener for each sensor and we are saving data on sensor callback. Please find the source code link https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/Sensor.java

**Comment by avaidyam** [comment]
@saranya-sajeev Apologies, that's not what I meant. Can you:

1. Convert the `lamp.accelerometer` and `lamp.device_motion` data format to match exactly what iOS receives? 
2. Share the link to the source code in the LAMP repos for where this is done.

**Comment by saranya-sajeev** [comment]
@avaidyam https://github.com/BIDMCDigitalPsychiatry/LAMP-core-android/tree/master/app/src/main/java/digital/lamp/mindlamp/sensor . In sensor package you can see the class for each sensor. In each sensor callback we are saving data under device motion.

**Comment by avaidyam** [comment]
I don't see any DeviceMotion? With the same parameters as the iOS counterpart?

**Comment by saranya-sajeev** [comment]
@avaidyam there is no separate class for device motion. For each sensor callbacks we are saving data under device motion. You can check in GyroscopeData , MagnetometerData  etc classes.

**Comment by avaidyam** [comment]
Please merge these into a single DeviceMotion. **There should NEVER be any discrepancy between iOS and Android sensors, even HealthKit/GoogleFit.** Can you outline any remaining differences in sensors and data format if there are any?

**Comment by saranya-sajeev** [comment]
@avaidyam In Android we will get sensor values only in callback method. There is no option to poll current values of sensor. So we will be saving values for that particular sensor on callback along with empty object for other sensors under device motion. And we will be sending data as below. In current implementation we are assigning null values to other sensor values and it is discarded while sending. So we will be creating an empty object.

	
"data": {
        "gravity": {},
        "magnetic": {},
        "motion": {
          "x": 0.15299999713897705,
          "y": 0.7269999980926514,
          "z": 9.574000358581543
        },
        "rotation": {}
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1638790770408
    }

Current implementation is as below.
"data": {
        "motion": {
          "x": 0.15299999713897705,
          "y": 0.7269999980926514,
          "z": 9.574000358581543
        },
      },
      "sensor": "lamp.device_motion",
      "timestamp": 1638790770408
    }

**Comment by saranya-sajeev** [comment]
@avaidyam shall we implement above change?

**Comment by avaidyam** [comment]
Yes. Please work with @jijopulikkottil to make the data format identical as well.

**Comment by avaidyam** [comment]
@saranya-sajeev mentioned this was pushed to beta. //cc @lukeoftheshire and @ryan-hays We should test this to verify that Cortex works correctly with this correct data format.
