### ISSUE TITLE
Handle Logout events correctly

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#41]
[Right now the dashboard code is sending a `LOGOUT` event to the native apps.](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/master/src/index.tsx#L70) When this occurs, send a `SensorEvent` with the device token set to `null` and the `action` set to `"logout"`.

**Comment by jijopulikkottil** [comment]
Ok, we can send a sensor event when logout, and can do the cleaning task (deleting the stored credentials and resetting data) when get response from server regardless of success or not.

**Comment by amaljofyzco** [comment]
This change will be updated to playstore beta.
