### ISSUE TITLE
Issue with duplicated tip activity events

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#410]
**Describe the bug**
For participant U1989357557, they have an extremely large number of activity events that are tips. There are 90 of them with timestamp 0, and that seem to have response data duplicated from other activity events. In particular, there seem to be 9 duplicates each of 10 of the other activities.

**Expected behavior**
There should not be duplicated activity events.

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.0.1

**Additional context**
The database seems to match the output of LAMP.ActivityEvent, so it seems that the issue must be occurring sometime before data makes it into the database.

**Comment by sarithapillai8** [comment]
This is updated in production.
