### ISSUE TITLE
Tips and Breathe 'completion' data

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#411]
We want to be able to measure the engagement with a tip. We find that users don't usually click the 'Mark complete' or 'Done' when they access tips or breathe activity, and we want to be able to determine the timestamp a tip or Breathe activity was opened. 

Subsequently, we want to know the duration spent on the screen, either by timestamp that the back-button was pressed, timestamp that they exited the app, or timestamp they pressed the Mark Complete button.

**Comment by avaidyam** [comment]
FYI - this is a bug, not a feature, as every single Activity in the app/dashboard **MUST** produce an ActivityEvent with the `timestamp` and `duration` fields at a minimum.

**Comment by sarithapillai8** [comment]
@SuruPa00 @avaidyam 
I have added duration parameter in every activity submission. 

Before implementing that in back press please confirm : 
Do we really need to add activity event on back button press? The steak popup is expected at the time of activity event data generation. So if we create activity event on back press, an activity event will be created. So steak popup will be shown and the entry will show up in portal tab. Is that acceptable?

**Comment by avaidyam** [comment]
If you have added the duration parameter to Tips/Breathe then it should end the activity and generate the event on: 
1. Clicking "Mark Complete" OR
2. Clicking the back button at the top left of the page. 

This code to calculate duration should be within the LAMP-activity codebase. I don't understand the confusion with the streak popup system? If a user opens a Tip and views it and presses the back button, they have still viewed the Tip for say 3 seconds. This should be considered towards streaks.

**Comment by sarithapillai8** [comment]
@avaidyam 
Please see the 5th point in https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/453#issue-1076884291.
There was a requirement to remove steak on back press(I don't have the issue reference, it was a few months back.) and we are not saving activity event in such cases. We are saving event on submit/mark complete cases. So if you can confirm this for all type of activity including survey, we can start changing that.

**Comment by avaidyam** [comment]
The back button requirement is only for Tips and Breathe as users are not pressing the "Mark Complete" button. Not for any other activity. The code changes should only be done in the folders of these two specific activities. Is there a technical issue blocking that from being implemented?

**Comment by sarithapillai8** [comment]
@avaidyam 
No issues. We just wanted to confirm that is it required for all type of activities as we are not considering back press for event generation. So we can do the change for Tips and breathe. Thanks.

**Comment by sarithapillai8** [comment]
@avaidyam 
We have one confusion with Tips. Suppose we have 2-3 sub sections for a tip activity. If we are submitting with 'mark complete', 3 activity events will be generated and on back press, an extra event with a total duration required? or Can we just change it like levels in jewels using temporal slices or something and generate event will all the operations together? 

The current format is 
       {
        timestamp: new Date().getTime(),
        duration: new Date().getTime() - time,
        static_data: {
          sentiment: status,
        },
        temporal_slices: [],
       }
Please suggest.

**Comment by avaidyam** [comment]
The timestamp is when the activity was opened, duration when the overall activity was exited/completed. Each tip category should be its own temporal slice. Item should be the tip category index, duration should be time spent on the particular tip category, and value should be sentiment level (good/bad). Level and type should be null. (Please ensure across ALL activities that only the fields item, value, type, level, and duration, are being used for temporal slices.)

**Comment by sarithapillai8** [comment]
@avaidyam 
We need to work on the change with parameters. The games having fields - item, value, level, duration and status. Value is null , so status can be saved in value, and type can be kept null. We did this first for jewels first, and copied the same for all the games.

**Comment by avaidyam** [comment]
Please rename the status field to type. Make no other changes to where the data is stored (ie. do not store status in value).

**Comment by sarithapillai8** [comment]
This is updated in staging. The back buttons in notifications having no functionality for now. There is not page available to go back from notification as this is separate URL loading on notification. Could you suggest what to do with back buttons? We have removed back buttons for now. Please let us know if that is to be restored.

**Comment by avaidyam** [comment]
@sarithapillai8 The main back button needs to have the same functionality as before - it should close the Tips session. If no Tip was viewed, it still needs to record that info in the `ActivityEvent`. Do not remove the back buttons.

**Comment by sarithapillai8** [comment]
@avaidyam 
In the case of tips we will have some success page with tips activity. What should happen for other kind of activities like surveys in notifications? do we need to show dashboard/login screen on back click?

**Comment by avaidyam** [comment]
Restore the old functionality of the back button across all activities, including Tips. It should still create an ActivityEvent for any activity when the back button is pressed.

**Comment by sarithapillai8** [comment]
@avaidyam 
There was no functionality in notification screen for the activities. For tips and breathe we have activity event creation now. But in other cases there is no functionality. I am asking about notification screen, not from dashboard.

**Comment by avaidyam** [comment]
Then show the dashboard on the back button action - we need the back button to work the same across all the home tab screens or the Feed tab.

**Comment by sarithapillai8** [comment]
We removed the back button only for notifications. We can restore and on clicking we can move to dashboard then.

**Comment by divyav2020** [comment]
Updated the build in Dashboard staging
[LAMP_Admin Website_Streak Fixes.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7829106/LAMP_Admin.Website_Streak.Fixes.xls)

[LAMP_Admin Website_Notification Back button.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7829108/LAMP_Admin.Website_Notification.Back.button.xls)

**Comment by avaidyam** [comment]
@sarithapillai8 It appears that the duration spent in a sub-tip is only recorded if you press 👍/👎, otherwise, it's just the total duration. Can you see if there's a way to record sub-tip duration if the back button is pressed to go out to the list of all sub-tips?

**Comment by avaidyam** [comment]
@sarithapillai8 @divyav2020 We also found in our QA testing that the back button generates an ActivityEvent for **every ActivitySpec** (including Survey, DBT Diary Card, etc.) and not just Tips. We need to rethink the current implementation if this is the case. Can you confirm the behavior we're seeing?

**Comment by sarithapillai8** [comment]
@avaidyam 
We are not able to reproduce this issue. Could you confirm with your QA team?

**Comment by avaidyam** [comment]
@tlakhtak reported that our collaborators are seeing streaks and empty DBT Diary Card data when the activity is opened and the back button is pressed.

**Comment by sarithapillai8** [comment]
@avaidyam  @tlakhtak 
Do you still have any issue with the back button press?

**Comment by avaidyam** [comment]
@sarithapillai8 This issue looks resolved now, thanks!
