### ISSUE TITLE
Selecting/deselecting doesn't always work

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#414]
Selecting/deselecting doesn't always work; takes very long and sometimes when someone is deselected after selecting all, nothing change

**Comment by SuruPa00** [comment]
@sarithapillai8 is there an update or eta on this? the 1 day marker was assigned 8 days ago so just wanted to follow up.

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in production in the previous release. Missed to update the status.

**Comment by SuruPa00** [comment]
@sarithapillai8 i just tested this and when i select all, deselect all, and select a specific user, everyone gets selected again

**Comment by divyav2020** [comment]
@SuruPa00 We are unable to reproduce this issue

**Comment by SuruPa00** [comment]
@sarithapillai8 @divyav2020 currently, when the select all button is clicked, users are loaded one by one, can this be fixed so that all users are loaded at once to save loading time?

**Comment by sarithapillai8** [comment]
@SuruPa00 
We couldn't reproduce the issue. Please see the attached recording and let me know what is actually experiencing on your side.

https://user-images.githubusercontent.com/63710347/144014178-4d1efa6d-1f64-4686-b699-11404676a5c6.mp4
