### ISSUE TITLE
Changing the color bars for recent GPS / accelerometer to check if data quality is good

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#415]
Changing the color bars for recent GPS / accelerometer to check if data quality is good - not always accurate; green, yellow, and red dont accurately reflect data quality/most recent collected data

See example below of green color bar for data quality as the page under a researcher account where you see a list of users
![image](https://user-images.githubusercontent.com/86117379/140806090-5ea8ff77-34c0-46e0-b7c9-3eb6841750ba.png)

This should show the color bars as follows for passive data: green if gps/accelerometer were collected in the last hour, yellow if in the last day, and red if last collected more than a day ago; this should apply if there is gps AND accelerometer, not if only one is collected - though this would need to be exempt is accelerometer is intentionally not being collected

The color bars for active data: green if active data collected in the last day, yellow if in the last 3 days, and red if last was more than a week ago

**Comment by avaidyam** [comment]
Since this change only requires updating the threshold values in the [`LAMP-dashboard` src right here](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/2ecdecf3d6baefec0d00bd855ce7b49fa2023f71/src/components/Researcher/ParticipantList/Index.tsx#L110), let's discuss this change internally. 

---

**Ignore the below - preserved for posterity ONLY.** A previously internally discussed (but now scrapped) implementation of this was instead using the JSONata system built into the LAMP API:

1. If the Tag `lamp.dashboard.indicators` exists:
    1. Load the `string` value of this Tag, which is a JSONata query in the format:
        ```
        (
            /* Get activity/sensor events. Parameters: id, origin, from, to, limit. */
            $gps = $LAMP.SensorEvent.list($$PARTICIPANT_ID$$, "lamp.gps", null, null, 1);
            $accel = $LAMP.SensorEvent.list($$PARTICIPANT_ID$$, "lamp.accelerometer", null, null, 1);
            $survey = $LAMP.ActivityEvent.list($$PARTICIPANT_ID$$, null, null, null, 1);
            
            {
                "Last GPS": {
                    "color": ($millis() - $gps[0].timestamp < (60 * 60 * 1000)) ? "green" : "red",
                    "text": $fromMillis($gps[0].timestamp),
                },
                "Last Accel": {
                    "color": ($millis() - $accel[0].timestamp < (60 * 60 * 1000)) ? "green" : "red",
                    "text": $fromMillis($accel[0].timestamp),
                },
                "Last Survey": {
                    "color": ($millis() - $survey[0].timestamp < (24 * 60 * 60 * 1000)) ? "green" : "red",
                    "text": $fromMillis($survey[0].timestamp),
                }
            }
        )
        ```
    1. Replace-all the string `$$PARTICIPANT_ID$$` with the current Participant ID.
    1. Execute this query (`POST /` with this string).
    1. Each key-value pair becomes an indicator bubble (`color` is a CSS color-name or hex code, `text` is the tooltip value). 
1. Else:
    1. Do nothing (indicators are hidden entirely).

---

//cc @lukeoftheshire
