### ISSUE TITLE
Vega Graph resizing

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#416]
Vega Graphs in the portal page of LAMP could be dynamically resized to fit the width of the box - currently graphs can overflow

See example of a cutoff graph below on the phone:
![image](https://user-images.githubusercontent.com/86117379/140812210-b3525fb0-d651-4404-a110-ac9acef7d34b.png)

See the correctly displayed visualization on the dashboard below:
![image](https://user-images.githubusercontent.com/86117379/140812308-da3905f4-8d63-47af-9e02-d7d40e0824c2.png)

**Comment by avaidyam** [comment]
@lukeoftheshire @SuruPa00 Can you share the Vega graph JSON + maybe an SVG here as well? (Also, Slack me credentials if there's a staging account set up with this that we can use to test code changes.)

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production.
