### ISSUE TITLE
No notification receipt events are being saved

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#42]
Whenever a notification is received by the device, it should save a `SensorEvent` with `action` set to `"notification"` and the entire payload that was given to the app should be present, including, for example, the `aps` object for iOS.

**Comment by jijopulikkottil** [comment]
Completed on app side, but this new sensor event may affect the server side logic of getting device token. So it need to test. @Linoy339 can close it on early next week.

**Comment by avaidyam** [comment]
@amaljofyzco What's the progress for this on the Android side?

**Comment by jijopulikkottil** [comment]
Let us clarify one more thing that we have to send the SensorEvent when received the notification. right ? Or when user responding the notification ?

**Comment by amaljofyzco** [comment]
Aditya, Implemented this on - when user tap on the notification.

**Comment by avaidyam** [comment]
@jijopulikkottil @amaljofyzco Let's send the notification as soon as it is received by the app. When the user taps on it, they are (supposed to be) brought to the activity itself (i.e. Survey or Jewels), and from there a new timer is started in the UI code, so we are already tracking the timestamp for the start of their interaction. For the native app, we want to track when the notification is displayed, so that way we can later evaluate the lag time between when a patient received a notification and when they actually opened it/responded to it.

**Comment by avaidyam** [comment]
@jijopulikkottil @amaljofyzco Has this change been made yet in the beta builds?

**Comment by amaljofyzco** [comment]
Adithya, Yes it's already done.

**Comment by jijopulikkottil** [comment]
Yes iOS build is in testflight, but there is an issue that it will send twice if its in foreground. Its fixed. I can commit today.

**Comment by avaidyam** [comment]
@jijopulikkottil Let me know when this issue is resolved. @amaljofyzco Is the build with this update already out for beta testers?

**Comment by jijopulikkottil** [comment]
@avaidyam  It is resolved and build 69 uploaded.

**Comment by avaidyam** [comment]
Thanks! 

@jijopulikkottil @amaljofyzco As a heads up, please switch to making pull requests to the master branch for `LAMP-core-ios` and `LAMP-core-android` going forwards, as we discussed during Monday's meeting. (cc @michaelmenon)

**Comment by amaljofyzco** [comment]
> @jijopulikkottil Let me know when this issue is resolved. @amaljofyzco Is the build with this update already out for beta testers?

Yes Adithya.
