### ISSUE TITLE
Daily Survey Error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#421]
> There seems to be a coding error somewhere. I’m on the daily survey, and after I fill out the overall mood question, it gives me the pictured errors. I tried to scroll and tilt my phone, but it doesn’t allow me to see the rest of the error message. I’ve tried 3 times now and have tried with a different answer to the mood question, but the error persists

![image0](https://user-images.githubusercontent.com/86117379/139469624-6bfc970f-a599-4062-8d25-b1e804f06025.png)

![image1](https://user-images.githubusercontent.com/86117379/139469641-3fa62218-926d-4028-b898-5e98426d2735.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in production.
