### ISSUE TITLE
Labels overlapping on icons

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#423]
Some labels are overlapping with the activity icons - see screenshot below

<img width="1073" alt="Screen Shot 2021-11-02 at 1 22 29 PM" src="https://user-images.githubusercontent.com/86117379/139914918-bb05dd16-c0d4-49b5-a85b-3fb5a11c018b.png">

**Comment by SuruPa00** [comment]
@sarithapillai8 hi, is there an update on this issue?

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in staging with some other issues. We will be releasing after QA.

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production.
