### ISSUE TITLE
Text Size issues

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#425]
See below screenshots of issues where text needs to be scrolled for or/text is not displayed as it should be - 

See how the user has to scroll to see the description of the activity, which has been slightly cut off
![image](https://user-images.githubusercontent.com/86117379/140749657-102b4442-bc01-4181-8cf2-6d9495e4858b.png)

See how there is an awkward space between the specified tip - it would be best if Psychologist vs Psychiatrist was on one line OR the vs was closer to the words
![image](https://user-images.githubusercontent.com/86117379/140750107-9bfea341-10c5-480a-8734-b0d769d7a08b.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 
We have updated some issues together in staging. After QA completed, we can release this with others. We plan to release these by this Friday or next Monday.

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production.
