### ISSUE TITLE
Optional Questions

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#427]
When creating a survey and adding questions, can we have a new box that allows us to flag questions as optional? This can take form of a check box where if we check it, it allows that question to be left blank/unanswered without making it so the survey cannot be completed. I've added a visual of where this go in the survey editor below:

![image](https://user-images.githubusercontent.com/86117379/140997621-35276151-29d0-4a49-bb91-6c330bd4f171.png)

---
## Support `required` question fields

A new `required` field should indicate that the survey cannot be completed without the completion of this particular question on which `required = true`. If this field does not exist, it should be considered optional for backwards compatibility. 

The current implementation of `slider` and `rating` questions defaults to the first value in the `options` list; this behavior must be changed such that no value is selected by default. If `required` is not true or undefined for the question, the activity event temporal slice `value` field must be `null` to indicate no user response. 

---

**Comment by sarithapillai8** [comment]
@SuruPa00 
Just to confirm - Currently no survey don't have this `required` field and thus all the current survey can be submitted without any responses. We did mandatory checking a few days back. That is why confirming that all the surveys that require this mandatory check need to update the survey.

**Comment by SuruPa00** [comment]
@sarithapillai8 yes, this is expected behavior

**Comment by sarithapillai8** [comment]
@SuruPa00 This is updated in production.

**Comment by SuruPa00** [comment]
@sarithapillai8 this is mostly functioning as intended, but can questions be required by default and toggled to be optional after? this could be done by making the default checked box to be required instead of option or to default have the optional box unchecked.

**Comment by SuruPa00** [comment]
@sarithapillai8 okay so by default, every survey is now optional, can this please be fixed ASAP to by default have every question required unless the box is toggled? this will affect other studies immensely so please prioritize this

**Comment by SuruPa00** [comment]
@sarithapillai8 per comments in #400, please update this asap alongside the different loading method in the aforementioned issue

**Comment by sarithapillai8** [comment]
@SuruPa00 The changes related to optional are updated in production.

**Comment by SuruPa00** [comment]
@sarithapillai8 thanks for this, this is now working as intended. another part of this ticket is also the slider questions starting at the first value instead of a null value at default when no user input has been made. Can this be addressed too now?

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in production.
