### ISSUE TITLE
Embedded Video Error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#429]
Embedded videos in Tips are not working even when the markdown code is correct: see screenshot below where it says "youtube refueses to connect" - for location of exact issue, see U5995826498 and the Strengths Tips

![image](https://user-images.githubusercontent.com/86117379/141122233-42f606df-ebc2-4430-aa87-91849c44cee1.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is not the issue with activity instead this the error thrown by YouTube for invalid URL in Iframe. In the activity settings , I can see the YouTube link included as https://www.youtube.com/watch?v=XZUK8JSGf6I.  
This should be given in the format like this - https://www.youtube.com/embed/XZUK8JSGf6I. You can get the link in this format by clicking the share option of YouTube and get the code with **_Embed_** option.
