### ISSUE TITLE
Mindfulness Loop and Error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#430]
Currently, the mindfulness and breathe activities are encountering an infinite loop. When a participant accesses the activity, the audio keeps looping and the only way to stop the activity is to exit it manually, which does not allow for any record of completion. 

See U8282161095 for an example. Despite being reported as completed by the user, the Inner Teacher activity is not shown as completed anywhere in the Portal tab of LAMP.

**Comment by SuruPa00** [comment]
@ZCOEngineer any update on this?

**Comment by SuruPa00** [comment]
@ZCOEngineer has this been looked into at all or has an eta?

**Comment by ZCOEngineer** [comment]
@SuruPa00 We shall check this issue this week based on priority

**Comment by divyav2020** [comment]
@SuruPa00  I have used U8282161095 user Id and checked mindfulness and Natural Relaxation breathe activity in website. But both the records ended up with success message. I have checked my records too. But couldn't reproduce the above mentioned issue.

**Comment by SuruPa00** [comment]
try U8550073055 and the morning 1 minute mindfulness - the first sentence of the video in the first few seconds keeps repeating at the end

**Comment by divyav2020** [comment]
I have used U8550073055 user Id and checked morning 1 minute mindfulness. But I am unable to reproduce this issue.
