### ISSUE TITLE
Android opening app error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#434]
> “It is Android version 8.1.0. When I try to open the app, I get the spinning circle (i.e. it is trying to open but never does.) I have uninstalled and reinstalled several times, but the app never opens.”

Can you look into why an Android 8 might have an infinite loading screen? This has been reported by multiple users on both Android 8 and Android 9. Let me know if you can reproduce with the same model and investigate.

**Comment by SuruPa00** [comment]
@ZCOEngineer any update on this? another report yesterday - see screenshot of this loading screen that never ends below:
![image000000](https://user-images.githubusercontent.com/86117379/144056152-2c7137b3-77c3-47ea-9f3a-a73b01a459f3.png)

**Comment by saranya-sajeev** [comment]
@SuruPa00 App opening error is fixed and pushed to beta. After confirmation we can move to production.

**Comment by SuruPa00** [comment]
@saranya-sajeev yes go ahead and move to production
