### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#435]
Upon download and opening the app, we are running into this 502 error as of yesterday and are unsure where it is stemming from - please see this as soon as possible as highest priority

![image (1)](https://user-images.githubusercontent.com/86117379/142630163-7c4472cf-e275-4da7-9f46-4bd2d0d26ec0.png)

**Comment by ZCOEngineer** [comment]
@SuruPa00 we checked in both iOS and Android and it seems to be working now. not sure if the server was out that time. Could you check now on your devices?

**Comment by SuruPa00** [comment]
@ZCOEngineer I am not encountering this error on some phones internally, but there are still reports coming in about the 502 error persisting and I believe this is for both iOS and Android

**Comment by SuruPa00** [comment]
@ZCOEngineer this issue is still persisting, can you check on it again?

**Comment by michaelmenon** [comment]
Hi @SuruPa00 This seems to be from the space issue on the Dashboard server can we have the space cleared off in the Dashboard server. We can monitor for this issue and confirm after that. Please have the dashboard server space cleared off.

**Comment by michaelmenon** [comment]
Great thanks @SuruPa00 can you please check with the user who was seeing the 502 error to see oof they are still getting that issue. We will check on our end as well.

**Comment by SuruPa00** [comment]
This issue has appeared since our team cleared the space, with a report at at 10:11am when we cleared it a bit before that, please check on your end

**Comment by michaelmenon** [comment]
Sure, we will check on our end, please check with the users who had this issue before as well and confirm.

**Comment by michaelmenon** [comment]
When we checked the server space issue has been resolved. QA was testing the app for the 502 error and we did not see it here after the space issue resolution.

**Comment by SuruPa00** [comment]
This seems to have been resolved since the space issue has been solved
