### ISSUE TITLE
Created credentials are not working

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#436]
When creating a new user, whenever I try to log in with my created credentials, I am unable to log in and receive the error message as if I entered my credentials wrong. This is happening for U0787924669 and many other users.

**Comment by sarithapillai8** [comment]
@SuruPa00 
We tried different logins for reproducing this issue. Created credentials from researcher, admin and participant. Couldn't reproduce this issue.
