### ISSUE TITLE
Notification is not working for Every 2 weeks schedule

### ISSUE THREAD

**Issue by divyav2020** [BIDMCDigitalPsychiatry/LAMP-platform#437]
Scheduled a lamp activity for 2 weeks schedule. But the push notification is not working for the particular schedule

**Comment by sarithapillai8** [comment]
This is updated in production.

**Comment by Linoy339** [comment]
@lukeoftheshire . Can you please latest image of Lamp-worker in production, for this to reflect?

**Comment by ZCOEngineer** [comment]
This is complete and tested
