### ISSUE TITLE
Activity ID is showing up as undefined

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#438]
When making an API call, the activity ID under a user is showing up as undefined - please see how this can be fixed ASAP
<img width="941" alt="Screen Shot 2021-11-29 at 9 40 35 AM" src="https://user-images.githubusercontent.com/86117379/143897445-8051556c-c637-45d7-b883-a9fadc5e6c23.png">

**Comment by Linoy339** [comment]
@SuruPa00 .  We can check this.
Can we create a user under this particular study (SA) for testing purpose ?

**Comment by SuruPa00** [comment]
@Linoy339 yes name it ZCO1

**Comment by Linoy339** [comment]
Thank you @SuruPa00

**Comment by Linoy339** [comment]
@SuruPa00 . I have updated this for now.  We have tested  it and couldn't find how the activity id got undefined.
Can you please confirm whether these events came through mindlamp app or via any migration script?

**Comment by SuruPa00** [comment]
@Linoy339 this is not through a migration script, can confirm it is from mindLAMP

**Comment by Linoy339** [comment]
@SuruPa00 . We couldn't reproduce this issue, as activity was saving properly

**Comment by SuruPa00** [comment]
See this screen recording for more info: this is a test user i created with the id U3078457698
https://user-images.githubusercontent.com/86117379/145047246-be5a2df1-1e75-4739-8c61-338c51e486cf.MP4

**Comment by Linoy339** [comment]
Thanks @SuruPa00 for the feedback . We realized that the issue raised when taking it from feed. We will check it and let you know

> You can see the activity, from the frontend, does not show up as completed in the feed tab when accessed from the feed, nor does it show up in the portal tab

This was created to be held in assess tab and not in portal tab

**Comment by Linoy339** [comment]
Sorry for the that. We will check that too and update

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in production.
