### ISSUE TITLE
 "Nice Work" pop-up between activities in grouped activities and custom pop-up

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#441]
Currently, when activities are grouped together (let's say 5 surveys), upon completion of each survey, a pop saying "Nice Work" comes up. Can this be adjusted so that this pop-up only comes up after completion of the final activity in the group?

Additionally, can we have the current pop-up be customizable in the survey builder? By this, I mean that the intended feedback in the pop-up could be adjusted to anything a researcher or admin wants. This could take place as a new box to edit anywhere in the survey builder towards the top. See the screenshot below for an idea

![image](https://user-images.githubusercontent.com/86117379/144123367-53080e94-1f92-453a-b94a-ad75d7feef19.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 
'can we have the current pop-up be customizable in the survey builder?' - Actually is this for all the survey popups or the group activity ?

**Comment by SuruPa00** [comment]
@sarithapillai8 each individual survey should be able to have their popup text customized, so even if they are in a group activity, when that individual survey is completed, their popup will say the custom popup. But as requested, these should also be able to be toggled on and off in case someone does not want any popup to appear. Additionally, have a custom pop-up for the completion of the group activity as well

**Comment by sarithapillai8** [comment]
@SuruPa00 
Do we need to show individual popup for activities in group activity? I believe it should be removed and show the popup after the group activity. 
All the type of activities having popups after completion. So we need a toggle button and custom texts to be used for 'Nice work' and 'You’re on a streak, keep it going' sections for each activity. I hope the steak days should remain there untouched.  
@avaidyam  So can we add these fields in activity object or do we need to manage these in 'activity_details' tag?

**Comment by SuruPa00** [comment]
@sarithapillai8 you can remove the individual popups in the group activity; there needs to be a toggle button for the nice work and you're on a streak texts, but by default they should be toggled on and with those texts.

**Comment by avaidyam** [comment]
@sarithapillai8 Please use the Tag and not the Activity object for this.  We can revisit the data model later if needed.

**Comment by sarithapillai8** [comment]
This is updated in dashboard-staging. QA continuing testing for production release.

**Comment by divyav2020** [comment]
We have updated the build in Dashboard staging
[LAMP_Admin Website_Good Job Done changes.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7829113/LAMP_Admin.Website_Good.Job.Done.changes.xls)
