### ISSUE TITLE
Check other login credential removal

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#443]
Can we make sure there is no code in the dashboard and native apps that removes login credentials other than the when the user manually logs out? The only instance in which a user should be logged out is when the user presses logout themselves. Please check on this, as it should be related to auto-logout issue we have been regularly experiencing as mentioned in #323

**Comment by avaidyam** [comment]
Since the affected issue hasn't occurred in some time, this issue will be closed for now.
