### ISSUE TITLE
Large Survey Option

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#445]
We are looking to have a new type of survey that we could call "Large Survey". This would function as a survey that contains multiple other surveys, but is different from a group in that you can access these surveys at any time. Additionally, we want an indication that a survey is completed with a green check mark. I've drafted a mock-up of what we envision with this request from a UI perspective below.

From the base assess page:
![image](https://user-images.githubusercontent.com/86117379/144667272-a3374d0b-f80d-47aa-b179-e5c009d0bb6c.png)

Let's say a user clicks "Mega Survey". It would lead to a screen that showcases the numerous surveys nested inside the the Mega Survey. This interface would look similar to an assess page, but also feature a header of what large survey these surveys are nested under and a back button to return to the original assess page
![image](https://user-images.githubusercontent.com/86117379/144667333-69c7e5b4-fbf4-40eb-b552-c3487c921449.png)

Upon completion of any mini survey, add a check mark to the survey icon like this:
![image](https://user-images.githubusercontent.com/86117379/144667471-8f4ec4d6-1a9f-4614-a4ab-f9f43665602e.png)

Lastly, once all nested surveys are completed under a large survey, indicate this completion with a green check mark on the large survey in the original assess page. Example below:
![image](https://user-images.githubusercontent.com/86117379/144667549-471a2067-153c-4832-91d9-bcb1beb96dd9.png)

From a researcher perspective, create this as another option other than "create survey instrument". Let me know if you have any questions.

**Comment by avaidyam** [comment]
Closing this issue as it's not something technically feasible at this time.
