### ISSUE TITLE
User Hierarchy Update

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#447]
Can you please add the permission for User Admin roles to have access to the manage credentials button in the top left corner when they click on their listed role (where it says User Administrator in the corner). Additionally, make it so they can only assign the roles of user administrator and practice lead, not system administrator

**Comment by sarithapillai8** [comment]
@SuruPa00 
This is updated in staging. Please check and let me know.

**Comment by SuruPa00** [comment]
@sarithapillai8, checked - push to production and let me know when you have

**Comment by SuruPa00** [comment]
@sarithapillai8 has this been pushed to production yet?

**Comment by sarithapillai8** [comment]
@SuruPa00 
No. This will be updated with #442 as that is also updated to master branch, we can only release with that.

**Comment by sarithapillai8** [comment]
Please see the test report attached
[LAMP_Admin Website_Hirearachy Updates.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7716873/LAMP_Admin.Website_Hirearachy.Updates.xls)
