### ISSUE TITLE
Activities are not showing up for users in any page

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#449]
We are encountering an issue where people's assess page is not populating with all of the activities that they have in their account even though they are configured to be there for the user. See the first screenshot below for what is showing up in their assess page and see the second screenshot to see how multiple activities in the assess page are in fact configured. See the third screenshot to see how the feed still shows an activity that is not appearing in the assess page (though this is one that is configured). This issue is happening not only to the assess page, but includes the manage and learn page as well.

![image](https://user-images.githubusercontent.com/86117379/145404350-ffdb4f34-9ee5-4b6e-9f3d-b673e558a319.png)
![image](https://user-images.githubusercontent.com/86117379/145404761-d8b30cce-1b26-4df4-a9e4-d41d43f33dd6.png)
![image](https://user-images.githubusercontent.com/86117379/145405306-32c09495-da4b-4b03-93d0-95b40a763002.png)

The user is using a pixel 4a on android 12 and has the id U6298298612

**Comment by SuruPa00** [comment]
There are other reports that when there are activities configured, nothing shows up for any tab as well. Please see what's going on here.

**Comment by michaelmenon** [comment]
Thanks Suraj, Saritha is checking on this. Will update asap.

**Comment by SuruPa00** [comment]
A user example for where a user is having nothing up is U0010811412

**Comment by michaelmenon** [comment]
Thanks @SuruPa00  the fix will be active within an hour.. Will update asap

**Comment by sarithapillai8** [comment]
@SuruPa00 
The fix is updated in production. We can update you after QA confirm.

**Comment by SuruPa00** [comment]
Hi Michael,

Is there an update on this? Last comment was that it will be confirmed after QA testing.

Best,
Suraj

Suraj Patel
Clinical Research Assistant
Division of Digital Psychiatry
Beth Israel Deaconess Medical Center
www.digitalpsych.org<https://urldefense.com/v3/__http:/www.digitalpsych.org__;!!CvMGjuU!o_0g-D8A-mzf2TsRzBaC3r-qVLSOKMXARmqztvy7N5bddEyfBXw78R3xKjD324moL0dQF60$>
Email: ***@***.******@***.***>

From: Mike ***@***.***>
Sent: Thursday, December 9, 2021 10:38 AM
To: BIDMCDigitalPsychiatry/LAMP-platform ***@***.***>
Cc: Patel,Suraj (BIDMC - Torous - Psychiatry) ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [BIDMCDigitalPsychiatry/LAMP-platform] Activities are not showing up for users in any page (Issue #449)


Thanks @SuruPa00<https://urldefense.com/v3/__https:/github.com/SuruPa00__;!!CvMGjuU!oePFw7zQQjHzL5En_wlEpK8UspMmEG0UD-ztgGXBvMVmK8ij3IC-YcHHgOmOA2yq2f1y7Ufi$> the fix will be active within an hour.. Will update asap

**Comment by michaelmenon** [comment]
Hi @SuruPa00 its already updated to production and working. You can confirm with the user  U0010811412.
