### ISSUE TITLE
Restore Pop The Bubbles and Balloon Risk games to Assess tab

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#45]
These two cognitive tests should be restored - their activity specs are `lamp.pop_the_bubbles` and `lamp.balloon_risk`. Also, move the Jewels, Spatial Span, etc. games to the Assess tab instead of the Manage tab.

---
> The original demonstration PPTs:
> [Pop The Bubbles](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5652461/Pop.The.Bubbles.pptx)
> [Balloon Risk](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5652460/Balloon.Risk.pptx)

**Comment by sarithapillai8** [comment]
@avaidyam 
What kind of settings expected for these 2 games? Also please provide the response format (game result)

**Comment by avaidyam** [comment]
@sarithapillai8 Let me prepare this info for you and let you know by end of day.

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please specify rhe settings so that I can update estimate based on that.

**Comment by sarithapillai8** [comment]
@avaidyam 
We are not done with result submission of games except for box and jewels variants. Do you want complete those as part of this task?

**Comment by avaidyam** [comment]
Yes, let's add those to this issue as it's the same core functionality. All activities should be reporting results if they are in the UI.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
What will be the values for the settings of Balloon Risk and Box Game?
Can you please specify the values for temporal_slices and static_data ?
For Balloon game, when we collect points OR when the balloon is burst we will store the data as temporal_slices(multiple data till there are 15 records since the balloon limit is 15)

**Comment by avaidyam** [comment]
## For Balloon Risk:

### `settings`
1. `balloon_count`: number of balloons (`integer`), default = `15`
1. `breakpoint_mean`: mean of number of pumps to reach breakpoint
1. `breakpoint_std`: standard deviation of number of pumps to reach breakpoint
    - The two variables `breakpoint_mean` and `breakpoint_std` form a normal distribution for the "coin flip" of whether the pump action will succeed or cause the balloon to burst.

### `static_data`
1. `points` = total number of points earned across the game (`integer`)

### `temporal_slices`
1. `item` = number of pumps (`integer`)
1. `value` = number of points given for this pump, or `0` if popped (`integer`)
1. `type` = `true` if balloon was pumped, `false` if balloon was popped (`boolean`)
1. `level` = current balloon number (`integer`)
1. `duration` = time since last event in milliseconds (balloon tap or burst) (`integer`)

---
> Previous Pop The Bubbles Settings Mockup
> ![Pop The Bubbles Settings](https://user-images.githubusercontent.com/1361003/101348262-5ab52d80-3859-11eb-81f5-67b321aed345.PNG)

**Comment by sarithapillai8** [comment]
@avaidyam 

With a mean of 90, and standard deviation of 10, we will be having normal distribution of 15 breakpoints with values ranging from 20 to 150 , right?. So do we have to keep this array and take each breakpoint randomly or in sorted order? If sorted order, the user will have an idea of next breakpoint after some trails. Is that what expected here?

**Comment by sijugeorge-zco** [comment]
@avaidyam 

Can you please confirm whether i'm right with the below for the temporal_slices :

1. item = number of pumps (integer)
is the number of pumps just before collecting points or burst ?
For Eg: The number of pumps is that ,when starting pumping from balloon 1 to collecting points of balloon 1 or till the balloon 1 burst

5. duration = time since last event in milliseconds (balloon tap or burst) (integer)
is the duration calculated between collecting points or burst ?
For Eg: The duration is that the time when starting pumping from balloon 1 to collecting points of balloon 1 or till the balloon 1 burst.

If there are 15 balloons, the maximum number of data for temporal_slices will be 15 , which will have data for each balloon (collect or burst).

**Comment by avaidyam** [comment]
@sijugeorge-zco 

> is the number of pumps just before collecting points or burst ? For Eg: The number of pumps is that ,when starting pumping from balloon 1 to collecting points of balloon 1 or till the balloon 1 burst. 
> 
> is the duration calculated between collecting points or burst ? For Eg: The duration is that the time when starting pumping from balloon 1 to collecting points of balloon 1 or till the balloon 1 burst.

The number of pumps should be until the balloon bursts (which is the end of the "level"), and the duration is BETWEEN pumps (including the the pump that caused the balloon to burst). For example:
```
 0: { item: 1, value: 1, type: true, level: 1, duration: 200 }
 1: { item: 2, value: 1, type: true, level: 1, duration: 100 }
 2: { item: 3, value: 1, type: true, level: 1, duration: 200 }
 3: { item: 4, value: 1, type: true, level: 1, duration: 400 }
 4: { item: 5, value: 1, type: true, level: 1, duration: 300 }
 5: { item: 6, value: 0, type: false, level: 1, duration: 200 }
 6: { item: 1, value: 3, type: true, level: 2, duration: 200 }
 7: { item: 2, value: 3, type: true, level: 2, duration: 600 }
 8: { item: 3, value: 1, type: true, level: 2, duration: 200 }
 9: { item: 4, value: 1, type: true, level: 2, duration: 100 }
10: { item: 5, value: 3, type: true, level: 2, duration: 200 }
11: { item: 6, value: 0, type: false, level: 2, duration: 800 }
12: { item: 1, value: 5, type: true, level: 3, duration: 100 }
13: { item: 2, value: 5, type: true, level: 3, duration: 200 }
14: { item: 3, value: 5, type: true, level: 3, duration: 100 }
15: { item: 4, value: 0, type: false, level: 3, duration: 200 }
```
(The `value` parameter is used differently here per level only as an example.)

> If there are 15 balloons, the maximum number of data for temporal_slices will be 15 , which will have data for each balloon (collect or burst).

The number of balloons is not the number of temporal slices, it should be the sum of number of pumps for each balloon. (As shown in the example above.)

**Comment by avaidyam** [comment]
@sarithapillai8 
> With a mean of 90, and standard deviation of 10, we will be having normal distribution of 15 breakpoints with values ranging from 20 to 150 , right?. So do we have to keep this array and take each breakpoint randomly or in sorted order? If sorted order, the user will have an idea of next breakpoint after some trails. Is that what expected here?

No need to keep the array saved, it should be a function you call for each pump action. Since `Math.random()` does not follow a normal distribution, [you will need to use the Box-Muller transform](https://en.wikipedia.org/wiki/Box–Muller_transform), for which the adapted code is reproduced below: 
```js
function random_gaussian(mean, std) {
    let u = 0, v = 0;
    while(u === 0) u = Math.random();
    while(v === 0) v = Math.random();
    let num = Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
    num = num / 10.0 + 0.5;
    if (num > 1 || num < 0) return random_gaussian();
    return (num * std) + mean;
}
```

**Comment by sijugeorge-zco** [comment]
@avaidyam 
Thank you for the example of temporal_slices.

We will store the data for each pumping on temporal_slices.
As you suggested we will call this function(which you provided random_gaussian() ) on each _Collection of Points_ or _Balloon Popped_ .
When i tried calling the above function with an example like Mean = 64.5 and StandardDeviation = 37,
 i was only getting values between 70 and 95 as break points and the values below them are not getting using this function
 ie; balloons cannot have low break points. 

Please correct me if i'm wrong.

**Comment by avaidyam** [comment]
@sijugeorge-zco That's correct and expected! Here's a demonstration: 

### `Math.random()` (uniform distribution)
<img width="1135" alt="Screen Shot 2020-12-09 at 7 42 31 AM" src="https://user-images.githubusercontent.com/1361003/101631393-4193b480-39f2-11eb-9a53-0d0eb4643a40.png">

### `random_gaussian()` (normal distribution, mean=1, std_dev=1)
<img width="1135" alt="Screen Shot 2020-12-09 at 7 42 54 AM" src="https://user-images.githubusercontent.com/1361003/101631396-422c4b00-39f2-11eb-80ee-a6f2573e35e0.png">

### `random_gaussian()` (normal distribution, mean=64.5, std_dev=47)
<img width="1135" alt="Screen Shot 2020-12-09 at 7 43 09 AM" src="https://user-images.githubusercontent.com/1361003/101631397-422c4b00-39f2-11eb-94d4-7674853804a9.png">

**Comment by sijugeorge-zco** [comment]
@avaidyam 
Can u please let me know after adding activity specs "lamp.pop_the_bubbles" and "lamp.balloon_risk"

**Comment by avaidyam** [comment]
@sijugeorge-zco Done!

**Comment by sijugeorge-zco** [comment]
@avaidyam 
Can you please specify static_data and temporal_slices values for Pop the bubble game ?
Also can you please specify the settings columns for the Pop the bubble game?

**Comment by avaidyam** [comment]
@sijugeorge-zco: **This information is all provided in great depth in the attached PowerPoint presentation** but I have reproduced it here for clarity. 

### `settings`
1. `bubble_count: number[] = [60, 80, 80]`: number of bubbles per level; array length = number of levels, must match below array's length
1. `bubble_speed: number[] = [30, 30, 30]`: speed at which bubbles enter level in seconds; array length = number of levels, must match above array's length
1. `intertrial_duration: number = 0.5`: duration between trials, in seconds
1. `bubble_duration: number = 1.0`: length of time bubbles remain on screen, in seconds

### `static_data`
1. `N/A` (unused)

### `temporal_slices`
1. `item: number`: the index of the bubble in the current level
1. `value: string`: the color of the bubble (i.e. `yellow`, `red`, etc.) followed by trial type (i.e. `go`, `no-go`, `no-go-lure`, `no-go-constant`, `no-go-2inrow`).
1. `type: boolean`: whether this tap was correct or incorrect
1. `level: number`: the level number
1. `duration: number`: the reaction time to tap the bubble, in milliseconds, or `null` if bubble ignored

**Comment by sijugeorge-zco** [comment]
@avaidyam @michaelmenon 
As discussed today, we will hold this task and will be working on the task of Unit testing.

**Comment by avaidyam** [comment]
@sijugeorge-zco Are you able to at least commit/PR your current progress?

**Comment by michaelmenon** [comment]
@sijugeorge-zco as discussed in our meeting yesterday we need to work on this task as priority once al the games are ported we can start on the unit test case addition.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
Regarding Pop the Bubbles game on the temporal_slices , can you specify the 'value' ?
Because on value its says as value: _string: the color of the bubble (i.e. yellow, red, etc.) followed by trial type (i.e. go, no-go, no-go-lure, no-go-constant, no-go-2inrow)._
Can you specify the trial type ?

**Comment by avaidyam** [comment]
@sijugeorge-zco Please review the PPT file attached in the main issue that covers these different trial types. It should provide the info you need. As for the format of the `value` key, it would look something like this: `value: "yellow no-go-lure"`.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
Can you please confirm that our understanding is correct for below:

1. go : If user needed to click either balloon color Pink, Blue Or Yellow and if the balloon displayed is either Pink, Blue Or Yellow
2. no-go : If the user needs to click balloon color (Pink, Blue Or Yellow) and the balloon displayed is Green.
3. no-go-2inrow : if a balloon with same color occurs one after another . for eg: if blue occurs one after another.
4. no-go-lure : Can you please specify this?
5. no-go-constant : Can you please specify this?

**Comment by avaidyam** [comment]
Here is what the PowerPoint slide notes say: 
```
Screen 14: Level 2 of game
-first bubble appears 1 second after previous screen disappears
-bubbles appear on screen as if they are being blown up from infinitely small bubble 
-bubble appears, rests, and disappears in same spot – only variable is length of time before disappearing ( depending on if popped by user or not) and method of disappearing (popping if tapped by user, vs dissolving if not tapped)
-when tapped by user, bubbles will pop and disappear 
-unpopped bubbles will dissolve from screen 

-tuning parameters for bubbles on backend of portal will control : duration of time bubble spends on screen, speed of bubbles entering/exiting, intertrial duration, etc (see later slide for details)

Bubble features:
-bubble diameter should be approximately 0.5 inches for all colors
-bubbles should not overlap on the screen
-bubbles will appear one at a time, but multiple bubbles may exist on the screen simultaneously
-bubble placement on screen should be randomized


Level two specifics: 
-go trials = yellow, blue but NOT two of same color in a row ;  correct response for go trials = tap screen to pop bubble
-no go trials = constant no-go trials + lure trials + two in a row trials;   correct response for no-go trials = do NOT pop bubble 
	-lure trials =pink bubbles
	-two in a row= yellow or blue bubble immediately following bubble of same color (yellow following yellow; blue following blue) 
	-constant no go = any other color besides yellow, blue or pink
-proportion of go trials : no go trials should be 4:1,  in a randomized order 
-80 total bubbles in level 2 ( should be able to edit in tuning parameters)
	-60 go trials
	-6 no go trials
	-7 lure trials
	-7 two-in-a-row trials (for two in a row trials, first instance of blue or yellow bubble is considered go trial, second instance of same color is considered a no-go two in a row trial)
	randomly assigned order and placement on screen

Data collection: 
-for each bubble in the sequence:
	-its number in the sequence
	-type of trial (go vs no-go)
	-type of response (correct, incorrect)
	-reaction time (time between bubble appearing on screen and user tapping to pop bubble) (excluding correctly answered NoGo trials)
-at end of level:
	-percent accuracy (#correctly answered/total)
	-raw number of correctly answered (unpopped) No-Go trials and percentage accuracy
	-raw number of incorrectly answered (popped) No-Go trials and percentage (raw number incorrect/total no-go trials)
	-raw number of correctly answered (popped) Go trials and percentage accuracy
	-raw number of missed (unpopped) Go trials  and percentage (raw number missed/total go trials)
	-number of false hits (hitting screen anywhere other than a bubble)
	-total time taken to complete level
```

Specifically, please follow this guideline: 
```
-go trials = yellow, blue but NOT two of same color in a row ;  correct response for go trials = tap screen to pop bubble
-no go trials = constant no-go trials + lure trials + two in a row trials;   correct response for no-go trials = do NOT pop bubble 
	-lure trials =pink bubbles
	-two in a row= yellow or blue bubble immediately following bubble of same color (yellow following yellow; blue following blue) 
	-constant no go = any other color besides yellow, blue or pink
-proportion of go trials : no go trials should be 4:1,  in a randomized order 
```

**Comment by sarithapillai8** [comment]
@avaidyam 

All these points were not clear from the PPT. From the above explanations, we are almost clear with the details provided. 

1) We we not considering any proportion (4:1) in rendering bubbles. We have to change the implementation. 
 
2) Currently for the no-go trials - we pop the bubbles and mark it as a wrong click. So as you explained, we can change like do not pop the no-go trails. 

3) As a conclusion , the key 'value' of  temporal slices will be stored like : 
- Level 1 will have data only for no-go-constant.
- Level 2 will have data for no-go-2inrow, no-go-lure  and no-go-constant.
- Level 3 will have data for no-go-2inrow and no-go-constant.

4) At the end of level , we are now showing the percentage as score. Do we need to show all these details ? :
-raw number of correctly answered (unpopped) No-Go trials and percentage accuracy
	-raw number of incorrectly answered (popped) No-Go trials and percentage (raw number incorrect/total no-go trials)
	-raw number of correctly answered (popped) Go trials and percentage accuracy
	-raw number of missed (unpopped) Go trials  and percentage (raw number missed/total go trials)
	-number of false hits (hitting screen anywhere other than a bubble)
	-total time taken to complete level

**Comment by avaidyam** [comment]
@sarithapillai8 Just so we are on the same page before I answer your questions, could you revisit both PPT files and **make sure to check all the slide notes as well?** All of this information is in the PPT and for each slide there are corresponding notes.

**Comment by sarithapillai8** [comment]
@avaidyam 
Sorry, we missed this notes. We were only checking the slides.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
Can you please provide details for the below queries ?

1. _At end of level we are now only showing the percentage as score. Do we need to show all these below details under each level ?_
	-raw number of correctly answered (unpopped) No-Go trials and percentage accuracy
	-raw number of incorrectly answered (popped) No-Go trials and percentage (raw number incorrect/total no-go trials)
	-raw number of correctly answered (popped) Go trials and percentage accuracy
	-raw number of missed (unpopped) Go trials and percentage (raw number missed/total go trials)
	-number of false hits (hitting screen anywhere other than a bubble)
	-total time taken to complete level

2.  On Screen 17	
	-no go trials = constant no-go trials + lure trials + two in a row trials;   correct response for no-go trials = do NOT pop bubble 
		-lure trials =pink bubbles
		-two in a row= yellow or blue bubble immediately following bubble of same color (yellow following yellow; blue following blue) 
		-constant no go = any other color besides yellow, blue or pink

	_As per our understanding, no-go trials will be only for success = false conditions
	Can you please explain no-go trials (no go trials = constant no-go trials + lure trials + two in a row trials;   correct response for no-go trials = do NOT pop bubble )?_
	
3. On Screen 17	
	-80 total bubbles in level 2 ( should be able to edit in tuning parameters)
		-60 go trials
		-6 no go trials
		-7 lure trials
		-7 two-in-a-row trials (for two in a row trials, first instance of blue or yellow bubble is considered go trial, second instance of same color is considered a no-go two in a row trial)

	_Since lure trials =pink bubbles, from the above we will be having 7 pink bubbles(please correct me if i'm wrong)
	How do we calculate no-go trials(since it is shown as, no go trials = constant no-go trials + lure trials + two in a row trials;   correct response for no-go trials = do NOT pop bubble), please explain?_

**Comment by avaidyam** [comment]
1. No; all of this data should be possible to access (that is, the raw data must be found here) from `ActivityEvent`s that are created from the game, however. 
2. Unfortunately I do not have the answer here — I will check with our collaborator and get back to you on that. 
3. As above, I do not have the answer for this, so let me ask the collaborator.

**Comment by sijugeorge-zco** [comment]
@avaidyam 

1. Can we store this data on object _static_data_ under ActivityEvent? If yes , can you please specify the format ?
2. Okay. 
3. Okay.

**Comment by avaidyam** [comment]
> **Collaborator:** 
> 1. No, that was more for researcher data collection, the screen at the end of each level should only show the % correct 
> 2. I'm not sure at what part they had a question, but all that info is correct. A no-go trial will be either one of the following for that level (slide 17): 1) pink bubble 2) second blue or yellow bubble in a row or 3) any color other than pink yellow or blue ....and yes a correct response is to not pop that bubble / an incorrect response would be to pop it 
> 3. breakdown should be as follows:
> -80 total bubbles in level 2 ( should be able to edit in tuning parameters)
> -60 go trials 
> -6 constant no-go trials (any color other than pink blue or yellow)
> -7 lure trials (pink bubbles) 
> -7 two-in-a-row trials (for two in a row trials, first instance of blue or yellow bubble is considered go trial, second instance of same color is considered a no-go two in a row trial)

**Comment by sijugeorge-zco** [comment]
@avaidyam 

As per our current implementation on Balloon Risk game , when a balloon is burst we are currently clearing the Total points and Current points . 
Do we need to clear Total points and Current points _OR_ only the Current Points on balloon burst ?

**Comment by avaidyam** [comment]
Only the current points are cleared; total points are maintained.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
What **data** should we show for the Pop the Bubbles game on the Prevent screen graph, since there is no **score** store on _static_data_ for this game. 
For other games we are storing **score** in _static_data_.

**Comment by avaidyam** [comment]
For Balloon Risk use the sum of the temporal slice `value` (total points accumulated), and for Pop The Bubbles, use the sum of the temporal slice `type` where `true` divided by the total length of the temporal slices (% accuracy).

**Comment by sijugeorge-zco** [comment]
Hi @avaidyam , @elenamrv

Please find the strings to be translated(to _Spanish and Hindi_) for the _Balloon Risk Game_ and _Pop The Bubbles game_.


	"Please enter breakpoint standard deviation.": "Please enter breakpoint standard deviation.",
	"Multiple should be comma seperated": "Multiple should be comma seperated(Eg:60,80,80)",
	"Please enter Bubble Count with comma seperated.": "Please enter Bubble Count with comma seperated.",
	"Please enter Bubble Speed with comma seperated.": "Please enter Bubble Speed with comma seperated.",
	"Please enter Intertrial Duration.": "Please enter Intertrial Duration.",
	"Please enter Bubble Duration.": "Please enter Bubble Duration."	
	"BALLOON_RISK": "Balloon Risk",
	"PUMP_UP_BALLOON": "PUMP UP BALLOON",
	"TOTAL_POINTS": "Total Points",
	"CURRENT_POINTS": "Current Points",
	"COLLECT_POINTS": "COLLECT POINTS",
	"BALLOON_BURSTED": "Balloon Bursted",
	"CONGRATULATIONS": "Congratulations",
	"GO": "GO",
	"LEVEL_NUMBER": "Level {{ gameLevel }}",
	"LEVEL_NUM_COMPLETED": "Level {{ levelNumber }} Completed",
	"NUMBER_OF_CORRECTLY_ANSWERED_GO_TRIALS": "{{ correctGoCount }} number of correctly answered (popped) Go trials and {{ percentage }}",
	"NUMBER_OF_CORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ correctGoCount }} number of correctly answered (unpopped) No-Go trials and {{ percentage }}",
	"NUMBER_OF_FALSE_HITS": "{{ falseHitsCount }} number of false hits (hitting screen anywhere other than a bubble)",
	"NUMBER_OF_INCORRECTLY_ANSWERED_GO_TRIALS": "{{ missedClicks }} number of missed (unpopped) Go trials and {{ percentage }}",
	"NUMBER_OF_INCORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ wrongNoGoCount }} number of incorrectly answered (popped) No-Go trials and {{ percentage }}",
	"POP_THE_BUBBLES": "POP THE BUBBLES!",
	"TAP_TO_CONTINUE": "Tap to continue",
	"TAP_TO_POP_LEVEL_1_BUBBLES_BOTTOM":"POPPING CORRECT BALOONS WILL EARN YOU POINTS.",
	"TAP_TO_POP_LEVEL_1_BUBBLES_TOP":"TAP TO POP ALL PINK, BLUE AND YELLOW BUBBLES ONLY.",
	"TAP_TO_POP_LEVEL_2_3_BUBBLES_TOP":"DON’T POP TWO BUBBLES OF THE SAME COLOR IN A ROW.",
	"TAP_TO_POP_LEVEL_2_BUBBLES_BOTTOM":"ONLY POP YELLOW AND BLUE BUBBLES.",
	"TAP_TO_POP_LEVEL_3_BUBBLES_BOTTOM":"ONLY POP PINK YELLOW AND BLUE BUBBLES.",
	"YOU_GOT_PERCENT": "You got {{ percentage }}",

_Note:_
Translation for the above strings should be done for the right side value, not the left side.

**Comment by sarithapillai8** [comment]
@avaidyam 
Please see the PR added on Lamp-activities and Lamp-dashboard repos.

**Comment by elenamrv** [comment]
@sijugeorge-zco I have requested the translation! I will post the Hindi and Spanish versions here as soon as I have them. Thanks!

fyi @avaidyam

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco fyi @avaidyam - please see below for the Hindi translation. Thank you!!

"Please enter breakpoint standard deviation.":"कृपया मानक विचलन मान दर्ज करेंl"
"Multiple should be comma seperated": " एक से अधिक अल्पविरामो (comma) को अलग किया जाना चाहिए (Eg:60,80,80)", 
"Please enter Bubble Count with comma seperated.": "कृपया बुलबुले
की संख्या को अल्पविराम(Comma) के साथ अलग-अलग दर्ज करेंl ",
"Please enter Bubble Speed with comma seperated.": "कृपया बुलबुले
की गति को अल्पविराम(Comma) के साथ अलग-अलग दर्ज करेंl ", 
"Please enter Intertrial Duration.": "कृपया दोनों की बीच की अवधि को दर्ज करेंl", 
"Please enter Bubble Duration.": "कृपया बुलबुले की अवधि दर्ज करें."       
"BALLOON_RISK": "गुब्बारा जोखिम", 
"PUMP_UP_BALLOON": "गुब्बारे में हवा भरो", 
"TOTAL_POINTS": "कुल_अंक", 
"CURRENT_POINTS": "वर्तमान_अंक", 
"COLLECT_POINTS": "इकट्ठा_अंक", 
"BALLOON_BURSTED": "गुब्बारा_फट गए", 
"CONGRATULATIONS": "बधाई हो", 
"GO": "जाओ", 
"LEVEL_NUMBER": " स्तर {{खेल का स्तर}}",
"LEVEL_NUM_COMPLETED": " स्तर {{स्तर की संख्या}} पूरा हुआ ", 
"NUMBER_OF_CORRECTLY_ANSWERED_GO_TRIALS": "{{सहीगणनाकेलिएजाए}} दिए गए सही जवाब (पॉपअप) परीक्षण में जाएं और {{प्रतिशत}}", 
"NUMBER_OF_CORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ सहीगणनाकेलिएजाए }} दिए गए सही जवाब (पॉपअप नही) परीक्षण में नही जाएं और {{प्रतिशत}}", 
"NUMBER_OF_FALSE_HITS": "{{गलतहिटकीगणनाकेलिएजाए}} गलत हिट की संख्या (बुलबुले के छोड़कर अलावा कहीं भी स्क्रीन पर हिट करें)", 
"NUMBER_OF_INCORRECTLY_ANSWERED_GO_TRIALS": "{{क्लिक्समिस्ड्सकिए}} मिस्ड्स क्लिक्स की संख्या (पॉपअप नही) परीक्षण पर जाएं और {{प्रतिशत}}", 
"NUMBER_OF_INCORRECTLY_ANSWERED_NO_GO_TRIALS": "{{गलतकीगणनाकेलिएजाए }} गलत उत्तर की संख्या (पॉपअप) परीक्षण पर नही जाए और {{प्रतिशत}}", 
"POP_THE_BUBBLES": " बुलबुलो_दिखाएँ!", 
"TAP_TO_CONTINUE": " जारी रखने के लिए दबाएं",

"TAP_TO_POP_LEVEL_1_BUBBLES_BOTTOM":" सही गुब्बारे पॉपिंग होने पर आप अंक प्राप्त करेंगे.", 

"TAP_TO_POP_LEVEL_1_BUBBLES_TOP":" सभी पिंक को पॉप करने के लिए दबाएँ, केवल नीले और पीले रंग के बुलबुले l", 
"TAP_TO_POP_LEVEL_2_3_BUBBLES_TOP":" एक ही पंक्ति में समान रंग के दो बुलबुलों को पॉप नही करें ", 
"TAP_TO_POP_LEVEL_2_BUBBLES_BOTTOM":" केवल पीला और नीले रंग के बुलबुलों को पॉप करें l ", 
"TAP_TO_POP_LEVEL_3_BUBBLES_BOTTOM":" केवल गुलाबी, पीला और नीला बुलबुले पॉप करें l", 
"YOU_GOT_PERCENT": " आपको मिला {{प्रतिशत}}",

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - see below for the Spanish translation. Thanks again! fyi @avaidyam 

"Please enter breakpoint standard deviation.": " por favor ingrese la desviación estándar del punto de interrupción.",
"Multiple should be comma seperated": " Varios deben estar separados por comas
 (Eg:60,80,80)",
"Please enter Bubble Count with comma seperated.": " Por favor ingrese Bubble Count con coma separada/o.",
"Please enter Bubble Speed with comma seperated.": " Por favor ingrese Bubble Speed con coma separada/o.",
"Please enter Intertrial Duration.": " Ingrese la duración entre ensayos.",
"Please enter Bubble Duration.": " Ingrese la duración de la burbuja."	
"BALLOON_RISK": "Riesgo de globo",
"PUMP_UP_BALLOON": "Inflar globo",
"TOTAL_POINTS": "Puntos Totales",
"CURRENT_POINTS": "Puntos actuales",
"COLLECT_POINTS": "Acumular puntos",
"BALLOON_BURSTED": " explosión de globo",
"CONGRATULATIONS": " Felicidades",
"GO": "Vamos",
"LEVEL_NUMBER": "Nivel {{ gameLevel }}",
"LEVEL_NUM_COMPLETED": "Nivel {{ levelNumber }} Completado",
"NUMBER_OF_CORRECTLY_ANSWERED_GO_TRIALS": "{{ correctGoCount }} número de ensayos respondidos correctamente(popped) Go ensayos y {{ percentage }}",

"NUMBER_OF_CORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ correctGoCount }} número de ensayos respondidos correctamente (unpopped) No-Go ensayos and {{ percentage}}",

"NUMBER_OF_FALSE_HITS": "{{ falseHitsCount }} número de aciertos falsos (hitting screen anywhere other than a bubble)",
"NUMBER_OF_INCORRECTLY_ANSWERED_GO_TRIALS": "{{ missedClicks }} número de ensayos respondidos incorrectamente(popped) Go ensayos y {{ percentage }}",

"NUMBER_OF_CORRECTLY_ANSWERED_NO_ (unpopped) Go ensayos and {{ percentage }}",
"NUMBER_OF_INCORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ wrongNoGoCount }} número de ensayos respondidos incorrectamente(popped) Go ensayos y {{ percentage }}",

"POP_THE_BUBBLES": "Estallar las burbujas!",
"TAP_TO_CONTINUE": "Toque para continuar",
"TAP_TO_POP_LEVEL_1_BUBBLES_BOTTOM": “toque para hacer estallar las burbujas fondo del nivel 1

"POPPING CORRECT BALOONS WILL EARN YOU POINTS." hacer estallar globos corect te hará ganar puntos”
"TAP_TO_POP_LEVEL_1_BUBBLES_TOP": “toque para hacer estallar las burbujas cima del nivel 1”

"TAP TO POP ALL PINK, BLUE AND YELLOW BUBBLES ONLY."Toca para hacer estallar todas las burbujas rosadas, azules y amarillas solamnte”
"TAP_TO_POP_LEVEL_2_3_BUBBLES_TOP": “toque para hacer estallar las burbujas cima del nivel 2_3”

"DON’T POP TWO BUBBLES OF THE SAME COLOR IN A ROW.", “No reviente dos burbujas del mismo color seguidas”
"TAP_TO_POP_LEVEL_2_BUBBLES_BOTTOM": “toque para hacer estallar burbujas fondo de nivel 2”
"ONLY POP YELLOW AND BLUE BUBBLES.", “solo estallan burbujas amarillas y azules”
"TAP_TO_POP_LEVEL_3_BUBBLES_BOTTOM": “toque para hacer estallar burbujas fondo de nivel 3”
"ONLY POP PINK YELLOW AND BLUE BUBBLES.", “solo estallan burbujas roasas, amarillas y azules”
"YOU_GOT_PERCENT": "Tienes el {{ percentage }}",

**Comment by sijugeorge-zco** [comment]
@elenamrv 
We have updated the translations in our code.
We wil update this all together once we get the new translated strings, which i have created as a new git task 
_( Translation Required https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/138)_

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - I'll work on getting these translations and post each of them as soon as I have them. Thanks! fyi @avaidyam
