### ISSUE TITLE
Support server-wide "unlisted" Tags 

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#450]
Currently, `target = "*"` is not supported. Once implemented, this combination of `origin = null` and `target = *` allows resources to query server-wide Tags.
- These Tags will not appear when `Tag.list()` is called on a resource, unlike Tags set from `origin = SOME_RESEARCHER` to `target = "Participant"` .
- Normally, `Tag.list(null)` should fail unless authenticated as the root/admin user, but this should now be handled as a special case where if the calling credential is not root/admin, Tags with the specific combination of `origin = null` to `target = "*"` shall be returned. 

Tags set as `origin = null` (root/admin) to `target = null` (root/admin) are only visible and modifiable by server administrators (this is the current behavior); in future versions of LAMP, these can henceforth be used for server-level configuration (or overrides) **in addition to** environment variables, but affecting both `LAMP-server`, `LAMP-worker`, and future `LAMP-*` components.

**Comment by ZCOEngineer** [comment]
@avaidyam we are reviewing this, shall post our understanding soon.

**Comment by avaidyam** [comment]
More updates to this `on hold` issue: 
- The implementation of #451 led to a little confusion in #494. 
    - The `target = *` functionality is currently short-circuited by `origin = null && target = me` on the server-side. 
- Better `Tag.list()` functionality now has its own issue and discussion at #498.

**Comment by Linoy339** [comment]
@avaidyam . Can you please review this :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/221](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/221)

**Comment by ZCOEngineer** [comment]
@avaidyam did you get a chance to check the update from @Linoy339

**Comment by avaidyam** [comment]
We are testing this internally. @carlan1 will reply today in this issue and #736 with the results.

**Comment by carlan1** [comment]
Works in staging server.
