### ISSUE TITLE
Support password rules when creating accounts on the dashboard

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#451]
A new Tag `lamp.dashboard.security_preferences` must be set by the system administrator to add support to control certain user account creation settings. Currently, we will support password rules. Example:

```json
{
    "password_rule": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$"
}
```

This Tag **MUST** be set from `origin = null` (root/admin) to `target = "*"` (all resources on the server are able to read it). (This is currently blocked by #450.)

The password rule must be specified as a **valid regular expression** (see example above; [see RegExR to test these](https://regexr.com)). The above expression matches: 
- `^.* ...  .*$` = The entire string must match the expression, and cannot contain line breaks (`\n`).
- `(?=.{8,})` = Minimum of 8 characters.
- `(?=.*[a-z])` = Must contain lowercase letters.
- `(?=.*[A-Z])` = Must contain uppercase letters. 
- `(?=.*[0-9])` = Must contain numeric digits. 

Additional parameters (such as required special characters, etc.) can also be added to the regular expression. 

When setting a password on **any user account across LAMP**, this system-level Tag must be referenced first. 
1. If no such Tag exists, any password of any complexity with any characters is permitted (current behavior).
1. If such a Tag exists, but the `password_rule` is missing or not a valid regular expression, any password of any complexity with any characters is permitted (current behavior).
1. If such a Tag exists, and the `password_rule` is a valid regular expression, the password text field in the UI must validate the text input by the user against the regular expression.
    1. If the text matches the regular expression, the password is accepted and the dialog is allowed to proceed.
    1. If the text does NOT match the regular expression, the password is not accepted, and the dialog (and its continue button) is disabled until the text is modified to match the regular expression. (An error message must be displayed under the text field to inform the user.)

The UI must be updated to visually match this example: 

<img width="343" alt="Screen Shot 2021-12-09 at 4 35 26 PM" src="https://user-images.githubusercontent.com/1361003/145479379-54e722ab-9164-43ef-8f53-cec7dd223366.png">

However, the error text underneath the password field must instead be: `"Password is not complex enough and does not comply with organization password requirement."` The confirm password text field error text should be `"Does not match the password you entered above."`.

**Comment by sarithapillai8** [comment]
@avaidyam 
1. Where do we need to add this option for system admin? Can we just create a new menu item saying '**Manage password rule**' under manage credentials? 
2.Do we need to permit the user admin for managing this new option? 
3. Currently some default password is created while adding a new participant. So do we need to change that based on this password rule? 
4. I hope the screenshot with password attached above refers to be changed in the 'Manage credentials' popup screen. No new UI required, instead just add the validation there. Please correct me if I am wrong.

**Comment by avaidyam** [comment]
1. There is no UI to manage the password rule - that wasn't even part of the original implementation I posted. 
2. No, for now the default password can be the same as patients should change the password later. 
3. Yes, it's the same UI but with added validation text.

**Comment by sarithapillai8** [comment]
This is updated in dashboard-staging. QA confirmed with some sample 'password_rule' tags in api-staging.

**Comment by divyav2020** [comment]
We have updated the build in Dashboard staging

**Comment by avaidyam** [comment]
> QA confirmed with some sample 'password_rule' tags in api-staging.

@sarithapillai8 Can you share how these rules were set? Preferably share the terminal cURL command or Python code.

**Comment by lukeoftheshire** [comment]
@avaidyam Per our slack discussion, here's how things worked around 25 days ago:


Target * does not appear to work, btw
```
rule = {
    "password_rule": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$"
}

LAMP.Type.set_attachment("null",'me','lamp.dashboard.security_preferences',rule)
```
does appear to work however.
1. I could log into the staging api with our OLD staging password, which though complex, does not meet these requirements
2. Could not create a "dumb" credential on dashboard-staging. Created one successfully on dashboard regular
3. I could not edit an existing (dumb) password without making it "smart"
