### ISSUE TITLE
DBT + Misc Bugs

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#453]
Please see below for a list of five new general bugs and DBT diary card related bugs - 

1. When I open the Diary Card or a Tip or Instrument, etc. I see (Dbt diary card) or (Tips) or Breathe, etc. under the title (See screenshots). I did not see this before. This is appearing for all activities - surveys say (Survey).
![2](https://user-images.githubusercontent.com/86117379/145584890-c0fff17d-ff47-4add-9cab-516e1b864ed1.png)
![1](https://user-images.githubusercontent.com/86117379/145584892-2755e3bc-5c64-4620-bbdd-dbe8fdb5cf9d.png)
![3](https://user-images.githubusercontent.com/86117379/145584893-05c0ce38-2183-4907-b86a-bdf14f62c1c6.png)

2. In the Portal tab, the data visualizations are one day off. For example, I selected 11/8-11/14 but it is showing 11/7-11/13. This is showing up the DBT diary card and other visualizations. See below.
![4](https://user-images.githubusercontent.com/86117379/145585178-31c5aa81-3bcb-4dc4-b66d-1d72e5901095.png)

3. Can we move the "Skills used:" visualization right after the "Actions (Timeline)" visualization?
4. For the "Skills used:" visualization, put them above the "Didn't use skills because..." visualization 

5. When I open a diary card and then click the back button, I am still getting a streak notification. See below
![5](https://user-images.githubusercontent.com/86117379/145585619-baa426dc-f9af-42c8-b17d-ee0520f0c155.png)
![6](https://user-images.githubusercontent.com/86117379/145585614-fffccfe2-ce2e-4cf8-b920-a17a56f8d0fc.png)

**Comment by sarithapillai8** [comment]
@SuruPa00 
1 . We added this for the games in assess tab initially to identify which game is going to be started. @avaidyam confirmed to put that in brackets. So while doing the activity tab changes, we added this to identify the type of activity going to be opened in general as there can be mix of different types.  So we can remove if this is not required. 

3. : The skills used section is already after Actions (Timeline). Do you mean anything different?
![image](https://user-images.githubusercontent.com/63710347/145759549-1ea7bcb9-d2ef-4755-a99d-f08da28307c2.png)

We can work on the other fixes.

**Comment by sarithapillai8** [comment]
![image](https://user-images.githubusercontent.com/63710347/145815942-6ca0bbbc-9d39-4fc0-85b2-3d37f44e9ca9.png)
![image](https://user-images.githubusercontent.com/63710347/145815994-f6dbcdaa-7b3e-4122-b822-973a6a16e927.png)
![image](https://user-images.githubusercontent.com/63710347/145816043-54a62950-b966-47dd-b486-303a8b7c47c3.png)

@SuruPa00 
2. Are you testing production or any old instance? I am not able to reproduce the date issue. Could you recheck or give me the participant id to debug.?

**Comment by SuruPa00** [comment]
@sarithapillai8 we are checking on this and will update if the issue is persisting - can you confirm #4 is also fixed? if so, push that to production

**Comment by sarithapillai8** [comment]
@SuruPa00 
#4 and #5 are updated in staging.

**Comment by SuruPa00** [comment]
@sarithapillai8 push these to production asap

**Comment by SuruPa00** [comment]
@sarithapillai8 for #1 please go ahead and remove these in staging

**Comment by SuruPa00** [comment]
@sarithapillai8 for #2, the same issue is happening with user U8550073055 when you look at the daily survey, which has an entry today dec 14th but it is not showing up on the graph

**Comment by sarithapillai8** [comment]
@SuruPa00 
We were checking DBT graphs and we couldn't find issue. In the daily survey graph , I can see the entry with Dec 14. Please see the screenshot. I tried one survey submission today with test account and it is also visible in the graph.  Let me know If I am missing anything.
![image](https://user-images.githubusercontent.com/63710347/146124044-ca4a81c6-cb7b-4224-b226-77522e7c62d2.png)
![image](https://user-images.githubusercontent.com/63710347/146124387-9168c3d4-5cb3-40b2-9c58-4e7f1f2daa2f.png)

**Comment by sarithapillai8** [comment]
Please see the test report attached.
[LAMP_Admin Website_DBT fixes.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7716869/LAMP_Admin.Website_DBT.fixes.xls)

**Comment by SuruPa00** [comment]
@sarithapillai8 This is fine for now, let's keep on hold till further changes are necessary

**Comment by sarithapillai8** [comment]
@avaidyam Could you expect anything from our side for this task? We put 'on hold' as no other changes requested.

**Comment by avaidyam** [comment]
@sarithapillai8 I'll mark this issue as complete now!
