### ISSUE TITLE
Race condition when getting very recently set attachment

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#454]
Calling LAMP.Type.get_attachment on a tag that was recently (<1s) set by LAMP.Type.set_attachment can lead to a race condition where the non-updated tag is returned (i.e., the value previously stored to that key).

See attached screenshot where I set a tag to 'initial', set it to 'second' and quickly call get (returns initial), and then set it to 'third', sleep, and then call get(returns 'third)

<img width="793" alt="Screen Shot 2021-12-14 at 10 28 12 AM" src="https://user-images.githubusercontent.com/34659264/146028398-f2b55006-6739-4eb4-9484-c5ff939f649c.png">

**Comment by lukeoftheshire** [comment]
Upon investigation with @avaidyam - it appears this is due to increased load on our DocumentDB cluster due to a recently added replica DB for an unrelated issue that has since resolved.

Removing this replica DB should resolve the root cause of this issue.

**Comment by avaidyam** [comment]
It looks like the issue can be resolved and the solution is in motion now so let's close the issue. If the solution doesn't work as expected we can reopen and resume discussion here.
