### ISSUE TITLE
Optional Question Default

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#455]
Can it be fixed amongst the platform that studies are by default unchecked for the optional questions? Both studies w researcher id yhe0wtfn6n6sbvsan0js and 4aq1kry81ktrb5v1smvs include many, if not all surveys to entirely composed of optional questions when they are all required. Please see to this asap. Move this to production asap once its done.

**Comment by SuruPa00** [comment]
@ZCOEngineer can we get an update on this?

**Comment by sarithapillai8** [comment]
@SuruPa00 
We don't understand the issue. By default the the survey questions are required. If any surveys are created while we initially updated with default optional questions, those cannot be unchanged. Those need to be manually updated. Any new surveys are with default required option.
