### ISSUE TITLE
"0" entries in Portal tab

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#456]
Responses in the Portal tab are showing up as "0" even when people have numerous entries with completed and varied responses. See U8847026339 and the gratitude journal activities for the pictured example below. This is also occurring for other users, such as U9902494734
<img width="587" alt="Screen Shot 2021-12-20 at 8 37 09 AM" src="https://user-images.githubusercontent.com/86117379/146781396-83e2db41-e7ce-4fe1-94aa-bfd842e62730.png">

**Comment by divyav2020** [comment]
This is updated in staging

**Comment by sarithapillai8** [comment]
The fix is updated in staging.
