### ISSUE TITLE
Activities tab very slow when a Researcher has many studies (~50)

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#46]
It seems like changing tabs always reloads everything, and opening the + Add menu item also reloads everything. When I test on this person's Researcher account I also get a blank list after everything loads, so I have to toggle a study first to re-reload the list and then see all activities.

**Comment by michaelmenon** [comment]
I think we should have all the filters unselected by default and only load the data for the selected filters(study). I also saw that I have to unselect a filter in order to see the data. @sarithapillai8 please check on it, seems like a small fix that can be updated asap.

**Comment by avaidyam** [comment]
No, the expected behavior is everything enabled by default, as it is implemented already. However, it should be caching the data so changing the selected studies should not be making API calls.

**Comment by avaidyam** [comment]
Closing this - let’s move discussion to #16 for this.
