### ISSUE TITLE
Links not working in Tips

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#460]
Participant ```U5344706698``` in researcher ```yhe0wtfn6n6sbvsan0js``` reported that youtube links were not working for the tips Strengths and Behavioral Activation. This was replicated by our team on Chrome as shown below.

<img width="905" alt="Screen Shot 2022-01-05 at 3 20 19 PM" src="https://user-images.githubusercontent.com/82968538/148284761-0e3456ce-00cb-4e23-89d5-ada1f935bc4b.png">

<img width="902" alt="Screen Shot 2022-01-05 at 3 29 03 PM" src="https://user-images.githubusercontent.com/82968538/148284763-c49e7627-a7f8-479e-bda8-7cd7292a922c.png">

**Comment by avaidyam** [comment]
Possible duplicate of #448.
