### ISSUE TITLE
Calendar feature on Feed skipping ahead

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#461]
The calendar feature on the Feed skips ahead to the next week on Sunday, thus showing the activities for the wrong day. User ```U5344706698``` in study ```yhe0wtfn6n6sbvsan0js``` reported this issue from a Samsung Galaxy phone, exact model not known.

![Capture+_2021-12-26-18-48-08](https://user-images.githubusercontent.com/82968538/148286908-e96f9bbd-648b-4ea6-8cd9-8bca443a1470.png)
![Capture+_2021-12-19-12-15-34](https://user-images.githubusercontent.com/82968538/148286910-5d675e97-fb74-470e-9df3-2c84b90cca43.png)
![Capture+_2021-12-12-10-55-50](https://user-images.githubusercontent.com/82968538/148286911-fdc1cb9c-6784-4b8c-baad-af4be5096c98.png)
![Capture+_2021-12-11-14-40-33](https://user-images.githubusercontent.com/82968538/148286917-eb80de95-4347-4fb7-89e2-d18e96d1dabf.png)

**Comment by sarithapillai8** [comment]
@avaidyam 
This is updated in dashboard-staging. QA completed.
