### ISSUE TITLE
TypeError when viewing some user survey data 

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#462]
For at least one user for a collaborator, attempting to view the ActivityCard for their user leads to an error in React. See the attached screenshot. 

![Screen Shot 2022-01-06 at 3 52 35 PM](https://user-images.githubusercontent.com/34659264/148451332-d32f3552-0bf5-4951-b807-a8934c74e6f1.png)

There is already some null checking in the code at the line in question (or rather line 45), but it is a strict equality checker (`t.value !== null`) which ironically has contributed to the issue (I think t.value !=null would not have lead to this bug). Though this bug is occuring in a collaborator's version of LAMP, I can recreate it in our current build on user U7100184772 in my test study by adding an Activity event that has one or more temporal slices with out a 'value' key. E.g.: 
```
new = {'timestamp': 1641502206797,
   'activity': 'e2wxcekbb0typzdtz0pb',
   'static_data': {},
   'temporal_slices': [{'item': 'Question 1',
     'value': '1',
     'type': None,
     'level': None,
     'duration': 2799},
    {'item': 'Question 2',
     'type': None,
     'level': None,
     'duration': 817}],
   'duration': 0}
LAMP.ActivityEvent.create('U7100184772',new)
```
As this was a known bug in previous versions of LAMP (where data could be added to the database missing a value key) this bug will almost certainly affect other users. Fortunately, I think the fix should be simple - simply add `t.value !== undefined` to the if statement in line 45.

**Comment by avaidyam** [comment]
@lukeoftheshire Are there TypeScript compilation rules or ESLint rules we can add to the projects to force mandatory type definitions and disable the use of `any` types?

**Comment by lukeoftheshire** [comment]
> @lukeoftheshire Are there TypeScript compilation rules or ESLint rules we can add to the projects to force mandatory type definitions and disable the use of `any` types?

To be completely honest I hardly a typescript expert, so this is just based off some googleingbut according to https://palantir.github.io/tslint/rules/no-any/ we could add "no-any":true to our linter to disable the use of any. We'd have to do some reviews before implementing this, I assume, to get out all the "any" type declarations already in the codebase.

A cursory review reveals ~26 uses of the <any> tag in the codebase (5 of these are in the data portal so I'll get them out for the next release).

**Comment by sarithapillai8** [comment]
@avaidyam Do you want to remove all any types as part of this ticket? The bug fix is updated in staging.

**Comment by avaidyam** [comment]
@sarithapillai8 Yes, Any types must be removed and every function parameter and return type MUST be strictly typed. @lukeoftheshire and I will determine which linting rules and compiler options to enforce for this.
