### ISSUE TITLE
DBT Diary Card Updates: new questions to be added

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#463]
SCREENSHOTS TO BE ADDED
For the DBT Diary Card, we want to add the following 2 questions:

"Urge to quit therapy"

and "Urge to die by suicide" 

Preceded by a Likert scale as per the rest of the questions, going from 0-5 for intensity.

**Comment by sarithapillai8** [comment]
@avaidyam @tlakhtak Where to add these questions? if these are part of emotions, the questions can be added directly.

**Comment by tlakhtak** [comment]
These questions are to be added as follows, as the flow depends on previous responses to the Did you use any of the skills today? question:

Question 1: 

"Urge to quit therapy"

Response: Intensity, 0-5 (Likert scale)
 
Question 2: 

"Urge to die by suicide"

Response: Intensity, 0-5 (Likert Scale)

Flow 1: If user endorses Yes to: Did you use any of the skills today?

Add questions immediately after question #6 of 7 (Did the skills help?)
[External] Fw: Screenshots from Today's Bugs
Alex Elliott <ASElliott@dmh.lacounty.gov>
Tue 1/11/2022 2:41 PM


Alex Elliott, MSW
Quality, Outcomes, and Training Division
Los Angeles County Department of Mental Health
Mobile: 213.760.1734
From: Alex Elliott <ASElliott@dmh.lacounty.gov>
Sent: Monday, January 10, 2022 2:33 PM
To: Lakhtakia,Tanvi (BIDMC - Torous - Psychiatry) <tlakhtak@bidmc.harvard.edu>
Cc: Ivy Levin <ILevin@dmh.lacounty.gov>; Alexandra King <AKing@dmh.lacounty.gov>
Subject: Re: Screenshots from Today's Bugs
 
Hi Tanvi,
When you open a diary card then click the back arrow, without completing a diary card entry, the number of entries for the diary card increases by 1.
It should only increase when a client completes a diary card entry



Please add the following questions to the DBT diary card in the order listed below.
The placement of the questions is dependent on the clients response to the Did you use any of the skills today? question:

1.     Urge to quit therapy-  

1a. intensity 0-5 

 

2.     Urge to die by suicide-  

2a. intensity 0-5 


Flow 1: If client endorses Yes to: Did you use any of the skills today?
Add questions immediately after question #6 of 7 (Did the skills help?)



Flow 2: If client endorses No to: Did you use any of the skills today?
Add questions immediately after question #4 of 5 (Why didn't you use any skills?)



Best,
![image](https://user-images.githubusercontent.com/82968538/149018675-55721071-2691-4adb-9517-8fbb29a343cb.png)


Flow 2: If client endorses No to: Did you use any of the skills today?

Add questions immediately after question #4 of 5 (Why didn't you use any skills?)

![image](https://user-images.githubusercontent.com/82968538/149018712-7bf81e39-c996-4057-9d12-1e8479465ef8.png)

**Comment by sarithapillai8** [comment]
@avaidyam 
Can we save these 2 answers are with keys in static_data : urgeToQuitTheray and urgeForSuicide like we save notes?

**Comment by avaidyam** [comment]
Yes, that should work.

**Comment by sarithapillai8** [comment]
@avaidyam Could you please add project to this issue - I am not able to change the status.

**Comment by avaidyam** [comment]
@sarithapillai8 Please add the labels to the issue instead going forward.

**Comment by sarithapillai8** [comment]
@avaidyam 
Please clarify :  any updates to master branch of LAMP-activities will update the production?

**Comment by avaidyam** [comment]
Master branch updates staging. Only once I create the GitHub release will it affect production.

**Comment by sarithapillai8** [comment]
@avaidyam 
The build files are not getting updated because of warnings like react-hooks/exhaustive-deps.
Locally I am able to build the files. Could you please have a look? I have handled other significant warnings in code.

 src/containers/patient/index.js
  Line 84:8:  React Hook useEffect has a missing dependency: 'i18n'. Either include it or remove the dependency array                       react-hooks/exhaustive-deps
  Line 96:8:  React Hook useEffect has missing dependencies: 'props.report' and 'time'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

**Comment by sarithapillai8** [comment]
@tlakhtak 
Could you suggest some page titles for these questions  like the 'skills' marked in sttachment? 
![Screenshot 2022-01-13 170931](https://user-images.githubusercontent.com/63710347/149323826-fbd6188e-199f-4193-9019-4cebcc447be1.png)
?

**Comment by avaidyam** [comment]
> The build files are not getting updated because of warnings like react-hooks/exhaustive-deps.
Locally I am able to build the files.

How are you able to build it locally if the CI build fails? This shouldn't be possible unless you're disabling the linter. If you're using `useEffect(..., [])` then temporarily do this instead: 

```typescript
useEffect(() => {
   // code

   // eslint-disable-next-line react-hooks/exhaustive-deps
}, []) 
```

**Comment by sarithapillai8** [comment]
@avaidyam @michaelmenon @tlakhtak The changes are updated in dashboard-staging. QA started testing on dashboard staging.

**Comment by sarithapillai8** [comment]
@avaidyam 
Staging build with LAMP-activities is ready to be deployed. QA done with #471 also.
