### ISSUE TITLE
Scratch card not working

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#464]
For patients server sangath.psych.digital, the scratch card does not seem to work and instead renders loading screen. This was observed on Google Chrome, with test user U1088609897. Phone users on iPhone and Android also report the same issue, causing them to force quit the app.

**Comment by sarithapillai8** [comment]
@avaidyam LAMP-activities were not updated. I have updated 'latest' tag for activities repo and now it seems working.

**Comment by avaidyam** [comment]
@sarithapillai8 Please immediately change the URLs in the dashboard code to point ONLY to the generated GitHub Pages output. You are not to make any manual releases or override the latest tag in any way.

**Comment by sarithapillai8** [comment]
@avaidyam @michaelmenon 
I was re-tagging the dist branch with 'latest' for the last few months as we discussed before. You suggested in an old ticket to use different URLs in this way for staging and production and we updated it like you suggested and I also shared the code we used with you at that time. Initially it was same for staging and production, and we didn't have a way to test in staging.
After updating master branch, dist branch files gets updated automatically, but no tag was created through that process. So it was like we edit 'latest' tag of the recent release to the date it released and re-tag dist branch with 'latest' tag for production. We used and env variable for this. 

let activityURL = "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/"
activityURL += process.env.REACT_APP_GIT_SHA === "dev" ? "dist/out" : "latest/out"  

If this process has changed, let us know.
Thanks.

**Comment by sarithapillai8** [comment]
@avaidyam 
The latest release in LAMP-activities was noticed was on Dec 3rd with slider updated for surveys by Suraj. That is why I did manual release today.

**Comment by avaidyam** [comment]
@sarithapillai8 
1. [When I look at the `latest` tag, I see numerous commits](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commits/latest) titled `Add files via upload`. **You cannot be modifying the build output.** This leads to serious integrity issues with the code and trust in our build process by collaborators that use our platform. 
2. Please do not manually tag `latest` - [it is auto-generated and tagged by the build pipeline](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/5c2a2b944abe0d973405e7d53f663fc92ea6c78c/.github/workflows/release.yml#L14).
3. The build pipeline is only started once the GitHub Release is created with a date like `2022.1.10` - so you should not be changing this date or creating a new release with the same date. 
4. We cannot use `https://raw.githubusercontent.com/*` URLs anymore as they are rate-limited and require authentication to bump the limit from 60 requests per hour to 5000 per hour. Use the GitHub Pages URLs only.
5. [The latest release was created by me yesterday.](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/releases/tag/2022.1.10) Please do not create any GitHub Releases on any of the LAMP repos going forward: I am required to handle this process.

**Comment by avaidyam** [comment]
As this issue is resolved, this discussion should be continued in #467.
