### ISSUE TITLE
Crash when submitting survey

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#469]
A user (U9952522913) reports crashes upon attempting to submit two different surveys in the last day.

![IMG_8612](https://user-images.githubusercontent.com/34659264/149153396-aa1850eb-adc0-42a5-85ea-1cca97fc183c.PNG)

Based on the code at this location, it looks like a "SubmitSurvey" function is not being correctly supplied, or that whatever is supplied is not a function.

This is a significant bug as it is actively inhibiting data collection.

**Comment by avaidyam** [comment]
It looks like `submitSurvey` is provided to `ActivityPage` by `Feed` or `ActivityPopup` which also gets it from another higher component in the component tree. Everything looks strictly typed to require a non-null `Function`, so I'm unsure how the TypeScript compiler is missing this.

**Comment by sarithapillai8** [comment]
@avaidyam This is already fixed and updated in dashboard-staging.
