### ISSUE TITLE
DBT New Questions Visualization

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#470]
This is how LAC would like the new questions to be visualized in the Urges (ineffective) plot.
![image](https://user-images.githubusercontent.com/82968538/149196391-b935e129-d289-40df-b9bf-561dbd7885d7.png)

As an alternative to how we're planning on adding the questions into the survey now, in case it's easier to implement, they would also be okay with the questions being placed within the Target Behaviours section of the Diary Card:

![image](https://user-images.githubusercontent.com/82968538/149196549-211b6037-19f4-4fea-bd74-191ab1206740.png)

**Comment by avaidyam** [comment]
Depends on #463 and #466 being completed.

**Comment by sarithapillai8** [comment]
@tlakhtak We already developed like sperate questions as explained in #463 . I hope we don't need to change that.

**Comment by sarithapillai8** [comment]
@avaidyam @michaelmenon @tlakhtak The changes are updated in dashboard-staging. QA started testing on dashboard staging.
