### ISSUE TITLE
Portal: Activity filter resetting after page refresh

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#472]
The Activity filter is not working properly. When I select the DBT Diary Card and then click done. The filter works and only shows the tile for the DBT Diary Card (see screenshot)
![image](https://user-images.githubusercontent.com/82968538/149563607-1a0b080d-4b11-4f56-833d-87b42651aab2.png)
However, when I leave the Portal Section, go to another section and then comeback to the Portal Section, all of the tiles show up again.  It forgets the filters I entered earlier. I should only see the DBT Card.
![image](https://user-images.githubusercontent.com/82968538/149563649-10c7fcea-411e-4b0b-b9aa-91025e8282cf.png)

**Comment by sarithapillai8** [comment]
This implementation was changed and expecting not to save the filter as requested in the task - https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/419.

**Comment by avaidyam** [comment]
@sarithapillai8 Absolutely correct - the current implementation is working as expected, so I am closing the issue.
