### ISSUE TITLE
Demo account (clinician) not accessible

### ISSUE THREAD

**Issue by changchunlei** [BIDMCDigitalPsychiatry/LAMP-platform#474]
**Describe the bug**
Demo account (clinician) not accessible on iphone/andriod/desktop, the page is in loading mode forever.

**To Reproduce**
1. open login page: eg: https://dashboard.lamp.digital/
2. click “try it” → “clinician”

**Expected behavior**
to load and view the demo account page.

**Screenshots**
![image](https://user-images.githubusercontent.com/3335476/149846948-a948ec8b-9942-44a0-a5b7-24bf86ff62e3.png)

**all devices**
 - OS: windows 10; iphone app; andriod app;
 - chrome and app
 - Version v1662 2022.1.10

**Comment by sarithapillai8** [comment]
@tlakhtak 
This issue could not be reproduced. Could you please recheck?

**Comment by changchunlei** [comment]
Thanks, it is working now.
