### ISSUE TITLE
Version update question

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#481]
Hi,

Currently we are referring ` image: bidmcdigitalpsychiatry/lamp-server:2021`  in the yml. 

Do I need to update to `image: bidmcdigitalpsychiatry/lamp-server:2022` ? If update to 2022, do we have most recent open api document to refer.

I believe currently I am referring [openapi_modified_akana.json.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6452430/openapi_modified_akana.json.txt).

Please let me know. Thanks!

**Comment by avaidyam** [comment]
@jeydude That's correct - the OpenAPI document should not have changed. Please make sure you're [subscribed to the consortium forum](https://mindlamp.discourse.group) for updates!
