### ISSUE TITLE
Implement some sort of automatic survey scoring in LAMP

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#483]
Currently, LAMP surveys are not automatically (or indeed at all) scored. Instead, to score a survey, data must be extracted using the API and then scored in another location using Python, R or another analysis language.

This is a *large* timesink during data analysis - because a rather minimal amount of information is stored in each ActivityEvent, there is no one reliable way to score a survey. Currently, all methods employed even by the Digital Psychiatry team use lots of hardcoding and - because of how data and activities are stored in LAMP, are not (and indeed cannot be) robust against things like changes in question titles, or answers.  Small changes to typos in question titles or answers can lead to delays or unnecessary hunts for non-existent bugs.

While implementing a scoring method for all questions is a bit complicated (what does it mean to score a free-response question?), questions like multiple-choice, list,  and slider questions can be  easily scored. If we could implement/mandate a basic scoring protocol that runs at the end of each survey and is stored in static data,perhaps, it would be of great usefulness to our team and other collaborators.

**Comment by avaidyam** [comment]
> If we could implement/mandate a basic scoring protocol that runs at the end of each survey and is stored in static data

See issue #266 - let's merge this feature idea into that.
