### ISSUE TITLE
Pop the bubbles: partial bubbles displayed at the edges of the screen 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#486]
Bubbles in the Pop the Bubbles game should fit within the boundaries of the screen, but bubbles are displaying at the edge of the screen and are partially cut off. The game does not seem to fit the expected resolution. 
![IMG_2147](https://user-images.githubusercontent.com/82968538/151208983-760c1aab-39ee-45fc-bbf4-4de66468a3c7.PNG)

![IMG_2146](https://user-images.githubusercontent.com/82968538/151208986-10dcb043-e558-4c40-8b21-5eedaa1fb764.PNG)

**Comment by jijopulikkottil** [comment]
@tlakhtak  Hope the screenshot is from iOS device.
There were some issue with height constraint, and it is fixed now. The latest iOS build is available on test flight version [2022.1.13 (307)](https://testflight.apple.com/join/TSpdLc6U)

We still have some related pending issues discussing here https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/301#issuecomment-1049010014

**Comment by divyav2020** [comment]
This issue has been fixed in the latest iOS build is available on test flight version [2022.1.13 (307)](https://testflight.apple.com/join/TSpdLc6U)

**Comment by tlakhtak** [comment]
See #551 for new error with Pop the Bubbles
