### ISSUE TITLE
App requiring log-in every time

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#490]
User U1456972679 (email: U1456972679@lamp.com, pass: U1456972679) has to re-log in to the app everytime they open it to respond to notifications, as opposed to being persistently logged in as they should be. This issue has been happening since Jan 27, which is when the account was made, and continues today, Feb 1. The device being used is an iPhone XR.

**Comment by avaidyam** [comment]
Duplicate/variant of #323. @tlakhtak Can you share this info in that issue as well?

**Comment by Linoy339** [comment]
@tlakhtak 
Just to confirm: Is it happening every time when tapping  notification?

**Comment by tlakhtak** [comment]
If the user clicks on a notification it stays logged in. If the user goes to the app directly it makes them log in.

**Comment by Linoy339** [comment]
Thanks @tlakhtak
