### ISSUE TITLE
Dashboard slow downs for specific research study

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#491]
We are experiencing slow downs in the study TECC Lite (Erica), ID 'yhe0wtfn6n6sbvsan0js'. This was observed on Chrome using Macbook Air, for admin user, and persisted across log ins from other devices of the same kind and on the same browser.

**Comment by MattMatt27** [comment]
TECC Lite is complete. Performance issues with dashboard addressed in more recent issues.
