### ISSUE TITLE
Individual survey response view in Portal not displaying on mobile and Chrome

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#493]
For user U7465003834 in study '4aq1kry81ktrb5v1smvs', the Switch view button does not render a visualization of individual survey questions and responses. Button can be 'clicked' but no change from the default view of a line plot showing summary of total scores over time. The first two image below shows what can be displayed

![Image from iOS](https://user-images.githubusercontent.com/82968538/152353923-b1c24da1-41f1-4460-b091-c46fd6e439a4.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/82968538/152353891-472a511d-eb84-4f54-bce2-d1a9ed0c5a7a.png)

And this is what the expected output for a typical user should be when clicking the switch views button:
<img width="535" alt="Screen Shot 2022-02-03 at 8 48 02 AM" src="https://user-images.githubusercontent.com/82968538/152355597-7ce9c225-bc82-4226-bb88-39324246deb0.png">
<img width="602" alt="Screen Shot 2022-02-03 at 8 47 56 AM" src="https://user-images.githubusercontent.com/82968538/152355592-5c13117f-56c9-47f2-9b42-5bc7678a8821.png">

**Comment by divyav2020** [comment]
We are unable to reproduce this issue. So request you to provide us with the user credentials that produce the issue when you tested.
