### ISSUE TITLE
Unable to set password requirement rules

### ISSUE THREAD

**Issue by liningpan** [BIDMCDigitalPsychiatry/LAMP-platform#494]
**Describe the bug**
I’m trying to set password requirement rules, based on the instructions in issue #451 [and the API playground.](https://docs.lamp.digital/api/set-a-tag-for-a-researcher-study-participant-activity-or-sensor-or-its-childen/)

**To Reproduce**
When I used this curl command to set the password requirement,
```
curl -u admin -L -X PUT 'https://<our mindlamp server>/type/null/tag/lamp.dashboard.security_preferences/*' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
--data-raw '{
    "password_rule": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$"
}'
```

the response I got was always
```
{
  "data": {}
}
```

When I tried to get the tag, it said 404.object-not-found.

**Additional context**
lamp-server container version: 2022.1.10 with digest `sha256:efdd6335dea6948a942c6ae63debf590bad024c43ced0cf3efd49fd4079dbc8d`

**Comment by avaidyam** [comment]
@liningpan [From new discussion](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/451#issuecomment-1030306278) in #451, it looks like you may need to change the `*` to `me` and test if that works.

**Comment by liningpan** [comment]
@avaidyam Thanks! Changing it to `me` worked!

**Comment by avaidyam** [comment]
Fantastic, thanks for the update!
