### ISSUE TITLE
Dashboard incorrect credentials error and loading error

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#499]
We've been having trouble logging into the dashboard for the past few days as researcher. It shows invalid login credentials even though the credentials are entered correctly. This only seems to be happening on Mac Big Sur and Windows 11. It's logging in fine with Windows 10. Server: api.mindlamp-nimhans.com.

Also, we need to refresh the dashboard multiple times to see the last time the users have been active. Most of the times it's greyed out saying Last Active and Last Passive as Never. 

Our priority is to get the dashboard login issue resolved at the earliest so that we can keep track of the usage of the app. Please let me know if you have faced a similar issue with the OS mentioned above.

**Comment by avaidyam** [comment]
It seems like this actually isn't an issue with LAMP, but rather the server infrastructure itself for `api.mindlamp-nimhans.com`. [This might be related to the forum post @lukeoftheshire authored about the issue](https://mindlamp.discourse.group/t/traefik-letsencryp-ssl-certificate-revocation-jan-2022/522/1), if the collaborator is using `Traefik` and `LetsEncrypt` (which we can confirm in the SSL Certificate Details is being used). **Please alert the collaborator's IT department/support contact to review the procedures outlined in the post liked above.**

| Safari Error | SSL Certificate Details |
|-|-|
| <img width="689" alt="Screen Shot 2022-02-04 at 1 32 01 PM" src="https://user-images.githubusercontent.com/1361003/152583745-d63c829b-90bb-48e6-bd5b-cc238bcc9a1c.png"> | <img width="473" alt="Screen Shot 2022-02-04 at 1 32 16 PM" src="https://user-images.githubusercontent.com/1361003/152583782-e36626e6-a8d6-4164-aef8-273b39b8c86e.png"> |
