### ISSUE TITLE
App Gateway crashes

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#50]
Making a separate issue outside of the push notifications/automations engine issue so we can track it and resolve it quicker. 

@Linoy339 mentioned that occasionally there's an error when sending a notification payload to the App Gateway:
```
url: 'https://app-gateway.lamp.digital/push',
status: 502,
statusText: 'Bad Gateway',
headers: Headers { [Symbol(map)]: [Object: null prototype] },
counter: 0
```

The App Gateway crashes and restarts automatically with this error:
```
undefined:1
<HTML>
^
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ClientHttp2Stream.request.on (/usr/src/app/app.js:91:24)
    at ClientHttp2Stream.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

So it seems like the payload being sent causes Google/FCM to return some invalid JSON or some kind of HTML instead despite an `HTTP 200 OK` response code. [The line of code is linked here. ](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/7b1d8a24653f4f14aa3e04a18140d187ced51d89/app.js#L91) 

Can you investigate, @Linoy339? At the very least we should gracefully catch this error and return it to the client correctly.

**Comment by Linoy339** [comment]
As we know that the android notifications are not working, shall we comment the android notification part from Lamp server, so that IOS notification won't get affected?

**Comment by avaidyam** [comment]
The app gateway simply restarts upon failure right now so there is no issue. Furthermore it seems like this issue is only for the Android staging build. Let’s investigate the error being returned from Google’s FCM gateway and see what that is first, and perhaps that will give us a clue as to why it’s not working correctly.

**Comment by michaelmenon** [comment]
It seems to me the payload structure while sending the Android notification is not correct. @Linoy339 can we please check

**Comment by Linoy339** [comment]
@avaidyam I have proposed some changes in app-gateway for not getting crashed. Could you please check the pull request created and deploy, ?

**Comment by Linoy339** [comment]
Also, we were able to get notifications in local with the server key which Amal gave. But the json payload to the android device from FCM seems to be broken or not in proper json format:

{expiry=3600000, actions=[{"name":"Open App","page":"dashboard.lamp.digital"}], page=https://dashboard-staging.lamp.digital/#/participant/U1155520779/activity/xx9tx0rg2by5r45jja46, title=ainSurvey --2, notificationId=101, message=You have a mindLAMP activity waiting for you: ainSurvey 2}
This is not a valid json, so that navigation won't work.

**Comment by avaidyam** [comment]
@Linoy339 @amaljofyzco **[This is the expected behavior, please read the Google documentation.](https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages)** You should convert this object in the `LAMP-core-android` code to a `Map<String, Object>` to work with it like a JSON payload.
