### ISSUE TITLE
Integrate Telephony sensor in Android

### ISSUE THREAD

**Issue by saranya-sajeev** [BIDMCDigitalPsychiatry/LAMP-platform#508]

**Comment by saranya-sajeev** [comment]
@avaidyam Development is completed and given for QA testing.

**Comment by avaidyam** [comment]
@jijopulikkottil Can you share what the `lamp.telephony` sensor data looks like on iOS? @saranya-sajeev Can you share what the data looks like on Android? It **MUST** be identical or I will reject the staging releases for both iOS and Android.

**Comment by jijopulikkottil** [comment]
@avaidyam 
In iOS, it is:
```
{
            "sensor": "lamp.telephony",
            "data": {
                "type": "outgoing",
                "duration": 28,
                "trace": "AA54B3A8-6256-41F1-BE9B-369C8FDD0733"
            },
            "timestamp": 1645626155496
}
```

In Android, it is:
```
{
            "sensor": "lamp.telephony",
            "data": {
                "type": "outgoing",
                "duration": 28
            },
            "timestamp": 1645626155496
}
```

As android doesn't have 'trace' and If we are not using it, we can remove it from the iOS to make the data identical.

**Comment by ZCOEngineer** [comment]
Development for this in Android is complete, QA to start today.

**Comment by avaidyam** [comment]
> As android doesn't have 'trace' and If we are not using it, we can remove it from the iOS to make the data identical.

For Android, please include the `trace` parameter but it should always be set to `null`.

**Comment by saranya-sajeev** [comment]
@avaidyam Qa testing is completed and pushed to beta.

**Comment by avaidyam** [comment]
@saranya-sajeev Thanks - if the CI/CD pipeline is fixed for production release, we'll handle that today or Monday morning. 

@jijopulikkottil Did you end up removing the `trace` parameter from iOS?

**Comment by jijopulikkottil** [comment]
@avaidyam Yes, removed `trace`, but not pushed.

**Comment by dcurrey88** [comment]
This does not appear to be working in staging. I'm not sure if there are phone permissions that prevent call / text data from being collected from certain phones, but both test users U5053982269 (iOS) and U9848191154 (Android) do not appear to be collecting any data.

**Comment by ZCOEngineer** [comment]
We shall check this and update the status here

**Comment by jijopulikkottil** [comment]
let us investigate it.

**Comment by jijopulikkottil** [comment]
@dcurrey88 
1. When we check iOS user, https://api-staging.lamp.digital/participant/U5053982269/sensor_event, there is 'GPS disabled'  analytics and we couldn't find the push device-token. 
Also we logged in using U5053982269, and it is collecting data from device.

2. We are seeing sensor data from April 12 to April 15 for the android user U9848191154
https://api-staging.lamp.digital/participant/U9848191154/sensor_event

**Comment by jijopulikkottil** [comment]
We are getting lamp.telephony data, we will login using the same above userid and can check.

**Comment by lugray1** [comment]
This seems to be fixed in staging! 🎉
