### ISSUE TITLE
Prevent Data Visualizations

### ISSUE THREAD

**Issue by ryan-hays** [BIDMCDigitalPsychiatry/LAMP-platform#51]
Prevent Visualizations

Data visualizations on the LAMP prevent page are JSON Vega objects. They are regenerated each day for each person via a CRON job to include new user data. Once generated, they are saved as LAMP attachments (under the “LAMP.dashboard.experimental.*” spec).

For all visualizations:
* Dynamically size the objects so that they have optimal height, width, and padding in their container
* Bars/points are correctly aligned with their respective x-axis tick
* “Date” tick markers on the x-axis are readable, consistent, and easily-understood for a given graph (for example, currently on some graphs one marker will be “Sat 23” while another will be “June 10, 2020”)
* Allow users to dynamically select a range of dates on a graph to view

For specific visualizations:

    * Activity Segmentation (“lamp.dashboard.experimental.activity_segmentation”)
        * Bar width is optimized so that there is some white space between each one
        * Color gradient between the stacked bars (as opposed to a discrete border)
        * Marker legend is sized so that it is not cut-off due to padding
    * Sensor Data Quality (“lamp.dashboard.experimental.sensor_data_quality”)
        * For individuals with high density sensor data, there are too many sensor readings (>10^4) to plot without blowing up the image size. Currently in these cases, the points are being downsampled by picking a random 50,000-point sample of them. A better method would be to bin sensor readings into consistent time frames (say 1 per 10 seconds) and plot one point for each frame
        * Different color for each sensor

**Comment by ryan-hays** [comment]
Here is the code for the activity segmentation and sensor data quality graphs, respectively. 

activity_segmentation.py

`
import LAMP
import pandas as pd
import altair as alt
import datetime
import numpy as np
import math 
from functools import reduce
import os

def activitySegmentationAll():
    researchers = [res['id'] for res in LAMP.Researcher.all()['data']]
    studies = reduce(lambda x, y: x + [study['id'] for study in LAMP.Study.all_by_researcher(y)['data']], 
                     researchers[1:], 
                     [study['id'] for study in LAMP.Study.all_by_researcher(researchers[0])['data']])

    participants = reduce(lambda x, y: x + [part['id'] for part in LAMP.Participant.all_by_study(y)['data']], 
                     studies[1:], 
                     [part['id'] for part in LAMP.Participant.all_by_study(studies[0])['data']])

    log_data = []
    for participant in participants:
        try:
            #Get sensor data; first lamp.accelerometer; if not, beiwe.accelerometer
            accel_sensor = "lamp.accelerometer"
            sensor_data = sensor_results(participant, "lamp.accelerometer")
            if "lamp.accelerometer" not in sensor_data:
                accel_sensor = "beiwe.accelerometer"
                sensor_data = sensor_results(participant, accel_sensor)
                if 'beiwe.accelerometer' not in sensor_data:
                    accel_sensor = None

            #Create activity dataframe; graph it; set as attachment
            participantActivityDf = create_df(sensor_data)
            partChart = activitySegmentationBarChart(participantActivityDf)
            chart_dict = partChart.to_dict()

            LAMP.Type.set_attachment(participant, "me", 
                                    attachment_key="lamp.dashboard.experimental.activity_segmentation", 
                                    body=chart_dict)

            #Log results for participant
            # Columns of ['id', 'sensor', 'day_fist', 'day_last', 'days_elapsed', 'is_notnull']
            if accel_sensor is None:
                log_data.append([participant, accel_sensor, np.nan, np.nan, np.nan, False])
            
            else:
                day_first = datetime.datetime.utcfromtimestamp(sorted([sensor_data[dom][0][0]/1000 for dom in sensor_data])[0])
                day_last = datetime.datetime.utcfromtimestamp(sorted([sensor_data[dom][-1][0]/1000 for dom in sensor_data])[-1])
                days_elapsed = (day_last - day_first).days 
                if participantActivityDf is None:
                    is_notnull = True
                else:
                    is_notnull = False
                log_data.append([participant, accel_sensor, day_first, day_last, days_elapsed, is_notnull])


        except Exception as e:
            continue
    
    #Output log file
    log_today_date = datetime.date.today().strftime('%Y-%m-%d')
    logDf = pd.DataFrame(log_data, columns=['id', 'sensor', 'day_fist', 'day_last', 'days_elapsed', 'is_notnull'])
    logDf.to_csv("/data/LAMP_Development/Visualization_Logs/ActivitySegmentation/"+ ".".join([log_today_date, 'csv']))

###### Df creation helper 
def create_df(sensors):
    """
    Create activity segmentation df; return sensor that was used to create it
    """
    if "lamp.accelerometer" not in sensors and "beiwe.accelerometer" not in sensors:
        return None

    #Find the first, last date
    day_first = datetime.datetime.utcfromtimestamp(sorted([sensors[dom][0][0]/1000 for dom in sensors])[0])
    day_last = datetime.datetime.utcfromtimestamp(sorted([sensors[dom][-1][0]/1000 for dom in sensors])[-1])
    days_elapsed = (day_last - day_first).days 
    
    if days_elapsed == 0:
        return None

    #Create based on resolution
    date_list = [day_first + (datetime.timedelta(days=1) * x) for x in range(0, math.ceil(days_elapsed))]

    accelDf = activities(sensors, date_list, list(sensors.keys())[0])

    return accelDf

def sensor_results(participant, sensor):
    """
    Get dictionary of sensor data
    """

    def get_sensor_events(sensor_events, subj, origin, to=None):
        """
        Recursively get sensor events
        
        results: list containing all sensor event results up to that point
        """
        if to is None:results = sorted(LAMP.SensorEvent.all_by_participant(subj, origin=origin)['data'], key=lambda x: x['timestamp'])
        else: results = sorted(LAMP.SensorEvent.all_by_participant(subj, origin=origin, to=to)['data'], key=lambda x: x['timestamp'])
            
        sensor_events += results
        if len(results) < 1000 or len(sensor_events) > 90000: #done
            return sensor_events

        new_to = results[0]['timestamp']
        
        return get_sensor_events(sensor_events, subj, origin, to=new_to)

    participant_sensors = {}
    s_results = sorted([(res['timestamp'], res['data']) for res in get_sensor_events([], participant, origin=sensor)], key=lambda x: x[0])

    if len(s_results) > 0:
        participant_sensors[sensor] = s_results

    return participant_sensors

##### Get activity segmentation
def get_optimal_inactivity(df, length=8):
    #Find maximum bout of inactivity
    times = [(datetime.time(hour=h, minute=m).strftime("%H:%M"), (datetime.datetime.combine(datetime.date.today(), datetime.time(hour=h, minute=m)) + datetime.timedelta(hours=8, minutes=0)).strftime("%H:%M")) for h in range(18, 24)  for m in [0, 30] ] + [(datetime.time(hour=h, minute=m).strftime("%H:%M"), (datetime.datetime.combine(datetime.date.today(), datetime.time(hour=h, minute=m)) + datetime.timedelta(hours=8, minutes=0)).strftime("%H:%M")) for h in range(0, 4) for m in [0, 30] ]
    mean_activity = float('inf')
    for t0, t1 in times:
        if "18:00" <= t0 <= "23:00":
            selection = pd.concat([df.loc[datetime.datetime.strptime(t0, "%H:%M").time() <= df['Time'], :], df.loc[df['Time'] <= datetime.datetime.strptime(t1, "%H:%M").time(), :]])
        else:
            selection = df.loc[(datetime.datetime.strptime(t0, "%H:%M").time() <= df['Time']) & (df['Time'] <= datetime.datetime.strptime(t1, "%H:%M").time()), :]

        sel_act = selection['magnitude'].abs().mean()

        if sel_act < mean_activity:
            mean_activity = sel_act
            period = (t0, t1, sel_act)
         
    if mean_activity == float('inf'):
        return None
    return period


def sleep_time_mean(sensor_data, dates, accelDf):
    """
    Return mean expected bed and wake time
    """
    #accelDf = convert_to_df(sensor_data)
    bed_raw, wake_raw, _ = get_optimal_inactivity(accelDf)
    bed, wake = pd.to_datetime(bed_raw, format= '%H:%M' ).time(), pd.to_datetime(wake_raw, format= '%H:%M' ).time()
    return bed, wake

def activities(sensor_data, dates, sensor):
    """
    Get percentage of sleep, active, and sedentary for the patient
    """
    TIME = dates[0].time()
    accelDf = convert_to_df(sensor_data, sensor)
    bed_time, wake_time = sleep_time_mean(sensor_data, dates, accelDf)

    #Get mean accel readings of 10min bins for participant
    times, magnitudes = [], []
    accelDf.loc[:, 'Time'] = pd.to_datetime(accelDf["Time"].astype(str))
    for s, t in accelDf.groupby(pd.Grouper(key='Time', freq='10min')):
        times.append(s.time())
        magnitudes.append(t['magnitude'].abs().mean())

    df10min = pd.DataFrame({'Time':times, 'Magnitude':magnitudes}).sort_values(by='Time')
    
    #Calculate sleep
    sleepStart, sleepStartFlex = bed_time, (datetime.datetime.combine(datetime.date.today(), bed_time) - datetime.timedelta(hours=2)).time()
    sleepEnd, sleepEndFlex = wake_time, (datetime.datetime.combine(datetime.date.today(), wake_time) + datetime.timedelta(hours=2)).time() 

    #We need to shift times so that the day begins a midnight (and thus is on the same day) sleep start flex begins on 
    accelDf.loc[:, "Shifted Time"] = pd.to_datetime(accelDf['UTC time']) - (datetime.datetime.combine(datetime.date.min, sleepEndFlex) - datetime.datetime.min)

    daily_activity_data = []
    accelDf.loc[:, "Shifted Day"] = pd.to_datetime(accelDf['Shifted Time']).dt.date 

    for day, df in accelDf.groupby('Shifted Day'):
        
        #Keep track of how many 10min blocks are 1. inactive during "active" periods; or 2. active during "inactive periods"
        night_activity_count, night_inactivity_count, day_inactivity_count = 0, 0, 0
        for t, tDf in df.groupby(pd.Grouper(key='Corrected Time', freq='10min')):
            #Check if 10 minute readings exist for mag
            df10min.loc[df10min['Time'] == t.time(), 'Magnitude'].values[0]
            if (sleepStartFlex <= t.time() < sleepStart) or (sleepEnd <= t.time() < sleepEndFlex):
                if tDf['magnitude'].abs().mean() < df10min.loc[df10min['Time'] == t.time(), 'Magnitude'].values[0]: #df10min.loc[df10min['Time'] == t.time(), 'Magnitude'].values[0]:
                    night_inactivity_count += 1
                    
            elif sleepStart <= t.time() < sleepEnd:
                if tDf['magnitude'].abs().mean() > df10min.loc[df10min['Time'] == t.time(), 'Magnitude'].values[0]: #df10min.loc[df10min['Time'] == t.time(), 'Magnitude'].values[0]:
                    night_activity_count += 1

            else: #if sleepEndFlex <= t.time() < sleepStartFlex:
                if tDf['magnitude'].abs().mean() < df10min.loc[df10min['Time'] == t.time(), 'Magnitude'].values[0]:
                    day_inactivity_count += 1

        #Calculate day's sleep using these activity account
        daily_sleep = (datetime.datetime.combine(datetime.date.today(), datetime.time(hour=8)) - datetime.timedelta(minutes = night_activity_count * 10) + datetime.timedelta(minutes = night_inactivity_count * 10)).time()
        daily_sedentary = datetime.time(hour = int(day_inactivity_count * 10 / 60), 
                                        minute = (day_inactivity_count * 10) % 60)
        #Label rest of the day as being active
        h1, m1, s1 = daily_sleep.hour, daily_sleep.minute, daily_sleep.second
        h2, m2, s2 = daily_sedentary.hour, daily_sedentary.minute, daily_sedentary.second
        t1_secs, t2_secs = s1 + 60 * (m1 + 60 * h1), s2 + 60 * (m2 + 60 * h2) 

        SECS_IN_A_DAY = 86400
        t3_secs = SECS_IN_A_DAY - (t1_secs + t2_secs)
        daily_active = datetime.time(hour = int(t3_secs / 3600),
                                     minute = int((t3_secs % 3600) / 60),
                                     second = (t3_secs % 3600) % 60)
        
        daily_activity_data.append([datetime.datetime.combine(day, TIME), daily_sleep, daily_sedentary, daily_active])

    return pd.DataFrame(daily_activity_data, columns = ["Date", "Sleep Duration", "Sedentary Duration", "Active Duration"])

def convert_to_df(sensor_data, sensor):
    """
    Turn sensor data dict into df
    """
    sensorDf = pd.DataFrame(data=[[r[0], r[1]['x'], r[1]['y'], r[1]['z']] for r in sensor_data[sensor]], 
                            columns = ['timestamp', 'x', 'y', 'z']).drop_duplicates()
    
        
    sensorDf['UTC time'] = [str(d.date()) + "T" + str(d.time()) for d in pd.to_datetime(sensorDf['timestamp'], unit='ms')]
    
    sensorDf['Day'] = sensorDf.apply(lambda row: row['UTC time'].split('T')[0], axis=1)
    sensorDf['Time'] = sensorDf.apply(lambda row: row['UTC time'].split('T')[1], axis=1)
    sensorDf['Time'] = pd.to_datetime(sensorDf['Time']).dt.time
    sensorDf['magnitude'] = sensorDf.apply(lambda row: np.linalg.norm([row['x'], row['y'], row['z']]), axis=1)
    sensorDf.loc[:, 'magnitude'] = sensorDf.loc[:, 'magnitude'] - 1 
    
    return sensorDf

def empty_chart():
    """
    Create empty graph of last week (no non-zero values)
    """
    defaultDf = pd.DataFrame({"Date": [datetime.date.today() - datetime.timedelta(days=d) for d in reversed(range(0, 7))],
                              "Hours": [0] * 7})
    defaultDf.loc[:, 'Date'] = defaultDf['Date'].astype(str)

    chart = alt.Chart(defaultDf, title="More sensor data required!").mark_bar(size=20).encode(
        x=alt.X('Date:T', axis=alt.Axis(title='Date')),
        y=alt.Y('sum(Hours)', axis=alt.Axis(title='Hours'), scale=alt.Scale(domain=[0, 24]))
    ).properties(padding=150, height=550, width=550, autosize={"type": "none", "contains": "padding"}).configure_title(fontSize=24)

    return chart


###### Create chart
def activitySegmentationBarChart(activityDf):
    if activityDf is None:
        #Upload default graph
        chart = empty_chart()

    else:
        emptyStatus = False
        sliceObj = activityDf[['Date', 'Sleep Duration', 'Active Duration', 'Sedentary Duration']].dropna()

        sliceObj.loc[:, 'Date'] = sliceObj['Date'].apply(lambda x: x.date())
        sliceObj.loc[:, 'Sleep Duration'] = sliceObj['Sleep Duration'].apply(lambda x: x.hour + (x.minute / 60))
        sliceObj.loc[:, 'Active Duration'] = sliceObj['Active Duration'].apply(lambda x: x.hour + (x.minute / 60))
        sliceObj.loc[:, 'Sedentary Duration'] = sliceObj['Sedentary Duration'].apply(lambda x: x.hour + (x.minute / 60))

        graphDf = sliceObj.melt('Date', var_name='Measurement', value_name='Hours')
        graphDf.loc[:, 'Date'] = graphDf['Date'].astype(str)
        chart = alt.Chart(graphDf).mark_bar(size=20).encode(
            x=alt.X('Date:T', axis=alt.Axis(title='Date')),
            y=alt.Y('sum(Hours)', axis=alt.Axis(title='Hours')),
            color='Measurement'
        ).properties(padding=150, height=550, width=550, autosize={"type": "none", "contains": "padding"})

    return chart

if __name__ == '__main__':
    
    #Enter username/password below
    #LAMP.connect("USERNAME", "PASSWORD")
    
    alt.themes.enable('none')
    activitySegmentationAll()
`

sensor_data_quality.py

`import LAMP
import pandas as pd
import altair as alt
import datetime
import numpy as np
import math 
from functools import reduce
import base64
import altair_saver
import time

def sensorQualityAll():

    researchers = [res['id'] for res in LAMP.Researcher.all()['data']]
    studies = reduce(lambda x, y: x + [study['id'] for study in LAMP.Study.all_by_researcher(y)['data']], 
                     researchers[1:], 
                     [study['id'] for study in LAMP.Study.all_by_researcher(researchers[0])['data']])

    participants = reduce(lambda x, y: x + [part['id'] for part in LAMP.Participant.all_by_study(y)['data']], 
                     studies[1:], 
                     [part['id'] for part in LAMP.Participant.all_by_study(studies[0])['data']])

    for participant in participants:
        try:
            partChart = sensorQualityChart(participant)

            if partChart is None:
                continue

            chart_dict = partChart.to_dict()
            LAMP.Type.set_attachment(participant, "me", 
                                    attachment_key="lamp.dashboard.experimental.sensor_data_quality", 
                                    body=chart_dict)

        except Exception as e:
            continue
        

def load_raw(user_id):
    timestamp_now = lambda: int(round(time.time() * 1000))
    TIMESTAMP_LIMIT = (1000 * 24 * 60 * 60 * 1000) # 10 days of data
    data = []
    to = timestamp_now()
    _from=timestamp_now()-TIMESTAMP_LIMIT
    while True:
        res = LAMP.SensorEvent.all_by_participant(user_id, _from=_from, to=to, transform="{\"data\":data.{\"timestamp\":timestamp,\"origin\":sensor}[]}")
        if 'error' in res:
            raise RuntimeError(res["error"])
        chunk = res["data"] if 'data' in res else []
        data.extend([{ 'id': user_id, **x } for x in chunk])
        if not chunk or (timestamp_now() - chunk[-1]['timestamp']) > TIMESTAMP_LIMIT:
            break
        to = chunk[-1]['timestamp']
    return data

def sensorQualityChart(participant):
    df = pd.DataFrame([x for x in load_raw(participant)])
    df = df[df['origin'].isin(['lamp.accelerometer.motion', 'lamp.accelerometer','lamp.gps','lamp.screen_state'])]
    df['timestamp'] = df['timestamp'].astype('datetime64[ms]')

    if len(df) > 50000:
        df = df.sample(n=50000)

    partChart = alt.Chart(df).mark_tick().encode(
        x=alt.X('timestamp:T', title='Date'),
        y=alt.Y('origin:O', title="Sensor")
    ).properties(padding=100, height=400, width=800, autosize={"type": "none", "contains": "padding"})

    return partChart


if __name__ == '__main__':
    
    #Enter username/password below
    #LAMP.connect("USERNAME", "PASSWORD")
    
    alt.themes.enable('none')
    alt.data_transformers.disable_max_rows()
    sensorQualityAll()
`

**Comment by gabrieldev755** [comment]
I checked all other visualizations.
There are 3 problems now.
1. I don't see Sensor Data Quality visualization
2. Current activity segmentation graph is base64 image, it is not vega. So should I convert it to vega graph? if yes then I need data sample too.
3. On current lamp dashboard diary not work. I can see the setting but it is not loaded and also graph is incorrect. I think it is related to DBT diary card graphs task.

**Comment by avaidyam** [comment]
> I don't see Sensor Data Quality visualization

@gabrieldev755 It's not in our Try It just yet. @ryan-hays Could you generate a sample Vega JSON file for @gabrieldev755 to look at/work with for this? 

> Current activity segmentation graph is base64 image, it is not vega. So should I convert it to vega graph? if yes then I need data sample too.

I think @ryan-hays recently succeeded in getting the Vega version to generate so maybe you could attach that here too?

> On current lamp dashboard diary not work. I can see the setting but it is not loaded and also graph is incorrect. I think it is related to DBT diary card graphs task.

Yep, @sarithapillai8 is currently working on connecting the data to the chart correctly, but do you have any insights you can share with her on this based on the code that's in `LAMP-dashboard`'s `master` branch?

**Comment by gabrieldev755** [comment]
1. Ok, please attach sample Vega JSON file once it is ready.
2. Okay
3. Let me know once master branch is updated.

**Comment by ryan-hays** [comment]
Here is a folder containing sample Vega JSON files for both the sensor data quality and activity segmentation. (They were both generated from the same participant.) 

[LAMP Sample Vega Graphs.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5630247/LAMP.Sample.Vega.Graphs.zip)

**Comment by gabrieldev755** [comment]
How about 2 and 3 points that I said before?

**Comment by gabrieldev755** [comment]
I need to know standard for it.
1. like what date format should we use
2. What is the design for selecting custom date range
3. Should we remove other graph framework and convert all to Vega?

**Comment by avaidyam** [comment]
1. I think it makes sense to use an abbreviated date format like "Sep 23, 2020" or similar.
2. Anything that Vega supports. There is no design requirement for this yet. It must be implemented entirely as part of the Vega spec, however.
3. By other graph framework, do you mean Altair? That's a Python library for creating Vega graphs. You should be able to take the JSON output and modify it from there by hand if needed, or use the Altair methods to update it.

**Comment by gabrieldev755** [comment]
3. I mean @data-ui/xy-chart library.
