### ISSUE TITLE
Unnecessary sensor_event call on Portal/Prevent Page

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#510]
When navigating to the portal page in User view, two GET requests are always made - one to activity_event and one to sensor_event.

The purpose of the activity_event call is clear - it loads data for the graphs that are shown under the `Activity` portion of the page.

It is not clear why sensor_event is called - there are no spec or origin params set so the result is always just the last 1000 sensor events logged and nothing seems to change on the page to reflect the resuilts of the query. If it is unnecessary it should probably be removed. The execution of the query seems to take ~250 ms, so it's not *catastrophic* but if other elements of the page are awaiting its completion, it should only run if the raw data is required for something.

**Comment by avaidyam** [comment]
Yes, please remove both. 

### Rationale
Step count can now be achieved using the data studio (cc @lukeoftheshire is this correct?) so we want to focus on active data for the tiles. We can number crunch the step count and add it as a visualization afterwards too.

**Comment by divyav2020** [comment]
[LAMP_Admin Website_Unnecessary sensor event.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8189953/LAMP_Admin.Website_Unnecessary.sensor.event.xls)

**Comment by lukeoftheshire** [comment]
QA tested in staging, looks good!
