### ISSUE TITLE
'Fetching messages' loop in NavigationView

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#512]
While using the navigation view page (e.g. while looking at Researcher or participant view) it can be seen in the network requests that a request for the `lamp.messages` attachment on the current page (researcher, participant, etc.) is made repeatedly -- regardless of the page being viewed or if there are messages.

This appears to happen every 30s or so. What is the purpose of this call? (the origin is on line 294 in NavigationLayout.tsx, if that helps)

Additionally, while in user view I can see a `lamp.analytics` GET request being made with similar frequency, but it has no payload and the response is always empty. This call also appears to originate from NavigationLayout.tsx (line 253)

**Comment by avaidyam** [comment]
This loop exists to refresh conversations - but it shouldn't be happening in the background when I'm not looking at the conversations page. And it shouldn't be part of `NavigationLayout`, which is a root-level component spanning all pages.

**Comment by sarithapillai8** [comment]
@avaidyam 

>And it shouldn't be part of NavigationLayout, which is a root-level component spanning all pages.

It is placed in NavigationLayout for the purpose of showing the message count badge on the 'Conversation' Icon in top section, which is placed in the same file.
![image](https://user-images.githubusercontent.com/63710347/153579173-1b3aaaa2-6df9-403a-962e-d3d40aae08a3.png)

>but it shouldn't be happening in the background when I'm not looking at the conversations page

While on the conversations page, new messages are also showing with the help of this call, so why do we need to remove it from Conversations page? 

Note : There is one missing, the conversation page is not opening with separate URL, which was missed as part of #341 and I can do that soon.

**Comment by avaidyam** [comment]
> It is placed in NavigationLayout for the purpose of showing the message count badge

Right, this makes sense. 

> I can move it to a sub component, but it will be part of NavigationLayout.

But this means nothing is really being changed? 

> new messages are also showing with the help of this call, so why do we need to remove it from Conversations page?

We don't. I explicitly mentioned that it should not be fetching messages so frequently **outside** the conversations page. 

1. Fetch messages count upon login. 
2. Fetch messages when the patient is on the home screen every **minute**. 
3. Do not fetch messages if the patient is doing a survey, etc. (on some other screen). 

> conversation page is not opening with separate URL, which was missed as part of #341 and I can do that soon.

Are these items being missed in the QA phase or not being tested?

**Comment by avaidyam** [comment]
Yes, that's what I meant. 👍

**Comment by sarithapillai8** [comment]
@avaidyam 
In the conversations page, while sending and viewing messages, new messages are getting through the API in frequent intervals. So if we remove it in while in that page, the user won't be able to view new messages if any are sent at that time.

**Comment by avaidyam** [comment]
> So if we remove it in while in that page, the user won't be able to view new messages if any are sent at that time.

1. That page is **the only page** where this loop should be running after the home screen is loaded the first time. If i'm not on the `conversations` page, it should not be checking. 
2. We should be using the SSE event listener part of the API for this anyway, but let's not change that for now.

**Comment by sarithapillai8** [comment]
>That page is the only page where this loop should be running after the home screen is loaded the first time. If i'm not on the conversations page, it should not be checking.

- But you asked to fetch messages every minute - https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/512#issuecomment-1036193772. So is it like, fetch the messages on home screen(any tab, not inner page) and looping should only be done when inside conversations.

**Comment by sarithapillai8** [comment]
@avaidyam 
There is an issue which actually cannot be solved with the current implementation. 
Consider a situation like : While a user is in the conversation page, and admin sends a message; The user see the messages and after that he go back to any previous page. The message badge will still show the count of messages that are received while on the conversation page. This is because, we are calculating the count of messages with the open_page sensor event of conversations page. It will be saved with the time of opening the page and there is no way to identify whether the user is still on the page. So those will be considered as unread messages. Can we leave it as it for now, or do you have any suggestions to resolve this issue?

**Comment by divyav2020** [comment]
[LAMP_Admin Website_Fetching messages loop.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8189963/LAMP_Admin.Website_Fetching.messages.loop.xls)

**Comment by lukeoftheshire** [comment]
QA testing on our end looks good too.
