### ISSUE TITLE
Moderate slowdown issues when editing or completing activities

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#515]
We're noticing increased loading spinners in areas of the app where surveys or tips are being edited  by a clinician or submitted by a patient.

> @tlakhtak: When finishing a survey and heading back to the assess page, the spinning wheel lingers just a second or so too long. This might weaken UI experience.

I'm parking this issue to collect screen recording evidence and network logs to determine potential causes, but @sarithapillai8 do you have any initial insight on why some folks are experiencing dashboard slowness?

**Comment by sarithapillai8** [comment]
@avaidyam  @lukeoftheshire 
I believe the current slowdown issues/extra loaders are after the changes we did with separate URL changes and the change requested in this comment -  https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/400#issuecomment-995162775. 
Before implementing separate URL, the local storage data once fetched was using different sections in the admin side through the props. Currently we are fetching the data in each URL(not the API call, but the local IndexDB data), which might be the cause of extra delay now.

**Comment by avaidyam** [comment]
@lukeoftheshire Would you mind profiling the dashboard to see what data we can pull from the Web Inspector around sluggishness or slowness? I'm not entirely convinced it's the dashboard, as some of our collaborators have pretty bad internet connections which can cause the same effect.

**Comment by avaidyam** [comment]
This issue doesn't seem to be happening anymore.

**Comment by ertjlane** [comment]
This issue occurred in testing. Using an api testing account & on non-api testing account on testflight. 

Api staging user id: U9245591907
Non api user id: U4829584893
Device: iPhone 6s
Software version 15.6

https://user-images.githubusercontent.com/104088715/181357277-0b15308e-2349-4bc4-a4ac-5b9cf71ece23.MP4

If the above recorded wait time is lower than than which prompted this issue originally disregard this.

**Comment by michaelmenon** [comment]
Hi @sarithapillai8 can we check on this

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you check and let me know if we need to work on this? I think this delay was there for long time. The delay is there to get the activity icons from tags when loading the assess tab activities.

**Comment by michaelmenon** [comment]
Team will be working on caching the icons.

**Comment by divyav2020** [comment]
We have updated in staging
