### ISSUE TITLE
Configuration parameters for voice diary

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#516]
We want regular “clinician side” user to be able to edit the text shown on the audio diary card, so it is closer to the function of a survey but with audio as input:
 
Patient/Client facing Current State:
- The Voice Recording assessment, once the user selects “Begin” they see a series of screens as shown below:
    - The “Record” screen states “Press the microphone to record” 
        - **There is no way to customize text on this screen.**
    - After recording, the “Upload” screen states “Click upload or clear to record again” 
        - **There is no way to customize this text**
    - After clicking upload, the “Submission” screen shows “Nice work!  You’re on a streak, keep it going.”
        - <strike>There is no way to customize this text</strike> (See issue #441.)
 
<img width="881" alt="image001" src="https://user-images.githubusercontent.com/1361003/153672578-83cf80b2-9847-4c8f-a803-7a479648f446.png">

 
For Clinician-facing, we were imagining something like the “Question” configuration page (shown below), where the researcher can enter a Title for the “Record” screen and maybe also what text appears on the “Upload” and/or “Submission” screen. 

<img width="560" alt="image002" src="https://user-images.githubusercontent.com/1361003/153672593-3ffeb378-31f1-47d3-a415-4cb9bf2b7de4.png">

**Comment by sarithapillai8** [comment]
This is updated in dashboard-staging. QA done.
