### ISSUE TITLE
Error pop-up if no selected group for activity

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#517]
**Describe the bug**
If I create an activity and do not select a group and press save, no error will be thrown and the activity will not be created. There should be some warning to the user to indicate that they need to select a group.

https://user-images.githubusercontent.com/21200061/154139068-8cf11e82-e673-40d2-8f45-506983102e61.mov

**Comment by avaidyam** [comment]
@dcurrey88 Can you attach a screen recording to your original post?

**Comment by dcurrey88** [comment]
https://user-images.githubusercontent.com/21200061/154138389-62ad069b-d726-4ada-b7d3-2fb4d2560527.mov

**Comment by sarithapillai8** [comment]
Updated the fix in dashboard-staging.

**Comment by tlakhtak** [comment]
This appears to be fixed in staging.
