### ISSUE TITLE
Read only text / images in surveys

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#518]
**Describe the solution you'd like**
I think it would be useful to have an activity that is a combination of surveys and tips which can have both questions as well as free text / images segments. Ideally temporal slices would still contain the values from the survey but the Activity itself would have additional text, images etc. 

**Additional context**
Ideally we would like to have this feature for the College Study that we will be running in the next month.

**Comment by avaidyam** [comment]
> but the Activity itself would have additional text, images etc.

Have you tried using Markdown text with survey questions/descriptions/options? It does work.

<img width="971" alt="Screen Shot 2022-02-10 at 10 37 06 AM" src="https://user-images.githubusercontent.com/1361003/154138192-23e79ba7-445f-43cc-9f86-b9386be7fd4e.png">
 <img width="204" alt="Screen Shot 2022-02-10 at 10 37 17 AM" src="https://user-images.githubusercontent.com/1361003/154138189-6eeced0e-873a-453d-9a7a-256a3bddfd67.png">

**Comment by dcurrey88** [comment]
This is a work-around, but I still feel like in the long-run this would be something beneficial to have. From an analysis point of view, it would be annoying to string match long markdown strings when scoring surveys.

**Comment by avaidyam** [comment]
> annoying to string match long markdown strings when scoring surveys

So this sounds like the real issue here? If so, this feature suggestion is being tracked in issue #266 ([specifically this comment](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/266#issuecomment-1029327057) from @lukeoftheshire).

> activity that is a combination of surveys and tips which can have both questions as well as free text / images segments

I'm not sure I'm able to imagine what you mean by this if not for markdown support in surveys... could you elaborate/sketch it out?

**Comment by dcurrey88** [comment]
I don't think this is already in #266 but it's related so I can add it there. And yes, I mean markdown (but read only with no question component).

**Comment by avaidyam** [comment]
Oh, I see what you mean. Maybe the right issue is either #385 or #265 and not #266. Sorry!

**Comment by dcurrey88** [comment]
Yes, "null" questions is what I mean. Thanks!
