### ISSUE TITLE
Custom time changes while changing the timezone

### ISSUE THREAD

**Issue by divyav2020** [BIDMCDigitalPsychiatry/LAMP-platform#519]
Custom time changes while changing the time zone

**To Reproduce**
1. Go to ' Schedule screen'
2.  Select Date and time and click on 'Custom option'
3. Shows default time in Custom field.  Without changing the time, select tick option. Current time saved.
4.  Save the schedule. 
5.  Save the particular activity
6.  Change the time zone and check the time.
7.  Added custom time changes to currently selected time zone's current time

**Comment by divyav2020** [comment]
Updated in Staging

**Comment by tlakhtak** [comment]
Custom time functionality is still unclear in staging. To test, a notification was set to Time (1:23pm) and Custom Time (1:25) showed a notification every day at 1:25pm, nothing at 1:23pm.

**Comment by sarithapillai8** [comment]
@tlakhtak 
Could you please provide more details like timezone, activity etc. ? 
Is this happens in push notifications only?  
We tried setting both 1:23 am and 1:23 pm and they are showing fine in feed section.
![image](https://user-images.githubusercontent.com/63710347/163108602-62b8a3d4-ccfd-4479-a99b-bca07146ab67.png).

**Comment by evinkalengaden** [comment]
We have tested the notification receival time in different schedules, Here it is working fine. Please refer the recordings attached.

**Comment by tlakhtak** [comment]
timezone seems to be fine, but the function of custom times is unclear. What is the purpose of a custom time, and how is it functionally different from scheduling an activity for 1:45pm everyday in this case?
<img width="1157" alt="Screen Shot 2022-04-13 at 8 48 17 AM" src="https://user-images.githubusercontent.com/82968538/163183642-1b8c2b93-4662-4598-af02-62f71f8e840f.png">
![IMG_2946](https://user-images.githubusercontent.com/82968538/163183687-d901e5ce-a524-4850-842a-6a4ed0841686.PNG)

**Comment by sarithapillai8** [comment]
@tlakhtak We can add multiple custom times for single schedule using custom option.

**Comment by tlakhtak** [comment]
This functionality is working as expected.
