### ISSUE TITLE
iOS - The notification should be removed from the Notification Center if it's expired

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#52]
Current approach:
When ever receive a notification, we are starting a thread to remove the notification after the expiry-interval.
Notification expired can still display if user force quit the app or the app is not running in the background when the expiry thread is executed.
Proposed:
Instead, use a background timer or something similar that schedules with the OS directly, so the app can be awoken correctly in all scenarios.

**Comment by jijopulikkottil** [comment]
We have still issues in auto expire notifications with the current approach. Working on it..

**Comment by avaidyam** [comment]
@jijopulikkottil Thanks for the update! Could you update the `NO ETA` label on this issue?

**Comment by jijopulikkottil** [comment]
It's worked with 5, 10, 30, 60 minutes of expiry. But not auto removing from Notification Center when test with 6 hours of expiry time . We will investigate it, or we can check and remove the expired notification on the app launch.

**Comment by avaidyam** [comment]
@jijopulikkottil [Can you look into this method for expiring/updating push notifications?](https://stackoverflow.com/a/38473755) Basically, after receiving a silent push with data, the native app will convert the silent remote push notification into a local scheduled notification that can be easily removed/updated. This is also important as we want notifications to work offline in the future.

**Comment by jijopulikkottil** [comment]
> Basically, after receiving a silent push with data, the native app will convert the silent remote push notification into a local scheduled notification that can be easily removed/updated.

Yes, we can start working on it.

**Comment by jijopulikkottil** [comment]
Hi @avaidyam The local notification is also having same behaviour.. We can remove it from the Notification Center. But can't schedule a task/notification to remove a notification from the Notification Center in background. So we can't auto expire a delivered notification. The one solution is (as we discussed earlier) to schedule two notifications from server for a notification. one for original notification and second is for removing the first one.

**Comment by avaidyam** [comment]
@jijopulikkottil That makes sense, so then this would be the expected approach (for when there is network access): 
1. Server sends initial (silent) push notification.
2. App schedules a local notification based on the activity/info from the remote push. 
3. Server sends a second (silent) push notification upon expiry. 
4. App uses this notification to remove the local notification previously created. 

If there is no network access, then the app must be responsible for scheduling the notifications (reading the schedule from the Activity API) and expiring them independently. Do you believe that to be possible with this workflow?

**Comment by jijopulikkottil** [comment]
If there is network access, step 1 (server sends initial -not silent- push notification) and step 3 (Server sends a second -silent- push notification upon expiry with same apns-collapse-id of step1 push to remove the notification from device) are fine. [no need of step 2 and step 4]

**Comment by jijopulikkottil** [comment]
hi @avaidyam , so can we implement the same? (Server sends a second silent-push notification upon expiry time to remove the notification from device) @Linoy339

**Comment by Linoy339** [comment]
Okay

**Comment by jijopulikkottil** [comment]
> If there is no network access, then the app must be responsible for scheduling the notifications (reading the schedule from the Activity API) and expiring them independently. Do you believe that to be possible with this workflow?

Yes, Get the schedule from Activity API, And scheduling local notifications. When ever app get a remote notification, then cancel/remove the scheduled local notification. To meet this, we need a unique identifier which should get from Activity API for each schedule and the same will be available in the remote push payload.

**Comment by avaidyam** [comment]
@jijopulikkottil It looks like then Activity schedules will need some method of identification - this seems easily doable, thanks for pointing that out.

**Comment by jijopulikkottil** [comment]
And to do this, can we get all activity/schedules once login and schedule local notification for all activity Or only for next 3/5/7 days of activity?
How frequent the activity can edit on dashboard?
As per that, in some interval (maybe in 1/3/5/7 days) app need to refetch the activity from server, and remove all scheduled local notifications and schedule again based on new data.
Please confirm.

**Comment by jijopulikkottil** [comment]
@avaidyam Can we create new task "Activity API integration for creating local/offline notification" ?. 
Before that please confirm the following:
If there is no network and If we show local notification, the activity page won't load when user tap on the notification because of no connectivity.

**Comment by avaidyam** [comment]
@jijopulikkottil 
> How frequent the activity create/edit on dashboard?
> in some interval (maybe in 1/3/5/7 days) app need to refetch the activity from server, and remove all scheduled local notifications and schedule again based on new data

Ideally this is not more than once or twice for the study so infrequent checking (i.e. daily) is preferred. 

> Can we create new task

Yes! 

> If there is no network and If we show local notification, the activity page won't load when user tap on the notification because of no connectivity.

The dashboard code should be cached and loaded locally; the work @sarithapillai8 is currently working on should also be able to enable offline mode in the near future, so there should be no issues proceeding this way.

**Comment by jijopulikkottil** [comment]
Created new task https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/115. 

So pending task on this thread (only for iOS) is 
[Server should send a second silent-push notification upon expiry time to remove the notification from device](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/52#issuecomment-775076309)

I think we don't need to send a second silent push notification for repeated activity. If we use same identifier (apns-collapse-id), then the previous will be replaced when new one arrives. @avaidyam  please confirm

**Comment by avaidyam** [comment]
@jijopulikkottil Yes, this sounds correct to me as far as I can tell.
