### ISSUE TITLE
Make tip editing window expandable

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#520]
The tip description window on the dashboard is only about 5 lines tall and cannot be expanded as you add more text. I would like to be able to make it larger so I can see all of the content I have typed at once
<img width="1062" alt="Screen Shot 2022-02-17 at 9 03 14 AM" src="https://user-images.githubusercontent.com/21200061/154497798-b4d7809d-f4a8-4888-a85c-4c562535dafe.png">
.

**Comment by divyav2020** [comment]
[LAMP_Admin Website_Tip Activity Changes.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8189954/LAMP_Admin.Website_Tip.Activity.Changes.xls)

**Comment by tlakhtak** [comment]
Could not test due to #606
