### ISSUE TITLE
Tip files cannot be deleted

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#521]
**Describe the bug**
Media files for tips can only be deleted by selecting a new file and hitting cancel.

**Expected behavior**
There should be some way to clear the file without loading a new file. 

https://user-images.githubusercontent.com/21200061/154498170-c7dc18a5-a2eb-45cc-ac94-83b999cb4e50.mov

**Comment by divyav2020** [comment]
[LAMP_Admin Website_Tip Files delete.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8189962/LAMP_Admin.Website_Tip.Files.delete.xls)

**Comment by tlakhtak** [comment]
Could not test due to #606

**Comment by sarithapillai8** [comment]
@tlakhtak @avaidyam Could you please recheck?
