### ISSUE TITLE
No local notifications if schedule activity with new unhandled repeat-type

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#525]
1. Fix the issue of no local notification if add new 'repeat-type'.

Steps to reproduce the issue:
- With current Appstore version 2021.10.20, if we configure an activity with repeat type 'every two weeks', there will be no local notification for all activities.

**Comment by avaidyam** [comment]
@jijopulikkottil Can you confirm with @saranya-sajeev that this is also implemented and working on Android?

**Comment by saranya-sajeev** [comment]
@avaidyam It is working on Android.

**Comment by jijopulikkottil** [comment]
This issue has been fixed and available in test flight version [2022.1.13 (304)](https://testflight.apple.com/join/TSpdLc6U)

**Comment by ZCOEngineer** [comment]
@avaidyam we can close this?

**Comment by tlakhtak** [comment]
Every two weeks repeat time can be scheduled for a survey, but implemented in staging with a bug #526
