### ISSUE TITLE
Local notification of activity - Implement new repeat type 'every two weeks'

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#526]

**Comment by saranya-sajeev** [comment]
@avaidyam It is already implemented in Android and it is available in current beta build.

**Comment by jijopulikkottil** [comment]
Found an issue in testing. Its fixed and given to QA again.

**Comment by jijopulikkottil** [comment]
waiting for the server side fix https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/417#issuecomment-1049575346

**Comment by avaidyam** [comment]
@jijopulikkottil The frontend, backend, and native core are all independent components. **An update to the native app CANNOT require an update to a backend or frontend component.** Please QA test and stage this issue independently, assuming the frontend/backend components will never be fixed/updated.

**Comment by jijopulikkottil** [comment]
> "when you mark the issue as QA testing, please confirm with @saranya-sajeev that the Android side is being QA tested as well. Both iOS and Android MUST be in sync."

Yes, we are taking care of this.

**Comment by divyav2020** [comment]
This issue is fixed in iOS. But android build is not stable now. So we will update the status once the android build is stable

**Comment by ZCOEngineer** [comment]
Testing Android with new build today

**Comment by divyav2020** [comment]
This issue is fixed in iOS and Android

**Comment by tlakhtak** [comment]
This is incorrectly implemented in staging. I scheduled an activity every 2 weeks starting April 12. The schedule was as follows

April 12
April 26
May 3 (1 week from last date)
May 17 (2 weeks from last date)
May 31 (2 week from last date)
June 7 (1 week from last date)
June 21(2 week from last date) 

Thus, it seems like it does not how to correctly transfer the 2 week schedule between months

**Comment by evinkalengaden** [comment]
This issue is updated in the dashboard-staging. We have scheduled an activity on 13th APR 2022 and the schedule was available on the following dates and so on [Apr-13, Apr-27, May-11, May-25, Jun-08, Jun-22].

**Comment by tlakhtak** [comment]
this appears to be fixed in staging.
