### ISSUE TITLE
Missing sensor availability for certain LAMP server

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#528]
sangath.psych.digital server is unable to see screen_state sensor in their LAMP dashboard to add. Considering the device_state sensor is no longer functional, the screen_state sensor is necessary to add to users but right now it doesn't appear as an option
![configure2](https://user-images.githubusercontent.com/82968538/155149177-f6c0b455-1160-41d3-a15f-f1999eb13ea4.png)
![SensorConfigure](https://user-images.githubusercontent.com/82968538/155149181-98f705cb-c59e-4b0d-9cf4-67ba8174ab80.png)

**Comment by avaidyam** [comment]
@tlakhtak @lukeoftheshire We'll have to add the `screen_state` `SensorSpec` for them on our end and it should work from there. [This change was confirmed here.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/357#issuecomment-987928976)

**Comment by lukeoftheshire** [comment]
Noting here for closure that the `screen_state` Sensor was added to the Sangath server.
