### ISSUE TITLE
LAMP page titles in lowercase

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#529]
LAMP page titles appear to be in lowercase, as seen in the screenshots below:
![Screen Shot 2022-02-23 at 11 53 20 AM](https://user-images.githubusercontent.com/34659264/155367603-00a01b0f-3f37-431c-a6ae-0fb2f853ceb6.png)
![Screen Shot 2022-02-23 at 11 53 15 AM](https://user-images.githubusercontent.com/34659264/155367605-b987ab84-37ad-496b-9ee0-13498e31f88e.png)
![Screen Shot 2022-02-23 at 11 53 10 AM](https://user-images.githubusercontent.com/34659264/155367606-af0928b6-1b69-476d-9760-de9bf09ee0ea.png)

While this lends LAMP a whimsical, 'apple-esque' flair, I suspect this is unintended behavior. Could this be related perhaps to the translation file? It's interesting that the capitalization is 'correct' in the tab selection pane but incorrect in the page title - it should probably be standardized.

I also suspect this is a recent change but can't seem to find any screenshots showing evidence of this.

**Comment by divyav2020** [comment]
[LAMP_Admin Website_User details Page titles.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8189958/LAMP_Admin.Website_User.details.Page.titles.xls)

**Comment by tlakhtak** [comment]
This appears to be fixed on staging.
