### ISSUE TITLE
Blue border when viewing patient screen while logged in as admin

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#53]
According to Tim’s designs, there should be a blue border around the Patient UI when viewed by/logged in as a clinician.

**Comment by sarithapillai8** [comment]
The changes updated includes the researcher side top blue bar changes also as per Figma design.

**Comment by avaidyam** [comment]
@sarithapillai8 An issue I have identified in the staging environment today is that if you're logged in as an administrator (i.e. please test this with the staging server) the blue banner doesn't show up when viewing Researchers or Participants.

**Comment by sarithapillai8** [comment]
@avaidyam 
Yes it was not included in the Tim's design. What all things should be included in the menu in this case? Do we need to just show the blue border on top?

**Comment by avaidyam** [comment]
Yes, but if logged in as an administrator, when viewing a Researcher, it should show `← Researcher View: <Name>` at the top instead.

**Comment by sarithapillai8** [comment]
Okay, got it.

**Comment by avaidyam** [comment]
@sarithapillai8 The recent PR seems to have caused a regression where the back arrow shows when logged in as a clinician, instead of as the administrator.
<img width="159" alt="Screen Shot 2020-12-09 at 10 06 46 AM" src="https://user-images.githubusercontent.com/1361003/101647161-67c34f80-3a06-11eb-93ee-ac52e5234d3e.png">

**Comment by sarithapillai8** [comment]
@avaidyam 
Updated the PR with fix. Could you please check?

**Comment by avaidyam** [comment]
I still see the issue on the latest staging. Here are the minor details: 
1. The Back arrow is still showing when using Try It → Researcher or Clinician. 
1. The text "Me" should be replaced with: 
    a. "System Administrator" if logged in as an admin. (Right now it shows "Me".)
    a. The `researcher.name` if logged in as OR viewing a Researcher. (Right now it shows the ID which is not good.)

**Comment by sarithapillai8** [comment]
@avaidyam 
Added pull request with changes.
