### ISSUE TITLE
Alias `device_state` and `screen_state`

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#530]
There has been a lot of confusion about which sensor (`lamp.device_state` or `lamp.screen_state`) is responsible for collecting data about events like screentime.

Both of these sensors can be found in varying places in the documentation or forum posts and claim to collect the same thing. While we should pick one sensor name to use going forward, at this point we may have to accept the need to support both. If we could alias `device_state` and `screen_state` sensor names in the backend and ensure that they both turn on the same sensor and report the same events that would be very helpful.

As a note, currently our team is using the `lamp.screen_state` sensor, so I would suggest that be the 'version' we support going forward.

**Comment by avaidyam** [comment]
The official name of the sensor is `device_state` -- `screen_state` is actually a legacy Beiwe sensor we carried forward with NIH 1 data imports. We don't want to use that name because `device_state` in LAMP captures more information, such as battery level, device lock/unlock, notification flashes, etc. compared to the old sensor it replaces from Beiwe. 

@jijopulikkottil Can you please ensure on iOS that `lamp.device_state` is the name of this sensor, but `screen_state` also works for it? If you need to duplicate the code to register it as an identical sensor, that is fine. Can you also check with @saranya-sajeev to confirm the same behavior on Android?

**Comment by jijopulikkottil** [comment]
In iOS and Android, we are using `lamp.screen_state`. It has three fields: 
**value** (0, 1, 2, 3)
**representation** (screen_on, screen_off, screen_locked, screen_unlocked)
**battery_level**

Let us know if we need to change

**Comment by avaidyam** [comment]
@jijopulikkottil The data itself is fine, but as my prior comment states, both `lamp.screen_state` and `lamp.device_state` should enable this sensor on **BOTH** iOS and Android. Can you check with @saranya-sajeev to confirm the data on Android **looks identical** to iOS data?

**Comment by jijopulikkottil** [comment]
> Can you check with @saranya-sajeev to confirm the data on Android looks identical to iOS data?

Yes, data is identical on both platform.

> both lamp.screen_state and lamp.device_state should enable this sensor on BOTH iOS and Android

Ok, So if `lamp.screen_state` is configured, app should post the data under `lamp.screen_state`. And if `lamp.device_state` is configured, app should post the same data under the `lamp.device_state` identifier. If Both identifiers are configured, we should post same data under both identifier. @avaidyam  please confirm

**Comment by jijopulikkottil** [comment]
> No, it should post under lamp.device_state.

@avaidyam So hope we don't need to take care of backward compatibility.

**Comment by avaidyam** [comment]
Nope - all the old data will still exist under `lamp.screen_state` and and new data will appear under `lamp.device_state`. 

My team can prepare a migration script to rename the events on the database-side if needed or simply patch Cortex/API bindings to work with both `lamp.screen_state` and `lamp.device_state` going forward. //cc @lukeoftheshire @dcurrey88

**Comment by jijopulikkottil** [comment]
iOS part is completed, we can provide to QA once android is done.

**Comment by saranya-sajeev** [comment]
@avaidyam Android part also completed. Given for QA testing.

**Comment by jijopulikkottil** [comment]
in iOS, it was not reporting `unlocked` state. It was reporting `screen_on` or `screen_off` when device is unlocked state. We fix it by checking last state. So it will report `unlocked ` only if the previous state was `locked`.

**Comment by divyav2020** [comment]
@avaidyam This issue is fixed in iOS. But android build is not stable now. So we will update the status once the android build is stable

**Comment by ZCOEngineer** [comment]
Testing android with new build today

**Comment by divyav2020** [comment]
QA testing completed

**Comment by avaidyam** [comment]
> Also in iOS, the battery level was reported value from 0 to 1. Now its changed similar to Android [0 to 100]. In Android it is Int, but it is Float in iOS.

@jijopulikkottil @saranya-sajeev Please report battery level as a `Float` with range `0.0 → 1.0` on both iOS and Android. Otherwise all good!

**Comment by dcurrey88** [comment]
device_state data appears to be collecting for Android (U9848191154) but not iOS (U5053982269).

**Comment by jijopulikkottil** [comment]
@dcurrey88 Could you confirm the build number is 343.

@avaidyam Currently we are only providing the version name in user_agent
`user_agent": "NativeCore 2022.2.28; iOS 15.3.1; iPhone iPhone10,4`

**Comment by dcurrey88** [comment]
I have updated to the new build (352) and data is collecting for iOS as well.
