### ISSUE TITLE
Survey "Save" button obscures "Add new item"

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#533]
When editing surveys in a narrow window, the "Save" Buttton can overlap the "Add new item" button. This is not an unavoidable issue as the window can be widened again and even in very narrow windows or mobile devices the "Add new item" button can still be clicked - but this would be an inconvenience when editing a survey, particularly on a mobile device as even in landscape mode the buttons overlap.

<img width="870" alt="Screen Shot 2022-02-25 at 11 11 45 AM" src="https://user-images.githubusercontent.com/34659264/155749326-a52d4dc8-9228-4fe0-9cf5-855b8a9cc283.png">

**Comment by sarithapillai8** [comment]
@lukeoftheshire
This is already fixed as part of #442

**Comment by tlakhtak** [comment]
This issue does not appear to be fixed on dashboard-staging on the desktop, api-staging with test user, researcher 'b0b9mcsxr7z6eaepnpjv', while using admin credentials

![Screen Shot 2022-04-15 at 8 58 38 AM](https://user-images.githubusercontent.com/82968538/163573563-322c9f32-3b38-4677-9d35-b9ddc53671f3.png)

**Comment by avaidyam** [comment]
@sarithapillai8 Can you switch these buttons to be anchored to the bottom of the page instead of floating (i.e. remove the absolute/fixed positioning in CSS)?

**Comment by sarithapillai8** [comment]
@avaidyam This is updated in dashboard-staging.

**Comment by divyav2020** [comment]
We have updated in Staging
