### ISSUE TITLE
Pop the Bubbles sensitivity issues

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#535]
Users have reported, and we've observed as well, that Pop the Bubbles does not have that high of sensitivity to taps - such that correctly tapped bubbles do not pop because the tap does not register.

**Comment by divyav2020** [comment]
We have updated in Staging
[LAMP_Admin Website_Pop the Bubbles sensitivity.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8260141/LAMP_Admin.Website_Pop.the.Bubbles.sensitivity.xls)
