### ISSUE TITLE
LAMP Notification schedule wrong

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#539]
As of March 2, 2022 I am seeing the error for User U2736691852 where notifications are set for Evening activity group at 7pm and Cognitive Games at 8pm and yet show up respectively at 3pm and 4pm. 

![IMG_2621](https://user-images.githubusercontent.com/82968538/156451020-18d92bd2-1ea0-4e86-934f-9eb6f7d71588.PNG)
![IMG_2622](https://user-images.githubusercontent.com/82968538/156451255-b48b5946-879b-48f2-be71-88404456b4bd.PNG)

**Comment by tlakhtak** [comment]
My app says it updated to 2022.2.28 but the version number within the app still 2022.2.22
![969D235E-66D3-407B-B080-C377C64DF093](https://user-images.githubusercontent.com/82968538/156453609-704a07a3-41ae-4703-b552-413709cfebfb.jpeg)
![DA642447-BBDD-49E1-9539-DC1F3C02430F](https://user-images.githubusercontent.com/82968538/156453615-d6c5c9d2-3897-4509-827a-1abbe0b39c26.png)

**Comment by avaidyam** [comment]
That's correct. The version number in the app store is for the iOS app (which handles push notifications, sensor collection, etc.). The version number on the login screen is for the dashboard (which is the user interface that runs inside the iOS app or a web browser).
