### ISSUE TITLE
Add Spanish translations

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#54]
Here are all the new translation files to be converted/added now:

[DBT Diary Card Specifc - Spanish Translation.docx](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5629537/DBT.Diary.Card.Specifc.-.Spanish.Translation.docx)
[translation_Spanish.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5629538/translation_Spanish.txt)
[translation_hindi.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5629539/translation_hindi.txt)

**Comment by sijugeorge-zco** [comment]
@avaidyam 

The Spanish translation are not proper, please check the attached json file (Need_Spanish_Translation.txt)
For Eg: the translation on English is
"Breathing exercise (__ mins)": "Breathing exercise ({{ mins }} mins)",
But the given translation on Spanish is
"Breathing exercise (__ mins)": "Ejercicio de respiración (__mins)",
the value for {{ mins }} will be dynamically passed and should not be changed on translation.

The attached json file (Need_Hindi_&_Spanish_Translation.txt) requires translation for Hindi & Spanish, since they are the newly added .

[Need_Hindi_&_Spanish_Translation.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5636230/Need_Hindi_._Spanish_Translation.txt)
[Need_Spanish_Translation.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5636231/Need_Spanish_Translation.txt)

**Comment by avaidyam** [comment]
@sijugeorge-zco Do you think you could briefly go through and fix this for this file? @elenamrv and I will let our collaborators know going forward about this as we request translations.

**Comment by sarithapillai8** [comment]
@avaidyam 
We will be updating this task by early next week.

**Comment by sijugeorge-zco** [comment]
@avaidyam 
We check the texts (from Need_Spanish_Translation.txt) with google translator and update .
Can we translate the texts (from Need_Hindi_&_Spanish_Translation.txt) using google translator for Hindi and Spanish ?

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - our collaborators have begun translating Need_Hindi_&_Spanish_Translation.txt . We can wait for them to return the texts to us. Please do not use google translator - thank you! @avaidyam

**Comment by sijugeorge-zco** [comment]
@elenamrv 
Sure, we will wait for them. Thanks.

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - please see below for the latest SPANISH translations that were requested (we are still waiting on the last Hindi txt):

[Need_Spanish_Translation (DONE)2.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5652793/Need_Spanish_Translation.DONE.2.txt)
[Need_Spanish_Translation(DONE)1.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5652794/Need_Spanish_Translation.DONE.1.txt)

Thank you! 

fyi @avaidyam

**Comment by sijugeorge-zco** [comment]
@avaidyam @elenamrv 
We have updated already with all the translations provided. 

We have found a translation missing on the Spanish document you provided:

"Don't tap the boxes with a cat behind them"

**Comment by elenamrv** [comment]
Thanks @sijugeorge-zco - I'll work on getting that last sentence translated and will post it here when I have it.

**Comment by elenamrv** [comment]
Don't tap the boxes with a cat behind them : Continúa tocando las cajas que tienen un gato detrás de ellas/ ellos

@sijugeorge-zco thank you!

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - please see below for the additional Hindi txt you requested earlier: 

[Need_Hindi_Translation_Dec 4_Azaz.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5702569/Need_Hindi_Translation_Dec.4_Azaz.txt)

Let me know if you have any questions!

**Comment by elenamrv** [comment]
also @sijugeorge-zco - another wants to translate into a new language. Do we have one blank .txt file I can send him that is inclusive of all .txt files and that is up to date? Thank you!

**Comment by sijugeorge-zco** [comment]
@elenamrv 
The attached file (all_texts.txt) includes all the updated texts.
On the attached file, Translations needed to be done for the value but not the key.

Few of the below words need translation for Hindi and Spanish.
	"Balloon Count": "Balloon Count",
	"Breakpoint Mean": "Breakpoint Mean",
	"Breakpoint Standard Deviation": "Breakpoint Standard Deviation",
	"Please enter balloon count.": "Please enter balloon count.",
	"Please enter breakpoint mean.": "Please enter breakpoint mean.",
	"Game Settings": "Game Settings"

Thank you.

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - I just sent these out for translation. I'll post when I have them back! Thanks.

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - see below for Spanish. Thanks!

Balloon Count": "Conteo de globos",
"Breakpoint Mean": "Media del punto de ruptura",
"Breakpoint Standard Deviation": "Desviación Estándar del punto de ruptura",
"Please enter balloon count.": "Por favor ingrese el número de globos .",
"Please enter breakpoint mean.": "Por favor ingrese media del punto de ruptura.",
"Game Settings": "configuraciones de juego"

**Comment by elenamrv** [comment]
Hi @sijugeorge-zco - see below for Hindi. Thank you!

"Balloon Count": "गुब्बारों की गिनती",
"Breakpoint Mean": "विभाजन बिंदु का मध्यमान",
"Breakpoint Standard Deviation": " विभाजन बिंदु का मानक विचलन",
"Please enter balloon count.": "कृपया गुब्बारों की संख्या भरे",
"Please enter breakpoint mean.": "कृपया विभाजन बिंदु का मध्यमान डाले",
"Game Settings": "खेल को सेट करें "

**Comment by sijugeorge-zco** [comment]
Hi @avaidyam , @elenamrv 

Please find the strings to be translated(_to Spanish and Hindi_) for the _Balloon Risk Game_ and _Pop The Bubbles_ game.

	"Please enter breakpoint standard deviation.": "Please enter breakpoint standard deviation.",
	"Multiple should be comma seperated": "Multiple should be comma seperated(Eg:60,80,80)",
	"Please enter Bubble Count with comma seperated.": "Please enter Bubble Count with comma seperated.",
	"Please enter Bubble Speed with comma seperated.": "Please enter Bubble Speed with comma seperated.",
	"Please enter Intertrial Duration.": "Please enter Intertrial Duration.",
	"Please enter Bubble Duration.": "Please enter Bubble Duration."	
	"BALLOON_RISK": "Balloon Risk",
	"PUMP_UP_BALLOON": "PUMP UP BALLOON",
	"TOTAL_POINTS": "Total Points",
	"CURRENT_POINTS": "Current Points",
	"COLLECT_POINTS": "COLLECT POINTS",
	"BALLOON_BURSTED": "Balloon Bursted",
	"CONGRATULATIONS": "Congratulations",
	"GO": "GO",
	"LEVEL_NUMBER": "Level {{ gameLevel }}",
	"LEVEL_NUM_COMPLETED": "Level {{ levelNumber }} Completed",
	"NUMBER_OF_CORRECTLY_ANSWERED_GO_TRIALS": "{{ correctGoCount }} number of correctly answered (popped) Go trials and {{ percentage }}",
	"NUMBER_OF_CORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ correctGoCount }} number of correctly answered (unpopped) No-Go trials and {{ percentage }}",
	"NUMBER_OF_FALSE_HITS": "{{ falseHitsCount }} number of false hits (hitting screen anywhere other than a bubble)",
	"NUMBER_OF_INCORRECTLY_ANSWERED_GO_TRIALS": "{{ missedClicks }} number of missed (unpopped) Go trials and {{ percentage }}",
	"NUMBER_OF_INCORRECTLY_ANSWERED_NO_GO_TRIALS": "{{ wrongNoGoCount }} number of incorrectly answered (popped) No-Go trials and {{ percentage }}",
	"POP_THE_BUBBLES": "POP THE BUBBLES!",
	"TAP_TO_CONTINUE": "Tap to continue",
	"TAP_TO_POP_LEVEL_1_BUBBLES_BOTTOM":"POPPING CORRECT BALOONS WILL EARN YOU POINTS.",
	"TAP_TO_POP_LEVEL_1_BUBBLES_TOP":"TAP TO POP ALL PINK, BLUE AND YELLOW BUBBLES ONLY.",
	"TAP_TO_POP_LEVEL_2_3_BUBBLES_TOP":"DON’T POP TWO BUBBLES OF THE SAME COLOR IN A ROW.",
	"TAP_TO_POP_LEVEL_2_BUBBLES_BOTTOM":"ONLY POP YELLOW AND BLUE BUBBLES.",
	"TAP_TO_POP_LEVEL_3_BUBBLES_BOTTOM":"ONLY POP PINK YELLOW AND BLUE BUBBLES.",
	"YOU_GOT_PERCENT": "You got {{ percentage }}",
	
	
_Note:_ 
Translation for the above strings should be done for the right side value, not the left side.
