### ISSUE TITLE
LAMP Page headers in lowercase

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#540]
Noticed today March 2, 2022 that all 5 LAMP dashboard pages (Feed page, Learn page, etc.) are displaying their headers in lowercase instead of first letter capitalized, as they used to.
![IMG_2622](https://user-images.githubusercontent.com/82968538/156451679-760c8c12-7b97-4f60-988e-89e7d6d7a2e7.PNG)

**Comment by avaidyam** [comment]
Duplicate of #529.
