### ISSUE TITLE
Make maximum sensor frequencies equal on both Android and iOS

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#541]
While going through the LAMP-core-android library for an unrelated reason, I noticed the [following block of code:](https://github.com/BIDMCDigitalPsychiatry/LAMP-core-android/blob/568814c14375b5d502c453007928d592a222f8bf/app/src/main/java/digital/lamp/mindlamp/repository/LampForegroundService.kt#L248)
```
2 -> {
    var accelerometerDataRequired = false
    var sensorSpec = ""
    var frequency: Double? = null
   /* if (sensorSpecList.isEmpty()) {
        accelerometerDataRequired = true
    } else {*/
        sensorSpecList.forEach {
            if (it.spec == Sensors.ACCELEROMETER.sensor_name ||
                    it.spec == Sensors.DEVICE_MOTION.sensor_name) {
                accelerometerDataRequired = true
                sensorSpec = it.spec!!
                it.frequency?.let {
                    if (it != 0.0 && it <= 1)
                        frequency = it
                }
            }
        }
    //Invoke Accelerometer Call
    if (accelerometerDataRequired) {
        AccelerometerData(
                this@LampForegroundService,
                applicationContext,
                frequency, sensorSpec)
    }
}
```

This line in particular 
```
 if (it != 0.0 && it <= 1)
    frequency = it
```
seems to cap frequency of accelerometer collection to 1 Hz. Is that correct? I think the iOS implementation is 5 Hz so we should make sure that the caps are the same.

**Comment by saranya-sajeev** [comment]
@avaidyam We were sending the sensor data of 10 minutes and there was a hang issue in the Android app when we tried to set the frequency to 5 for the accelerometer. Currently, we are sending sensor data of 5 minutes.  So the issue may be fixed.  We will check and update you.

**Comment by avaidyam** [comment]
> Currently, we are sending sensor data of 5 minutes.

Where was this documented as an issue? Do I understand correctly that if I set `frequency = 5` (that is, `5 Hz sampling rate`), I'm instead going to be limited to `0.0033 Hz`?

**Comment by jijopulikkottil** [comment]
Currently the maximum frequency set in Android is 1. So if we set `frequency = 5,` it will be limited to` 1`.

Earlier there was an issue when collect with frequency 5, it was the issue  when syncing sensor date to server (I think so). the reason was, in every sync interval, the app was trying to sync last 10 minutes sensor data (all sensor data in last 10 mins) in a single url request.

In current build, in every sync interval, the app is syncing last 5 minutes data in a single url request. So the data length is reduced now. So we can try with frequency 5. If still having issue of data length when syncing, we can try with 3 minutes of sensor data.

**Comment by ZCOEngineer** [comment]
@avaidyam, @saranya-sajeev will confirm this after fixing the android build workflow

**Comment by saranya-sajeev** [comment]
@avaidyam Seems app is working fine after changing the frequency to 5. Will update you after further testing.

**Comment by avaidyam** [comment]
@saranya-sajeev @jijopulikkottil Please ensure that the `frequency` and `cellular_upload` flags for the `Sensor.settings` are correctly supported! I can mark this issue closed when QA testing has confirmed this.

**Comment by saranya-sajeev** [comment]
@avaidyam frequency and cellular_upload flags are properly handled.

**Comment by jijopulikkottil** [comment]
@avaidyam 
In iOS, for lamp.device_motion, the maximum frequency allowed is 100. 
Default given is 5.
Hope we should set this maximum frequency same on both  iOS and Android, so in iOS also, can we set the maximum as 5?

**Comment by avaidyam** [comment]
@jijopulikkottil Yes, let's set the maximum frequency on iOS and Android to be identical **for all sensor types.**

**Comment by dcurrey88** [comment]
It looks like the max frequency has been set to 5.
