### ISSUE TITLE
Timestamps record END of activity, not START

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#542]
Timestamps for activity events seem to reflect the END of an event, not the beginning. 

I did the following:

1. Open the dashboard using my test user (U0566162887)
2.  Start a survey (id:"e2wxcekbb0typzdtz0pb") at 9:20
3. Fill out the survey, wait until 9:25, then submit.

The timestamp recorded for the activity event was `1646317501445`. This timestamp corresponds to 9:25 (EST).

This is technically a bug as the intended implementation is that timestamp should be when the activity is started, not ended. No data is (technically) lost since we have duration and can thus calculate the time the activity was started.

I see two options here:
1. Change the implementation of timestamp to the intended one - this will cause us to need to process data differently from before and after we make this change (and we'll have to alert collaborators).
2. Leave the implementation as is, but update the docs (and any scripts) to reflect the true nature of the 'timestamp' field - this has the nice side effect of not causing the 'split' in the database that option 1 does (but will require more extensive docs updates).

**Comment by lukeoftheshire** [comment]
I have spent some time looking into this. I cannot nail down the exact problem. For at least non-survey activities, I think EmbeddedActivity is not the issue - as far as I can tell [this block of code](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/ea752df49318f42f4e2cdfd71371a17eb8808cda/src/components/EmbeddedActivity.tsx#L102) should faithfully report the timestamp data reported from the embedded activity.

HOWEVER, some(most?) activities may not implement timestamps correctly - see [this line](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/453236efbb5c1e72846d8bf2db7df94a240d8261/Tips/src/components/LearnTips.tsx#L196) in Tips - which as near as I can tell has always been this way. If I am reading this correctly, it looks like data will be erroneously passed to the parent with the timestamp at time of Tip *completion*, which matches the behavior I see when I complete Tips.

Some activities, in particular Breathe, do implement this the [intended way](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/e3d687d5ecfb2a09b40d7f50e3c8b17133fdb961/Breathe/src/components/Breathe.tsx#L281), so for Breath Activities timestamp data should be recorded as originally intended.

Surveys are a particular can of worms. EmbeddedActivity.tsx processes them differently [(there is a particular if/else that checks for a hardcoded `lamp.survey` spec)](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/ea752df49318f42f4e2cdfd71371a17eb8808cda/src/components/EmbeddedActivity.tsx#L99) and appears to avoid some preprocessing done to other activities, instead just calling a provided onComplete function.

The specific `onComplete` functions used in the NotificationPage.tsx script that I found [does not implement timestamps correctly](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/4ba5f42615580eaa9b3458ed84a0421863343afb/src/components/NotificationPage.tsx#L134). I think this is the root issue for *SURVEYS* (again, errors in the LAMP-Activities scripts may account for other issues). This issue has been present for at [least 15 months that I can tell.](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/commit/755e3ab2cd0aa77747831008241b04a1ccb28dba#diff-11abe2f443d779a9bf5e3401587112b9776900d5efe19dcad0f5a2c3852ee4e3R145)

I have attempted to tease apart the SurveyQuestions.tsx file to see if there is anything else relevant in there but it is difficult as it is largely uncommented - I can see some references to a `prefillTimestamp` but am having trouble finding out what that is. I think the root error here is the one mentioned above that occurs in NotificationPage.tsx

[(I think this is also happening in grouped activities, for the record)](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/a720455f8bcb3175e950a1cb06e5e20e6ad8fd84/src/components/GroupActivity.tsx#L79)

**Comment by sarithapillai8** [comment]
@avaidyam @lukeoftheshire 
Timestamp field value is implemented like saving the timestamp of activity event creation. So it is not saving the start, but the end of activity. This is same for all the activities. No exception for survey. And I am sorry , but this is the first time I get to know that starting time of activity is expected for timestamp value. We implemented the event creation by referring survey event which was already there as a sample. This was the initial state of the file :
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/ee5480e6e7ee108f4f54d90808456473ecc09e76/src/components/Participant.tsx#L401

If we want to change this, we need to update all the activity submissions.

@lukeoftheshire 
prefillTimestamp - this is actually not using for now, but keeping the code as @avaidyam suggested. This was for survey edit from portal screen, which is not available now.

**Comment by avaidyam** [comment]
> processes them differently (there is a particular if/else that checks for a hardcoded `lamp.survey` spec) and appears to avoid some preprocessing done to other activities

@sarithapillai8 Do you have a list of remaining hard-coded items like this in the codebase? We _REALLY_ need to move away from this kind of logic ASAP. 

> I think this is also happening in grouped activities, for the record

I think this is the main concern, for me. For most things like individual surveys, the timestamp delay will be a few minutes (far less, but sometimes more) which is negligible, since we really want to know what hour or time of day the survey was taken, usually, and how long it took. Grouped activities exhibiting this behavior concerns me because I worry that each ActivityEvent recorded within a grouped set of activities is going to either have the same `timestamp` or cascading delays. @lukeoftheshire I don't think we've noticed such a behavior though in the data we've collected? 

> Timestamp field value is implemented like saving the timestamp of activity event creation. So it is not saving the start, but the end of activity. This is same for all the activities. No exception for survey. 

It should always be saving the start of the user interaction. The timer needs to begin counting when the iframe is loaded with the script.

> And I am sorry, but this is the first time I get to know that starting time of activity is expected for timestamp value. 

This was [last mentioned here, about 3 months ago](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/411#issuecomment-994889346) (`timestamp is when the activity was opened`). It's also likely been mentioned in Basecamp in 2020 a few times. 

@lukeoftheshire To be clear, in the future, we should update the [OpenAPI comment for this field](https://github.com/BIDMCDigitalPsychiatry/LAMP-protocol/blob/0578484619073950c42c6747308581aa7328824a/openapi.yml#L3841) as well (`representation of when this event was recorded` is not as detailed as we would like).  

> This was for survey edit from portal screen, which is not available now.

Good point -- there are some very outdated sections of code still, this being one of them. We should focus on cleaning that up in the future instead, though.

**Comment by sarithapillai8** [comment]
@avaidyam 
>Do you have a list of remaining hard-coded items like this in the codebase? We REALLY need to move away from this kind of logic ASAP

We have the condition there to keep the code for the option to edit survey from portal screen to manage prefillTimestamp and prefillData.  Could you please let me know if I can remove that? otherwise I can check if that can be removed and do some alternative for that.

>It should always be saving the start of the user interaction. The timer needs to begin counting when the iframe is loaded with the script.

Ok. I can update this every activities implemented.

**Comment by avaidyam** [comment]
> We have the condition there to keep the code for the option to edit survey from portal screen to manage prefillTimestamp and prefillData.

@sarithapillai8 Please remove that. 

> an additional popup displaying for recording activity after completion

Can you share a screenshot and the code link? I'm not sure what this is.

**Comment by sarithapillai8** [comment]
@avaidyam Please see the attachment for the details : 
https://user-images.githubusercontent.com/63710347/157171787-6329924f-eaab-4d70-aa63-5db0477380e4.mp4

https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/master/src/components/NotificationPage.tsx#L248

**Comment by avaidyam** [comment]
@sarithapillai8 Why is this dialog even present in the `LAMP-dashboard` code? Please remove it.

**Comment by sarithapillai8** [comment]
@avaidyam It was asked to keep this dialog along with streak popup while implementing voice recording.  We can remove it.

**Comment by avaidyam** [comment]
@sarithapillai8 It should be part of the `lamp.recording` code in `LAMP-activities` then, not `LAMP-dashboard`. But please remove it, the streaks feature being customizable can now achieve the same thing.

**Comment by sarithapillai8** [comment]
@avaidyam There is one more hard-coded code for lamp.survey which is actually using for managing with tag.
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/master/src/components/Researcher/ActivityList/ActivityMethods.ts#L886
Could you please let me know if we need to work on changing this?

**Comment by divyav2020** [comment]
We have updated in Staging
[LAMP_Admin Website_Timestamps record END of activity.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8261530/LAMP_Admin.Website_Timestamps.record.END.of.activity.xls)

**Comment by lukeoftheshire** [comment]
DBT diary card timestamp at least still reflects when the activity was submitted.

Currently there is a bug with surveys so I can't check those, but I will update here when I am able to.

**Comment by sarithapillai8** [comment]
@lukeoftheshire 
>DBT diary card timestamp at least still reflects when the activity was submitted.

We are not able to reproduce this issue. I have opened DBT activity at time - 1649832043819. The actual end time of the activity was 1649832239141, but the activity event generated with timestamp - 1649832043855. There will be some negligible difference.

>Currently there is a bug with surveys

We are still trying to reproduce this issue. Not yet able to reproduce.

@avaidyam

**Comment by avaidyam** [comment]
What is the cause for the discrepancy in event timestamp? (completion vs submission)

**Comment by sarithapillai8** [comment]
@avaidyam 
I mentioned the opening time which is the time the activity being clicked to begin, the activity event timestamp - the time when the iFrame is loading with the activity html. Hope that will be fine.

**Comment by avaidyam** [comment]
Please use the time when the iframe is loaded as the start point, and the time when the activity is unloaded from the iframe as the end point.

**Comment by sarithapillai8** [comment]
@avaidyam 
Currently the start time is the time IFrame is loading. End time is not recording, instead the duration value changed with time difference between Iframe load-unload.

**Comment by divyav2020** [comment]
We have updated in staging
