### ISSUE TITLE
Schedules not firing for some Participants

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#55]
A few participants including `U6846466506` and `U1195842253​` (on the `api.lamp.digital` server) have not been getting Activity schedule notifications.

**Comment by Linoy339** [comment]
@avaidyam . For U6846466506, there are 2 activities named "Daily Survey"(created on 27 October) and "Weekly Survey"(created on 20 November) with schedules under the study  "College Study C". Here, we can see the second one in redis. 

For U1195842253 too, has 2 activity schedules named "Daily Survey (created on 27 October) "  and "Weekly Survey"(created on 20 November) under the study  "College Study D".  But none got entered in redis.

We are still looking into it, as we couldn't trace out the issue
Just to confirm: Is there any script which you use to dump activities to couch db directly?

**Comment by avaidyam** [comment]
@Linoy339 Thanks for checking this out - we do have a script to automate the study setup, but it interfaces only with the API and not the database directly... but this was set up before the push notifications work was integrated so it definitely could be the issue. Is there a way to manually trigger a flush and rebuild of the notifications cache? 

> //cc @jennymelcher (study coordinator)

**Comment by Linoy339** [comment]
Okay. If the issue exists only for  four activities described above , we can simply update the activity schedules of the same without applying any changes from dashboard.lamp.digital (via admin/researcher login), so that those activities gets scheduled with participant details. 
May I know what the script does?

**Comment by avaidyam** [comment]
@Linoy339 I just flushed all the schedules so I hope this will resolve the issue. [The script is located here.](https://github.com/BIDMCDigitalPsychiatry/LAMP-college-study)

**Comment by Linoy339** [comment]
@avaidyam . Yes. Now the mssing schedules got entered Redis

**Comment by avaidyam** [comment]
@jennymelcher Looks like it's fixed! Thanks, @Linoy339 🎉
