### ISSUE TITLE
TimePicker format default bug

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#555]
Around a month ago the way the TimePicker survey question determines its format (military vs. am/pm) was changed - see this commit: https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commit/b9058f567b17e58637b70ba21e1bd41de68a14f5 (example: line 494/495)

As far as I can tell, previously the format was determined by looking at the first element of an *array* of options. This is, in my opinion, not a perfect implementation - it makes it more difficult to add new options and may not be clear to an new user.

The new implentation uses an object instead, determining the format using the value associated with the `timePattern` key. This is a better implementation, but this change has created a different problem by breaking backwards compatibility. 

We have seen two direct effects from this, but there may be more:
1. TimePicker questions created before this change are now ALL defaulting to military time - obviously the property "timePattern" does not exist on an array, so the ternary always returns `""`.
2. In the dashboard, questions created before the change don't show a time pattern under "Response Options," probably for the same reason as effect 1 
<img width="922" alt="Screen Shot 2022-03-10 at 9 15 44 AM" src="https://user-images.githubusercontent.com/34659264/157683356-38c5b4bb-86f3-4633-9419-8ab4498c256f.png">

In my opinion, we REALLY need to avoid making these changes that break backwards compatibility *whenever* possible. Changing the type (e.g. `array`->`object`) of things we read from the database is going to lead to issues for us and/or collaborators unless we plan around it carefully.

I think we need to address issue number 1 by adding some additional logic to the TimePicker question that looks at the type of the `options` variable and branch based on whether it is an array or an object to support backwards compatibility. Issue 2 is not as big a deal to me since it's not affecting actual survey functionality.

**Comment by avaidyam** [comment]
@sarithapillai8 Can you share the issue where it was decided to switch the array format to an object?

**Comment by sarithapillai8** [comment]
@avaidyam 
The array format was not actually converted. This change is actually a bug fix. The actual change you can see 
 here : https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/commit/c24867b0e797eb694225526816207fed07a15c4f#diff-e6b92b145055f197fefa6d487f1d6262f67e99611638bcd76506a6679c3882dcR627
It was actually done like this before, and bug noticed at the time matrix changes I believe.

**Comment by avaidyam** [comment]
So is the `activity.settings[i].options` still an `Array` type? If so, that is correct and should stay that way, or it will break Activity/survey question parsers for downstream client libraries/scripts.

**Comment by sarithapillai8** [comment]
@avaidyam 
activity.settings[i].options - this is still an array. But time pattern is implemented like object property. I am not sure what is the issue with old data. Let me check and confirm if anything changed on survey JSON schema implementation.

**Comment by sarithapillai8** [comment]
@avaidyam This happened while changing into survey JSON schema. https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/3c0f81712e558120c5628965d08d610d50bbb273/src/components/Researcher/ActivityList/SurveyCreator.tsx#L358
Can we keep the current change and also manage the old format? because the current format looks seems better.

**Comment by lukeoftheshire** [comment]
Hi @sarithapillai8 - thanks for taking a look at this so quickly. I apologize for any confusion I might have caused. If it helps, when we look at stored activities using the API, we do see two different types stored for options:

1. I made this a day ago using the dashboard (options as dict):
```
{'id': 'bxsn1g084k89d22v71cb',
   'spec': 'lamp.survey',
   'name': 'Test Timepicker',
   'settings': [{'text': 'Pick a time',
     'type': 'time',
     'options': {'timePattern': 'military'},
     'required': True},
    {'text': 'Pick a time again',
     'type': 'time',
     'options': {'timePattern': 'standard'},
     'required': True}],
   'schedule': [],
   'category': ['assess']}
```
2. An older survey (at least 2-3 months old) (options as array):
<img width="490" alt="Screen Shot 2022-03-10 at 9 05 38 AM" src="https://user-images.githubusercontent.com/34659264/157900712-82f57907-5975-4e91-9ca0-65c20dc91854.png">

**Comment by sarithapillai8** [comment]
@lukeoftheshire  I can make the fix that can manage old format.

**Comment by avaidyam** [comment]
I think we need to revert entirely to the old format (array). We can't break data schema and legacy compatibility.

**Comment by sarithapillai8** [comment]
@avaidyam This time parameter added in Oct 2021 using old UI. But when using the old format with RJSF JSON schema the UI will look like : 
![image](https://user-images.githubusercontent.com/63710347/158106748-61e5ca84-ab28-41f3-aad3-077b59f89e15.png)
which will look like adding more options for time, which can add more confusion to the user. So can we do it like keeping current format and handle the old data?

**Comment by avaidyam** [comment]
@sarithapillai8 It should be possible to set minLength and maxLength to 1, meaning there MUST be one element ONLY. Please do that instead.

**Comment by divyav2020** [comment]
We have updated in Staging server

**Comment by tlakhtak** [comment]
timepicker questions work well on staging dashboard such that I could design a survey with both types of time and answer questions with both types of time. However, portal output didn't really make logical sense it just added them up.

**Comment by avaidyam** [comment]
@tlakhtak Can you share a screenshot of what you mean with the portal output?

**Comment by tlakhtak** [comment]
![Screen Shot 2022-04-12 at 1 51 55 PM](https://user-images.githubusercontent.com/82968538/163028895-a4828d27-4ec7-4be8-a677-eaeb1d98aa26.png)
![IMG_2941](https://user-images.githubusercontent.com/82968538/163029231-656f6d43-4b16-4e3f-84b8-24f5cf1e9b63.PNG)

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you suggest how to show this time picker response in graph?

**Comment by avaidyam** [comment]
Hmm, it's actually not easy to represent the time picker result data in a different way right now. Perhaps we need to ignore that, actually. @lukeoftheshire Can you check to make sure the Activity settings are an array and not an object? I'll mark the issue closed until further notice.

**Comment by lukeoftheshire** [comment]
The activity settings are as follows:
```
{'text': 'Matrix Time 1',
     'type': 'time',
     'options': [{'value': 'standard'}],
     'required': True}
```

**Comment by avaidyam** [comment]
@lukeoftheshire Thanks! I think this will work for now... we may need to convert it from `{"value": "standard"}` to `"standard"`. Thoughts?

**Comment by lukeoftheshire** [comment]
I'm a big fan of having a key where possible - as I said above, if it were possible within LAMP I would prefer settings to be an object entirely.

As long as we maintain backwards compatibility I think we could leave this.
