### ISSUE TITLE
Add back button on Activity-Success screen to go back.

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#559]
![success copy](https://user-images.githubusercontent.com/63795052/158227280-79b32166-9020-4505-b19e-c76bf52fed45.png)
Reference: https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/323#issuecomment-1062815254

**Comment by divyav2020** [comment]
Updated in Dashboard Staging
[LAMP_Admin Website_Back button on activity success screen.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8253359/LAMP_Admin.Website_Back.button.on.activity.success.screen.xls)
