### ISSUE TITLE
HealthKit Step Count Improvements

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#56]
1. step_count
For CMPedometer (lamp.steps), currently on every fetch interval, we are fetching cumulative steps count since the login time.

For HealthKit steps (lamp.step_count), 
We can use HKStatisticsQuery instead of HKSampleQuery to identify the source. and we can add the 'source name' in the schema of 'data'.
When we query, we can use the same predicate(cumulative steps count since the login-time) of lamp.steps.

**Comment by jijopulikkottil** [comment]
@avaidyam  Let us know if we need to change the start time as start-time-of-day rather than login-time when we query!

@amaljofyzco could you comment how the step count is calculated in android?. since login time or since startOfTheDay ?

**Comment by avaidyam** [comment]
@jijopulikkottil Login time should work fine. 👍

**Comment by jijopulikkottil** [comment]
1.
For the source (`[HKSource](https://developer.apple.com/documentation/healthkit/hksource)`), the get properties are `name` and `identifier`.
name will be like "Jijo's iPhone"
identifier will be like "com.apple.health.A7A7DCB8-2DC2-4C1B-BED7-D6497CF509A3"

So both might be different for different devices.  Should we include both properties or any one of them?

2.
Do we need to get rid of the data(step counts) which is manually entered ?

**Comment by avaidyam** [comment]
@jijopulikkottil 
1. Please only include `identifier` -- the `name` property will leak sensitive/private data (like patient names).
2. Don't get rid of it, but please use a marker to indicate it was self-entered (i.e. if `identifier` is `null` it means it was user-entered).

**Comment by jijopulikkottil** [comment]
1. yes. fine
2. If it is manual entry, the `identifier` we are getting is "com.apple.**H**ealth" (didn't find any documentation). Is that fine to pass as it is ? (Or do we need to check identifier is 'com.apple.Health' and pass nil value ?). Please comment and confirm

(FYI - For ignoring manual entry, using predicate with key `HKMetadataKeyWasUserEntered`)

**Comment by avaidyam** [comment]
@jijopulikkottil Pleas keep the identifier as is. What does it show if the pedometer automatically recorded the steps? It would be a device identifier instead of "com.apple.Health" right? If so, it will be fine.

**Comment by jijopulikkottil** [comment]
> What does it show if the pedometer automatically recorded the steps? It would be a device identifier instead of "com.apple.Health" right? 

- Yes, it will be like "com.apple.health.A7A7DCB8-2DC2-4C1B-BED7-D6497CF509A3"
