### ISSUE TITLE
When tap on push notification, load activity page on the same web view of lamp dashboard.

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#560]
The new activity page is not loading when user is interacting another activity. Android also have the same issue. 

Ref: https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/323#issuecomment-1062815254

**Comment by ZCOEngineer** [comment]
iOS and Android is progress now

**Comment by avaidyam** [comment]
I've closed issue #323 so we can redirect discussion here. Ideally this issue should resolve any "auto-logout" issues, since we determined that it was just the logout screen being shown, and not that the user was actually being logged out.

**Comment by jijopulikkottil** [comment]
@saritha made a fix on front-end to open the activity when another activity is loaded.
On app(iOS and Android) side, now we are going to open the activity (when tap on push notification) in same web view. So the login won't appear.

**Comment by jijopulikkottil** [comment]
When user open and played on second activity over the first activity, Done the issue fixes: 
1. dismiss keyboard when new activity page open [native side fix]
2. Update portal with second activity. [front end fix]

**Comment by divyav2020** [comment]
[LAMP_Admin Website_load activity page on the same web view.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8364529/LAMP_Admin.Website_load.activity.page.on.the.same.web.view.xls)

**Comment by jijopulikkottil** [comment]
Both iOS and Android code pushed.

**Comment by ertjlane** [comment]
@avaidyam Was this issue QA tested by someone on the bidmc team? I don't see a report of such here.

**Comment by avaidyam** [comment]
@ertjlane I recall testing it myself, though this was a long time ago. I think we can close this issue and reopen if it returns.
