### ISSUE TITLE
iOS - Remove all storyboards.

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#57]
Remove LaunchScreen, Main, WatchKit, and Notification storyboards.

**Comment by jijopulikkottil** [comment]
To continue, we can move to Xcode 12 and can set min. deployment target as 13.0 and can use SwiftUI.

**Comment by jijopulikkottil** [comment]
Display issues with iOS13 devices when removing `LaunchScreen storyboard` and configuring using `plist`. So should we keep it for now ?

**Comment by avaidyam** [comment]
@jijopulikkottil Let's push minimum deployment version up to iOS 14, seeing as it has 85% user adoption already.

**Comment by jijopulikkottil** [comment]
Removed all storyboards except WatchKit App. We will try to use new SwiftUI's `@main` with iOS14/Xcode12.2 so that we can remove the storyboard.
For new launch screen, we can specify background color and icon. So new launch screen will looks like:
![Simulator Screen Shot - iPhone 8 - 2020-12-11 at 11 32 00](https://user-images.githubusercontent.com/63795052/101901323-e373f680-3bd6-11eb-853e-bf4ad6128435.png)

**Comment by avaidyam** [comment]
@jijopulikkottil Yes that's perfect. @amaljofyzco This is exactly what it should look like on Android as well.

**Comment by jijopulikkottil** [comment]
1. The new launch screen is not working well (sometime the centered icon enlarged up to the screen size or getting blank) on older device below iPhone 8 (issue found on iPhone6s and iPhone6s+)

2. We are having issues with WKWebView when converted to SwiftUI. The text area is scroll away when keyboard appear. Also zoom-in issue when keyboard disappear. Tried some workarounds to fix the content height, but none are getting satisfactory output. So reverting back to ViewController (without storyboard).

3. WatchKit storyboard is still exist. To remove this, we have to migrate to new SwiftUI App life cycle. And it need more work to implement ExtensionDelegate.

**Comment by avaidyam** [comment]
1. If it's a graphical glitch that's perfectly fine.
2. As long as there's no storyboard or NIB files across the project that's okay. SwiftUI still seems pretty buggy right now. 
3. I think it's a good idea to make that change as soon as possible.

**Comment by jijopulikkottil** [comment]
hi @avaidyam ,
3. To remove storyboard and to use SwiftUI lifecycle in watch app, we have to update the watch app deployment target to watchOS 7.0. May we proceed ?

**Comment by avaidyam** [comment]
Yes, that should be fine!
