### ISSUE TITLE
Android data not collecting

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#570]
**Describe the bug**
For a study we recently started, no Android users appear to be collecting any passive data. No sensors have been added in the dashboard, so all sensors should be collecting. The majority of iOS users are collecting data.

Researcher ID: 09qmega5t15avq065re4
Test user (Android): U2898028549
Test user (iOS): U1753020007

**Additional context**
I don't know if sensors need to be added in the dashboard for Android in order for data to collect. I have set up another test user (Android; U0902905000) with just lamp.gps to see if this collects data.

**Comment by avaidyam** [comment]
Sensors must be added for data collection to work (on legacy servers without the ability to add SensorSpecs server-wide, having no sensors added will default to the pre-2021 behavior of collecting all sensor data - this is not true of our BIDMC production server). The fact that iOS is collecting data despite not having been explicitly enabled for such is actually a serious HIPAA-related concern. 

@dcurrey88 Do you know which app versions are being used on iOS and Android? (You should be able to check the lamp.analytics events.)

@jijopulikkottil Can you confirm that the logic for this was implemented correctly?

**Comment by dcurrey88** [comment]
It looks like most iOS devices are on 2022.2.28:
"NativeCore 2022.2.28; iOS 15.3.1; iPhone iPhone10,3"

And Android on 2022.0.27:
"NativeCore 2022.0.27; Android 10; samsung; SM-G9600"

Just to make sure I understand, with no sensors added the expected behavior is the same as "lamp.none" ie nothing should collect?

**Comment by avaidyam** [comment]
That's correct. `lamp.none` should not be used and will need to be removed from the server too.

**Comment by jijopulikkottil** [comment]
@avaidyam in iOS, we have not implemented the task 'collect no sensors if nothing is configured'. So our current appstore build will collect all sensors if no sensors are configured.
In Android, it ('collect no sensors if nothing is configured') is implemented.
This task was mentioned [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/145#issuecomment-971802082)

**Comment by avaidyam** [comment]
> So our current appstore build will collect all sensors if no sensors are configured.

Please make sure this is implemented ASAP!

**Comment by jijopulikkottil** [comment]
Yes it is done [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/572)
