### ISSUE TITLE
If there are no sensors for a user, no sensor data should be collected.

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#572]
Reference: https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/145#issuecomment-971802082

This task is already implemented in Android.

**Comment by jijopulikkottil** [comment]
This is completed on iOS too and the code is pushed.

**Comment by avaidyam** [comment]
@jijopulikkottil Is this available in TestFlight beta now?

**Comment by jijopulikkottil** [comment]
When merge a PR, currently the deploying task failed due to "The train version '2022.2.28' is closed for new build submissions".

**Comment by avaidyam** [comment]
Ah, that's because the version `2022.2.28` was submitted and approved for production release. The version string can't be reused. Can you modify the script to take the current date in this format `YYYY.M.D`? That should resolve it.

**Comment by dcurrey88** [comment]
This does not appear to be working in staging. I created a user in staging with no sensors added (U6942434912). They have collected GPS and accelerometer data.

**Comment by avaidyam** [comment]
@dcurrey88 (and @lukeoftheshire) Is the behavior the same on iOS and Android? (i.e. does Android also collect sensor data when it should not?)

**Comment by avaidyam** [comment]
@dcurrey88 Thanks for reporting – it's true it's an iOS specific issue but we also want to make sure we catch **all iOS/Android behavior discrepancies** as part of QA testing too! 😄

**Comment by jijopulikkottil** [comment]
@avaidyam Could you release new TestFlight version, so we can make sure all are testing with latest version of iOS app. Otherwise we have to check the build number is 343 or greater.

**Comment by avaidyam** [comment]
Why would you have to check against the app's build number? I'm not sure I understand your request.

**Comment by jijopulikkottil** [comment]
@avaidyam ignore my comment!.. I commented it without thinking -currently- we are updating the version each time we push.

**Comment by michaelmenon** [comment]
Thanks @jijopulikkottil  lets check why this issue is there in the iOS staging. Hi @avaidyam we will update on this asap.

**Comment by jijopulikkottil** [comment]
@dcurrey88 For iOS user U6942434912 , checked with /participant/U6942434912/sensor_event api, it is collecting no sensor data after updated to latest version of app.

**Comment by dcurrey88** [comment]
This appears to be working in staging.
