### ISSUE TITLE
iOS - Set low frequency for GPS if not configured.

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#573]
Set low frequency if `lamp.gps` is not declared in the user's sensor list. Also set low frequency if no sensors are configured.

In Android, location fetch will not happen if the `lamp.gps` is not declared in the user's sensor list. So this task is only needed in iOS.

**Comment by jijopulikkottil** [comment]
Now we are using the desired accuracy as [kCLLocationAccuracyReduced](https://developer.apple.com/documentation/corelocation/kcllocationaccuracyreduced) if lamp.gps is not configured or no sensors are configured.
[We are using [kCLLocationAccuracyBestForNavigation](https://developer.apple.com/documentation/corelocation/kcllocationaccuracybestfornavigation) is lamp.gps is added]

**Comment by jijopulikkottil** [comment]
This task is completed and code is pushed.

**Comment by dcurrey88** [comment]
My understanding is that GPS permissions should be asked for regardless of whether the GPS sensor is added. It seems that if multiple sensors (but not GPS) are added, the app will ask for GPS permissions, but at least for iOS if there are no sensors added then the app does not ask for permission. This may be related to #572.

**Comment by avaidyam** [comment]
Hmm, this may still be acceptable behavior, since if no sensors are added, there's no background collection process, so there's no need to use GPS callbacks to drive sensor data collection and upload. @jijopulikkottil Can you confirm this?

**Comment by jijopulikkottil** [comment]
> but at least for iOS if there are no sensors added then the app does not ask for permission

Yes, we had the same thought. Currently we keep it running with reduced accuracy. Only benefit is, we can keep app running in background, and we can reschedule local notifications if any change in activity schedule timings. 
Otherwise (if we turn-off gps) we will refetch activity schedules when app launch.

Please confirm if we need to turn-off gps if no sensors are configured.

**Comment by avaidyam** [comment]
We want GPS on for the reasons you mentioned, but @dcurrey88 reports that if there are no sensors added, the GPS prompt is not happening, so please double check that.

**Comment by jijopulikkottil** [comment]
> but @dcurrey88 reports that if there are no sensors added, the GPS prompt is not happening, so please double check that.

We will check and reply

**Comment by jijopulikkottil** [comment]
@dcurrey88 @avaidyam We think the location service is already turned on for the mindLAMP2 app. that's why it is not asking the permission again.
Please check **mindLAMP 2** app is listed under  `Settings -> Privacy -> Location Services`

We can confirm another way that , turn-off location services and relaunch (quit from background and open) the **mindLAMP 2** app , then app will show an alert that location is disabled.

**Comment by dcurrey88** [comment]
Does deleting and re-downloading the app not reset the Location Services permissions?

**Comment by jijopulikkottil** [comment]
We tested that behaviour. The location is turned on (previous state) when we check the `Settings -> Privacy -> Location Services` after delete mindLAMP app also after reinstall (delete and re-download) without open it. @divyav2020  could you confirm.
