### ISSUE TITLE
Add TTL to android push notification 

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#575]
Add `TTL `to push android notification request.

**Comment by Linoy339** [comment]
@avaidyam . We need to add `TTL` to android notification part. Can we add in
[https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L96](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L96) as we did in
[([https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L68](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L68))

**Comment by avaidyam** [comment]
@Linoy339 I'm not sure why `app-gateway` needs to be modified for this. It forwards the push notification payload exactly as provided by the client (i.e. `server` or `worker`). Please stick to modifying only the `worker` component for push notifications.

**Comment by saranya-sajeev** [comment]
@aditya In Qa testing we found an issue that , when device become online all previous notifications will appear, it is because the Firebase will retry to send the message when the device become online. To mange this we can add ttl field with zero value in push message(https://firebase.google.com/docs/cloud-messaging/concept-options#ttl). Shall we proceed on this?

Firebase
[About FCM messages  |  Firebase Documentation](https://firebase.google.com/docs/cloud-messaging/concept-options#ttl)

**Comment by jijopulikkottil** [comment]
@avaidyam , In iOS, For remote-notifications, we have handled expiry of notifications as per the expiry intervals in the push payload. But we have not handled expiry for local notifications. 

Also in iOS, for remote push notifications, we are not removing the delivered notifications. Instead we will show 'expired' alert when tap on it.

Let us know if we need any update on iOS.

**Comment by saranya-sajeev** [comment]
@avaidyam In Android, we are handling the expiry of notification based on the expiry value in push payload. For local notification, it is not handled.  In Android notification will be cancelled after specified time.
Let us know if we need to add 6 hours expiry for local notification?

**Comment by saranya-sajeev** [comment]
@avaidyam Ok.

**Comment by jijopulikkottil** [comment]
`Can you see if it's possible to remove the notification instead of just an expired alert?`
Yes.

**Comment by jijopulikkottil** [comment]
Reviewed the iOS code, for  remote-notifications, we are removing delivered notifications by using a timer. And we are showing expired alert in case the notification is still there and user tap on it. So we have nothing to work on this.

Similar to Android TTL, iOS using `apns-expiration` @Linoy339 hope we are using this header.

**Comment by Linoy339** [comment]
@jijopulikkottil . Yes, we use the header field, `apns-expiration`

**Comment by avaidyam** [comment]
Can we send an updated push notification after the expiration to remove the original one? Or is that the implementation you're both referring to?

**Comment by avaidyam** [comment]
Thanks, @jijopulikkottil, this is incredibly helpful! I think I better understand now where we are on this. No remaining questions from my end.

**Comment by Linoy339** [comment]
@avaidyam @jijopulikkottil .
From the above explained, we have to do 3 things here:
1)We need to provide UNIX epoch date expressed in seconds (UTC) here :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/blob/master/src/queue/SchedulerQueue.ts#L194]
(https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/blob/master/src/queue/SchedulerQueue.ts#L194)
2)We need to add TTL here  : [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/blob/master/src/queue/SchedulerQueue.ts#L111](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/blob/master/src/queue/SchedulerQueue.ts#L111)
3)We need to add header, `TTL`  here  : [https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L102](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L102) which arrives from `LAMP-worker`

**Comment by Linoy339** [comment]
@avaidyam . 
As we have nothing to do in this, We believe we can close this issue. Can we do it ?
