### ISSUE TITLE
Need help with getting couchdb back

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#579]
Hi, I need help with CouchDB, I was trying to clean up some of the old GPS/Accelerometer data in CouchDB senser_event database, I believe I messed up the Couch DB sensor_event database.

When I run
```
https://<mydomain>/participant/U2932822766/sensor_event?origin=lamp.accelerometer
```
I am getting
```
{
"error": "{gen_server,call,[<0.10826.1>,{get_state,130929528},infinity]}"
}
```

other databases are fine, only sensor_event database is in issue now.

when I go to Couch DB tool 'http://myservername:5984/_utils/#/_all_dbs'

I see the sensor_event

when I run the query

```
{
   "selector": {
      "#parent": "U2932822766",
      "sensor": "lamp.gps"
   }
}
```

I get result.

But i run the query

```
{
   "selector": {
      "#parent": "U2932822766",
      "sensor": "lamp.gps",
      "timestamp": {
         "$gte": 1623063653000,
         "$lte": 1623121253000
      }
   }
}
```

then I get this error
![image](https://user-images.githubusercontent.com/841011/159576262-3c751655-40f9-4ec0-9fc1-2b42e3e3fffc.png)

Is there a way to fix this? Thanks for your help!

**Comment by jeydude** [comment]
Here is the error I am getting  if I run the query with timestamp in couch db

![image](https://user-images.githubusercontent.com/841011/159576412-e8ac9df9-3e66-48cf-b9be-9c06311fe546.png)

**Comment by avaidyam** [comment]
@jeydude Unfortunately we can't provide support for CouchDB itself, and you may have better luck seeking assistance on this in their repository instead.

**Comment by jeydude** [comment]
Sorry forgot to update solution we applied to fix this, we restored the files from the server backup.
