### ISSUE TITLE
Survey questions are not showing up (but answer options are)

### ISSUE THREAD

**Issue by elenamrv** [BIDMCDigitalPsychiatry/LAMP-platform#58]
Hi @sarithapillai8 , 

A handful of people are not seeing survey question 1 (out of 75) on both android and apple devices. They can see answer options, but not the question itself. See attached for the photo I shared in this morning's meeting. I will send the user info to you over basecamp! Thanks.

<img width="578" alt="6UexL2rk_o" src="https://user-images.githubusercontent.com/74274511/101361617-36634c00-386d-11eb-85f3-6751960acd7f.png">

**Comment by sarithapillai8** [comment]
Elena, the same block of code is handling the similar type survey question. So it seems like the question text is missing in the survey itself as the next question is visible with similar options.  I got the credentials and checked the web app, and same missing is there. But I don't have researcher credentials, so I am not able to confirm whether the question is actually there in the survey.

**Comment by elenamrv** [comment]
Hi @sarithapillai8 ,

The researcher on our team checked and the Question 1 is there on the survey on the research side. I've attached a photo:

![Screen Shot 2020-12-07 at 10 37 55 AM](https://user-images.githubusercontent.com/74274511/101371105-6106d200-3878-11eb-94ef-0522785d439e.png)

**Comment by sarithapillai8** [comment]
@avaidyam 
The fix for this issue is included in the pull request added to the master branch.
