### ISSUE TITLE
Malformed sensor event post

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#584]
A researcher is reporting seeing a 403 error occur for some of their user's sensor event data post requests.

```
POST /participant/U7219056717/sensor_event 200 - 6.516 ms
Failure Msg On sensor events post 403.security-context-out-of-scope
POST /participant/U7219056717@lamp.com/sensor_event 403 - 38.392 ms
```

I am unclear as to what exactly may be causing this but I do note that the second request is actually made for the participant `U7219056717@lamp.com` -- note the inclusion of `@lamp.com`. Could this be causing the error? If so, we should probably fix this as soon as possible. Unfortunately, I am not sure exactly what sensor event post is calling this but I will post any updates here as soon as I get them.

**Comment by Linoy339** [comment]
@lukeoftheshire . The request `POST /participant/U7219056717@lamp.com/sensor_event` is completely invalid. Is  this request from lamp side or other collaborator's? 
This  (`403.security-context-out-of-scope`) happens because of reasons mentioned below:
1) The user might got deleted
2) Basic auth might got wrong .

**Comment by lukeoftheshire** [comment]
The researcher further reports:
```
This POST happens when I logged out from the iOS app:
POST /participant/U7219056717@lamp.com/sensor_event
and finally failed as mentioned earlier.
```

Is it possible this is related to issue #506? I ask since this post event appears to be triggered by a logout.

**Comment by sarithapillai8** [comment]
@lukeoftheshire 
Could you share more details for this like server details or how to reproduce? Can you confirm whether the client is using latest version? We have checked the events created in web, Android, iOS devices. We couldn't reproduce the issue.
[U4438904359_SE.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8470279/U4438904359_SE.txt)

**Comment by lukeoftheshire** [comment]
Hi @sarithapillai8, the researcher sent along this additional list of server logs:

```
GET /participant/U6554671513 200 - 14.168 ms
POST /participant/U6554671513/sensor_event 200 - 47.107 ms
POST /participant/U6554671513/sensor_event 200 - 103.946 ms
PUT /type/U6554671513/attachment/lamp.participant.timezone/me 200 - 104.917 ms
GET /participant/U6554671513/sensor 304 - 60.105 ms
GET /participant/U6554671513/activity?ignore_binary=true 200 - 52.064 ms
GET /participant/U6554671513/activity?ignore_binary=true 304 - 33.266 ms
GET /type/U6554671513/attachment/lamp.dashboard.hidden_events 404 - 92.253 ms
POST /participant/U6554671513/sensor_event 200 - 22.758 ms
GET /type/e291psaece8gesgcemsz/attachment/lamp.dashboard.activity_details 200 - 191.224 ms
POST /participant/U6554671513/sensor_event 200 - 25.570 ms
Failure Msg On sensor events post 403.security-context-out-of-scope
POST /participant/U6554671513@lamp.com/sensor_event 403 - 59.147 ms
Failure Msg On sensor events post 403.security-context-out-of-scope
POST /participant/U6554671513@lamp.com/sensor_event 403 - 45.696 ms
```

They are using the latest version of the LAMP server on an iOS device. They also add that this error appears to fire on logout.

**Comment by sarithapillai8** [comment]
@lukeoftheshire
Are they using latest LAMP-dashboard? This logout sensor events are added from dashboard not from server. So could you please confirm?
 @avaidyam

**Comment by FrancisThibaultNRC** [comment]
@lukeoftheshire ,
In fact, I used your dashboard (dashboard.lamp.digital, version 2022.2.22) to create the study and even if I use the App mindlamp 2 version 2022.4.23, when I logout from the App, I am still having that bad POST while looking at the log of the dcoker server container:

**Comment by Linoy339** [comment]
> and it seems that no sensor data is streamed to the database, even if I wait for a long period of time.

@FrancisThibaultNRC .  Did you place variables `CACHE_SIZE` and `CACHE_FLUSH_ALL` in env ? If yes, can you please let us know the values which you have kept in ?

**Comment by sarithapillai8** [comment]
@lukeoftheshire We are not yet able to reproduce this. Tried different logins, we could not see such requests. 
Failure Msg On sensor events post 403.security-context-out-of-scope
POST /participant/U6554671513@lamp.com/sensor_event 403 - 43.846 ms

@avaidyam With assumption, we did one change and added PR a few days back. As we couldn't reproduce the issue, we put that PR on hold. https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/586/files. Do you have any suggestion on this?

**Comment by FrancisThibaultNRC** [comment]
Good morning @Linoy339,

We did not set those two variables,, I guess default values will be assumed.

Thanks.

Francis

**Comment by Linoy339** [comment]
Good morning  @FrancisThibaultNRC 
Can you please confirm that you are using latest LAMP-server version (bidmcdigitalpsychiatry/lamp-server:2022 or bidmcdigitalpsychiatry/lamp-server:latest ?

**Comment by FrancisThibaultNRC** [comment]
@Linoy339,
we are using the latest version of LAMP-server.
Francis

**Comment by Linoy339** [comment]
Can we have the api server url and credential (test credential) to check from our side 
or can you check latest sensor event record inserted for U6554671513 ?

**Comment by Linoy339** [comment]
Thanks @FrancisThibaultNRC. Please let us know

**Comment by Linoy339** [comment]
Also, Can we confirm that the database you are using is `mongodb` ?

**Comment by FrancisThibaultNRC** [comment]
We have been using apache/couchdb in the docker env, so I do not know if mongodb is used behind the scene.

**Comment by Linoy339** [comment]
@FrancisThibaultNRC .
Okay. Thanks for the information.

**Comment by sarithapillai8** [comment]
We are not yet able to reproduce this issue.

**Comment by Linoy339** [comment]
> @Linoy339 I am doing some tests today, and will let you know about the sensor event record inserted for U6554671513. Thanks. Francis
@FrancisThibaultNRC 
Did you find any `sensor_events ` for this user ?

**Comment by FrancisThibaultNRC** [comment]
Good morning @Linoy339 ,
yes I have finally found some sensor events for that user, however, no screen_state event recorded.
Thanks.
Francis

**Comment by Linoy339** [comment]
Thanks for the information @FrancisThibaultNRC .

**Comment by sarithapillai8** [comment]
@avaidyam We have added a fix for the issue. The issue found after tab change from browser. Hope this is the same happening with mobile app on hidden/visibility event changes. Update is available on dashboard-staging now.

**Comment by FrancisThibaultNRC** [comment]
@avaidyam ,

So you have been able to reproduce the issue, great news!

Thank you so much.

Francis

**Comment by sarithapillai8** [comment]
We have checked sensor events in different scenarios and it seems fine.  As this is a backend process, @lukeoftheshire  Could you check from your side?
