### ISSUE TITLE
Cannot schedule activities for 4/1

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#585]
**Describe the bug**
Activities cannot be scheduled for today (4/1). 

**To Reproduce**
If I try to programmatically schedule the activities, they will not show up in the feed. If I try to add a schedule on the dashboard, it will change the date to 5/1. This does not seem to be an issue for other days (4/2 etc).
<img width="1225" alt="Screen Shot 2022-04-01 at 8 49 07 AM" src="https://user-images.githubusercontent.com/21200061/161266841-1d27e4bb-e628-4ffa-b96a-a5598c442458.png">

<img width="1227" alt="Screen Shot 2022-04-01 at 8 49 21 AM" src="https://user-images.githubusercontent.com/21200061/161266937-880d861e-a47f-43ef-944c-414bff843313.png">

**Comment by tlakhtak** [comment]
Also cannot schedule activities for November 1, changes date to December 1

**Comment by lukeoftheshire** [comment]
Also cannot schedule for February, June, September 1st

As we all know, "30 days hath September, April, June, and November...except for February, which has 28" so I'm guessing the error has something to do with validation checking for months w/ less than 31 days. No error is being thrown in the console, by the way.

**Comment by divyav2020** [comment]
We are unable to reproduce this issue

**Comment by divyav2020** [comment]
We have updated in Staging
[LAMP_Admin Website_Activity schedule on apr 1st.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8451660/LAMP_Admin.Website_Activity.schedule.on.apr.1st.xls)

**Comment by dcurrey88** [comment]
This appears to be fixed in staging. However, if I try to create a schedule without specifying a repeat interval nothing will happen. The schedule will show in Activity data from the API (with repeat interval set to None) but will not show up in the dashboard or in the feed. It seems that there should be some sort of notification to the user that this information is required.

**Comment by evinkalengaden** [comment]
We have updated the issue in the dashboard-staging. In such way that, User will not be allowed to save a schedule until the (Repeated Interval, Start Date and Time) are added. On editing schedule also same condition is validated. Please find the validation screenshot attached.
