### ISSUE TITLE
Filter for Portal page does not persist 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#586]
Toggle filter to select range of data displayed in visualizations when using the DBT diary card do not persist after leaving and returning to the Portal page, either when leaving to a different page in the app or when leaving the app entirely.

**Comment by tlakhtak** [comment]
Additionally - the 'Didn't use skills' visualization does not appear to have its own filter as the rest of the individual visualizations do.

**Comment by sarithapillai8** [comment]
This seems a change, not a bug . We didn't consider this before.

**Comment by divyav2020** [comment]
We have updated in staging
[LAMP_Admin Website_Filter for Portal page does not persist.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8918259/LAMP_Admin.Website_Filter.for.Portal.page.does.not.persist.xls)

**Comment by Devayani0102** [comment]
This seems to be fixed in staging
