### ISSUE TITLE
Scratch Card images not center aligned

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#588]
Scratch card images are not shown at a consistent size. Additionally, the images are centered horizontally but not vertically. This can lead to cases where a user can swipe and reveal no image, which is then confusing when the completion message shows up.

Small image is horizontally centered but not vertically:
![Screen Shot 2022-04-06 at 8 52 09 AM](https://user-images.githubusercontent.com/34659264/161979523-b47dccd7-8470-4c60-ab89-364f4ea88537.png)

Image improperly aligned:
![Screen Shot 2022-04-06 at 8 51 07 AM](https://user-images.githubusercontent.com/34659264/161979525-350ecc9b-db6a-412e-b1f4-1b0490ac6237.png)

Another of the small image:
![Screen Shot 2022-04-06 at 8 50 20 AM](https://user-images.githubusercontent.com/34659264/161979529-eebaefa9-a8cf-49ad-ae53-895d74e5ce09.png)

Example of not finding an image:
![Screen Shot 2022-04-06 at 8 42 34 AM](https://user-images.githubusercontent.com/34659264/161979531-481d7a82-7d0c-4953-9aba-d3099cec6984.png)

**Comment by divyav2020** [comment]
We have updated in Staging
[LAMP_Admin Website_Scratch Card images not center aligned.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8451669/LAMP_Admin.Website_Scratch.Card.images.not.center.aligned.xls)

**Comment by lukeoftheshire** [comment]
Can confirm this issue is fixed in dashboard-staging
