### ISSUE TITLE
Notifications are not taking users to an activity - instead, they are seeing a blank screen

### ISSUE THREAD

**Issue by elenamrv** [BIDMCDigitalPsychiatry/LAMP-platform#59]
We have reports from different that users that when they click on a notification, they are not taken to the intended activity or survey. Instead, they see a blank screen OR are shown an "error." Please see the below for a video of the issue:

[Video.mov.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5659582/Video.mov.zip)

I think this was a previous issue, but the problem seems to persist.

**Comment by sarithapillai8** [comment]
@elenamrv 
The notification gets expired after the time limit - 5mins. In the video it is shown as the notification received 13mins ago. This is not actually rendering the blank page, instead it is showing expired popup, and redirected to home screen as it is expired.

**Comment by elenamrv** [comment]
@sarithapillai8 is it possible to make it so that a notification will always take you to the desired activity? 5 minutes is a very short window.

**Comment by sarithapillai8** [comment]
@avaidyam @elenamrv 
The notification is for the scheduled activity. If we do not need any time restriction for this schedule, we can remove the expiry. Otherwise we need to manage different expiry time based on the schedule type. 
For eg :  Hourly scheduled activity will have 1 hour expiry limit, daily will have 24 hour , once in 3 hours will have 3 hour expiry time. 
So could you please confirm notification expiry is not needed at all or do we need to manage it based on schedule type?

**Comment by avaidyam** [comment]
@sarithapillai8 @elenamrv So this sounds more like a quick fix for @Linoy339 to update the `expiry` parameter, and the blank screen is actually bugs #37 and #52.

**Comment by Linoy339** [comment]
@avaidyam . Is it to make expiry as null or to update it in a manner which @sarithapillai8 said ?

**Comment by avaidyam** [comment]
@Linoy339 Let's make it 6 hours for now (i.e. `6h * 60m * 60s * 1000ms = 21600000ms`). In the future the `expiry` parameter may need to come from the `Activity`'s `schedule` (allowing clinicians to set it).

**Comment by Linoy339** [comment]
Yes. We will make it 6 hours then for time being

**Comment by Linoy339** [comment]
@avaidyam . Its done. Please check [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/35](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/35)

**Comment by avaidyam** [comment]
@Linoy339 Great - just merged it. All of these changes are now in the staging environment so could you do another round of stability testing to make sure nothing crashes/fails before we push to production?

**Comment by Linoy339** [comment]
@avaidyam . We will do a round of testing and let you know

**Comment by Linoy339** [comment]
@avaidyam. We have tested. Its found that no apns-collapse-id in  app-gateway ios notification part. This is required for autoremoval of notification after expiry period(as Jijo said). Also, deviceType need to be passed inorder to identify whther its phone or watch. For phone, the apns-push-type should be "alert" and "background" for the watch. All these changes has been pushed and initiated a pull request in app- gateway. Please check [https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/pull/4](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/pull/4)

Also, we had to do some minor change(notificationId generation) in ShedulerQueue. This is also given as a pull request.
Please check  [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/36](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/36)

**Comment by avaidyam** [comment]
@Linoy339 I think these changes should only be made in `LAMP-server` and not in `LAMP-app-gateway`. These same parameters can be added to the body of the request already. Please make a new PR to update the `LAMP-server` repo with these minor changes.

**Comment by Linoy339** [comment]
@avaidyam . But, apns-collapse-id and apns-push-type need to be passed from app-gateway like this :
[https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/pull/4/files#diff-e07d531ac040ce3f40e0ce632ac2a059d7cd60f20e61f78268ac3be015b3b28fR75](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/pull/4/files#diff-e07d531ac040ce3f40e0ce632ac2a059d7cd60f20e61f78268ac3be015b3b28fR75)

Can you please check ?

**Comment by avaidyam** [comment]
@Linoy339 [This is the correct implementation for adding support for those parameters.](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/pull/5) Please adjust your code accordingly.

**Comment by Linoy339** [comment]
Okay. Is the new changes in app-gateway deployed in server. Can I call test it locally ?

**Comment by avaidyam** [comment]
@Linoy339 Yes - the changes should be live.

**Comment by Linoy339** [comment]
@avaidyam .Can you please put buffer variable above the HEADERS variable. Its making some error, it seems.

[https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L73](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/master/app.js#L73)

**Comment by avaidyam** [comment]
Done and updated!

**Comment by Linoy339** [comment]
Thank you.

**Comment by Linoy339** [comment]
Please check 
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/37](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/37)
