### ISSUE TITLE
App crashes with null pointer error

### ISSUE THREAD

**Issue by nsrilakshmi96** [BIDMCDigitalPsychiatry/LAMP-platform#592]
**Describe the bug**
Trying to open the app after keeping it in the background for a while, the app opens and immediately closes and on trying to open the app, a blank white screen opens. 

**Smartphone (please complete the following information):**
 - Device: Samsung A50s and Samsung M31
 - OS: Android 11

**Additional context**
Error in LampLog.txt
java.lang.RuntimeException: Unable to start service digital.lamp.lamp_kotlin.sensor_core.Screen@9855aca with null: java.lang.NullPointerException:
[Samsung_A50s.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8445365/Samsung_A50s.txt)
[Samsung_M31.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8445366/Samsung_M31.txt)
![Screenshot_20220407-103638_mindLAMP](https://user-images.githubusercontent.com/46331228/162266102-6085dc3d-d000-4d16-8d7e-738f8fa5cc1b.jpg)

**Comment by saranya-sajeev** [comment]
@nsrilakshmi96 Could you please share the app version?

**Comment by nsrilakshmi96** [comment]
Version - 2022.0.27

**Comment by saranya-sajeev** [comment]
@nsrilakshmi96 Are you using the latest beta version?

**Comment by nsrilakshmi96** [comment]
@saranya-sajeev No, I'm using the production version. Last updated was on March 6.

**Comment by saranya-sajeev** [comment]
@nsrilakshmi96 We have already added a fix for this issue and it is available in the beta version. Could you please try the beta?

**Comment by nsrilakshmi96** [comment]
@saranya-sajeev I've installed the beta version now. Will keep the app running and let you know if it doesn't crash with the same error.

Should we apply the same fix to the participants in the study or will the code be updated in the production release?

**Comment by saranya-sajeev** [comment]
@nsrilakshmi96 Beta will be pushed to production soon.

**Comment by avaidyam** [comment]
@saranya-sajeev Please do not push it to production on your team's end - my team needs to do a full round of QA testing first and we will push it once everything is confirmed okay.

**Comment by saranya-sajeev** [comment]
@avaidyam no we will not push to production.

**Comment by saranya-sajeev** [comment]
@avaidyam as per our current implementation the [WhatTheStack](https://github.com/haroldadmin/WhatTheStack) will work only in debug build. Shall I change it to work in release build and commit?

**Comment by avaidyam** [comment]
Yes, please do that.

**Comment by saranya-sajeev** [comment]
@avaidyam Committed to beta after change and it is In Review status.

**Comment by saranya-sajeev** [comment]
@nsrilakshmi96 Is this issue exists in the new beta build?

**Comment by nsrilakshmi96** [comment]
@saranya-sajeev No, haven't had this issue in beta. Thanks!

**Comment by saranya-sajeev** [comment]
@nsrilakshmi96 thanks for the update.
