### ISSUE TITLE
Several bugs for one user: looping, adaptive interventions error, notifications error

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#593]
User U3600685320, on Android device Samsung Galaxy S22 Ultra reported that they were experiencing an issue where the adaptive intervention script would send them a notification for an activity but when they clicked on it, it never opened up the corresponding tip or mindfulness activity, and there was essentially no record for them to use to determine what activity they had been assigned to do.

Notifications for feed-scheduled activities also did not directly lead to the activity - the app would default to a loading screen and then Assess page. Sometimes, they could simply go to the feed and click on the activity, but sometimes the feed would report that they completed it even if they did not.

Looping of activities is continuing, though since we have a fix for this upcoming this does not need to be worked beyond that, but a note that it was occurring with them in case it happens again.

**Comment by avaidyam** [comment]
Thanks for sharing - I'm marking this as a duplicate and closing it for now since all the sub-issues are tracked separately, but we can reopen it after QA testing the production release if these issues persist.
