### ISSUE TITLE
Back button on Learn tips not working 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#594]
For LAC dashboard, v1871 (2022.2.22) after selecting "Learn tab" and then picking a Learn activity the Back arrow button does not seem to be working, I remain on the same page after clicking the back arrow icon:

**Comment by sarithapillai8** [comment]
@avaidyam This is already fixed in dashboard-staging.

**Comment by lukeoftheshire** [comment]
This is not fixed in dashboard staging - my back button does not work.

**Comment by evinkalengaden** [comment]
We were able to navigate back from the activities and survey took from the Learn, Access, Manage and Portal. But it never stuck in the same screen of activities especially TIPS or surveys on back navigations. Refer the recording attached.

**Comment by sarithapillai8** [comment]
@lukeoftheshire @avaidyam @michaelmenon
Updates are available in staging build . Please find the attachment.
Note:  Beta/TestFlight builds are pointed to production build where the dashboard updates are not available. Could you confirm on this?

https://user-images.githubusercontent.com/63710347/163177493-f4e5f608-2372-4191-b5b5-1a256e13b936.MP4

**Comment by avaidyam** [comment]
@sarithapillai8 @jijopulikkottil @saranya-sajeev @michaelmenon 
It should have always been the case that beta builds for iOS and Android point to dashboard staging. I recall we specifically set up build configs for this. Can we double check this is still the case, and if not, address it immediately?

**Comment by michaelmenon** [comment]
Thanks @avaidyam we will check and update the build pointing to staging.

**Comment by jijopulikkottil** [comment]
Ok, both iOS and Android, we can pointed to staging server in case of 'Push'. And can pointed to production server in case of Github 'release'.

**Comment by evinkalengaden** [comment]
Right now, the beta build is live. We have tested the build and its working fine.
We will update you status on iOS TestFlight build soon, Once it got live.

@avaidyam @michaelmenon @lukeoftheshire

**Comment by jijopulikkottil** [comment]
iOS Test flight build (staging pointed) is submitted for beta review.

**Comment by evinkalengaden** [comment]
The iOS beta build (Pointed to staging) is **Ready for test** in TestFlight. We have tested the build and its working fine.

@avaidyam @michaelmenon @lukeoftheshire

**Comment by lukeoftheshire** [comment]
QA Android looks good - I can now exit a tip using the in-app back button.

**Comment by tlakhtak** [comment]
appears fixed on iOS as well
