### ISSUE TITLE
DBT Portal View

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#595]
Date range for Actions (Summary) visualization is not present for DBT
![Screen Shot 2022-04-08 at 3 33 45 PM](https://user-images.githubusercontent.com/82968538/162511942-4d2505cc-4cbd-4bad-8e39-93dfec2a27cb.png)

**Comment by evinkalengaden** [comment]
We have updated in Staging.

[LAMP_DBTview.on.apr.12th.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8472658/LAMP_DBTview.on.apr.12th.xls)

**@avaidyam**
