### ISSUE TITLE
Toggling battery saver mode with LAMP open crashes LAMP

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#598]
Toggling battery saver mode while in LAMP, *but LOGGED OUT* leads to a crash.

![Screenshot_20220412-140341](https://user-images.githubusercontent.com/34659264/163025761-a40d803f-b2c1-4a18-b5c0-9f25bb50a2d9.jpg)

This does not occur if logged in.

**Comment by dcurrey88** [comment]
For the record, low power mode appears to work for iOS:

```
{'sensor': 'lamp.analytics',
  'data': {'device_type': 'iOS',
   'value': 1,
   'user_agent': 'NativeCore 2022.2.28; iOS 15.3.1; iPhone iPhone10,4',
   'action': 'lowpowermode'}
```

**Comment by avaidyam** [comment]
@lukeoftheshire Does this same thing happen when you're logged in? I imagine the app is trying to post the sensor event regarding low power mode enable/disable but isn't authenticated. It seems like there are many cases where null data isn't being appropriately handled or unwrapped before a method or API call... [despite Kotlin having advanced null safety features.](https://kotlinlang.org/docs/null-safety.html) //cc @saranya-sajeev @michaelmenon

**Comment by lukeoftheshire** [comment]
No, this does *not* occur if not logged in.

**Comment by lukeoftheshire** [comment]
QA checked in beta, looks good! Gonna close this as it seems to be fixed
