### ISSUE TITLE
HTTP Security Headers

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#599]
- [ ] All API responses should provide header `Cache-Control: no-store`
- [ ] All API responses should provide header `Content-Security-Policy: default-src 'self'`
- [ ] All API responses should provide header `X-XSS-Protection: 1; mode=block`
- [ ] All API responses should provide header `X-Content-Type-Options: nosniff`
- [ ] All API responses should provide header `X-Frame-Options: deny`
- [ ] All API responses should provide header `Strict-Transport-Security: max-age=31536000; includeSubdomains`

We will need to add these headers and **confirm all API and dashboard behavior remains unchanged.** Should any header cause problems in loading API results or dashboard pages, we will need to identify and remove those specific headers only, temporarily.

**Comment by Linoy339** [comment]
@avaidyam .  Can we push this to staging?
If we release this week, this would also gets pushed to live. If the release is planned next week, QA will get enough time for testing it

**Comment by avaidyam** [comment]
Unfortunately we want to push to production this week, so please hold off on merging this into staging! You can keep an open PR for this though.

**Comment by Linoy339** [comment]
Okay. We can do after the release

**Comment by carlan1** [comment]
Appears fixed in staging
