### ISSUE TITLE
Automation engine core system

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#6]
Basecamp Conversation: 
---
> **@michaelmenon set the ETA to 11/18/20.**
> @michaelmenon: This includes the development of all the Listener APIS and NATS publishers and subscribers as defined the in the architecture proposed for the Automation engine.

**Comment by michaelmenon** [comment]
Hi @avaidyam, we will be working on a consumer which we will be developed in Go for now and later will replace it with node JS implementation. Consumers are responsible to subscribe to event tokens to NATS server and based on the data received for a specific token will run the corresponding uploaded script. 

You can upload a JS script or a Python script to the consumer with the curl command : 

For eg : if  you want to run a JS script whenever the consumer receives a data for the study id 1234, the token will be passed as the query parameter in this format study.studyid

 curl -F 'jsscript=@/path/to/script.js' http://consumeraddress/uploadJSScript?token="study.1234"

to upload a python script : 

 curl -F 'pyscript=@/path/to/script.js' http://consumeraddress/uploadPYScript?token="study.1234"


Consumer service will be subscribing to the NATS server for each token and when it receives the data it will run the uploaded script in a separate child process.


Consumer will keep a collection of tokens and paths to the uploaded script in the couch DB.

**Comment by michaelmenon** [comment]
@avaidyam It will be given for internal testing by tomorrow and then we can push this to staging for your testing by Friday.

**Comment by Linoy339** [comment]
HI @avaidyam . We need to commit listener api and corresponding changes(Lamp server). Do I need to create a pull request for this against production or staging? We can test in staging properly and move to production

**Comment by Linoy339** [comment]
We have committed our changes to the branch, nats-publish.  You have to set the nats server address in env and the variable for this is NATSServers (eg: NATSServers=0.0.0.0:4222).  If you can deploy in staging server, we can test it.
Pull request has been created against master.

**Comment by avaidyam** [comment]
@Linoy339 @michaelmenon Thanks, this is great - let me spin it up in staging, review it in depth, and respond with some comments by Monday!

**Comment by michaelmenon** [comment]
Hi Aditya, Linoy was in the process of changing the GET method to SUBSCRIBE for the SSE server , in that case we also need to change the SSE consumer  and it seems al the client libraries for SSE uses GET by default and we may need to change the library code in order to use SUBSCRIBE for the SSE client
this may become an issue for other clients as well when they are trying to connect to the SSE server
let us know if you still want to change the method from GET to SUBSCRIBE

**Comment by avaidyam** [comment]
@michaelmenon This is a really good catch (and a surprising one)... let's change it back to `GET /subscribe` temporarily.

**Comment by avaidyam** [comment]
@michaelmenon Is there any progress on the 2nd half of this? (i.e. what was written in Go but in TypeScript instead.)

**Comment by michaelmenon** [comment]
Hi @avaidyam Linoy will be working on that after we complete the unit test cases for all the UI elements as that is a priority item we need to complete. Also we need to check for any good package that runs a command as a separate process like  Go. does.

**Comment by avaidyam** [comment]
> good package that runs a command as a separate process
Just to clarify, what would this be for? I had thought the engine would be using Docker to launch scripts in their own isolated containers?

**Comment by avaidyam** [comment]
@michaelmenon mentioned the potential ETA is in 2.5 weeks (approx. 01/21/2021).

**Comment by Linoy339** [comment]
@aditya. Can you explain more on scriptrunner.ts and the way it is used ?

**Comment by avaidyam** [comment]
[For reference, this file is `ScriptRunner.ts`.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/master/src/utils/ScriptRunner.ts) It contains the following pieces: 
1. A queue on which executing commands will be run one-after-the-other. 
2. Several sub-classes for different types of scripts (`Bash`, `R`, `Py`, and `JS` -- only the first two are important).
3. `func containerExec()` which runs a new command inside an already-running container, returning the `stdout` to the caller.
4. `func makeTar()` which takes an object mapping strings to `Buffer`s and converts it into a single tar file. 
5. `func getFileInTar()` which extracts a single file as a `Buffer` from an existing tar file. 
6. `func systemDocker()` which creates and starts a new docker container with given options, and then executes a command inside of it. 

Within a specific ScriptRunner sub-class, such as `R`, here is the flow of execution: 
1. [Set up a template `Dockerfile` and `driverScript`.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L121) The `Dockerfile` is used to build the image and the `driverScript` is executed within a running container to interface between the `LAMP-server` code and the script itself. 
2. [If the Docker image DOES NOT exist, create it using the `Dockerfile`.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L215)
3. [Specifically for `R`, there is a helper command we have to execute to fix its libraries.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L229)
4. [Create the Docker container from the image. (R again specifically has a bind-mount to fix libraries...)](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L242)
5. [Inside the running container, execute a command that installs all the requirement libraries that the script declares. ](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L256)
6. [Copy the driver script, the user-specified script, and the input data into the container. ](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L276)
7. [Run the driver script and add its output to the running logs for this execution. ](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L284)
8. [Retrieve the script's output files from the container and extract the specific `stdout` file we need. ](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L287)
9. [Save the `output` and `logs` data to a Tag.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L290)
10. [Stop and delete the container. ](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/ScriptRunner.ts#L299)

Please keep in mind that the `R` code described above is more than what we want for this feature.

**Comment by Linoy339** [comment]
@aditya. As we discussed, Can you please provide a repository to work with Lamp-consumer?

**Comment by avaidyam** [comment]
@Linoy339 [It's here.](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker)

**Comment by Linoy339** [comment]
Thank you @avaidyam

**Comment by Linoy339** [comment]
Hi @avaidyam . When we tried to execute script, we faced some issues.
Can you please provide what arguments which you gives inside execute() function in ScriptRunner.ts.
Can you provide a sample call ?

**Comment by avaidyam** [comment]
Essentially it is the script code itself as a string, and the requirements indicate what packages need to be installed for the script. I do not have more information/sample code for it as the code is from 2018 and should not be used.

**Comment by Linoy339** [comment]
OKay. Thanks

**Comment by Linoy339** [comment]
It seems like I do not have permission to the repository: [https://github.com/BIDMCDigitalPsychiatry/LAMP-worker.](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker.)

**Comment by Linoy339** [comment]
Please find the PR:
[https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/1
](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker/pull/1)
