### ISSUE TITLE
Unify Android and iOS device_motion and accelerometer

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#602]
**Is your feature request related to a problem? Please describe.**
For iOS, lamp.accelerometer holds (x, y, z) coordinates and lamp.device_motion holds several other fields (motion, magnetic, altitude, gravity, rotation).

accelerometer:
```
{'sensor': 'lamp.accelerometer',
   'data': {'x': -0.0314483642578125,
    'y': -0.559173583984375,
    'z': -0.862274169921875},
   'timestamp': 1649504370983}
```
device_motion:
```
{'sensor': 'lamp.device_motion',
   'data': {'motion': {'x': -0.0017750263214111328,
     'y': 0.004897803068161009,
     'z': -0.00017660856246948242},
    'magnetic': {'x': 3.450927734375,
     'y': 8.881887435913086,
     'z': 53.096649169921875},
    'attitude': {'x': 2.9586798819128934,
     'y': 0.1373790520467436,
     'z': -0.9628289634642353},
    'gravity': {'x': 0.18018077313899994,
     'y': -0.13694733381271362,
     'z': 0.9740535616874695},
    'rotation': {'x': 0.001726057380437851,
     'y': -0.008104033768177036,
     'z': 0.004878027364611627}},
   'timestamp': 1647386641091}
```

Android appears to have the same fields as iOS device_motion in accelerometer and device_motion (except data is missing):

lamp.accelerometer
```
{'data': {'attitude': {},
    'gravity': {},
    'magnetic': {},
    'motion': {'x': -0.029183924198150635,
     'y': 0.04290225729346275,
     'z': 10.087298393249512},
    'rotation': {}},
   'sensor': 'lamp.accelerometer',
   'timestamp': 1649785600330}
```
lamp.device_motion
```
{'data': {'attitude': {},
    'gravity': {},
    'magnetic': {},
    'motion': {},
    'rotation': {'x': 0.0004161493852734566,
     'y': 2.6726163923740387e-05,
     'z': 0.00042760511860251427}},
   'sensor': 'lamp.device_motion',
   'timestamp': 1649861612058},
```

**Describe the solution you'd like**
It would be useful if the data was consistent across Android and iOS (Android fits the iOS format). We would also need to do some sort of database migration-type script to backfill the data.

**Comment by saranya-sajeev** [comment]
@dcurrey88 In Android  we will change lamp.accelerometer format same as in iOS.

**Comment by avaidyam** [comment]
@jijopulikkottil @saranya-sajeev Are there any implementation differences between lamp.accelerometer and lamp.device_motion on iOS right now?

**Comment by jijopulikkottil** [comment]
on iOS, `lamp.accelerometer` data is
```
 {'x': -0.0314483642578125,
    'y': -0.559173583984375,
    'z': -0.862274169921875}
```
But on Android `lamp.accelerometer` data is
```
{'attitude': {},
    'gravity': {},
    'magnetic': {},
    'motion': {'x': -0.029183924198150635,
     'y': 0.04290225729346275,
     'z': 10.087298393249512},
    'rotation': {}}
```
Now Android side fixing it to make similar to iOS.

**Comment by avaidyam** [comment]
Thanks! `lamp.accelerometer` should be the raw `x, y, z`, and `lamp.device_motion` should be the more complex object with `attitude, gravity, magnetic, motion, rotation` fields, with their own `x, y, z` sub-components. Both of these must be separate SensorSpecs, so if you add `lamp.accelerometer`, you get the RAW data, and if you add `lamp.device_motion` you get the filtered sub-component data. @jijopulikkottil Is that how iOS is set up right now too?

**Comment by jijopulikkottil** [comment]
@avaidyam  Yes correct.

**Comment by saranya-sajeev** [comment]
@avaidyam lamp.accelerometer dat modified as iOs and given for Qa testing.

**Comment by ZCOEngineer** [comment]
QA is in progress on this issue. we noticed a discrepancy and @saranya-sajeev is fixing it.

**Comment by divyav2020** [comment]
We have updated in staging

**Comment by carlan1** [comment]
Android accelerometer data is in proper format:
{'data': {'x': 4.976086616516113,
    'y': 0.1944964975118637,
    'z': 8.631780624389648},
   'sensor': 'lamp.accelerometer',
   'timestamp': 1659032699935}
However, there appears to not be additional information for Android device_motion? The extra fields are empty.
{'data': {'attitude': {},
    'gravity': {},
    'magnetic': {'x': -15.090576171875,
     'y': 17.097957611083984,
     'z': -21.479949951171875},
    'motion': {},
    'rotation': {}

**Comment by avaidyam** [comment]
@saranya-sajeev Can you manually request the sensor for its latest data point? If so, you should be able to fill in the other fields.

**Comment by saranya-sajeev** [comment]
@avaidyam There is no option to manually fetch the sensor data.
