### ISSUE TITLE
Cats and Dogs docs and code are incongruous

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#604]
In the documentation, the static data for Cats and Dogs suggests the static data should take the format:
```
- `static_data`:
    - `point`: The associated point value with the completed session. 2 if all 45 trials were answered perfectly, else 1.	
    - `rating`:	The associated rating of the completed session.	
    - `correct_answers`: The total number of correct answers made in the session.	
    - `wrong_answers`: The total number of incorrect answers made in the session.	
    - `total_questions`: The total number of questions encountered during the session.   
 ```
 
 After testing, my static data looked like:
 ```
 'static_data': {'StartTime': None,
   'correct_answers': 22,
   'point': 1,
   'score': 49,
   'type': 1,
   'wrong_answers': 1}
```

We should address the following:
- `StartTime` is not in the docs. Additionally, it is always None(presumably null in the backend) What should this measure? Is it unneeded since we have timestamp?   
- `rating` is in the docs but not in static_data
- `total_questions` is in the docs but not in static_data. I believe there are always 45 trials for cats and dogs, so maybe this is unnecessary
- `type` is in the static data but not in docs. It is hardcoded to always be 1. This should be removed, or replaced with what it was intended to measure.

**Comment by avaidyam** [comment]
`StartTime` is an old SQL column name, so that should absolutely be removed, along with anything else static and useless. Otherwise perhaps we need re-document this activity. My original documentation was from 2018 so things could have changed since then!

**Comment by lukeoftheshire** [comment]
I'm updating the documentation - I will not add StartTime if it will be imminently removed.

**Comment by sarithapillai8** [comment]
@lukeoftheshire @avaidyam 
Can I start working on this as below or after updating documentations?
 ```
`static_data`:
    - `point`: The associated point value with the completed session. 2 if all 45 trials were answered perfectly, else 1.	
    - `rating`:	The associated rating of the completed session.	
    - `correct_answers`: The total number of correct answers made in the session.	
    - `wrong_answers`: The total number of incorrect answers made in the session.	
    - `total_questions`: The total number of questions encountered during the session.   
```

**Comment by avaidyam** [comment]
@sarithapillai8 Thanks, please do begin working on this issue!

**Comment by sarithapillai8** [comment]
@avaidyam @lukeoftheshire 
I am  not clear with all the parameters. 
 1. Is this to be followed on every activity? 
 2. In the case of cats and dogs, total questions will always be 0, right? 
 3. Is this rating expecting score value?

**Comment by lukeoftheshire** [comment]
- Could you clarify 1, please? I think these specific static_data adjustments only need to be made to cats and dogs for now (unless we find more stuff while testing)
- For 2, I think total questions will always be 45 - I'd say it's better to have it in case we ever convert cats and dogs to be of variable length.
- I'll be honest, I don't know what rating is intended to be here - maybe @avaidyam has more info. If we decide it's not necessary we don't have to add it and I'll just remove it from docs. Our main goal here is to make sure the docs and activity are consistent, I think.

**Comment by lukeoftheshire** [comment]
Seems like removing `rating` from the docs is the move then and there's no need to add it to cats and dogs.

**Comment by sarithapillai8** [comment]
@lukeoftheshire Could you check and confirm the event data now?

**Comment by lukeoftheshire** [comment]
Actually - one final thing. It looks like the `score` parameter, which was the percentage of correctly answered questions, was removed. It could still be calculated, since we have total_questions and correct_answers, but if someone had an algorithm that relied on that variable this would break backwards compatibility. @avaidyam, do you think we should add that back in?

**Comment by avaidyam** [comment]
@lukeoftheshire I think it's fine to remove the `score` parameter. We shouldn't store easily calculated values.

**Comment by lugray1** [comment]
Need to remove 'score' parameter from documentation, but other than that the documentation and code are the same.

**Comment by lugray1** [comment]
@avaidyam done!
