### ISSUE TITLE
TypeError for Pop the Bubbles 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#606]
On dashboard-staging, api-staging, when I went to test Pop the Bubbles and change the game settings I encountered the following TypeError
![Screen Shot 2022-04-15 at 9 13 37 AM](https://user-images.githubusercontent.com/82968538/163575279-a5106147-a289-4e06-b2be-db6b16a2260f.png)
![Screen Shot 2022-04-15 at 9 17 36 AM](https://user-images.githubusercontent.com/82968538/163575405-7e08a01e-842a-4998-bf5e-66ecc56dfed4.png)

**Comment by tlakhtak** [comment]
Also experienced this for a Learn Tip
![Screen Shot 2022-04-15 at 10 55 01 AM](https://user-images.githubusercontent.com/82968538/163607003-87cedf3c-4038-468d-bd26-7737964681be.png)

**Comment by divyav2020** [comment]
We have updated in Staging

**Comment by Tuna9129** [comment]
This seems to be fixed in staging!
