### ISSUE TITLE
Red Notification Bubble on Top Right Corner of App Icon 

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#611]
Red bubble with a number indicates that a notification is there but even when it is completed the number does not go down or the bubble does not disappear.

**Comment by tlakhtak** [comment]
I got a notification at 7pm as per the feed. As you can see activities were completed. Yet, the notification bubble did not go away.

![IMG_3099](https://user-images.githubusercontent.com/82968538/164772985-cc197e80-c1f5-4671-90a4-e3906c7747bd.png)
![IMG_3100](https://user-images.githubusercontent.com/82968538/164772982-44d370a6-09b3-42b1-ac38-6d7176c2c6d2.jpeg)

**Comment by jijopulikkottil** [comment]
At the time of development, we experienced the [same issue](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/179#issuecomment-1008566383) once. The delivered-notifications count returns non-zero value even if there were no mindLAMP notifications listed in notification center. And it automatically cleared after some time.

**Comment by avaidyam** [comment]
@jijopulikkottil So if I understand correctly, this is not something that we can fix because it's an Apple-side issue?
