### ISSUE TITLE
Unable to select 12 in time picker

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#615]

**Comment by tlakhtak** [comment]
https://user-images.githubusercontent.com/82968538/164771934-e011b18a-ef3d-4d50-84bb-582197004638.MP4

![Image from iOS](https://user-images.githubusercontent.com/82968538/164772002-e294df60-7c0e-490e-83e1-8ddccb22c6f9.png)

**Comment by sarithapillai8** [comment]
@avaidyam 
It was done like 00:00 AM is for 12 am. It was asked to keep the range 0-12(standard) and 0-24(military) in the requirement -  https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/404. 
FYI 0 to 23 need to be kept for military time as there will not be a way to set time like 12.15am or 12.45am. We will be changing the standard time.

**Comment by divyav2020** [comment]
We have updated the time range from 1 to 12 (Standard) in Production

While testing, we have got an issue in Military time update.

**Comment by sarithapillai8** [comment]
@avaidyam @divyav2020 
Issue fix including UI fixes are updates in production.
Survey military time update issue is fixed (LAMP-dashboard) in dashboard-staging.  Production update required.

**Comment by divyav2020** [comment]
Tested the time range update (Standard time) and UI fixes in Production. 

We have updated the Military time Issue fixes in Staging.

**Comment by lugray1** [comment]
This seems to be fixed in staging! 🎉
