### ISSUE TITLE
Feed calendar not showing schedule dots correctly

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#62]
> **Collaborator**: So, it seems like there should be a green dot on each day but there is not. it is only showing up on saturday. the survey is scheduled for each day though.
![image](https://user-images.githubusercontent.com/1361003/101496543-e4d3c380-3937-11eb-9848-2a102d19deaf.png)

**Comment by divyav2020** [comment]
We are unable to reproduce this issue. Hence kindly provide us with more details.  
Meanwhile, we request you to clear the cache and retest.
