### ISSUE TITLE
Invisible Overhang

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#620]
There is a small invisible overhang present on the dashboard, that prevents clicking any element near the top of the page.

For example, the 'Add' button here is entirely uninteractable. 
<img width="1062" alt="Screen Shot 2022-04-25 at 11 45 31 AM" src="https://user-images.githubusercontent.com/34659264/165125273-275337ea-9c26-4eb0-9072-125e94f3d888.png">

It would be nice if this overhang could be removed.

**Comment by divyav2020** [comment]
We have updated in Staging

**Comment by noyalon** [comment]
“This seems to be fixed in staging!"
