### ISSUE TITLE
mindLAMP "Interrupted error" bug when opening home page

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#629]
The following error appeared for User U7851221787 after the most recent update, on an Android device LG K30, version 9, whenever they open the app.

![Screenshot_20220429-191357](https://user-images.githubusercontent.com/82968538/166269068-4afb1304-009d-4cf5-b8ef-40a03763e2b7.png)

**Comment by saranya-sajeev** [comment]
@tlakhtak is this user logged in to Gogole fit ?

**Comment by saranya-sajeev** [comment]
@avaidyam @tlakhtak is this user logged in to Gogole fit ?

**Comment by ZCOEngineer** [comment]
@avaidyam any updates here?
