### ISSUE TITLE
Sending messages entry field cuts off the message that you're typing

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#63]
> For messaging, you can't read everything you've typed (it's cut off). This is not a big deal, but this bubble does not expand as you type, so you cannot see your full message. you can only see a few words.
> 
> ![image](https://user-images.githubusercontent.com/1361003/101496851-43993d00-3938-11eb-8b67-177ebccc6488.png)

**Comment by sarithapillai8** [comment]
@avaidyam 
Updated in staging. Could you please check?
