### ISSUE TITLE
Matrix Survey Response renders textbox instead of matrix

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#632]
We found an issue with all of the matrix surveys on the LAC version of the dashboard after they updated to the latest version (2022.4.23). See images below. All of the matrix surveys turned into text boxes
![thumbnail_image001](https://user-images.githubusercontent.com/82968538/166521910-45b2ec40-936e-46b1-93bf-0c7d104f9e4f.png)
![thumbnail_image002](https://user-images.githubusercontent.com/82968538/166521916-e55be021-469b-4c9c-a249-fdb708e3fa67.png)

All of the questions on the matrix surveys disappeared:
![thumbnail_image003](https://user-images.githubusercontent.com/82968538/166521933-04070771-de33-4dd3-b4d2-f3ed4c45474d.png)

**Comment by avaidyam** [comment]
@sarithapillai8 I suspect this is due to #442? Is this expected behavior? If so, @tlakhtak, the guidance here would be to re-create the survey as it should work correctly then.

**Comment by sarithapillai8** [comment]
@avaidyam Yes this is expected behavior. First question is matrix type and there is no preceding type, it will render as text. If the first question is rating and next is matrix, then it will show as matrix with rating options.

**Comment by tlakhtak** [comment]
Can we get a demonstration of this? It is not clear to me how we would implement this, and it seems very convoluted and un-intuitive.

**Comment by sarithapillai8** [comment]
@tlakhtak Please provide the survey details to understand how you created your questions. 
https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/442#issuecomment-1029194134
Please have a look at this for understanding how to create matrix questions.
 
>The star is not in red so it is not clearly indicating that it is a required question.

I can check and update this.

**Comment by sarithapillai8** [comment]
>The star is not in red so it is not clearly indicating that it is a required question.

This is fixed and updated in dashboard-staging.

**Comment by avaidyam** [comment]
> This should not have broken backwards compatibility for previous matrix questions, as this creates serious implementation issues.

@tlakhtak @sarithapillai8 Going forwards our team will be strict about any kind of data format or API change that affects implementation and compatibility across sites. **Anything JSON/API related must be shared in full detail and approved by myself and @lukeoftheshire before merging into staging.**
