### ISSUE TITLE
Jewels to take up entire screen instead of just being restricted to top half

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#634]
We would like the jewels to take up the whole screen to make the task more robust. This should fit with dynamic screen resolution to adapt to different screen sizes.

https://mindlamp.discourse.group/t/jewels-trail-test-dispersion/585/3

**Comment by sarithapillai8** [comment]
@avaidyam We can fix and update it soon.

**Comment by divyav2020** [comment]
We have updated in Staging
[LAMP_Admin Website_Jewels to take up entire screen.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8759704/LAMP_Admin.Website_Jewels.to.take.up.entire.screen.xls)

**Comment by carlan1** [comment]
Appears fixed in staging.
