### ISSUE TITLE
App Won't Load - Android 

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#638]
**Describe the bug**
Timeline: Lamp was successfully downloaded, user account logged in. Activity data was entered. Following morning app would not load, but continually buffered. Issue continued after phone was restarted, and after app was reinstalled. Unclear if phone logged out of account prior to issue arising.

**To Reproduce**
1. reproducibility unclear. Occurred after app installation and sign on whenever app was opened. Reproduced on phone when opening mindlamp 2 app.

**Expected behavior**
Expected to open lamp to activities screen.

**Screenshots**
![280613721_1206054546890292_299876250594321402_n](https://user-images.githubusercontent.com/104088715/169328373-c91e2c41-8481-4752-b222-79a9c3a494ff.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [motorola moto g(7) power]
 - Browser [chrome, irrelevant]
 - Version [10]

**Additional context**
NA

**Comment by ZCOEngineer** [comment]
We are checking this, shall update our findings/questions soon

**Comment by saranya-sajeev** [comment]
@ertjlane could you please share the log file?

**Comment by saranya-sajeev** [comment]
@ertjlane is this production or staging user?

**Comment by divyav2020** [comment]
We have logged in the app with the provided credentials. So far we have not experienced any issues. We are trying to reproduce the issue. We shall update here as soon as we find anything.

**Comment by avaidyam** [comment]
@divyav2020 Please also ensure you are testing on the closest possible Android device to the one @ertjlane is using.

**Comment by ZCOEngineer** [comment]
We were not able to reproduce this issue @avaidyam

**Comment by ZCOEngineer** [comment]
@ertjlane, @avaidyam is there a reccurence of this issue?

**Comment by avaidyam** [comment]
@ZCOEngineer As I haven't heard from @ertjlane that the issue persists, I'm going to close the issue for now.

**Comment by ertjlane** [comment]
The issue has occurred again, this time without the 403 error, but with an endless spinning wheel. The app has been uninstalled and reinstalled several times, and the phone restarted. The error has also occurred on another android device, specs listed below. Both devices have access to service and/or wifi. 

The user is, to my knowledge, irrelevant, since my user account would have been logged out upon uninstalling the app.

Device: U202AA
OS: Android (version 9)
Version [Hardware: V1.0, Software: v02.72.11]

**Comment by ZCOEngineer** [comment]
Hi @ertjlane, previously we were not getting this issue here, could you give us the user and credentials to check this here. it will be easy to debug the issue if we have an user who is currently experiencing this issue.

**Comment by saranya-sajeev** [comment]
@ertjlane Could you please share the log file if possible?

**Comment by avaidyam** [comment]
It seems like the `Device: U202AA` is actually an Android Go edition device? That could be a restrictive factor causing the issue.

**Comment by saranya-sajeev** [comment]
There is no emulator available with Android Go. Android Go devices having very limited memory. So we have tried to create an emulator with low memory and tried to install Lamp from play store, but the play store app exit after sometime and I have installed directly from  Android studio. App showing spinner and then exits. App may not work properly on low memory devices.

**Comment by avaidyam** [comment]
@saranya-sajeev Thanks for the testing! 

@ertjlane Can you update the documentation to share that we do not support Android Go or low memory/CPU devices?

**Comment by ertjlane** [comment]
@avaidyam @saranya-sajeev 
Yes I can do that. Thanks for looking into it guys!

**Comment by ertjlane** [comment]
This issue has occurred again. The user downloaded the app, but immediately upon opening it the endless blue buffering wheel appeared. The user quit the app, uninstalled and reinstalled it, and restarted their phone. The issue persisted. The user had not logged into the app. As seen below, this is not on a low memory device. 

Samsung Galaxy S7 
Android 8

**Comment by zcocueless** [comment]
@ertjlane we shall check this

**Comment by ZCOEngineer** [comment]
@ertjlane we shall check this

**Comment by divyav2020** [comment]
We have tested Beta and Production build in Samsung Galaxy S7 (Version 8). But we are unable to reproduce this issue. We will check in detail. Meanwhile could you please share the log

**Comment by ertjlane** [comment]
Thank you for looking into this. I don't think it will be very feasible to retrieve the log, as the user is a patient who we don't know would be able to do that, and it wouldn't really be appropriate to ask. Correct me if there's an alternative, but my understanding is the user would have to provide the log.

**Comment by avaidyam** [comment]
@divyav2020 We cannot provide log files from patients' devices. The most we can do is provide (via email only) the Participant IDs.

**Comment by michaelmenon** [comment]
@ertjlane is the patient trying to open the app in the hospital network or on his/her home network.  Also can we ask the user to open this link the phone browser and see if its loading ? 

https://dashboard.lamp.digital/

**Comment by ertjlane** [comment]
I've passed this on to the team managing the user, and they have directed the user to do as such. However, the team doesn't have very frequent contact with the user, and can't guarantee that they'll do this. I have directed the team to try doing the same on a similar device to see if there is a network problem. I would explore other avenues of evaluating the issue in the meantime, as we still may not be able to verify the problem through this route.

**Comment by ertjlane** [comment]
@michaelmenon This issue has occurred again, in a motorola e32, android version 11 (both phone and software quite recent). While I have asked the collaborator who brought this issue forward to provide more detail, I strongly suspect this is a non-user related issue, and is not the product of them operating a low memory device, and rather is an issue with the code. It has occurred with multiple android devices across the past several months, as documented here. Could the team please look into this, while I bring back any insight provided from the collaborators?

**Comment by ZCOEngineer** [comment]
@ertjlane sure we shall check this on our side as well, in the details you are requesting, could you ask for a video as well, and if possible get to know the steps they followed?

**Comment by ertjlane** [comment]
@ZCOEngineer Yes of course, I'll try to get as much detail as I can. Thank you for the prompt reply.

**Comment by ZCOEngineer** [comment]
We are working on a retry mechanism. If the lamp web modules are not loaded in the expected time it will show a retry option. It also shows a retry option if the loading fails which was not handled earlier. App is given for internal QA and we shall update to staging beta once complete.

**Comment by ertjlane** [comment]
Sounds good, thank you!

**Comment by sijitg** [comment]
We pushed code and staging build is in review

**Comment by ertjlane** [comment]
This appears to be fixed in staging.
