### ISSUE TITLE
App Won't Load + 'Error 403'

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#640]
**Describe the bug**
Upon being selected the lamp app produces the error screenshotted below. Selecting the 'refresh' button leads to endless buffering. This may be the same as issue #638, in which lamp buffered endlessly, but did not produce an actual error notice. The error notice will sometimes appear when the phone is opened, without clicking lamp at all. 

**Screenshots**
![Screenshot_20220518-145958](https://user-images.githubusercontent.com/104088715/169376458-4096e128-c8b7-4430-805c-0078c7c06c6f.png)

**Smartphone (please complete the following information):**
 - Device: [Maestro U202AA]
 - OS: [Android 9 Go Edition]
 - Version [9]

**Additional Notes**
The app was logged into multiple accounts on this phone. A theory is that this could be conflict created by multiple accounts presenting conflicting information, i.e. the phone trying to load tasks that 'aren't there'. Just a hypothesis though.

**Comment by divyav2020** [comment]
We have logged in the app with the following credentials (e@e.com, pw: q). So far we have not able to reproduce the mentioned issue. We shall update here as soon as we find anything.

**Comment by ZCOEngineer** [comment]
We were not able to reproduce this issue @avaidyam, seems to be similart to #638

**Comment by ZCOEngineer** [comment]
We shall add an alert as well to inform the user

**Comment by saranya-sajeev** [comment]
@avaidyam As we discussed in the meeting  when an exception is occurred we will show an alert with a message " Something went wrong. Please try after some time" . On click we will restart the app. Please confirm.

**Comment by avaidyam** [comment]
Please use: "Something went wrong. Please try again later."

**Comment by ZCOEngineer** [comment]
Since we wont be able to see exception if we go ahead with alert, currently there is a share option @avaidyam will check on this and update here.
