### ISSUE TITLE
Uncaught Exception Error

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#647]
**Describe the bug**
'Uncaught Exception' error occurred while logging into a new account on June 3rd at 1:42pm. (see screenshot attached)

**To Reproduce**
1. Logged out of existing account (U2211044819)
2. Logging into U7677732771 (test account)
3. Random error came up, restarting the app removed the error

**Screenshots**
![Screenshot_2022-06-03-13-43-54-272_digital lamp mindlamp](https://user-images.githubusercontent.com/103677721/171935777-14c796ad-1bdd-4e39-bcee-180204f67a8d.jpg)

**Smartphone (please complete the following information):**
 - OS: Android 9 pie
 - Device: Xiaomi Redmi Note 6 Pro
 - Date and Time: 6/3/3033 13:42 pm
 - Server: api.lamp.digital

**Additional context**
Also In Issue #645  and issue #648

**Comment by saranya-sajeev** [comment]
@Devayani0102 could you please share the log file or complete stack track?

**Comment by avaidyam** [comment]
@saranya-sajeev Generally, we do not have access to that and cannot provide either a log file or complete stack trace. Maybe we should reduce the font size of the stack trace to fit longer symbol names? 

@Devayani0102 if this is reproducible, can you have the patient take a screenshot of the app after scrolling all the way to the right on the text? If it's not reproducible, please let me know too.
