### ISSUE TITLE
Visualization error for survey 

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#649]
**Describe the bug**
The x-axis for survey visualization is one day off. The last entered response is on June 8th, but it is plotted as June 7th on the axis.
Ideally, the last point on the axis should match with the last entered data. 

The screen shot below shows the error in the visualization of PHQ-9 survey

![image001](https://user-images.githubusercontent.com/103677721/172864882-7e14c7ba-f275-4d67-9965-a9facfec95b2.png)

**Comment by ZCOEngineer** [comment]
We shall check this and update.

**Comment by divyav2020** [comment]
We have updated in staging
[LAMP_Admin Website_Visualization error for survey.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8918268/LAMP_Admin.Website_Visualization.error.for.survey.xls)

**Comment by sarahperret2** [comment]
seems to be fixed in staging
