### ISSUE TITLE
Merging sensor code into the LAMP-swift/LAMP-Kotlin

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#65]
- For all http calls, use the LAMP-Swift/LAMP-Kotlin package.

**Comment by amaljofyzco** [comment]
In Android, I am planning to convert sensor-core to kotlin in this scope.
It's not safe to use android studio converter to convert java to kotlin. we will do it manually, that time is also included.

**Comment by jijopulikkottil** [comment]
hi @avaidyam , From LAMP-Swift, can we remove the classes (some model classes and APIs) which are not using now ?

**Comment by avaidyam** [comment]
@jijopulikkottil No, this is part of the library that you are supposed to use.
