### ISSUE TITLE
Missing Documentation for Complex Passwords

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#650]
**Describe the bug**
We know that there is a functionality for complex passwords to be deployed within LAMP. However, there is no available documentation of how to do so.

**Comment by avaidyam** [comment]
@ertjlane FYI The two relevant issues are #451 (feature request) and #491 (usage support).

**Comment by ertjlane** [comment]
### Implementing Complex Passwords

A new Tag lamp.dashboard.security_preferences must be set by the system administrator to add support to control certain user account creation settings. Currently, we will support password rules. Example:


```
rule = {
    "password_rule": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$"
}
LAMP.Type.set_attachment("null",'me','lamp.dashboard.security_preferences',rule)
```

The password rule must be specified as a valid regular expression (see example above; [see RegExR to test these](https://regexr.com/)). The above expression matches:

^.* ... .*$ = The entire string must match the expression, and cannot contain line breaks (\n).
(?=.{8,}) = Minimum of 8 characters.
(?=.*[a-z]) = Must contain lowercase letters.
(?=.*[A-Z]) = Must contain uppercase letters.
(?=.*[0-9]) = Must contain numeric digits.
Additional parameters (such as required special characters, etc.) can also be added to the regular expression.

When setting a password on any user account across LAMP, this system-level Tag must be referenced first. 

If no such Tag exists, any password of any complexity with any characters is permitted (current behavior).
If such a Tag exists, but the password_rule is missing or not a valid regular expression, any password of any complexity with any characters is permitted (current behavior).
If such a Tag exists, and the password_rule is a valid regular expression, the password text field in the UI must validate the text input by the user against the regular expression.
If the text matches the regular expression, the password is accepted and the dialog is allowed to proceed.
If the text does NOT match the regular expression, the password is not accepted, and the dialog (and its continue button) is disabled until the text is modified to match the regular expression. (An error message must be displayed under the text field to inform the user.)
The UI must be updated to visually match this example:

Screen Shot 2021-12-09 at 4 35 26 PM

However, the error text underneath the password field must instead be: "Password is not complex enough and does not comply with organization password requirement." The confirm password text field error text should be "Does not match the password you entered above.". The UI will not be modified with the exception of this additional text when generating new user credentials.

Upon initially creating a user account, user password will be automatically generated in the default format, regardless of password rules. I.e. a user given the account U1338759043@lamp.com will automatically be given the password "U1338759043" regardless of password complexity settings. 

### Usage
```
curl -u admin -L -X PUT 'https://<our mindlamp server>/type/null/tag/lamp.dashboard.security_preferences/me' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
--data-raw '{
    "password_rule": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$"
}'
```
