### ISSUE TITLE
mindLAMP Location Requests Repeat After Being Denied

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#652]
**Describe the bug**
User on IOS device is repeatedly asked by the mindLAMP app to share location data. 

**To Reproduce**
Unclear. Open app - if the bug is present it appears upon opening mindLAMP. 

**Expected behavior**
After initially downloading the app, the user will be asked if they will share their location data with the app. The user selects 'never', and the prompt disappears. The prompt does not appear after this.

**Screenshots**

https://user-images.githubusercontent.com/104088715/173151332-1016a9bf-9d82-4dab-8c45-d1478c4e8b89.mov

https://user-images.githubusercontent.com/104088715/173151334-c2fc6d17-19e9-40e9-81a9-04f011a98bce.MP4

https://user-images.githubusercontent.com/104088715/173151336-2ab32bfe-d205-496c-82b8-e16f6022b59b.mov

**Smartphone (please complete the following information):**
Device: [iPhone8]
OS: [iOS 15.5] (based on google of iphone 8 current OS), not user report
Version [14.8]

**Additional context**

**Comment by jijopulikkottil** [comment]
Yes, we are asking location permission on app launch if it is not allowed yet. 
@avaidyam  Let us know if need to stop asking permission in the case of 'Denied'.

**Comment by ertjlane** [comment]
@avaidyam Correct me if this is wrong, but @jijopulikkottil yes if case 'Denied' (user refuses permission for collection), we want the app to stop asking for permission.

**Comment by jijopulikkottil** [comment]
> We also just had a user report having a similar problem where the app requests permission to access phone call info, despite that participant not being assigned to have phone call data collected. Separate issue or same thing?

yes, it will be different thing.
call info (incoming/outgoing) will collect only if `lamp.telephony` is added to that user. So the app will not request phone-call info permission if lamp.telephony not added. Let us know if any issues.

**Comment by jijopulikkottil** [comment]
> @avaidyam Correct me if this is wrong, but @jijopulikkottil yes if case 'Denied' (user refuses permission for collection), we want the app to stop asking for permission.


@avaidyam  Could you confirm this

**Comment by jijopulikkottil** [comment]
@avaidyam please conform this too
<img width="901" alt="Screenshot 2022-06-23 at 7 24 02 PM" src="https://user-images.githubusercontent.com/63795052/175318055-1d0a799f-6d50-433e-ac27-6d99ecf1090d.png">
.

**Comment by jijopulikkottil** [comment]
Code is pushed, CD fails due to some issues with GitHub Actions.

**Comment by jijopulikkottil** [comment]
it is available on testflight now

**Comment by noyalon** [comment]
This seems to be fixed in staging!
