### ISSUE TITLE
Uncaught Exception (RemoteServiceException)

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#653]
**Describe the bug**
User U3868113460 on Samsung Galaxy A12 reported 'uncaught exception error'. They reported that sometimes the app gives the attached bug  when they are trying to complete an activity or are in the app and closes randomly. Date: 6/12/2022, Time: 5:54pm

**To Reproduce**
No clear steps to reproduce as the bug occurs at random.

**Screenshots**
![Screenshot_20220612-175459_mindLAMP](https://user-images.githubusercontent.com/103677721/173671151-38ba0f27-2537-4190-b21f-77e149853e74.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A12
 - OS: Android

**Additional context**
- Log file or complete stack track not available. 
- Could be related to issue #645 , #647 and #648

**Comment by avaidyam** [comment]
@saranya-sajeev In addition to this issue, please ensure all HTTP-related errors (i.e. HTTP 403 as shown in #647) are caught and display a proper error message like "You are not logged in" or "You are not connected to the internet".

**Comment by saranya-sajeev** [comment]
@avaidyam Ok we will handle all http related errors and  will show proper message.

**Comment by divyav2020** [comment]
We have got some issues while doing QA testing. Issue fixing is going on.  We will update the build once it is fixed

**Comment by saranya-sajeev** [comment]
@avaidyam We have handled the ClientException, ServerException, UnsupportedOperationException, HttpException, SocketTimeoutException, NetworkErrorException and UnknownHostException. We will show alert on exceptions and on tapping "OK" button app will restart. We have pushed the build to beta and is in review status.

**Comment by michaelmenon** [comment]
its pushed to beta today.

**Comment by sarithapillai8** [comment]
There was a bug in deleting participants. Credentials were not getting deleted on deleting a participant. So it was possible to login through a credential even if the participant was deleted. The issue is fixed and updated in dashboard-staging.

**Comment by avaidyam** [comment]
> There was a bug in deleting participants. Credentials were not getting deleted on deleting a participant. So it was possible to login through a credential even if the participant was deleted. The issue is fixed and updated in dashboard-staging.

@sarithapillai8 Can you create a new GitHub issue to track this?
