### ISSUE TITLE
DBT Diary Card - Adding answers to free-form text questions to Prevent Section

### ISSUE THREAD

**Issue by elenamrv** [BIDMCDigitalPsychiatry/LAMP-platform#66]
Hi all -

This is a high priority feature request for the DBT Diary Card. In the Prevent section, the answers to the questions below need to be visible:

Question 4 - Why didn’t you use any skills?
Question 7 - Optional: Are there any other details you want to share about your day?

For example, if I am a patient and I respond to Question 4 and say "I did not want to," I should be able to see this response under the graphs in the Prevent Page. The response needs to also have the date next to it that the text was written.

@avaidyam

**Comment by avaidyam** [comment]
@sarithapillai8 At the bottom of the graphs/data page, it would make sense to add a small list with this format: 
```
Didn't use skills because...
12/08    |    Too lazy.
12/10    |    Sample text.


Optional notes:
12/08    |    Hello!
12/10    |    Nothing new.
```
