### ISSUE TITLE
Activities edit-confirmation dialogue box error

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#661]
**Describe the bug**
For LA county: 
When trying to edit an activity, a dialogue box saying "Changes done to this activity will reflect for all the participants under the study. Are you sure you want to proceed?." pops up.  This warning is only suppose to show up if you're editing groups with more than one participant in them. However,  LA county investigators can only have one participant per group (based on how their server is set up), and therefore the warning should not show up. 

**To Reproduce**
1. Go to dashboard.lamp.digital  -> Enter any investigator
2. Create a "new user and group" using the add button on top right. 
3. Click on the setting icon
4. Add a new activity, save
5. Click on edit (pencil icon) for that activity
6. The dialogue box will pop up.

**Expected behavior**
The dialogue should not pop up when there is a single used in that group

**Screenshots**

![Screenshot 2022-06-22 153817](https://user-images.githubusercontent.com/103677721/175124791-61184a7d-2c8b-44ab-89dc-a74f7b471dfc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 [irrelevant]
 - Browser: chrome [irrelevant]

**Comment by avaidyam** [comment]
@sarithapillai8 Please ensure this dialog ONLY appears when the **number of participants in the study is GREATER THAN one**. It should not appear all the time.

**Comment by divyav2020** [comment]
We have updated this feature in staging server
[LAMP_Admin Website_Activities edit-confirmation dialogue box error.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8975494/LAMP_Admin.Website_Activities.edit-confirmation.dialogue.box.error.xls)

**Comment by sarahperret2** [comment]
seems to be fixed in staging
