### ISSUE TITLE
Sometimes Select Language dropdown selection shows blank

### ISSUE THREAD

**Issue by divyav2020** [BIDMCDigitalPsychiatry/LAMP-platform#663]
Login as a participant. Then kill the application from background. Login screen shows. Sometimes Select Language dropdown selection shows blank in Login screen
![A25938EA-CD49-479E-9D1D-8DF1685E4771](https://user-images.githubusercontent.com/74397668/175940921-27a94720-2ee1-4531-ad24-30999a2d2887.png)

**Comment by divyav2020** [comment]
We have updated in Staging

**Comment by noyalon** [comment]
“This seems to be fixed in staging!"
