### ISSUE TITLE
Inconsistent JSONata Activity behavior

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#665]
As seen in https://docs.lamp.digital/data_science/jsonata , `$LAMP.Activity.list()` by default uses `true` for `the ignore_binary` param. This behavior is different from other API implementations (to my mind both the JS and Python versions of the Activity list(/all_by_participant) function have ignore_binary set to false by default.

This behavior should be normalized across different languages to minimize difficulty when swapping between them - I would suggest adapting the JSONata command to fit the JS and Python versions as those are more commonly used and are the 'default' behavior.

**Comment by avaidyam** [comment]
@lukeoftheshire Are you suggesting we just change the default value of the parameter from `true` to `false` in `LAMP-server`? Or do you mean we need to update all the packages (`LAMP-js`, `LAMP-py`, `LAMP-r`, etc.)?

**Comment by mcurbelo-orangeloops** [comment]
I've just created a PR for this. It looks like `Activity.Sensor.list()` also has the default set to true ([here](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/5a2739b07d6a4746e87dec5682e5a22577cb861c/src/service/Query.ts#L182)
Should I also change that one to false so it is consistent across the board ?

**Comment by avaidyam** [comment]
Sure! That would be helpful. Also, `jsonata` upstream has finally merged my Promise-based rewrite so it should be possible to check whether we can switch to using the main library instead? It's not urgent by any means though.

**Comment by avaidyam** [comment]
@carlan1 @ertjlane Please test this one out! 

@Linoy339 @sarithapillai8 Please confirm that this change works for your team.

**Comment by Linoy339** [comment]
@avaidyam . Will check and let you know asap
