### ISSUE TITLE
Visualization error for DBT Diary card

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#666]
**Describe the bug**
When looking at the visualization for the diary card, the dropdown for Skill used does not fit the screen (see attached screen recording). The visualization looks okay in the first week, but starting from the data entered in the second week, it does not show up properly. 

First noticed for user U5128892212 on iPhone 7 and Redmi note 6 pro. 

**To Reproduce**
1. go to any user account with DBT Diary card. 
2. enter data for two weeks at least
3. starting on the second week, the bug can be replicated.

**Screenshots**
https://user-images.githubusercontent.com/103677721/176761386-5a92b050-f430-4c6b-a68e-bde36f1a2311.MP4

Can also be replicated on desktop (chrome ) using developer tools 

<img width="1354" alt="Screen Shot 2022-06-30 at 3 42 25 PM" src="https://user-images.githubusercontent.com/103677721/176763701-66f051d6-92bc-44bf-8363-77e7bbd911a3.png">

**Expected behavior**
The visualization should fit on the screen.
This is what it is supposed to look like-

https://user-images.githubusercontent.com/103677721/176765883-32916ff5-c80a-4849-8b05-8938718c2d36.MP4

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome

**Smartphone (please complete the following information):**
- Device: iPhone 7 
 - OS: 14.6
-Device : Redmi note 6 pro
 - OS: android pi

**Comment by divyav2020** [comment]
We have updated in staging
