### ISSUE TITLE
Slow Activity View 

### ISSUE THREAD

**Issue by jlavoie9** [BIDMCDigitalPsychiatry/LAMP-platform#67]
LAMP.Activity.view('act_id') was very slow (longer than LAMP.Activity.all_by_participant('part_id'))
<img width="616" alt="Screen Shot 2020-12-11 at 11 53 58 AM" src="https://user-images.githubusercontent.com/67972674/101944344-94b86380-3bba-11eb-98a8-f3f807e3c41d.png">

After Aditya's change to the database index, now much faster. However, large activities with base64 images still take a bit of time. 
<img width="722" alt="Screen Shot 2020-12-11 at 12 32 33 PM" src="https://user-images.githubusercontent.com/67972674/101944647-0ee8e800-3bbb-11eb-929d-528593f88abc.png">

**Comment by avaidyam** [comment]
This issue is solved by adding a CouchDB index `_design/id-timestamp` on the `Activity` database:
```json
{
 "type": "json",
 "partitioned": false,
 "def": {
  "fields": [
   { "_id": "asc" },
   { "timestamp": "asc" }
  ]
 }
}
```

However, the larger issue is still redacting the base64 data correctly based on the ActivitySpec provided JSONSchema.

**Comment by avaidyam** [comment]
@Linoy339 Could you add the index mentioned above to the database initialization in `LAMP-server`?

**Comment by Linoy339** [comment]
These following are the present indexes in activity database:
1.fields: ["timestamp"]
2. fields: ["#parent", "timestamp"]
3. fields: ["_id", "#parent", "timestamp"]
Can you clarify :  Apart from the above, we need to add -  fields: ["_id", "timestamp"] . Right?

**Comment by avaidyam** [comment]
@Linoy339 Take the above JSON from my comment and [add it to this array here in `LAMP-server/src/utils/index.ts`.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blob/56455f8e5ef014bdba6c785aab8c25b3ae260351/src/utils/index.ts#L348)

**Comment by Linoy339** [comment]
@avaidyam . Please check
[https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/43](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/43)
