### ISSUE TITLE
App Extended Load Time

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#670]
**Describe the bug**
An iphone user is experiencing extended loading times with the app. 

**Expected behavior**
The app logs in within 1-2 seconds at the very most. 

**Screenshots**
https://user-images.githubusercontent.com/104088715/180299547-02a28461-3e65-4df2-97d5-a0652df4a17e.MP4

**Smartphone (please complete the following information):**
 - Device: [iPhone XR]
 - Version [15.1]

**Comment by jijopulikkottil** [comment]
Could you provide a test user under same Group/Study? 
Are you experiencing any delay to load home page (Assess tab) when login (logout and login) ?

[In staging, we are also experiencing a delay but the login page flashes. let us investigate it.]

**Comment by jijopulikkottil** [comment]
This issue happened because of the fix https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/651. So we can remove the script injection to fix this issue.

**Comment by michaelmenon** [comment]
We will update in 2-3 days

**Comment by avaidyam** [comment]
@jijopulikkottil @michaelmenon I’m closing this issue as a duplicate of #651 - let’s continue the conversation there.

**Comment by jijopulikkottil** [comment]
I reported this issue was due to script injection in #651. But it was not. So reopening this issue.

**Comment by jijopulikkottil** [comment]
The time taken by app is improved now.  Code is pushed and staging pointed build 2022.8.9 will be available on test flight.

**Comment by ertjlane** [comment]
This issue does not seem to have re-appeared, and lamp-core-ios has been updated recently. As such, I'm going to close the issue unless it re-emerges.
