### ISSUE TITLE
LAMP UI simple/advanced mode button change

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#679]
The LAMP dashboard / data portal UI does not make the option to change from simple mode to advanced mode very clear. At the moment, it can easily be overlooked, and many have missed it entirely. Is there some way we can make it more visible?

Current implementation has the following appearance:
![image](https://user-images.githubusercontent.com/103652751/182650788-4df96511-d420-414c-8643-1103d76f6c50.png)

Could we perhaps add a notification in the corner, like the one below? (but with the text changed to something like, "WARNING: You are viewing the LAMP dashboard in [mode])"
![image](https://user-images.githubusercontent.com/103652751/182651002-e5b05a14-354a-4e88-9248-d947f8fd6ee3.png)

**Comment by sarithapillai8** [comment]
@carlan1 
Do we need append this warning to existing message or replace the existing one?
I am changing this to feature as this is not a bug.

**Comment by avaidyam** [comment]
@carlan1 I think if we add more notifications it might confuse the user and clutter the UI. @sarithapillai8 Please just change the color of the button to the default style (it should be white with blue text).

**Comment by divyav2020** [comment]
We have updated in staging

**Comment by divyav2020** [comment]
We have updated in staging
[LAMP_Admin Website_LAMP UI simpleadvanced mode button change.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/9299934/LAMP_Admin.Website_LAMP.UI.simpleadvanced.mode.button.change.xls)

**Comment by carlan1** [comment]
Closing this issue as it appears fixed in dashboard-staging.
