### ISSUE TITLE
Survey duplication does not work correctly

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#68]
> **Collaborator**: Some of our questions are reverting to "select one of the following" instead of "check all that apply" after duplicating the survey in order to make edits.

(I believe this refers to `MULTISELECT` turning into `LIST`.)

**Comment by divyav2020** [comment]
Hi Aditya, we are unable to reproduce this issue. Hence kindly provide us with more details.
