### ISSUE TITLE
Cron job not running at designated time 

### ISSUE THREAD

**Issue by Tuna9129** [BIDMCDigitalPsychiatry/LAMP-platform#682]
**Describe the bug**
Cron job (digital_clinic_daily_q in portainer) not running at designated time. I have tested different times but it doesn't seem to matter what time I specify.
When I run the script from terminal (chang/cron_jobs/daily_data_q_checks.sh), it works fine and sends me the correct msgs on the specified slack channel
Seems like something is wrong with maybe my container config? 

**To Reproduce**
Portainer --> cron stack --> digital_clinic_daily_q (all the way at the bottom) 
Shell script can be found at /chang/cron_jobs/daily_data_q_checks.sh
Python script can be found at /chang/cron_jobs/daily_q.py

**Expected behavior**
Expected the cron job to run at the time specified in the cron stack in portainer 

**Screenshots**
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/105741216/183102822-96936d12-6233-4427-9b0d-44822a5005e1.png">

<img width="656" alt="image (3)" src="https://user-images.githubusercontent.com/105741216/183101937-2849f7d8-f880-4c38-8cd7-04a55c5e7f7e.png">

**Additional context**
Thank you!

**Comment by dcurrey88** [comment]
I don't know if this was resolved, but if you go to the failed task and look at the logs (click the icon that looks like a document under Actions) then you'll see the errors. It looks like you missed pip installing a package in your script.

**Comment by Tuna9129** [comment]
hello! thank you! had to upgrade pip and sys path insert cortex.
