### ISSUE TITLE
Changes to DBT card

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#687]
Can we make the following changes to DBT diary card permanent: 

Currently we have the following 'Urges' questions in every diary card:
![Screenshot 2022-08-29 102702](https://user-images.githubusercontent.com/103677721/187229683-352a99c7-9f90-4d60-b0aa-3bd59aeedfa9.png)
![Screenshot 2022-08-29 102644](https://user-images.githubusercontent.com/103677721/187229704-19401677-8569-4c09-abb2-1af9fd6f4df1.png)

**We want to add the following 'Urges' as a permanent feature in every diary card** 
_This should be in form of a matrix instead of individual questions per screen._  
Once we have these set up, we can remove the earlier two questions because they are included in this.
![Screenshot 2022-08-29 104252](https://user-images.githubusercontent.com/103677721/187231861-e92e2313-0a30-4069-be2b-ad91c10e7069.png)

**Also, the following questions about 'Emotions' should be permanent in form of a matrix.**
We still want to give users the option to create new ones, but these should be included in every new DBT diary card.
![Screenshot 2022-08-29 102606](https://user-images.githubusercontent.com/103677721/187228889-0ac86ff7-e0fe-4126-983c-9a7c1a6287d0.png)

**A sample of this diary card can be found for _U7591765158_, labelled _Zco_DBTcard_Sample_**

**Comment by sarithapillai8** [comment]
@Devayani0102 

>We want to add the following 'Urges' as a permanent feature in every diary card

 - Are these expected at the end of Ineffective section along with user added items?
 
>Also, the following questions about 'Emotions' should be permanent in form of a matrix. 

 By matrix , do you mean to include column headings for these options? I understood the above 5 should come along with user added emotions list.

>A sample of this diary card can be found for U7591765158, labelled Zco_DBTcard_Sample

Can I get the researcher for this? Which server address to be used - api-staging or api server?

**Comment by Devayani0102** [comment]
> Are these expected at the end of the Ineffective section along with user-added items?
Yes, that will make the most sense. 

> By matrix , do you mean to include column headings for these options? I understood the above 5 should come along with user added emotions list.
The above 5 should come along with user added emotions list

>Can I get the researcher for this? Which server address to be used - api-staging or api server?
Used api server and researcher id is skb6k99hbamb5g6m70rg  and user id is U7591765158

**Comment by michaelmenon** [comment]
@sarithapillai8  is working on it and we will update on this as soon as we complete the QA. we will update the GitHub status once moved to QA

**Comment by divyav2020** [comment]
We have updated in Staging
[LAMP_Admin Website_LAMP DBT change.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/9581691/LAMP_Admin.Website_LAMP.DBT.change.xls)

**Comment by Devayani0102** [comment]
I just tested it in staging. For the 'urges', we have 'die by suicide and 'quit therapy' hardcoded. We also need to add the remaining 4 ("die", "suicide", "use/drink", self-harm").

Also, Is it possible to make adding 'emotions' while making a new diary card optional? Right now, you have to add at least one emotion (in addition to the one hardcoded) for the DBT diary card to work.

**Comment by ZCOEngineer** [comment]
Sure @Devayani0102, we shall update and let you know.

**Comment by sarithapillai8** [comment]
@Devayani0102 Changes are updated in dashboard-staging. Please have a look.

**Comment by Devayani0102** [comment]
More changes requested:

1. Change the scale for emotions and targets to read: **'0= Not at all- 5= Extremely Strong'** instead of '0= Not at all- 5= Extremely'.
2. In Emotions, change 'sad' to 'sadness'
3. In Urges, remove 'Use/Drink' and 'Suicide'

**Comment by divyav2020** [comment]
We have updated the changes in Staging

**Comment by Devayani0102** [comment]
Yes, that will work.

**Comment by sarithapillai8** [comment]
Updated in dashboard-staging. Please check and let me know if any change.

**Comment by Devayani0102** [comment]
Looks good! Can we also remove the line "Both good and bed emotions can be added here" from the emotions section.

**Comment by sarithapillai8** [comment]
@Devayani0102 Updated in dashboard-staging.

**Comment by carlan1** [comment]
Appears functional in staging.

**Comment by ZCOEngineer** [comment]
@Devayani0102 anything pending on this?

**Comment by Devayani0102** [comment]
After the latest release, the changes made before oct 6th do not show up in production.

**Comment by sarithapillai8** [comment]
@Devayani0102 @ertjlane @carlan1 @michaelmenon @ZCOEngineer 
LAMP-activities are not released to production. Last update was done on April 25. If you can release that to production, you can see the changes.

**Comment by carlan1** [comment]
Made release. Will close now, reopen if not functional in production.
