### ISSUE TITLE
mindLAMP tabs keep showing pop-up that gives an introduction/description of that tab

### ISSUE THREAD

**Issue by Tuna9129** [BIDMCDigitalPsychiatry/LAMP-platform#689]
**Describe the bug**
Whenever patients open up mindLAMP and click on one of the tabs, a popup (on the bottom) describing the tab comes up each time that the patient clicks on that tab. 

**To Reproduce**
1. Go to mindLAMP 
2. Click on any tab such as Manage
3. A popup on the bottom shows up saying "Welcome to the Manage section. Take steps to refocus, reflect, and recover"
4. Exit out of the app (on iPhone, swipe up and drag the mindLAMP2 window and swipe up again to fully close the app) 
5. Click on mindLAMP again and go back to any of the tabs and the popups will show up again 

**Expected behavior**
It should only show up once (the first time that the patient opens up the specific tab in the app) and not repeatedly as it can be very annoying and frustrating for patients to see it over and over again. 

**Screenshots**
![9293EC55-A6D3-4D4F-A6BC-BF5274BB9E16_1_102_o](https://user-images.githubusercontent.com/105741216/187552592-bf5ba726-4cb7-402b-8781-c29a0ee2d369.jpeg)

![255FEA78-B9AB-4BEC-81D5-3EB5623FB286_1_102_o](https://user-images.githubusercontent.com/105741216/187552594-35ef37c1-9aa1-415b-b916-40d2cb892493.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.6

**Comment by sarithapillai8** [comment]
@Tuna9129 
Once the popup is closed, it will not show up again. That was the requirement. It will show until the user closes it. Could you confirm on this and let us know if we need to change the functionality?

**Comment by Tuna9129** [comment]
Hello! Thank you for your response. So yes, that was the requirement and the expected behavior, but the pop ups keep showing up. 

I have attached a video showing the unexpected behavior. As you can see, even after closing the popups (and then closing the app), if I re-open the app, the popups show up again. 


![2059A0D4-C2BE-4107-898C-ABEA3399BEE1_1_102_o](https://user-images.githubusercontent.com/105741216/187718671-8727b65b-97f2-4b46-9676-00fd68469969.jpeg)

**Comment by jijopulikkottil** [comment]
@Tuna9129 Thanks for the details.
We were clearing the cache on every app launch, so clearing the cache leads to resetting the states of popups on every app launch.
With the #670 issue fix, we are clearing the cache only when user logged out. So this issue is also resolved.

The latest staging pointed test flight version [2022.8.24 (389)](https://testflight.apple.com/join/TSpdLc6U) is working fine.

**Comment by Tuna9129** [comment]
Great! Thank you!
