### ISSUE TITLE
User getting unexpected notifications 

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#691]
**Describe the bug**
User U9938684473 has been getting notifications for activities that have been deleted. See the video attached below. 

https://user-images.githubusercontent.com/103677721/187991586-30275e39-5bcd-4b5a-8ebc-14dec9a7694b.MP4

Currently, the user does not have any activities assigned. She still gets notifications for 'cognitive games' and 'evening' activities. 

**Smartphone (please complete the following information):**
_not relevant as it can be reproduced on any smartphone_
 - Device: iPhone 7
 - OS: [e.g. iOS14.6]

**Comment by jijopulikkottil** [comment]
We are able to reproduce it if we remove the activity just before the next notification firing time. But it will appear only once after the activity-delete [as per the repeat interval and connectivity].
e.g: Suppose we schedule an activity with hourly say 10 am. And got a notification @ 11 am. If we remove that activity at 11:45 am, we may receive the activity notification one more time at 12 pm. And it will not fire if the the device have ability to sync to server.

@Devayani0102 Could you say the repeat interval set for the activity and how many times receive the notification after deleting the activity.

**Comment by Devayani0102** [comment]
The notifications for "Cognitive Games.." pops up at 4:30 every day, and "Evening.." at 4pm every day. 

I want to note that while troubleshooting, I deleted some other activities and they are not firing any notifications. This issue might be specific to just those particular activities.

**Comment by michaelmenon** [comment]
Thanks @Devayani0102 , team will get back on this after testing by Monday, We have 2 days off(today and Friday) at the dev center so will update on this by Monday.

**Comment by Linoy339** [comment]
@Devayani0102 . Can you please let us know the researcher?

Also, Can you confirm whether these notifications triggered more than 1 day after deletion?

**Comment by Linoy339** [comment]
@Devayani.  There was a fix to be done in activity delete: The issue was that notification was getting fired for once if we delete activity and this won't appear in the next schedule time. This is fixed in staging now( It will not fire after activity delete)
We can push to production after testing it.

Can you please confirm on this :
Did you get the notification which you mentioned above for the past days?

**Comment by Devayani0102** [comment]
Yes, these notifications are still triggered every day.

**Comment by Linoy339** [comment]
@Devayani0102. There was a minor fix in LAMP-worker Its done in staging and got verified by QA.


@avaidyam  . Can you please push Lamp-worker to production, so that this issue gets resolved?

**Comment by carlan1** [comment]
New LAMP-worker release has been made.
