### ISSUE TITLE
Release failed with exit code 1 - Android core

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#692]
Upon new release (Hotfix Release 9.7.2022), we appear to get a new error with error code 1.

![image](https://user-images.githubusercontent.com/103652751/188942191-34ec17dc-5391-4b5b-908a-9770db9f96a1.png)

@saranya-sajeev

**Comment by carlan1** [comment]
![image](https://user-images.githubusercontent.com/103652751/188942822-e6c05203-131b-42e8-a9a5-0a0ea4e94085.png)
Further errors have been provided.

**Comment by saranya-sajeev** [comment]
@carlan1 could you please try now. We have committed a fix.

**Comment by saranya-sajeev** [comment]
@carlan1 Could you please try now. We have already tried to create a release without uploading to playstore with today's date as tag. So please create another tag.

**Comment by saranya-sajeev** [comment]
Ok thanks @carlan1.

**Comment by carlan1** [comment]
We have since received more errors as detailed below.
![image](https://user-images.githubusercontent.com/103652751/189916318-e2e815a1-c3a9-45ef-a70d-b8b81c7926dd.png)

**Comment by saranya-sajeev** [comment]
@carlan1 wearos workflow is not working properly, only mindLamp app workflow is working. Seems it is success.

**Comment by carlan1** [comment]
Thansk @saranya-sajeev. Closing this issue now.

**Comment by saranya-sajeev** [comment]
@carlan1 the release created is live in beta and it is pointing to production. You can move it to production from beta.
