### ISSUE TITLE
Server Address Dropdown Save Feature

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#693]
When using the mindLAMP server address dropdown, there is a set list of server addresses available, along with the option for the user to type their own in. It would be preferable if server addresses entered by specific users were saved to the list, on a user by user basis. I.e. a specific user will be able to save the server address they enter, but not all users can see all server addresses saved by all other users. 

<img width="1440" alt="Screen Shot 2022-09-09 at 10 06 53 AM" src="https://user-images.githubusercontent.com/104088715/189369024-4ff21beb-5757-4a2b-b948-8f395cc6b13e.png">

**Comment by mcurbelo-orangeloops** [comment]
@ertjlane 
This is a small recording of a proposed solution for both this and #694 

Let me know what you think

https://user-images.githubusercontent.com/42544460/192870097-e3edeb18-8e5a-40af-91b7-6cdfb36d990b.mov

**Comment by ertjlane** [comment]
@mcurbelo-orangeloops This is perfect, thank you! It occurs to me that it makes sense to remove 'mindlamp.pronet.med.yale.edu', since it is functionally being replaced by the -api version. But regardless that's exactly what we're looking for.

**Comment by mcurbelo-orangeloops** [comment]
@ertjlane I've removed the non-api version from the options and it's now waiting for review

**Comment by mcurbelo-orangeloops** [comment]
@ertjlane This was fixed here: https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/643
