### ISSUE TITLE
Add LAMP Domain Name to Dropdown

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#694]
**Is your feature request related to a problem? Please describe.**
Collaborators utilize a specific API address when logging into mindLAMP which is not in the dashboard drop-down. Users under this collaborator may have been entering the incorrect API as a result.

**Describe the solution you'd like**
Add 'mindlamp-api.pronet.med.yale.edu' to dropdown options

<img width="1440" alt="Screen Shot 2022-09-09 at 10 08 03 AM" src="https://user-images.githubusercontent.com/104088715/189369332-59932013-32df-45c9-828a-cf9bec31554d.png">

The long term solution for something like this has been requested as a feature in issue #693. However, this is an urgent short fix while that is a longer term solution.

**Comment by mcurbelo-orangeloops** [comment]
Fixed with this PR: https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/643
