### ISSUE TITLE
Survey Visualization issue on desktop

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#695]
**Describe the bug**
The survey visualization in the question view shows 'Nan' instead of dates( see attached screenshot). This only happens while using a desktop browser and not on smartphones. 
<img width="803" alt="Screen Shot 2022-09-20 at 4 08 12 PM" src="https://user-images.githubusercontent.com/103677721/191356540-47354583-4559-4608-92cf-0ac700d1722b.png">

**To Reproduce**
and 
**Expected behavior**
See attached video: 

https://user-images.githubusercontent.com/103677721/191359841-96fc7412-2316-4ace-b10e-69e3e80387b3.mov

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: iphone 13
 - OS: ios

**Comment by ZCOEngineer** [comment]
@Devayani0102, We shall check this and update

**Comment by divyav2020** [comment]
We have updated in staging

**Comment by Devayani0102** [comment]
![IMG_2483](https://user-images.githubusercontent.com/103677721/191843333-d5c9e29a-d0fd-4471-a1ff-2b73d256ff6a.PNG)

When I tried testing this in staging, this error comes up as soon as I click to access any visualization.

**Comment by divyav2020** [comment]
We have updated in Staging
