### ISSUE TITLE
Date format change for DBT Diary Card

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#696]
For the DBT Diary card, is it possible to switch the date format? For example in the image below- is it possible to say 7/19- 7/26 instead of 7/26-7/19. 

<img width="632" alt="Screen Shot 2022-09-20 at 4 54 04 PM" src="https://user-images.githubusercontent.com/103677721/191363041-8dd0721e-0919-4a7c-a005-f6b57523750a.png">

**Comment by ZCOEngineer** [comment]
@Devayani0102, we shall check and update

**Comment by divyav2020** [comment]
We have updated in staging

**Comment by Devayani0102** [comment]
appears to be working in staging
