### ISSUE TITLE
SensorKit duplicated SensorEvent

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#699]
Upon calling SensorKit's messages sensor, some of the events appear to be duplicates.

<img width="992" alt="Screen Shot 2022-10-04 at 3 23 11 PM" src="https://user-images.githubusercontent.com/103652751/193908817-b656933a-a8e2-43fd-a7b9-f649c45da379.png">

This appears to be the case for some other sensors as well.

The test user in question here is 'U4284235549', using beta app in iOS.

**Comment by ZCOEngineer** [comment]
@carlan1 we shall check this and update.

**Comment by jijopulikkottil** [comment]
We couldn't see `message_usage` data using the API https://api-staging.lamp.digital/participant/U4284235549/sensor_event?origin=com.apple.sensorkit.message_usage

We are testing it locally. but no data is captured yet. We will update here once we get the sufficient data to test.

**Comment by carlan1** [comment]
@jijopulikkottil The link you sent where you called the API specified "message_usage" in the SensorSpec field, but I believe the sensor is named "messages_usage". I tried replacing the spec with the proper name, and I am getting data using the API tool.

**Comment by jijopulikkottil** [comment]
Yes, we can see lot of duplicates on the account U4284235549.
We did some optimisation, but we have to reproduce it to verify the issue. So we are planning to keep the fetched results in another folder in device. So we can verify it with synced data in server vs the local data.
We need few more Daya to complete this task.

**Comment by carlan1** [comment]
Ok, as soon as testing is complete we would like this fix pushed.

**Comment by jijopulikkottil** [comment]
Coding completed. Testing is going on. We can push the code once we verified with enough samples.

**Comment by jijopulikkottil** [comment]
This fix is for all SensorKit sensors with duplicate timestamp.

**Comment by ZCOEngineer** [comment]
We will be pushing this today

**Comment by jijopulikkottil** [comment]
Duplicate timestamp issue seems to be fixed. The staging pointed version 2022.10.26 has been submitted last week

**Comment by carlan1** [comment]
Appears fixed in staging
