### ISSUE TITLE
Editing a survey after it's been made

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#70]
> **Collaborator**: I noticed that not changes can be made to a survey instrument once it has been saved. I understand this is to protect the integrity of the data, but if you are combining many instruments into one survey (which takes a long time to build) and notice an error when testing the survey on the app, we have to spend double the time by rebuilding the entire survey. Can you add a production mode feature, or something that allows you to go back and edit a survey to save time and streamline testing in the future?

This code should be removed from SurveyCreator.tsx and ActivityList.tsx.

**Comment by sarithapillai8** [comment]
@avaidyam 
Do you mean to enable the option to update a survey instrument and add an option to make it non-editable if the update option is to be disabled?

**Comment by avaidyam** [comment]
@sarithapillai8 Even simpler - surveys should always be editable just like Jewels/Tips/etc.

**Comment by divyav2020** [comment]
@avaidyam we are unable to reproduce this issue. Hence kindly provide us with more details.
Meanwhile, we request you to clear the cache and retest.
