### ISSUE TITLE
Add 'totalScreenWakes' property to deviceUsage SensorKit data

### ISSUE THREAD

**Issue by jijopulikkottil** [BIDMCDigitalPsychiatry/LAMP-platform#702]
Add 'totalScreenWakes' property to 'com.apple.sensorkit.device_usage' SensorKit data

**Comment by jijopulikkottil** [comment]
Fixed and code pushed.
Version 2022.10.6. is available for internal team members.

**Comment by jijopulikkottil** [comment]
The staging pointed version 2022.10.6 (391) is available for external testing.

**Comment by carlan1** [comment]
Will test and close after testing

**Comment by carlan1** [comment]
Closing for now as appears to be fixed.
