### ISSUE TITLE
Android Uncaught Exception SSLHandshake

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#705]
**Describe the bug**
Three users are experiencing the same uncaught exception error. 

**Screenshots**
![U0854727957_HK00030_Samsung-Galaxy-A42-5G-Android12](https://user-images.githubusercontent.com/104088715/196478749-65c6fdb0-2bac-43bf-87f2-98b9c2b536c7.jpeg)

Devices
- SamsungOne UI Core version 2.5
- Android 10

- Oppo-Find-X5_Color
- Android 12

- Samsung Galaxy A42 5G
- Android 12

**Additional context**
This appears to be part of a slew of recent android related issues that have arisen - see issues [638](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/638#issuecomment-1280930308) & [648.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/648#issuecomment-1281122594)

**Comment by michaelmenon** [comment]
@ertjlane we will check and confirm this in beta.

**Comment by michaelmenon** [comment]
Hi @ertjlane, @avaidyam , @carlan1  , This issue comes if the SSL certificate on the server has issues with Intermediate certificate .

Please resolve this issue with SSL certificate.
you can verify this with this command : 

openssl s_client -debug -connect api.lamp.digital:443

**Comment by michaelmenon** [comment]
@avaidyam yes team will be updating on this exception to show an alert to user.Want to make sure the root cause of this issue is resolved.

**Comment by ZCOEngineer** [comment]
We shall push an update for this on Tuesday. Issue is handled and we are testing it here.

**Comment by carlan1** [comment]
The root cause is handled? Or do you mean you have created the dialog/alert and are testing it?

**Comment by michaelmenon** [comment]
Hi @carlan1  yes we have created the dialog/alert and are testing it.. will be pushed by Tuesday. The SSL certificate issue needs to be she led by your team I think.

**Comment by saranya-sajeev** [comment]
We pushed code and build is in review.

**Comment by divyav2020** [comment]
Updated the changes in beta build

**Comment by ertjlane** [comment]
This appears to be fixed in Beta.
