### ISSUE TITLE
Changes to Jewels A and B

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#707]
In **Jewels B** the jewel shapes are really similar and hard to differentiate (look at the attached screenshots). We need to make sure that they are always differentiable. 
![IMG_2864](https://user-images.githubusercontent.com/103677721/197264058-9d9cebd4-872a-4e18-ba3f-84d424773827.jpeg)
![IMG_2868](https://user-images.githubusercontent.com/103677721/197264070-c162b894-e4b6-4e21-8033-9a66276c1878.jpeg)

For both **Jewels A** and **Jewels B**, can we make the following changes:
1. Increase the size of the jewels. 
2. Change the background color every time someone moves up a level.

**Comment by sarithapillai8** [comment]
@Devayani0102 
Do you suggest to use new different shapes or can we use different color?

**Comment by Devayani0102** [comment]
If possible, let's use different shapes.

**Comment by sarithapillai8** [comment]
[JEWEL ICONS.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/9869951/JEWEL.ICONS.zip)
@Devayani0102 Could you please check this attachment and confirm the shapes?

**Comment by Devayani0102** [comment]
Yes, these look distinct enough. Is there a way to ensure that the background color is different from the jewels color?

**Comment by sarithapillai8** [comment]
@Devayani0102 Can we use a common different background color for jewels game? Can you suggest?

**Comment by Devayani0102** [comment]
We want to change the background color every time someone levels up in the game. 

> For both Jewels A and Jewels B, can we make the following changes:
>
>1. Increase the size of the jewels.
>2. Change the background color every time someone moves up a level.

**Comment by sarithapillai8** [comment]
@Devayani0102 

Increase the size of the jewels. - This will be a major UI change, so it will take some time. 

Change the background color every time someone moves up a level. - Can we use a static set of colors? Do we have a set of colors to use?

**Comment by Devayani0102** [comment]
We can use different shades of blue starting from white- for example (color hex- #FFFFFF, #BDD2FA, #5E92F2, #1257D9, #1A4493)

We should remove the blue jewel as it will not show up properly on blue background.

**Comment by divyav2020** [comment]
We have updated the changes in Staging

**Comment by Devayani0102** [comment]
The white background blends in with the headers, we should remove #FFFFFF. 
Can we increase the font size for the numbers inside the jewels.

**Comment by sarithapillai8** [comment]
Updated changes in dashboard-staging. Could you review ?

**Comment by Devayani0102** [comment]
Looks good in staging!
