### ISSUE TITLE
Survey List Item Descriptions Missing

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#708]
**Describe the bug**
For list item questions in mindLAMP survey activities, the 'option text' is not appearing in the surveys, despite being written in the survey's activity creation page. Creating a new survey file does not appear to resolve the issue. This may be a product of the most recent update, as users started experiencing this issue after the update on 10/19. 

**Screenshots**
<img width="971" alt="Screen Shot 2022-10-25 at 10 18 36 AM (2)" src="https://user-images.githubusercontent.com/104088715/197803489-1a62d40f-79e8-4198-acc9-98cb8efd48ae.png">

<img width="1416" alt="Screen Shot 2022-10-25 at 10 19 22 AM (2)" src="https://user-images.githubusercontent.com/104088715/197803445-a1966928-33e1-47ac-84a9-256ee0c8e268.png">

This has been observed from the admin account on the dashboard across multiple computers, in addition to the below phone.
Samsung Galaxy S7, Android 9
Collaborators have also reported the issue appearing on iphone 10 devices

**Comment by sarithapillai8** [comment]
Fixed and updated in dashboard-staging.

**Comment by carlan1** [comment]
Appears fixed in dashboard-staging

**Comment by ertjlane** [comment]
Thanks for the quick attention to this. Can we get an update on how this issue occurred? It seems as though it may have been a byproduct of the 10/19/22 update.

**Comment by sarithapillai8** [comment]
@ertjlane 
This happened while we did the update for caching tags of activities on Aug 9 update. Missed question descriptions over there and didn't notice.

**Comment by ertjlane** [comment]
To clarify, this was part of an update implemented on August 9th? Because it manifested this week - I'm confused as to how a bug in an update from early August would only start affecting our systems now.

**Comment by sarithapillai8** [comment]
This was part of the update on Aug 9. But the production was release on [2022.10.20](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/releases/tag/2022.10.20) after that update.
