### ISSUE TITLE
(+) sign next to Cortex in Prevent tab causes page to crash

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#71]
> **Collaborator**: This is really about "Cortex." Sometimes when I click on the + sign next to cortex it works, but more recently it has been taking me to a blank page and logging me out. I experienced this on dashboard but had a participant just tell me that it is happening on mobile as well.

**Comment by sarithapillai8** [comment]
@avaidyam 
We are not able to reproduce this issue.
