### ISSUE TITLE
mindLAMP Blank Screen

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#710]
**Describe the bug**
A user reported seeing a blank screen when opening the app. Upon closing the app and reopening mindLAMP would open normally. 

iPhone 8 plus
Software version 15.6.1

This may or may not be connected to Issue #638

**Comment by jijopulikkottil** [comment]
FYI - last day same time, (about 25 hours back), we experienced same issue with staging dashboard (dashboard-staging.lamp.digital). After installing app, got white screen, the login page also not loaded.

**Comment by MattMatt27** [comment]
Duplicated in more detail by issue: https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/812
