### ISSUE TITLE
Android user receiving notifications for monthly activities 

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#712]
**Describe the bug**
User U3600685320 is receiving notifications for ALL the unassigned breathe activities. 

**To Reproduce**
1. install mindLAMP, log-in, reboot the phone
2. notifications will appear in ~30 mins after reboot 

**Screenshots**
![Screenshot_20221031-093503](https://user-images.githubusercontent.com/103677721/199041205-701ed58c-48c3-4576-82a5-7e3979ba546b.png)
![Screenshot_20221031-110249](https://user-images.githubusercontent.com/103677721/199041219-e47d31cb-5434-45ff-bf59-fa4e1b49afc4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy S22 Ultra (user), Moto g play:2021, android 10 (test phone), Google Pixel 2: Android 11 (test phone)

**Additional context**
Issues started after the latest update.

**Comment by ZCOEngineer** [comment]
We shall check this and update.

**Comment by ZCOEngineer** [comment]
We have checked for notifications but could see only scheduled notifications. We are continuing our testing on this.

**Comment by michaelmenon** [comment]
When we checked all these notifications are from the assigned activities only, but it seems all the old notifications are being fired after user switches on the device after a long gap. We can discuss this in our call today.

**Comment by michaelmenon** [comment]
Thanks @Devayani0102 , we will check on and update on it asap.

**Comment by ZCOEngineer** [comment]
We are working on a solution for this, shall post update soon.

**Comment by anjumg03** [comment]
We have pushed a fix for this issue.

- Monthly scheduled activities filtered on the basis of date and time

**Comment by carlan1** [comment]
Fix pushed to lamp-core-ios

**Comment by ZCOEngineer** [comment]
@carlan1 Fix pushed to LAMP-core-android

**Comment by ZCOEngineer** [comment]
Could you close this if this is tested ok.
