### ISSUE TITLE
Survey question description missing

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#714]
**Describe the bug**
For all the questions in mindLAMP survey activities, the 'question description' is not appearing in the surveys, despite being written in the survey's activity creation page. Creating a new survey file does not appear to resolve the issue. Users started experiencing this issue after the update on 10/19.

**Screenshots**
![Screenshot 2022-11-02 101019](https://user-images.githubusercontent.com/103677721/199512636-8d8bf153-5da0-42ae-a3ca-61ec88e6fe8f.png)

![Screenshot 2022-11-02 101128](https://user-images.githubusercontent.com/103677721/199512643-742b1e68-e964-49e2-9388-af40e83c5a8b.png)

**Comment by sarithapillai8** [comment]
@Devayani0102 It seems duplicate of https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/708 which is already fixed in staging.

**Comment by Devayani0102** [comment]
@sarithapillai8 #708 is list item description missing. This issue is for the question description missing. In the screenshot above, there should be a line below "over the past have you?" saying: "Rate form 1 to 10".

**Comment by divyav2020** [comment]
We have updated the fix in staging

**Comment by Devayani0102** [comment]
This is fixed in staging
