### ISSUE TITLE
New Game Request: Spin the wheel

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#715]
A new cognitive game needs to be added to mindLAMP. More instructions about the game can be found on this Webpage:
[Iowa Gambling Task](https://digitalpsychiatry.notion.site/Iowa-gambling-task-b3fe52b5482e42888724d60983515d88)

**Comment by michaelmenon** [comment]
we will be adding an ETA on this asap

**Comment by ZCOEngineer** [comment]
Development of this game is in progress.

**Comment by sarithapillai8** [comment]
We are progressing on the development and may take some more time to finish this , as there are some complexities in the implementation.

**Comment by sarithapillai8** [comment]
Please see the progress of game attached. Probability integration and the activity creation from dashboard and its integration are pending. We are trying to finish the development phase by the end of next week and QA will start after that.

https://user-images.githubusercontent.com/63710347/207266726-f9596b65-f9c1-4cde-b059-cf5aa1bd3ffd.mp4

**Comment by sarithapillai8** [comment]
Game development is in progress. Activity settings for this new game implemented in LAMP-dashboard and integrated with game. Translation changes are also completed. We are stuck with wheel pointer issue and we are trying to fix it ASAP. Hopefully we can update the game in dashboard-staging after QA by the end of next week.

**Comment by sarithapillai8** [comment]
@avaidyam @Devayani0102 

We have the data format for each entry in temporal_slices is like : 
     {
        duration: duration of last action,
        item: index of spin,
        level: index of buttons (1 - red, 2 - yellow, 3 - green, 4 - blue), 
        type: balance,
        value: null          
     }
Could you please confirm these values required for each of these keys? 
Do we need to record the won/loss values explicitly? if so where to include them?

**Comment by sarithapillai8** [comment]
@Devayani0102 Could you please review and confirm the above comment?. We have done as mentioned in the comment. Our QA started testing in our zco staging.

**Comment by Devayani0102** [comment]
@sarithapillai8 we do not need to record the win/loss values explicitly. However, we do need to record wether it was 'high risk' condition or 'low risk' condition, since these will be randomly assigned to different buttons each game.

**Comment by ZCOEngineer** [comment]
@Devayani0102 We shall review this and get back

**Comment by ZCOEngineer** [comment]
We shall update the ETA for this by this weekend

**Comment by sarithapillai8** [comment]
We have updated the game in dashboard staging. Our QA is doing testing. You can review and suggest changes if any.

**Comment by divyav2020** [comment]
We have updated Spin the Wheel game in Dashboard staging
[LAMP_Admin Website_New Game Request Spin the wheel.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/10360388/LAMP_Admin.Website_New.Game.Request.Spin.the.wheel.xls)

**Comment by Devayani0102** [comment]
The game looks good!  Can we make the following three changes:
1. change the default probability of '0' to 50 instead of 0. can we also add more options like 25 and 75.
<img width="1077" alt="Screen Shot 2023-01-06 at 10 03 59 AM" src="https://user-images.githubusercontent.com/103677721/211053147-73dad92d-faac-4c1e-b204-ca1d64deacb0.png">

3. The high and low conditions needs to be randomized each game. Currently the first two buttons are high risk and the next two are low risk. This order needs to be different each game.

5. can we make the wheels smaller in order to fit on a smartphone screen? I have attached the current screenshot below.
![IMG_6600304C0BDD-1](https://user-images.githubusercontent.com/103677721/211038286-4a9a3112-7285-4ae8-96c3-1425378ddc0b.jpeg)

**Comment by ZCOEngineer** [comment]
@Devayani0102 were you able to test the update?

**Comment by ZCOEngineer** [comment]
We shall check this and update @Devayani0102

**Comment by sarithapillai8** [comment]
>For the temporal slices, can we add the condition type (High risk/ Low risk) to the value key?

What do you expect here? 0/1 (0-high, 1-low) or in string format - High risk/ Low risk?

**Comment by sarithapillai8** [comment]
@Devayani0102 Graph change requested is updated in dashboard-staging.

**Comment by Devayani0102** [comment]
We can use 1- high risk and 0-low risk.

**Comment by sarithapillai8** [comment]
@Devayani0102 The changes are updated in dashboard-staging.

**Comment by divyav2020** [comment]
We have updated Spin the Wheel game changes in Dashboard staging

**Comment by Devayani0102** [comment]
Looks good in staging.
