### ISSUE TITLE
High Score for games

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#716]
Can we add a high score count for Jewels A, Jewels B, Spatial Span, Pop the balloon, Cats and Dogs. Example of what it can look like is in the screenshots below. This value should be that participant's highest score for that level/game. 

<img width="496" alt="Screen Shot 2022-11-08 at 4 31 31 PM" src="https://user-images.githubusercontent.com/103677721/200681629-afb0afe8-bd4d-46df-b088-eff2ce39dab6.png">
<img width="496" alt="Screen Shot 2022-11-08 at 4 24 32 PM" src="https://user-images.githubusercontent.com/103677721/200681648-c77f554c-d2c6-4080-a4d3-322f31af2f55.png">
<img width="499" alt="Screen Shot 2022-11-08 at 4 19 09 PM" src="https://user-images.githubusercontent.com/103677721/200681669-da47b3b1-9ec3-4df8-a887-52e9d72c79df.png">
<img width="499" alt="Screen Shot 2022-11-08 at 4 42 53 PM" src="https://user-images.githubusercontent.com/103677721/200682406-513b9af5-10bb-4020-ab89-d8e2cdcbef59.png">

**Comment by sarithapillai8** [comment]
@Devayani0102 We are not saving the score value for all games. The data we save in temporary slices are the only one common to all games. So we need to create new API for calculating the score using those data? Do you have any other suggestions?
