### ISSUE TITLE
Data Portal Error: Minified React Error #310

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#717]
**Describe the bug**
A Minified React error pops up while trying to assess the visualizations in data portal.  

**To Reproduce**
1. Make sure that you are in the advance mode
2. Go to any study in dashboard
3. Click on data portal 
4. Click on the analyze researcher arrow on the left 
5. Click on any tags (for visualization)
6. See error

**Screenshots**
<img width="1389" alt="Screen Shot 2022-11-10 at 9 51 23 AM" src="https://user-images.githubusercontent.com/103677721/201127006-b66909dc-7736-4a9e-ba22-584ca67029f9.png">

**Desktop (please complete the following information):**
 - OS: IOS 
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: IOS 16.0.2

**Comment by sarithapillai8** [comment]
@Devayani0102 Could you confirm whether we have to work on this? Your team developed this section and actually we have no idea about this section.

**Comment by ertjlane** [comment]
@sarithapillai8 We will pass this on to a separate team, thank you.

**Comment by falmeida-orangeloops** [comment]
Noted!

**Comment by falmeida-orangeloops** [comment]
This should be fixed by BIDMCDigitalPsychiatry/LAMP-dashboard#680.

**Comment by ertjlane** [comment]
This appears to be fixed in staging!
