### ISSUE TITLE
Step Count on Cortex showing up too many times

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#72]
> **Collaborator**: This "step count" box is showing up so many times that i cannot even scroll to the bottom of the page.
> 
>  [Cortex_Issue.mp4.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5688950/Cortex_Issue.mp4.zip)

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please provide the participant id and credentials to check this?
