### ISSUE TITLE
New cognitive game: Maze task

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#726]
A new cognitive game needs to be added to mindLAMP. More instructions about the game can be found on this Webpage:
[Maze Game](https://digitalpsychiatry.notion.site/Maze-task-604e8199db7647848eed1a64d54f6962)

**Comment by sarithapillai8** [comment]
@Devayani0102 The activities can be accessed from web browser also. So in that case do you want handle this with arrow buttons?

**Comment by Devayani0102** [comment]
Yes, it makes sense to use arrow buttons on web browser. However, can we make sure that these arrows are not displayed in the app version?

**Comment by sarithapillai8** [comment]
We are working on an algorithm to generate maze.

**Comment by sarithapillai8** [comment]
@Devayani0102 It will be difficult to use pictures as maze. We have to find out the co-ordinations of maze wall to handle hitting of balls. We are working on the algorithm based on this - https://github.com/codebox/mazes.

**Comment by sarithapillai8** [comment]
@Devayani0102 Maze generation is completed using the algorithm. On the same canvas of maze, we are generating the ball shape and we are trying to incorporate the ball movement inside the maze using the cell positions inside the maze.

**Comment by michaelmenon** [comment]
Hi @Devayani0102 , we have assigned one more engineer to work on the accelerometer integration for mobile devices in parallel to the Desktop development. The maze development is completed, we will update asap after the game play integration.

**Comment by sarithapillai8** [comment]
@Devayani0102 
Please see the progress of ball movement in desktop version.

https://user-images.githubusercontent.com/63710347/219619983-bd0c41ab-3dd3-467b-8573-ecf3e0cf5a85.mp4

**Comment by sarithapillai8** [comment]
@Devayani0102 

Please see the attached demo videos for desktop and mobile versions. Is it ok to continue with the maze designs shown in these videos?


https://user-images.githubusercontent.com/63710347/221777541-52bdd92b-2ee4-4228-b568-e6d6a88e00b6.mp4

https://user-images.githubusercontent.com/63710347/221777550-f8fb8687-f107-4ff4-8ce8-e7541c0b8914.mp4

**Comment by sarithapillai8** [comment]
@Devayani0102 
Please see the progress of the game with 2 balls: 
https://user-images.githubusercontent.com/63710347/222111002-98705a1c-db60-4212-9d94-f40804bfead0.mp4

After going through the attached videos, please let us know which one we can proceed with. The initial development was done to generate the exact matching maze in the requirement. But It was hard to manage accelerometer events in that. This latest one is integrated with both mobile and desktop events. But we might not be able to generate the exact maze requested. Please share your suggestion.

**Comment by Devayani0102** [comment]
The second version looks better. It is okay if the mazes are not same, however, we need to have levels (the number of circles/difficulty should increase). Is that possible in the current version?
Also, the ball need to be bigger to make the game more accessible.

**Comment by sarithapillai8** [comment]
Yes we can manage the difficulty levels with the number of circles. Ball can be made bigger. We can continue with the 2nd version. Thanks @Devayani0102 .

**Comment by sarithapillai8** [comment]
@Devayani0102 Please check the attached video for the ball size change and let us know if this is enough.


https://user-images.githubusercontent.com/63710347/223099544-124fade0-f9ad-4fcd-83c4-710d30a23ca7.mp4

**Comment by sarithapillai8** [comment]
@Devayani0102 We have implemented levels for the maze game. Please see the attached.

https://user-images.githubusercontent.com/63710347/223710493-cf0373ba-1bf6-46d3-af2c-b7b6c0d2f17f.mp4

**Comment by sarithapillai8** [comment]
@Devayani0102 Do we need to start the game from level 1 always? 
We will not be adding ball number settings for the activity. From level 1 to 6, there will be 1 ball and above 6 there will be 2 balls.

**Comment by Devayani0102** [comment]
Yes, the game will always start from level 1.

**Comment by sarithapillai8** [comment]
We are facing some package issues while generating build file for dashboard integration. Once it is fixed we can start QA and update dashboard staging.

**Comment by ZCOEngineer** [comment]
We had started QA, there is an issue that our QA reported. The ball getting stuck on borders on collision. We are working on a fix and its given to QA for testing. We shall update you once ready.

**Comment by ZCOEngineer** [comment]
We are doing QA and we hope to complete this by end of this week

**Comment by Devayani0102** [comment]
The game is not loading in staging dashboard.
<img width="1345" alt="Screen Shot 2023-04-04 at 4 00 23 PM" src="https://user-images.githubusercontent.com/103677721/229907003-6a8faeed-171f-4603-9adf-726f0ce4ebb6.png">

**Comment by sarithapillai8** [comment]
@Devayani0102 We are not seeing any issues with the game. Could you please share the credentials to check?

![image (10)](https://user-images.githubusercontent.com/63710347/229980052-f3071515-5ae1-40f7-a6b9-859223ffb59a.png)

**Comment by Devayani0102** [comment]
There is no option to add maze game for user in dashboard- staging.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Devayani0102** [comment]
https://user-images.githubusercontent.com/103677721/230036878-501ac1fb-4274-4956-b309-964fe72e7229.mp4

**Comment by sarithapillai8** [comment]
@Devayani0102 
You have to add activity spec "lamp.maze_game" using api.lamp.digital server. We have added on for api-staging.lamp.digital. If you have any credentials using staging server, please try.

**Comment by Devayani0102** [comment]
Please take a look at the following feedback and let me know if you have any questions:

1. The maze interface is not as sooth as we would like it to be. The ball seems to get stuck often, I also need to move my phone around too much to move the balls. This may be a result of the area between the circles being too small and the sensors are not sensitive enough.
2. The first few mazes still look really small compared to the phone screen, for someone who is visually impaired, this will create a problem.

Possible solution is to make the **maze size same across all levels** and increase the numbers of circles inside with each level. We should also try to make it more sensitive to phone movement. I have attached an image as an example of what it can look like.

<img width="903" alt="Screen Shot 2023-04-07 at 2 27 55 PM" src="https://user-images.githubusercontent.com/103677721/230659254-ae88ae9d-e7c6-4139-88c0-8f3a80647510.png">

**Comment by sarithapillai8** [comment]
@Devayani0102  We are working on this. Most probably we can update the fixes by the end of next week.

**Comment by divyav2020** [comment]
We have updated the changes in Dashboard Staging

**Comment by Devayani0102** [comment]
The maze itself looks good. 
The ball is still getting stuck at the edge, but it is better than before. Is it possible to bounce the ball in other direction automatically when it touches a 'wall'. 

The next step would be to work on the visualization in portal. 

![IMG_5528](https://user-images.githubusercontent.com/103677721/233454187-353b18c8-a3e8-4415-9ad9-f1a7c720a1da.png)

The screen above should show an average of the time take to complete each level in seconds. 
For example, it took the participant following time to finish the levels: level 1 - 5sec, level 2- 10 sec, level 3- 15 sec, level 4 - 20 sec, level 5 - 25 sec. The final output on the graph should be 15 sec. 

![IMG_5529](https://user-images.githubusercontent.com/103677721/233454164-55a85bde-b16b-469d-9c44-1561b9bd2c69.png)
On this screen it should display the time taken to finish individual levels in seconds.

**Comment by Devayani0102** [comment]
The Game and Portal visualization looks good.
I noticed that the scores are not saved when i exit the game after completing the level. The scores are saved only when I click 'no' in the dialogue box and wait for it to exit on its own. We need to save the scores every time someone completes a level regardless of wether they move to the next level, click on 'no', or exit using the back arrow. 

The video below shows cases where it is not saving the result.
https://user-images.githubusercontent.com/103677721/234359511-e145997b-49fd-4eaf-aa59-3befd43e2443.MP4

**Comment by ZCOEngineer** [comment]
@Devayani0102 the scores not getting saved issue, we shall check and get back

**Comment by sarithapillai8** [comment]
@Devayani0102 Updated in dashboard-staging. Please review..

**Comment by carlan1** [comment]
It appears that the activity will not load when running from the beta app. Is there a way to test this on mobile?

**Comment by sarithapillai8** [comment]
@carlan1 Android beta is pointing to production now. That is the reason for not loading the game there. Can you check the website dashboard-staging?

**Comment by carlan1** [comment]
Game functional on dashboard-staging and mobile app.
