### ISSUE TITLE
Pop the bubbles: Duration

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#727]
Currently pop the bubbles game does not capture duration in the temporal slices.
'temporal_slices': [{'item': 1,
     'level': 1,
     'type': True,
     'value': 'pink go'}

Can we add the duration since the last action to the temporal slice?
For example:

   'temporal_slices': [{'duration': '0.874s',
     'item': 1,
     'level': 1,
      'type': True,
     'value': 'pink go'}

**Comment by ZCOEngineer** [comment]
We shall work on this prior to maze game and update staging.

**Comment by sarithapillai8** [comment]
@Devayani0102 We have updated this dashboard-staging. Please review.
