### ISSUE TITLE
Add 'null' field to device usage property

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#729]
The device_usage sensor provides details about app usage. Native Apple apps are listed by name, but non-Apple apps are given an anonymous identifier without a bundle identifier. We would prefer non-Apple apps to still have a bundleIdentifier property but be given the 'null' value when the bundleIdentifier cannot be listed:

'bundleIdentifier': 'com.apple.MobileSMS' (for apps where the identifier can be recorded)

'bundleIdentifier': 'null' (for apps where the identifier cannot be recorded)

**Comment by ZCOEngineer** [comment]
We shall check on this @carlan1

**Comment by jijopulikkottil** [comment]
@carlan1 , yes we can set as 'null' if `bundleIdentifier` is not populated. [bundleIdentifier only populated for Apple apps].

**Comment by jijopulikkottil** [comment]
Code has been pushed and the Version 2023.2.1 is available for AppStore connect users.

**Comment by carlan1** [comment]
Changes working in staging
