### ISSUE TITLE
Lamp-core-ios build issue

### ISSUE THREAD

**Issue by markpagna** [BIDMCDigitalPsychiatry/LAMP-platform#73]
i tried to compile the master branch of Lamp-core-ios source from github with lamp-swift 1.1.4 package dependency but i’d some issue

“Type ‘Activity’ does not conform to protocol ‘Decodable’”
“Type ‘Activity’ does not conform to protocol ‘Encodable’”
“Type ‘ActivityEvent’ does not conform to protocol ‘Decodable’” and others…

I tried also lamp-swift version 1.1.2 but in the core app there are some classes not recognized.

**Comment by jijopulikkottil** [comment]
@markpagna We are updating our networking source code. Expected to complete on mid of next week.

**Comment by jijopulikkottil** [comment]
@avaidyam Could you please regenerate the networking classes and commit to the LAMP-Swift ?

**Comment by avaidyam** [comment]
@jijopulikkottil Done - they have been regenerated but also removed from the build options to simplify the package for now.

**Comment by jijopulikkottil** [comment]
@avaidyam please find the Pull Request for LAMP-Swift

**Comment by jijopulikkottil** [comment]
@avaidyam please see the [Pull Request](https://github.com/BIDMCDigitalPsychiatry/LAMP-core-ios/pulls) for Lamp-core-ios to fix the build issues.

**Comment by avaidyam** [comment]
@markpagna Could you give it another shot with the updated master branch?
