### ISSUE TITLE
Beta app build incorrect

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#737]
I noticed recently that data queried from the _visits_ and _device_usage_ sensors using the LAMP-py package has been returned in the improper format. The format/schema of the raw data collected throughout the past few days (2/23/23 - present) appears identical to the format from the original SensorKit implementation, before changes were made to the API package (October 2022 onward). Upon further inspection, these improper data points are timestamped with epoch time values indicating they were collected shortly after the most recent LAMP-swift release on 2023/2/23. It appears that this release and version update in LAMP-core-ios caused the TestFlight app to start using a build from October, despite TestFlight reporting that the current build is from January. We need the most recent build to be made available.

**Comment by jijopulikkottil** [comment]
Initially, we were not exposed all fields of some sensors. And later (last Oct, 2022) we exposed all fields of all sensor models.

Now our TestFlight build are seems to be working fine.
We can see device usage of a user here https://api-staging.lamp.digital/participant/U4489753215/sensor_event?origin=com.apple.sensorkit.device_usage

If we check the below data, there are two objects. first one doesn't have data in `webUsageByCategory` and `applicationUsageByCategory`. But the second object have all data. Hope this is not the case you mentioned. It can happen if no data collected in that time. 

Could you share your user id (or the device usage sensor data) to see the issue about  'improper format' ?

```
{
            "data": {
                "notificationUsageByCategory": {},
                "duration": 900000,
                "totalUnlocks": 0,
                "totalScreenWakes": 2,
                "webUsageByCategory": {},
                "totalUnlockDuration": 0,
                "applicationUsageByCategory": {}
            },
            "timestamp": 1677432599954,
            "sensor": "com.apple.sensorkit.device_usage"
        },
{
            "timestamp": 1677425399954,
            "sensor": "com.apple.sensorkit.device_usage",
            "data": {
                "webUsageByCategory": {},
                "duration": 900000,
                "applicationUsageByCategory": {
                    "SRDeviceUsageCategorySocialNetworking": [{
                            "textInputSessions": [{
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 4119.426012039185,
                                    "sessionType": 1
                                },
                                {
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 50402.544021606445,
                                    "sessionType": 1
                                }
                            ],
                            "reportApplicationIdentifier": "F3D64327-AEFD-4293-9794-09398EAA9EFF",
                            "usageTime": 93000,
                            "bundleIdentifier": "null"
                        },
                        {
                            "textInputSessions": [{
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 4119.426012039185,
                                    "sessionType": 1
                                },
                                {
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 50402.544021606445,
                                    "sessionType": 1
                                }
                            ],
                            "reportApplicationIdentifier": "F3D64327-AEFD-4293-9794-09398EAA9EFF",
                            "usageTime": 2000,
                            "bundleIdentifier": "null"
                        },
                        {
                            "textInputSessions": [{
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 4119.426012039185,
                                    "sessionType": 1
                                },
                                {
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 50402.544021606445,
                                    "sessionType": 1
                                }
                            ],
                            "reportApplicationIdentifier": "F3D64327-AEFD-4293-9794-09398EAA9EFF",
                            "usageTime": 35000,
                            "bundleIdentifier": "null"
                        },
                        {
                            "textInputSessions": [{
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 4119.426012039185,
                                    "sessionType": 1
                                },
                                {
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 50402.544021606445,
                                    "sessionType": 1
                                }
                            ],
                            "reportApplicationIdentifier": "F3D64327-AEFD-4293-9794-09398EAA9EFF",
                            "usageTime": 0,
                            "bundleIdentifier": "null"
                        },
                        {
                            "textInputSessions": [{
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 4119.426012039185,
                                    "sessionType": 1
                                },
                                {
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 50402.544021606445,
                                    "sessionType": 1
                                }
                            ],
                            "reportApplicationIdentifier": "F3D64327-AEFD-4293-9794-09398EAA9EFF",
                            "usageTime": 61000,
                            "bundleIdentifier": "null"
                        },
                        {
                            "textInputSessions": [{
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 4119.426012039185,
                                    "sessionType": 1
                                },
                                {
                                    "sessionTypeRepresentation": "keyboard",
                                    "duration": 50402.544021606445,
                                    "sessionType": 1
                                }
                            ],
                            "reportApplicationIdentifier": "F3D64327-AEFD-4293-9794-09398EAA9EFF",
                            "usageTime": 1000,
                            "bundleIdentifier": "null"
                        }
                    ]
                },
                "notificationUsageByCategory": {},
                "totalScreenWakes": 3,
                "totalUnlocks": 1,
                "totalUnlockDuration": 226000
            }
        }

```

**Comment by carlan1** [comment]
The problem isn't that there are empty fields. The fields do not exist in the data. One explanation could be that the user never gave applicationUsage permissions. However, if this were the case, "totalScreenWakes" would still be present. But it is not. Additionally, I have noticed the following: 
1. Duration key is in "s"
2. There are duplicate events / timestamps
3. Arrival and departure ranges are given in s.
Here is an example:
`{'timestamp': 1677350088085,
  'distanceFromHome': 3331.013271354101,
  'arrivalDateInterval': {'start': 698938200, 'duration': 900},
  'locationCategory': 0,
  'departureDateInterval': {'start': 698938200, 'duration': 900}},
 {'timestamp': 1677350088085,
  'distanceFromHome': 3331.013271354101,
  'arrivalDateInterval': {'start': 698938200, 'duration': 900},
  'locationCategory': 0,
  'departureDateInterval': {'start': 698938200, 'duration': 900}},
 {'timestamp': 1677350088085,
  'departureDateInterval': {'start': 698938200, 'duration': 900},
  'locationCategory': 0,
  'distanceFromHome': 3331.013271354101,
  'arrivalDateInterval': {'start': 698938200, 'duration': 900}},
 {'timestamp': 1677350088085,
  'arrivalDateInterval': {'start': 698938200, 'duration': 900},
  'departureDateInterval': {'start': 698938200, 'duration': 900},
  'locationCategory': 0,
  'distanceFromHome': 3331.013271354101},
 {'timestamp': 1677350088085,
  'arrivalDateInterval': {'start': 698938200, 'duration': 900},
  'distanceFromHome': 3331.013271354101,
  'locationCategory': 0,
  'departureDateInterval': {'start': 698938200, 'duration': 900}},
 {'timestamp': 1677350088084,
  'distanceFromHome': 3331.013271354101,
  'departureDateInterval': {'start': 698938200, 'duration': 900},
  'arrivalDateInterval': {'start': 698938200, 'duration': 900},
  'locationCategory': 0},
 {'timestamp': 1677350088084,
  'distanceFromHome': 3331.013271354101,
  'arrivalDateInterval': {'start': 698938200, 'duration': 900},
  'locationCategory': 0,
  'departureDateInterval': {'start': 698938200, 'duration': 900}},
 {'timestamp': 1677350088082,
  'locationCategory': 0,
  'departureDateInterval': {'start': 698885100, 'duration': 900},
  'distanceFromHome': 856.6103589269031,
  'arrivalDateInterval': {'start': 698884200, 'duration': 900}},
 {'timestamp': 1677350088076,
  'arrivalDateInterval': {'start': 698886000, 'duration': 900},
  'distanceFromHome': 0,
  'locationCategory': 1,
  'departureDateInterval': {'start': 698936400, 'duration': 900}}`

The above data came from user "U6937554718" and the timestamps when these events occurred are in the data

**Comment by carlan1** [comment]
@jijopulikkottil I have removed your comment by mistake but the problem was not that the fields were empty. In reality they did not exist. Upon further inspection, lamp.analytics showed that I was using the production version which explains the data format. This is still odd because this "switch" from the beta version to production version occurred immediately after
