### ISSUE TITLE
Personal Access Tokens (PATs) for OAuth2 Support

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#738]
# API/Backend
- The `Credential` object shall be extended with a new property `tokens: array<{ description: string; token: string; }>` where `description` is a user-friendly name provided by the user upon token creation, and `token` is the JWT-encoded token.
- The `service/Credential.ts` CRUD functions need to be updated to allow generation and viewing of tokens. (Could be updates to the existing functions to allow editing the array **or** maybe new API functions?)
- The token contains `origin` and `expiry` fields internally to allow the existing OAuth2 `Secret` or `Token` authorization code paths to work identically for the new PAT feature.
- If the tokens are **not** encoded as JWTs, modifications need to be made to `CredentialRepository._find` and `Security.ts` to ensure token lookup returns the valid non-expired `origin`.

# User Interface
- The existing Credential Manager interface shall be expanded to have a **new sub-dialog/menu** to support PAT management. 
- [See PAT creation steps from GitHub documentation here.](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token) Ignore Step 7 as LAMP PATs will not support scopes (Credential objects are already sufficiently scoped).
- Additionally, the same creation UI needs to support viewing active PATs with expiry and creation dates.
    - PATs will expire but not be automatically removed from the PAT list.
- It also needs to support revocation of individual tokens.

**Comment by bvescovi-orangeloops** [comment]
I realized that we need to verify that the token is valid by looking up the Credential and confirming that the token is in the array, to allow revoking tokens before the expiring date.
We should also do that for the OAuth process confirming that the credential is still alive when authorizing by access token. Currently the credential verification is only made on refreshToken and that could allow users to access the api with a deleted credential while the access token is valid.
Therefore I believe that we should only store the `access_key` inside the token and we should get the origin from the credential in case the token refers to a valid credential.
When verifying we should differentiate between access token which only verifies the identity of the credential with the given `access_key` and api token which should also verify that the token is valid in the tokens array.
We could use a different prefix (Bearer for the access token used within the app and another for personal access tokens from scripts)
In addition think that `created_at` and `expire_at` could also be stored in the array instead of being encoded in the token, then we can revoke it by deleting it from the array or by updating the expiring date to now.

**Comment by avaidyam** [comment]
> to allow revoking tokens before the expiring date

Yes, that’s a fair point. This should still be simple to do as the `Basic` auth flow does this. 

> should also do that for the OAuth process confirming that the credential is still alive

Yes, this is important — good catch! @mcurbelo-orangeloops Is that something already considered elsewhere in the OAuth2 code or no?

> We could use a different prefix

:+1:

> In addition think that created_at and expire_at could also be stored in the array instead of being encoded in the token, then we can revoke it by deleting it from the array or by updating the expiring date to now.

This is also an easier idea too. So the token effectively becomes a randomly generated “temporary” password then, which is exactly what we want.

**Comment by falmeida-orangeloops** [comment]
>> should also do that for the OAuth process confirming that the credential is still alive
>
> Yes, this is important — good catch! **mcurbelo-orangeloops** Is that something already considered elsewhere in the OAuth2 code or no?

@avaidyam I can answer that. No, such a credential validation is not done upon authenticating with a `Bearer` token. The token is only checked to be valid (that is, to be a valid JWT and to comply with the server's signature). That does not allow for manual token invalidation (which would be cool to have).

**Comment by avaidyam** [comment]
Thanks for answering, @falmeida-orangeloops! That is helpful to know. 

@bvescovi-orangeloops I think it would be simple/easy to actually implement it the way you described, since the `Basic` token pathway already does this and the code already exists, so a little bit of copy/paste/modify should go far.

**Comment by bvescovi-orangeloops** [comment]
@avaidyam I don't have permissions to push changes to the repo.
However I send a patch to Facundo and he created [this PR](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/226).
Is this what was on your mind for the server changes?

**Comment by avaidyam** [comment]
@bvescovi-orangeloops Thank you! This is perfect and exactly what I envisioned! I left a few **very** minor comments for changes. If this works as outlined above then I feel we are ready to move to the UI side.

**Comment by ertjlane** [comment]
Our team is currently testing this - we will provide an update by the EOD Friday (03/24) with the status.

**Comment by bvescovi-orangeloops** [comment]
<img width="595" alt="Screen Shot 2023-03-16 at 15 10 29" src="https://user-images.githubusercontent.com/12797520/227933595-f88b1649-a7ba-4729-8a99-bfc3457963be.png">
<img width="599" alt="Screen Shot 2023-03-16 at 15 10 46" src="https://user-images.githubusercontent.com/12797520/227933605-a1d8c697-5893-4b18-805c-80ddbfffbff8.png">
<img width="482" alt="Screen Shot 2023-03-16 at 15 10 56" src="https://user-images.githubusercontent.com/12797520/227933610-a652b1b7-a31d-4efa-8b33-880d8c1a620f.png">

**Comment by avaidyam** [comment]
This looks great for the frontend! @carlan1 Please do share testing results once you are able to replicate it.

**Comment by carlan1** [comment]
We are able to replicate using dashboard-staging.lamp.digital

![image](https://user-images.githubusercontent.com/103652751/231242515-685952df-da89-4c16-94fe-547f2a428dce.png)
