### ISSUE TITLE
"Loopback" OAuth2 server for existing Credentials support

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#739]
To support in-place upgrades to OAuth2, we need a plugin for an off-the-shelf OAuth2 server like Keycloak to support reading/writing credentials to the existing LAMP MongoDB database as the server currently does when OAuth2 is disabled. _(More info to come...)_

This means there are 3 main authentication strategies for LAMP: 
1. Legacy non-OAuth2 mode (aka Basic mode): everything functions the same as it currently does.
2. OAuth2 mode with loopback server: authentication will go through OAuth2 flow to the local Keycloak/other server which checks and modifies credentials in the LAMP database directly. 
    - Existing Credential functions to modify `Credential.password` will no longer work.
    - Non-interactive tools (i.e. scripts/automations) may not be able to authenticate through OAuth2 directly and can instead use the PAT feature in #738.
3. OAuth2 cloud-provider mode: authentication will go through OAuth2 flow to a remote server (Google/Azure/etc) which manages credentials and user info entirely separately. 
    - Existing Credential functions to modify `Credential.password` will no longer work.
    - Non-interactive tools (i.e. scripts/automations) may not be able to authenticate through OAuth2 directly and can instead use the PAT feature in #738.

**Comment by ertjlane** [comment]
Per @bvescovi-orangeloops Further research is needed to verify the viability of this feature. Are you able to provide a check in date when we should hear from you?

**Comment by bvescovi-orangeloops** [comment]
I would say first days of April, probably on my return I'll have feedback for the PAT piece. However I should be able to spend some more time researching that.

**Comment by avaidyam** [comment]
I’d like for us to write a small NodeJS/Express script/app instead of using Keycloak for now. We don’t necessarily want Keycloak to be used to manage multiple OAuth servers, this implementation should only be a “loopback” for OAuth to connect back to the built-in Credentials database for legacy support. 

Let’s use `node-oidc-provider`, which offers a LOT of functionality out of the box for free. [Here’s a tutorial.](https://www.scottbrady91.com/openid-connect/getting-started-with-oidc-provider) [The sample code from the tutorial should be really easy to get started with.](https://github.com/scottbrady91/node-oidc-provider-example/blob/master/src/app.js) In ~50 LOC it’s a functional OAuth/OIDC server with a built-in (debugging use) signing key and login page. Adding Mongo to this to verify accounts against the Credential database should be easy too. [It also has comprehensive API docs for writing adapters](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#adapter)

Here are the steps I think it will take: 
- [ ] Run `node-oidc-provider` demo app and verify it works.
- [ ] Integrate the Node `mongodb` driver and access/query the `Credentials` database. (We **do not** want to add credentials endpoints to `LAMP-server` directly when this makes a lot more sense for right now.)
- [ ] Write the `node-oidc-provider` adapter for our Credentials `mongodb` setup. 
- [ ] Basic “create first password”/“forgot password” implementation: 
    - At the bottom of the login page, there should be a “forgot password” button that takes you to this form.
    - The Forgot Password form should have “email address”, “current password”, “new password” fields.
    - Brand new accounts as created from LAMP are associated to the OAuth provider by email address, and the password is NOT set by LAMP or the user creating the account. 
    - In our case, this means the Credential has `{ access_key: “some@email.com”, password: “” }` (Perhaps `null` instead of `””` works too.)
    - This means if the user enters a blank string/nothing into the “current password” field, they are able to set their password for the first time using the Forgot Password form.

**Comment by bvescovi-orangeloops** [comment]
Hi @avaidyam 
We’ve got some progress in the OAuth custom server.
We were able to:
- Configure it to work with the mindlamp server
- Use it to log in with the credentials from the old database
- Reset the password (or set it for new credentials)
There’s still some way to go as we’ll need to review the configuration, document the set up process and polish the user interface.
To share this and discuss about it we’ll need a new repo.
Could you create one?

**Comment by avaidyam** [comment]
Fantastic, thank you @bvescovi-orangeloops! @ertjlane Could you create a new repo `LAMP-auth-server` for this? Thanks!

**Comment by ertjlane** [comment]
done

**Comment by bvescovi-orangeloops** [comment]
I’ve pushed my changes with a minimal documentation to the [repo](https://github.com/BIDMCDigitalPsychiatry/LAMP-oauth-server)
Here's a couple of videos showcasing the functionality.

https://user-images.githubusercontent.com/12797520/231712237-49411aab-ad20-4db4-bbb8-2b67ed3ab13f.mov

https://user-images.githubusercontent.com/12797520/231712175-6cded057-f745-43a8-a3eb-71b00706ddcf.mov

**Comment by ertjlane** [comment]
@Bruno thanks for this! @carlan1 Could you see if this is replicable?

**Comment by bvescovi-orangeloops** [comment]
@avaidyam I encountered some issues when adding typescript and docker to the project but I was able to run it after some changes.
[here's](https://github.com/BIDMCDigitalPsychiatry/LAMP-oauth-server/pull/1) the PR
