### ISSUE TITLE
DBT Diary Card - Add "Skills" Data to Prevent Page

### ISSUE THREAD

**Issue by elenamrv** [BIDMCDigitalPsychiatry/LAMP-platform#74]
For DBT Diary Card, if the user answers "Yes" to Question 3, then Question 4 shows a list of Skills they can choose from. 

The skills they selected should show up in the Prevent data. The user and their clinician should be able to go to the Prevent page and see a summary of what skills were used on what day. For example, if the user selected Wise Mind, Self Validation, End Relationships, and Cope Ahead on 12/17, then in Prevent there should be something similar to the below:

12/17: 
Mindfulness
- Wise Mind
Interpersonal
- Self Validation
- End Relationships
Emotion Regulation
- Cope Ahead
Distress Tolerance 
- STOP Skill

It should be possible to click on any date a Diary Card has been completed and see the skills reported on that date. They should be sorted by the categories already used (Mindfulness, Interpersonal, Emotion Regulation, and Distress Tolerance).

Please let me know if there are any questions.

**Comment by sarithapillai8** [comment]
@elenamrv @avaidyam 
I don't understand how to implement this  : 
It should be possible to click on any date a Diary Card has been completed and see the skills reported on that date. They should be sorted by the categories already used (Mindfulness, Interpersonal, Emotion Regulation, and Distress Tolerance).

Is this like showing week-view like in feed section and clicking on specific date show the details for skills? 
Do you want to include this above the free text data added last day?

**Comment by elenamrv** [comment]
Hi @sarithapillai8 - 

Please see the slide attached for anther explanation and let me know if you have more questions. We can also talk on the phone if that is easier!

[Skills Used _ DBT Diary Card.pptx](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5716828/Skills.Used._.DBT.Diary.Card.pptx)
