### ISSUE TITLE
Additional White Space Formatting Functionality for Survey Text Questions

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#743]
It would be good to have the ability to format Survey text questions in mindLAMP such that items could be listed, and that enter tabs could be executed in the question (not the answer) text. I.E. to avoid something like this: 
<img width="746" alt="Screen Shot 2023-03-13 at 4 31 02 PM (2)" src="https://user-images.githubusercontent.com/104088715/224825503-5cb345ac-8416-4340-8543-dbe0da08ba83.png">

**Comment by avaidyam** [comment]
@ertjlane Could you clarify this a bit more? I don't think I understand. If you mean allowing tabs and newlines in the question text, the question text should already support Markdown formatting.

**Comment by ertjlane** [comment]
@avaidyam That's exactly correct. Does the formatting of survey questions require formal markdown formatting, as in entering
 <p> This is a new row in the question text </p> 
Or should it be able to be introduced simply by pressing 'enter' on a keyboard? I had been attempting to do the latter.

**Comment by avaidyam** [comment]
Try shift+enter and be sure to use two newlines to create a new paragraph break.

**Comment by MattMatt27** [comment]
Resolved.
