### ISSUE TITLE
mindLAMP App Crashing Android

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#748]
**Describe the bug**
The mindLAMP app is crashing while using the app. This occurs when the user is opening a survey, but it does not seem to be connected to a particular survey question. No other users assigned to the same group (same .json survey file) have had this issue.

**Smartphone (please complete the following information):**
 - Device: Samsung s7
 - OS: Android 11

**Additional context**
I wonder if this issue is connected to similar challenges as 
1. https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/600
2. https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/592
Both of these issues report difficulties with the app loading, or crashing spontaneously, SPECIFICALLY in android 11. While there are slight differences (ex: this issue has not reported any extended buffering, it may be worth interrogating a connection between these issues).

**Comment by ZCOEngineer** [comment]
We shall check this on Android 11 @ertjlane, shall update our findings.

**Comment by ZCOEngineer** [comment]
@ertjlane we were working on #638 which is currently undergoing testing, we shall now check on this and update.

**Comment by ertjlane** [comment]
Great. Is there a relative ETA when we should be expecting to hear an update?

**Comment by ZCOEngineer** [comment]
@ertjlane this is in progress.

**Comment by sijitg** [comment]
QA is in progress.
We have done following changes
- Gradle and libraries updated.
- Log file implementation is optimized.
- Kotlin synthetics which is deprecated replaced with View binding.
- Target version updated to Android 33 .

**Comment by sijitg** [comment]
After watch app update we can consider to integrate Health Connect in phone app also because Fitness Client API is deprecated.
Please see the deprecation notice in below link
https://developers.google.com/android/reference/com/google/android/gms/fitness/HistoryClient
Health Connect details below.
https://developer.android.com/guide/health-and-fitness/health-connect

**Comment by sijitg** [comment]
We have submitted these changes and open testing build is in play store review.

**Comment by divyav2020** [comment]
QA testing is completed for Playstore beta build. It is working fine.
