### ISSUE TITLE
OAuth dashboard doesn't save server address

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#753]
Using the oauth staging dashboard (currently dashboard-oauth.lamp.digital), entering a server address does not persist after clicking out of the "server address" field. Here is a screen recording

https://user-images.githubusercontent.com/103652751/229580096-0300f4e0-6f1d-41d7-9993-5687b71b0be0.mov

Please fix this issue such that the entered server remains and is entered after clicking out of the field.

**Comment by bvescovi-orangeloops** [comment]
This was caused by the latest merge from master.

**Comment by bvescovi-orangeloops** [comment]
I've found the source of the issue.
The Autocomplete was playing with us.
Now is working as expected with the latest code from `feature/oauth`
Can you re-deploy @carlan1 ?

**Comment by carlan1** [comment]
Appears fixed
