### ISSUE TITLE
Introducing Level Up Dialogue Box for Jewels A & B

### ISSUE THREAD

**Issue by Devayani0102** [BIDMCDigitalPsychiatry/LAMP-platform#758]
The current version of Jewels A and B game keeps leveling up until someone presses the exit arrow in the top right corner. This creates an issue for new players who don't know when a level is considered complete. 

To address this, **we need to introduce a dialogue box after each level is finished**. An example of the dialogue box is shown in the image below, and it has already been implemented in maze game #726 
<img width="273" alt="Screen Shot 2023-04-27 at 11 05 31 AM" src="https://user-images.githubusercontent.com/103677721/234905104-93aa0d09-89bb-4d28-a267-05e90e681aed.png">

If the participant clicks on yes, move to the next level. 
If the participant clicks on no, save the current score and exit.

**Comment by sarithapillai8** [comment]
@ertjlane @Devayani0102 Please add priority if we need to work on this.

**Comment by divyav2020** [comment]
Dashboard staging has been updated with above changes

**Comment by ertjlane** [comment]
This has been tested and appears to be operating. Thank you!
