### ISSUE TITLE
Duplicating possible survey responses on mindLAMP

### ISSUE THREAD

**Issue by Tuna9129** [BIDMCDigitalPsychiatry/LAMP-platform#761]
**Is your feature request related to a problem? Please describe.**
When creating new surveys in mindLAMP, it can get quite time consuming because we have to type in the possible answer choices every single time. I know that we can export and import json files for previously used surveys, but this seems like a good feature to use since not everyone (ex: collaborators) will have access to the json files. 

**Describe the solution you'd like**
A possible solution is to have the option to duplicate questions (and thus their possible answer choices) when setting up new surveys on mindLAMP. This is how Google Forms does it. I have attached a screenshot of how google does it below. 

<img width="1453" alt="Screenshot 2023-05-31 at 09 33 57" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/105741216/ec0a72e5-e7bf-4593-9777-6d3593e384f0">

**Comment by sarithapillai8** [comment]
We have started working on this. We are not adding custom button instead we have copyable option for array item with that schema. Package update is required for that and it is almost done. After checking all sections we will be implementing this completely using that. We can update this by next week.

**Comment by ZCOEngineer** [comment]
we closed this by mistake, reopened, QA testing will soon start on this.

**Comment by divyav2020** [comment]
We have updated the changes in Dashboard staging

**Comment by Tuna9129** [comment]
It appears to be working. Thank you.
