### ISSUE TITLE
Custom notifications/activities under the same study

### ISSUE THREAD

**Issue by Tuna9129** [BIDMCDigitalPsychiatry/LAMP-platform#762]
**Is your feature request related to a problem? Please describe.**
Currently, to give users in the "same" study (really its just the same investigator account) custom notifications and or activities, you need to make a whole new study group. This can get a bit tedious if you have 20 different activities and just wanted to customize a notification or activity for that user out (out of 50 users in the study). The same applies for notifications. 

**Describe the solution you'd like**
It would be nice to be able to have at least customized activities and notifications for each user by going to their profile settings. The desired result would allow us to choose to give user A a weekly survey notification on Monday and user B a weekly survey notification on Tuesday without having to create different study groups for each user. 

I have attached a screenshot of a test profile setting page. Currently, if we were to set a schedule in this user's settings, it would apply to all the other users in the same study. It would be nice to have an option in which only the specified user's notifications were changed. Same for activities. 
<img width="1415" alt="Screenshot 2023-05-31 at 14 27 26" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/105741216/0a6415b7-d0a8-40dd-9d10-d55cd2cb8ecf">

**Describe alternatives you've considered**
If it is not possible to have customized activities under the same study, the ability to at least have customized notifications would be great. 

We would like for ZCO to propose a few solutions to this as we understand that this is complicated and don't want to mess up the scheduling/activities. After that, we can pick the one that makes the most sense.

**Comment by ZCOEngineer** [comment]
@Tuna9129 we shall review this and think of options. @avaidyam do you have any thoughts on this?

**Comment by sarithapillai8** [comment]
@Tuna9129 As activities are created under study, it will be difficult to handle activity schedules per user with the current structure. As suggested above, we can add custom notifications for each user.  
We can add a new section to the profile page, titled 'Notifications'. 'Add notification' can open a dialog similar to the current schedule dialog. But this needs some server-side changes. 
@avaidyam Please suggest.

**Comment by avaidyam** [comment]
@sarithapillai8 I've taken a look and tried to consider different options but there are no options I can see that do not require us to rearchitect major parts of the API and backend/database. Please avoid any changes affecting the backend at this time. I'll check in with @Tuna9129 and @jtorous offline about this issue.
