### ISSUE TITLE
Autosave entries

### ISSUE THREAD

**Issue by Tuna9129** [BIDMCDigitalPsychiatry/LAMP-platform#763]
**Is your feature request related to a problem? Please describe.**
We have received numerous comments from users saying that it is frustrating that their responses (especially free responses such as when journaling) are not autosaved. Currently, if users exit from the activity or fully close the app, users have to start over. 

**Describe the solution you'd like**
We would like for there to be an autosave option (for activities in progress) such that when a user starts an activity, their responses are automatically saved. Even after completely closing the app, if the user returns to the same activity, they should be able to pick up from where they left off.

**Comment by sarithapillai8** [comment]
@Tuna9129 @avaidyam 
Do you mean to save it as incomplete activity events or to resume the activity when the user re-opens the application?
Is this change applies to all the activities including games?

**Comment by michaelmenon** [comment]
@carlan1  please see above

**Comment by Tuna9129** [comment]
@sarithapillai8 resume the activity when the user re-opens the application. Instead of all activities, can we just do activities with user text responses?

**Comment by avaidyam** [comment]
@sarithapillai8 I think the clarification for this issue is that we need to store the application state so if the user or system reopens the app/dashboard we return them to where they were. This is not about saving activity-specific data locally (meaning, there should only ever be one active activity and event data bundle saved offline at a time).

**Comment by divyav2020** [comment]
We have updated the following changes in Dashboard Staging. Please Confirm.

**Comment by carlan1** [comment]
Are you saving the data locally or in the server?

If a participant fully exits the app, should they be able to restart?

**Comment by carlan1** [comment]
This does not appear functional in staging - the data does not save, nor is there a dialogue

**Comment by divyav2020** [comment]
The functionlity was working. This may be due to update of some current fixes. We will fix and update you as early as possible.

**Comment by carlan1** [comment]
Just to clarify, we do not want to save any partial or incomplete ActivityEvent here. There should only be an ActivityEvent saved if a participant chooses to submit their response.

**Comment by ZCOEngineer** [comment]
Yes @carlan1

**Comment by divyav2020** [comment]
We have updated the fix in Dashboard Staging. Please Confirm.

**Comment by carlan1** [comment]
Could you change the dialog text to: "Would you like to resume this activity where you left off?"

**Comment by sarithapillai8** [comment]
@carlan1 Updated the dialog text in staging.
