### ISSUE TITLE
mindLAMP Survey Question Load Time Lag

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#765]
**Describe the bug**
In between survey questions multiple participants are experiencing delays of 1.5 - 2 seconds before the next question will load.

Screenshots may be pending, but this should be investigated even if they are not available. 

**Expected behavior**
Survey questions take ~.5 seconds or less.

This error has occurred for the following devices
iPhone XR
iPhone 11
Oppo Find X5
Xiaomi MI CC9 Pro
iPhone XS Max
iPhone 7

**Comment by ertjlane** [comment]
@sarithapillai8  is there any update to the progress on this?

**Comment by sarithapillai8** [comment]
@ertjlane  We will be updating this with #764 next week.

**Comment by ertjlane** [comment]
@sarithapillai8 Thanks, please do as this is higher priority than 764

**Comment by ertjlane** [comment]
@sarithapillai8 Are there any updates on this?

**Comment by michaelmenon** [comment]
Hi @ertjlane , we will update on this asap. @sarithapillai8 is out sick(hospitalized) for last 3-4 days, we will update it by early next week.

**Comment by ertjlane** [comment]
@michaelmenon Ah, thanks for the update. I'm sorry to hear about Saritha, hope she feels better soon! Could you transfer someone else to it? This is an error brought to us by an external collaborator who provide substantial funding, and it is in our best interest to address it as quickly as possible. This can be done at the expense of other issues.

**Comment by sarithapillai8** [comment]
@ertjlane Yesterday we have updated the speed of survey questions in staging. But we are facing a new issue. One survey with matrix question was not loading in the app and app browser, but working in desktop browsers. So we are looking into that issue now.

**Comment by divyav2020** [comment]
We have updated the following changes in Staging. Please Confirm

**Comment by ertjlane** [comment]
This appears to be resolved in staging.
