### ISSUE TITLE
mindLAMP Participants Unable to Log In Unless Accepting App Permissions

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#767]
**Describe the bug**
We have had now 3 users report being unable to log into the mindLAMP app unless they have accepted permissions for passive data. 

Android, Galaxy S21+ Android ver. 13.

Android version 13
UI version 5.1
Samsung Galaxy S20

**To Reproduce**
Log into new account created in mindLAMP on the phone, deny all data collection permissions (allow notifications).

**Screenshots**
![Screenshot_20230622_153900_mindLAMP](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/17fa3671-bca0-4489-a341-7bc9e5424bee)

![Screenshot_20230612_150129_mindLAMP (1)](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/02af3118-ef0c-458d-8f1e-97a0bc36999e)

**Comment by ZCOEngineer** [comment]
@ertjlane We shall check this

**Comment by ZCOEngineer** [comment]
We got this issue reproduced here, we shall fix this as soon as possible.

**Comment by sijitg** [comment]
We fixed the issue and pushed source code.  Staging pointed build is in review in play store.

**Comment by divyav2020** [comment]
Google review is completed.

Staging pointed build is available for Open testing (Beta Buil). We have verified from our end

Please review and Confirm.








Please review

**Comment by carlan1** [comment]
Appears functional in beta
