### ISSUE TITLE
Cannot export activities - nothing downloads and "error" notice appears

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#77]
**Describe the bug**
Exporting activities result in a error screen without any file downloaded. I am using a Mac with Safari, it might well be a browser-related issue.

**Desktop (please complete the following information):**
 - Browser: Safari Version 14.0.1 (16610.2.11.51.8)

**Comment by sarithapillai8** [comment]
@avaidyam 
This does not seems to be safari issue as we are not able to reproduce. This might be related to some specific data. So please provide more details to debug.
