### ISSUE TITLE
Making Activity/Survey History Easier to Read in the Portal

### ISSUE THREAD

**Issue by lugray1** [BIDMCDigitalPsychiatry/LAMP-platform#770]
**Is your feature request related to a problem? Please describe.**
When you access survey/activity response history in the Portal, clinicians have noted that it is difficult to read the current layout. For example, if you click on a survey in the Portal, and then click on the 'Switch Views' button, it shows you the item on the survey/activity and each response with the date. However, as you scroll to the right to keep viewing their responses, you can no longer see the 'Item' column with the question text. An example of this is below

View before you slide to the right:
<img width="1298" alt="Screen Shot 2023-07-19 at 11 24 06 AM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/89207083/29f6581f-01a6-4931-bad5-4618e268be50">

View after you slide to the right:
<img width="973" alt="Screen Shot 2023-07-19 at 11 24 27 AM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/89207083/5f6929e7-fed6-4242-b9d7-3e33b6f1aecc">

**Describe the solution you'd like**
We are requesting that as you scroll to the right for the survey and activity history, the 'Item' column will stay on your screen (similar to how the 'Freeze column' would work in Excel). So, as you scroll to the right, the first column visible would always be the 'Item' column. So, the view would always look like the first image above, but with changing dates.

**Comment by ZCOEngineer** [comment]
@lugray1 we shall review this and add ETA

**Comment by divyav2020** [comment]
We have updated the fix in dashboard staging. Please confirm.
