### ISSUE TITLE
mindLAMP Notifications Not Available

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#772]
**Describe the bug**
A participant is not receiving notifications to complete the daily survey for the mindLAMP app. When the app was first downloaded, YP was receiving multiple notifications a day at random times. YP updated their phone software to try and fix this issue. Since then, the app has not produced any notifications. 
The user has allowed all permissions on the app, including the pop-up to allow notifications when initially installed. In their phone settings in mindLAMP app info - there is no toggle to allow notifications. In the section where they manage notifications for other apps, the mindLAMP app does not show up (please see screenshots below). User uninstalled and reinstalled the app, and still it does not appear in their app list. They have tried to clear the cache. This may not be an issue that is easily resolved, as it is a single user, so we can investigate if there is a readily available solution or not. 

**Screenshots**
![IMG_20230801_122658 - Sonia Birch](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/152ae8f2-cb90-4fb7-9af8-d33495706c98)
![IMG_20230801_122656 - Sonia Birch](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/4df2eb00-219a-4cc2-b593-d0f9d809a141)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold 3
 - OS: Android 13

**Comment by ZCOEngineer** [comment]
@ertjlane we shall check this

**Comment by sijitg** [comment]
We pushed code and staging build is in review

**Comment by ertjlane** [comment]
Thanks for working on this, the issue appears to be resolved in beta testing!
