### ISSUE TITLE
Spin the Wheel Task NaN Values

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#773]
It appears that sometimes the Iowa Gambling Task / Spin the wheel task produces NaN values for the amount of money remaining. Please see the attached screenshot:

<img width="978" alt="Screen Shot 2023-08-07 at 10 21 29 AM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/103652751/bf95cb9b-dc1f-4787-ac3f-d8264d02fb28">

Here are the settings associated with the game:
<img width="1025" alt="Screen Shot 2023-08-07 at 10 23 44 AM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/103652751/799d8800-c93f-43cf-89a1-c08d937456f4">

The researcher ID where the game was assigned is `arbra7fwgbzx4ba60nh8` and the activity ID is `kp9cnnkgb417ymm4r0jc`

Additionally, please add a setting to the game that allows researchers to specify the starting balance.

**Comment by evinkalengaden** [comment]
We have tested the Spin the wheel game in the dashboard staging using the customized settings as mentioned. Now its working fine .

**Comment by sarithapillai8** [comment]
@carlan1 We missed that, sorry. We can update it today.

**Comment by sarithapillai8** [comment]
>For each wheel (gain and loss wheels) the participant can gain/lose x dollars OR gain/lose 0 dollars. However there is currently no check to make sure that probability(x) + probability(0) = 1. What happens if I choose 50 and 25 for the "probability" options? Will the true probability be 50/(25+50) and 25/(25+50)?

If probablility 50 and 25 is selected now it works with probablility 50/(25+50) and 25/(25+50).  No checking for probability(x) + probability(0) = 1. Please refer the code: https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/master/Spin_Wheel/src/containers/Layout.tsx#L68

@carlan1

**Comment by sarithapillai8** [comment]
@carlan1 Balance added for game settings. Do we need top add any conditions for this parameter?

**Comment by carlan1** [comment]
Looks good in staging
