### ISSUE TITLE
No prompt to accept mindLAMP permissions.

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#775]
There is no dialog asking to turn on permissions when logging in.

Details:
- NativeCore 2023.8.28
- iOS 16.1.2
- iPhone 13.2
- Production server
- User ID U3069865020

Of note: This does not apply to HealthKit sensors. HealthKit sensors are working as expected.

**Comment by jijopulikkottil** [comment]
@carlan1 Could you provide more details about the issue.
PushNotification and Location permissions are the two which we ask when start using the application.
We will ask other permissions if needed as per the configuration of the sensor data collection.

**Comment by jijopulikkottil** [comment]
@carlan1  As we discussed in last meeting. iOS is caching the settings if you re-installed the app within a day. So app won't ask location permission again. 
If we need to reset for testing purpose, we have to reset the privacy settings to factory default.

**Comment by carlan1** [comment]
Sounds good, thank you.
