### ISSUE TITLE
Cannot create previously deleted SensorSpec or ActivitySpec

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#776]
A collaborator has attempted to delete a SensorSpec and ActivitySpec for debug purposes.

However, when attempting to re-add SensorSpecs or ActivitySpecs, they are returned with the error: 
```
{
  "error": "500.sensorspec-creation-failed"
}
```

I have noticed this is the same error that is returned when trying to create a Spec that has already been created. However, in this case, they were deleted using the SensorSpec.delete command.

**Comment by carlan1** [comment]
Would it make sense to make it such that re-adding a previously "deleted" SensorSpec will simply changed the deleted tag from false to true? @sarithapillai8

**Comment by carlan1** [comment]
Here is a summary of what we need:

If a SensorSpec.create command is called and the value of the "name" field matches a SensorSpec already existing in the database:
       if matching SensorSpec has `_deleted=True`, 
              then set `_deleted=False` 
      else:
              return an error with a description "A SensorSpec with this name already exists"

**Comment by sarithapillai8** [comment]
@carlan1 Could you please review the PR and let me know if we are good to go?

**Comment by carlan1** [comment]
I approved, I will let you merge

**Comment by sarithapillai8** [comment]
@carlan1 Upon merging this PR, the task got closed. Could you reopen if there is anything pending? Could you check the issue in staging and release the repo to production if everything looks good?

**Comment by carlan1** [comment]
Will test and close afterward

**Comment by carlan1** [comment]
This primarily functionality works, expect the error message is not what was requested "A SensorSpec with this name already exists"

Can you check this? @sarithapillai8

**Comment by ZCOEngineer** [comment]
We shall check this and update @carlan1

**Comment by sarithapillai8** [comment]
@carlan1 The format of sending error responses from other functions are like what you see now. I can update the message if you want. Please confirm.

**Comment by sarithapillai8** [comment]
@carlan1 Do we need to change it to "500.SensorSpec-already-exist" or just "SensorSpec-already-exists"?

**Comment by carlan1** [comment]
"500.SensorSpec-already-exists" is better

**Comment by sarithapillai8** [comment]
@carlan1 Updated the messages for sensor spec and activity spec.
https://github.com/BIDMCDigitalPsychiatry/LAMP-server/commit/529a1a4166f1fb88f1908246d74e30388d9a2612

**Comment by carlan1** [comment]
Looks good, you can merge and delete branch

**Comment by sarithapillai8** [comment]
Done.
