### ISSUE TITLE
Telephony duration units

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#778]
It appears that the telephony feature is reporting 'duration' in seconds. We would like it to be reported in milliseconds. 

Example: 

```
{'data': [{'sensor': 'lamp.telephony',
   'data': {'type': 'outgoing', 'duration': 6},
   'timestamp': 1696943243647}]}
```

I have checked my call logs on my device, and it reports the call I made to be 6 seconds in duration, which matches the SensorEvent.

iPhone 12, latest version of LAMP-server and LAMP-core-ios in use.

**Comment by ZCOEngineer** [comment]
@carlan1 we shall check this

**Comment by jijopulikkottil** [comment]
@carlan1 Its Done. Code has been pushed.

**Comment by ZCOEngineer** [comment]
@carlan1 we shall test iOS, and update in Android as soon as possible.

**Comment by sijitg** [comment]
Android staging build is live for open testing Version 2023.10.19

**Comment by jijopulikkottil** [comment]
Latest iOS build 2023.10.11 (414) is available on Test Flight now.

**Comment by carlan1** [comment]
Works in beta
