### ISSUE TITLE
Scheduled activities not showing up in Feed

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#78]
**Describe the bug**
Any scheduled activity does not appear in the "Feed" tab.

**Desktop (please complete the following information):**
 - Browser: Safari Version 14.0.2 (16610.3.7.1.9)

**Comment by sarithapillai8** [comment]
@avaidyam 
Please let us know if this issue still persist. Cannot reproduce after last update.

**Comment by avaidyam** [comment]
> **Collaborator**: I tried again by setting three “tips” activities [in the "AI-001" study] for this evening (22.20, 22.35, 22.50) but unfortunately when I log in as a user (by using the “impersonate” option), the feed is empty. I tried using Safari private mode (I can install other browsers if needed) but both 19 and 21 Jan Feeds are empty on my laptop. (Safari 14.0.2 (16610.3.7.1.9) & macOS Big Sur v11.1)
> 
> I checked AI-001 (patient view U7499221181) and this is what I see from my end:
> ![image](https://user-images.githubusercontent.com/1361003/106493706-7e76a780-6487-11eb-934b-374653d022cf.png)

> **Me**: This is quite an odd bug but I have one final request — could you change your system’s time zone to EST and then screenshot the page after closing/reopening the dashboard? I somehow suspect this is a date/time zone related issue as our developers are not able to reproduce it on their end either. 
> ![image](https://user-images.githubusercontent.com/1361003/106493669-71f24f00-6487-11eb-826a-545c27e5b372.png)

> **Collaborator**: Sure, done (below the screenshot, system time zone changed into EST 12:23). Do let me know if there is anything else I could do to give you details to fix this - glad to help!
> ![image](https://user-images.githubusercontent.com/1361003/106493862-b5e55400-6487-11eb-88f5-54f1b01568f2.png)

@sarithapillai8 This collaborator is located in the UK and this seems to be a timezone-based issue. Can you check to see if this bug is occurring on your after changing the timezone?

**Comment by sarithapillai8** [comment]
@avaidyam @michaelmenon 
The fix updated in PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/202
