### ISSUE TITLE
Audio Diary Upload Endless Spinning

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#780]
**Describe the bug**
Multiple users have reported that upon submitting a recorded audio diary, the app enters into an endless spinning circle. Examining the dashboard shows the diaries have not been uploaded. Participants should have access to stable wifi, as they are able to access the app and record the diary. I have submitted a request for screenshots.

**To Reproduce**
1. Go to audio diary activity
2. Click on record.
3. Select finish recording.
4. Select upload on top left.
5. Observe error.

Android 11
Android version 11

iPhone 11
ios 17.0

**Comment by ZCOEngineer** [comment]
@ertjlane we shall check this and comment

**Comment by ZCOEngineer** [comment]
@ertjlane could you check if this issue still occurs?, we would like to know if this is reproducible in staging.

**Comment by michaelmenon** [comment]
Also @ertjlane could you please let us know the time duration of the audio library you were trying to uplaod.

**Comment by ertjlane** [comment]
The issue has persisted per the reports of those who have forwarded it to me. I don't imagine duration should be a factor, as the audio diary should automatically stop recording upon reaching the 4 minute mark. I understand it may be difficult to replicate, and we're working with limited information so thank you. Even if we learn that it is a product of the phone settings being misconfigured rather than a code error that is useful.

**Comment by ZCOEngineer** [comment]
We shall check this right after #774.

**Comment by evinkalengaden** [comment]
Hi @ertjlane We found that, an audio diary having 4 minutes is taking more than one minute to upload. Please let us know your comments.

Thanks,
Evin K Alengaden

**Comment by ertjlane** [comment]
Hello @evinkalengaden - thanks for looking into this. Upon further discussion there isn't any need to have audio diaries as large as 4 minutes, perhaps we can simply reduce the capacity to 2?

Erlend

**Comment by evinkalengaden** [comment]
Hi @ertjlane Now we have reduced the capacity to 2min (Max) and also we have updated in the dashboard staging. Let us know.

Thanks,
Evin K Alengaden

**Comment by ertjlane** [comment]
It seems to be working in staging! Thank you for this!
