### ISSUE TITLE
Uncaught Exception (Foreground Service Did Not Start in Time)

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#781]
**Describe the bug**
Participant experienced an error page mid way through the survey. Was unable to go back to previous questions either. Needed to close and restart the app to be able to escape from the error page. Once restarted, the survey for that day will also be restarted (responses to completed questions lost). This has continued multiple times over the course of several weeks.

**Screenshots**
![received_7068705169823845 - Amirah Iskandar](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/84377259-0b78-4c31-bb08-664d552ab9fe)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10 Lite
 - Version: Android version 13

**Comment by ZCOEngineer** [comment]
@ertjlane We shall check this.

**Comment by sijitg** [comment]
We couldn't reproduce this issue here, but it may be because of restrictions in starting "Service" in new OS devices. 
We can change our implementation using "WorkManager".

**Comment by sijitg** [comment]
@carlan1 We are seeing issues in _Service_ when app is kept in background for several hours.  We assume this is because of battery optimization. As  a work around can we make following change in app?
 When app is opened, if there battery optimization enabled, we plan to display a prompt to disable it and navigate the user to settings for the same. Please confirm whether we can proceed. ?

**Comment by sijitg** [comment]
@carlan1 As per yesterday's discussion we will implement it and update staging build.

**Comment by sijitg** [comment]
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63729405/5c5d8fe4-9a4a-4e3e-9e38-65e33473e959)
Please review the message displayed followed by the system popup to disable optimization.

**Comment by sijitg** [comment]
@carlan1 This update is live for testing (Staging)
