### ISSUE TITLE
Changes to Spin the Wheel

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#782]
We would like some changes made to the Spin the Wheel task:

1. Please reset the user balance every time they begin a new session. (i.e. if they close the app and return to the session, maintain the game state as usual. However, when they complete the session and start a new session, they should start with the researcher-defined starting balance restored.)
2. Please change the buttons so that they are NOT colored and instead are identified by a number (1-4). In the current implementation, it is confusing because the colors of the buttons don't correspond to the colors of the wheel. We would like to fix this problem by removing colors from the buttons.

**Comment by ZCOEngineer** [comment]
Sure @carlan1, we shall review this.

**Comment by sarithapillai8** [comment]
@carlan1 This seems to be a change. So I just changed the label to feature.

**Comment by evinkalengaden** [comment]
@carlan1 We have tested the new changes, And updated in the dashboard staging.

**Comment by carlan1** [comment]
Looks good. Thank you.
