### ISSUE TITLE
Re-enable mindLAMP Chat Feature

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#783]
As was implemented in the past, we would like to have a chat function to enable back-and-forth messaging between clinicians/researchers and participants.

The appearance should mimic that which was previously designed, as is shown in the documentation: https://docs.lamp.digital/start_here/care_team

There should be a new button on the participant's UI on the top right corner, as shown in the images. This will open a "conversations" page. All the active conversations will be shown.

However, unlike what is shown in the link above, there should be only one "conversation": between the participant and the researcher/clinician/admin. When opening this new "Conversations" page, the participant can see their message history with the clinician/researcher.

On the researcher's view in the dashboard interface, there should be a new tab which can be selected on the left side of the page (similar to sensors, activities, etc... please name this new tab "Conversations"). After clicking on this new tab, it will open a new "conversations" page. From this new tab, the researcher can see the list of participant's. The researcher can select a conversation with a participant to send a message and see message history.

**If there is any way to modify the above instructions to match already-existing code, and making these modifications will speed up the process, please comment about it here.**

**Comment by ZCOEngineer** [comment]
We need to analyze what existed previously, shall study that, and update here on what needs to be done to enable this feature.

**Comment by sarithapillai8** [comment]
Hi,
Please see below the current working pattern of conversations. We don't have an option to see the history of messages now. Do we need conversations tab in admin section? Currently, the messages from participants can be seen inside the participant settings as shown in an image.

![Conversation-1](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/79134a54-b72f-4716-997d-6c49cbf02c93)
![Conversation-2](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/e62bc3e2-00d4-4240-a519-602ed8c7f53f)
![Conversation-3](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/75173c1c-85c1-468c-ba5f-3fd67426216b)
![Conversation-4](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/8c2808df-2123-4bd1-a574-c57544defa3a)
![Conversation-5](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/2f7a135f-00a8-4100-b908-0f629001e6a4)
![Conversation-6](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/84ce6ffe-6527-4615-bb32-e1f8e968ac0b)
![Conversation-7](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/a2163656-7198-4f7b-8823-10fb859c7c9a)
![Conversation-8](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/cef3bc74-7cb1-4753-a17b-2659b7fc85b0)
![Conversation-9](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/3030bf45-e7d2-45c8-8cc3-d48624ecdec1)
![Conversation-10](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/3e0fc104-17f2-4916-adfd-1b46fb3bc6d2)
![Conversation-11](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/9e534646-bb0c-48ed-bc38-9410eadbae7c)

**Comment by carlan1** [comment]
> We don't have an option to see the history of messages now

What do you mean by this?

Also, no need to add new tab for now, if you can access messages through the activities section

**Comment by sarithapillai8** [comment]
@carlan1 Conversations can be accessed through the user settings page, not from the activities page as I have shown in the first screenshot above. We can update the functionality to include history.
Thank you.

**Comment by carlan1** [comment]
Sorry. Yes, I meant user settings page. Please keep it as it is currently. 

However, using the production dashboard on web application, I am able to message from both the user-side and the researcher-side. However, I am unable to open the chat feature from the user-side using the mobile app. Could you re-enable access from the participant side, using mobile?

**Comment by carlan1** [comment]
Current implementation is participant and researcher can only see unread messages. Once they are read, they are not visible.

**Comment by sarithapillai8** [comment]
@carlan1
> Can you confirm that in the current implementation, it is not possible to see unread messages? 
Sorry, this was my mistake. 
I have enabled the messages button from the mobile view. Could you please check and let me know?

**Comment by carlan1** [comment]
Looks good. Thank you

**Comment by carlan1** [comment]
Is it possible to add dialog that says "This chat is not monitored and should not be used for urgent matters." At the bottom of the dialog, there should be two options that say "Okay" (proceed) and "Take me back" (return to previous page). This should be from the user's end only

**Comment by sarithapillai8** [comment]
@carlan1 Yes we can add that.

**Comment by sarithapillai8** [comment]
@carlan1 Updated in dashboard staging. Please review.

**Comment by carlan1** [comment]
Works in staging.
