### ISSUE TITLE
LAMP server silently fails

### ISSUE THREAD

**Issue by baylisscg** [BIDMCDigitalPsychiatry/LAMP-platform#785]
**Describe the bug**
The Encrypt and Decrypt functions swallow any errors that occur. See [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blame/e7e418b2b7bfbbf8abb293ac6f3b4283f66c5176/src/repository/Bootstrap.ts#L101) and [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/blame/e7e418b2b7bfbbf8abb293ac6f3b4283f66c5176/src/repository/Bootstrap.ts#L122)

**To Reproduce**

Self evident from code but for giggles start up a instance of LAMP server with a ROOT_KEY generated from `openssl rand -base64 32` it'll start normally but you won't be able to log in with the auto-created admin credential.

**Expected behaviour**

Any config issues that would prevent proper functioning should be flagged to the user at startup. Any runtime issues should be accurately reflected back to the user. e.g. the login code not returning a 403 when it should be some flavour of 500.

**Comment by carlan1** [comment]
Nice catch. We've added error messages for this occurrence.
