### ISSUE TITLE
Upgrade push notifications to Firebase HTTP v1 API

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#791]
[See documentation here.](https://firebase.google.com/docs/cloud-messaging/migrate-v1) [We are currently using the now-deprecated API in `LAMP-app-gateway`](https://github.com/BIDMCDigitalPsychiatry/LAMP-app-gateway/blob/e0137e1aaf81549455b302bd7dab9db4db824b17/app.js#L93C1-L93C1), but this should be a very quick fix with minor changes only.

**Comment by ZCOEngineer** [comment]
We shall work on this and update.

**Comment by sarithapillai8** [comment]
@avaidyam Could you provide the project ID for updating the API?

**Comment by carlan1** [comment]
firebase project ID

**Comment by carlan1** [comment]
api-6882780734960683553-445906 @michaelmenon

**Comment by avaidyam** [comment]
@sarithapillai8 The only changes to be made are in the [`LAMP-worker` repository](https://github.com/BIDMCDigitalPsychiatry/LAMP-worker). You shouldn’t need to modify the Firebase project directly. 

It looks like there are 2 open PRs from @Linoy339 still. @sarithapillai8 Can you confirm those need to be merged? If so, @carlan1 could you merge them and re-deploy the `LAMP-worker` (though it should be automatic)?

**Comment by sarithapillai8** [comment]
@carlan1 @avaidyam The changes done by @Linoy339 are related with language translations. Please merge.
@avaidyam We just need to use the project id to migrate to Firebase HTTP v1 API.

**Comment by ZCOEngineer** [comment]
We shall complete this right after vulnerability and dependency updates are complete.

**Comment by sarithapillai8** [comment]
As dependency updates are marked as 'priority low', we can start working on this and update it by early next week.

**Comment by carlan1** [comment]
> @carlan1 @avaidyam The changes done by @Linoy339 are related with language translations. Please merge. @avaidyam We just need to use the project id to migrate to Firebase HTTP v1 API.

I merged one of the PRs, can you check the conflicts for the other PR? @Linoy339

**Comment by sarithapillai8** [comment]
@carlan1 Resolved conflicts. You can merge now.

**Comment by sarithapillai8** [comment]
Upgradation completed and staging is updated. We have tested and confirmed using the Android staging build.

**Comment by carlan1** [comment]
Is there a beta build available for testing?

**Comment by sarithapillai8** [comment]
@carlan1 You can test it with a staging account. As this is a server-side update, you can access it with any build using user registered to api-staging.lamp.digital.

**Comment by carlan1** [comment]
Works for android account using api-staging
