### ISSUE TITLE
Remove Simple Mode From Dashboard

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#792]
**Is your feature request related to a problem? Please describe.**
The dashboard currently has a functionality allowing one to toggle in between 'simple mode' and 'advanced mode', as shown in the  screenshot below. However, the lack of functionality built into simple mode has led to confusion among certain users, underutilizing or misusing the features of the app. Given that simple mode was initially input into the user interface for circumstances that no longer apply, it would be simpler to default to advanced mode, and remove the option of a more restricted user interface.

<img width="1087" alt="Screen Shot 2023-12-11 at 3 39 48 PM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/19b18737-f9b9-4210-ac33-8291ea81d869">

**Comment by ZCOEngineer** [comment]
# Discussion and Confirmation: Removal of Simple Mode Feature
Hi @ertjlane, this feature was implemented after lot of discussions with @avaidyam, could you check with him and confirm the removal of Simple Mode?

**Comment by avaidyam** [comment]
Please default to advanced mode and hide the toggle for now.

**Comment by sarithapillai8** [comment]
@avaidyam @ertjlane Do we need to hide the button for toggling?

**Comment by carlan1** [comment]
Looks good. Works in staging, has been moved to production.
