### ISSUE TITLE
Symbol Digit Substitution Not Loading Across Users

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#796]
**Describe the bug**
Upon attempting to open the symbol-digit cognition task on the production dashboard in both the web based and app version of the platform the task spins in an endlessly buffering circle. The task functioned perfectly on the staging dashboard prior to the most recent dashboard release, so in theory this should be operating fine. 

**To Reproduce**
In a user, create a symbol-digit task as an activity. Go to open the task.

**Comment by ZCOEngineer** [comment]
We shall check @ertjlane

**Comment by sarithapillai8** [comment]
@ertjlane LAML-Activitiesd repo is not released . Please update the production and check.
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/c9d39bcd-cbb4-495c-8c65-6ecf800f722d)
