### ISSUE TITLE
Increase Number of Possible Rounds for Balloon Risk

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#797]
**Is your feature request related to a problem? Please describe.**
In the Balloon Risk activity, the user can only collect points 5 times (without popping the balloon) before the game ends. Could the number of collections be increased to 10, and the numeric representation at the bottom of the balloon increase with each new 'level' as it currently does.

**Comment by ZCOEngineer** [comment]
We shall check this @ertjlane

**Comment by sarithapillai8** [comment]
@ertjlane There is an activity setting to customize the balloon count. Can you please check and let us know if you are referring to something else?
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/b775e8ff-40bd-4e71-9947-574d3dc6c92a)

**Comment by carlan1** [comment]
Works as described
