### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#798]
We need to update all the dependencies/vulnerabilities as listed by dependabot in the following repositories:
LAMP-dashboard
LAMP-server
LAMP-activities

**Comment by sarithapillai8** [comment]
We have updated LAMP-dashboard repo. We are currently working on LAMP-Server repo. 
LAMP-activities repo contains around 21 applications, so it will take time to update each activity application.

**Comment by sarithapillai8** [comment]
@carlan1 
All the activities under the repo LAMP-activities are updated with vulnerability fixes.  We are proceeding with our testing. Please review from your side also.
You can check the vulnerability status here - https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/actions/runs/8017452698/job/21901348219
Please expand 'Run ./build.sh' section to see the details. 
We will be updating LAMP-server soon.

**Comment by sarithapillai8** [comment]
@carlan1 LAMP-server vulnerabilities are fixed. But we need to test staging to check for any issues. We can complete that in next week.

**Comment by sarithapillai8** [comment]
@carlan1 We have notification issues after LAMP-server vulnerability updates in staging. Do we have any option to get logs related to the issue?

**Comment by sarithapillai8** [comment]
We have fixed the notification issues. Changes are there in both LAMP-server and LAMP-worker and those are updated in staging.

**Comment by carlan1** [comment]
affected repositories:

LAMP-dashboard
LAMP-server
LAMP-activities
LAMP-worker
