### ISSUE TITLE
Survey Responses Not Reflective of Editor

### ISSUE THREAD

**Issue by kxllychxn** [BIDMCDigitalPsychiatry/LAMP-platform#799]
**Describe the bug**
The survey response options in the user view do not match the survey response options in the editor view for this survey called "Daily Check-In". This survey is displaying the same issue in multiple investigator accounts, each user in the test account is seeing the same wrong survey response option. 

**To Reproduce**
1. Go to https://dashboard.lamp.digital/
2. Click on LEAP Project (Mclean)
3. Scroll down to "Daily Check-In" on the activities also see "Daily Check - In" under Assess Tab
4. See error: The response options in the activity editor doesn't match that of the activity in the Assess Tab

**Expected behavior**
The response options in the activity editor should match that of the activity in the Assess Tab
The question should be: How do you feel today?
The response options should be:
Very Good
Good
Neutral 
Somewhat bad
Very Bad

**Screenshots**
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/141162100/cec3a277-775a-4cb9-8b01-6d765d4c0236)
![Screenshot 2024-01-10 112910](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/141162100/771b0b01-0bfb-4ce9-8cd1-bb556375c6bd)
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/141162100/d6615190-eca4-4879-9d3c-1e7737204407)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: Chrome
 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 

**Additional context**

**Comment by carlan1** [comment]
The customizations are under "warnings" not "response options" it works as intended
