### ISSUE TITLE
Patient Profile UI

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#8]
Please check the Figma diagram that was updated by Tim and ask any questions regarding the **Patient Profile** page or how to implement it so we can nail down an ETA for it.

**Comment by sarithapillai8** [comment]
@avaidyam 
Could you please specify what all screens come under this? Do we need to consider all the new screens including both  the researcher and patient top blue bar changes?

**Comment by avaidyam** [comment]
No, this item is specifically the Patient Profile page as mocked up in Figma (it's only one mockup screen) -- let me know if you had any questions about it that I need to relay to Tim as we discussed this with Tim a few weeks ago.

**Comment by sarithapillai8** [comment]
@avaidyam 
The following screens in Figma are titled with patient profile. 
https://www.figma.com/file/P3tLm5qD7TrdOwe4LJdVYC/LAMP?node-id=2768%3A421
https://www.figma.com/file/P3tLm5qD7TrdOwe4LJdVYC/LAMP?node-id=3865%3A0
https://www.figma.com/file/P3tLm5qD7TrdOwe4LJdVYC/LAMP?node-id=3839%3A404
https://www.figma.com/file/P3tLm5qD7TrdOwe4LJdVYC/LAMP?node-id=3839%3A155
And there is a general design change like blue bar on the top. So all these changes to be considered, right?

**Comment by avaidyam** [comment]
@sarithapillai8 Yes, that’s right - it’s one entire page, and then on top of that the blue border. I’ll make the blue border item its own issue so that can be developed separately from the Patient Profile UI.

**Comment by sarithapillai8** [comment]
@avaidyam 
1) Which button click will open this profile page? The row click opens the participant home page.
2) Where the care team will be shown on dashboard?
3) Do we need to add a study drop down in the profile page? 
4) Will the activities/sensors add/edit/delete be participant based? If so, how can we manage the study based listing?

**Comment by avaidyam** [comment]
@sarithapillai8 It seems like Tim's mockup for this was incomplete so we may need to make a few minor modifications:

> Which button click will open this profile page? The row click opens the participant home page.

Before: <img width="989" alt="before" src="https://user-images.githubusercontent.com/1361003/101494283-1e56ff80-3935-11eb-8ffa-d7705cb6a217.png"> After: <img width="989" alt="after" src="https://user-images.githubusercontent.com/1361003/101494280-1dbe6900-3935-11eb-95cb-71688377597e.png">

> Where the care team will be shown on dashboard?

Right now the care team may need to be on the right-hand-side of the Patient Profile UI. 

> Do we need to add a study drop down in the profile page?

No need for a drop-down here. Just show the Study name as a bubble, without edit ability.

> Will the activities/sensors add/edit/delete be participant based? If so, how can we manage the study based listing?

Any changes to the activities/sensors will be study-wide (so you should keep track of the participant's parent study ID), so let's do this: 
1. If the parent study of the participant has ONLY ONE participant (that is, the one we are looking at right now), then editing the activities/sensors will work fine.
1. If the parent study of the participant has MULTIPLE participants, when editing/saving, show a confirmation dialog: "You are about the make this change for all participants in this study. [Cancel] [Continue]".

**Comment by sarithapillai8** [comment]
@avaidyam 
So we need to add a settings icon, which can pen the profile page.

I don't understand what do you mean with care team. Care team is shown as table like structure now. I am asking about showing the data in participant dashboard. Do we have any option to see the care team values? Why we need it on right side? can we show like one by one as in the design just before the activities?

Other points are clear to me. Thanks.

**Comment by avaidyam** [comment]
@sarithapillai8 
> So we need to add a settings icon, which can pen the profile page.

Yes, exactly. 

> I am asking about showing the data in participant dashboard. Do we have any option to see the care team values? Why we need it on right side? can we show like one by one as in the design just before the activities?

I see now -- the care team is not visible in the patient dashboard. We can rethink that as a different issue later, but for now it should be part of the Patient Profile UI for clinicians only.

**Comment by sarithapillai8** [comment]
@avaidyam 
Which API to be used for CareTeam add/edit/delete operations?
Can I use similar workflow of Activities for Sensors for add/edit/delete operations?

The patient list row click now leading to patient home screen. Instead of that we need to add an icon as we need profile icon in the row. Can I change like in the screen?
![patients](https://user-images.githubusercontent.com/63710347/101753315-7db13d00-3af8-11eb-8410-0c4ee956326c.PNG)

**Comment by avaidyam** [comment]
1. [Please see this component (that was deleted a long time ago) for the implementation information.](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/0bf310b10177aef564c1b1503fa4d237871b704d/src/components/CareTeam.tsx)
1. Yes. 
1. That's fine but what is the other icon in the row, and why is there so much white-space? Please adjust that!

**Comment by sarithapillai8** [comment]
@avaidyam 
The other icon included for impersonating option as the participant. You can suggest an icon if it is not fine. We can do the design fix.

**Comment by avaidyam** [comment]
@sarithapillai8 Isn't clicking on the row going to do the same thing? So I think we should remove the additional icon in that case.

**Comment by sarithapillai8** [comment]
@avaidyam yes the row click do the same. So the profile icon click cannot be triggered as it causing the row click. So we need some additional icon or some other way. Please suggest.

**Comment by avaidyam** [comment]
@sarithapillai8 Having already implemented a working version of this in the much older version of the dashboard, this is definitely possible to implement without two buttons. Please look into it - or check older commits?

**Comment by avaidyam** [comment]
@sarithapillai8 Perhaps to speed things along and keep it simple, use the `arrow_forward` Material icon for the "impersonate"/"enter patient view" button, and `settings` Material icon for the "configure" view.  i.e. 
```jsx
<IconButton onClick={() => { /* ... handler here ... */ }}><Icon fontSize="large">arrow_forward</Icon></IconButton>
```
Then, let's: 
1. Remove the dropdown/disclosure button and conversations panel at the left side of the row (as the conversations are accessible from inside the Profile page).
1. Remove the ability to click on the row itself (this functionality is instead in the arrow button as explained above).

**Comment by sarithapillai8** [comment]
@avaidyam 
Which all sensor spec should be available for creating sensors similar to the filter for activities ?

**Comment by avaidyam** [comment]
You are able to find a list of all SensorSpecs using the "LAMP.SensorSpec.all()" method call (or if making a REST API call, the URL is https://api.lamp.digital/sensor_spec instead). Please dynamically fetch this list from the server. I've also attached the expected JSON output below **for testing purposes only:**

```json
{
  "data": [
    {
      "id": "lamp.accelerometer",
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        },
        "accuracy": {
          "type": "number"
        }
      }
    },
    {
      "id": "lamp.accelerometer.motion",
      "type": "object",
      "properties": {
        "tilt": {
          "type": "object",
          "properties": {
            "roll": {
              "type": "number"
            },
            "pitch": {
              "type": "number"
            },
            "yaw": {
              "type": "number"
            }
          }
        },
        "rotation": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "z": {
              "type": "number"
            }
          }
        },
        "gravity": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "z": {
              "type": "number"
            }
          }
        },
        "user_accel": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "z": {
              "type": "number"
            }
          }
        },
        "magnetic_field": {
          "type": "object",
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            },
            "z": {
              "type": "number"
            },
            "calibration_accuracy": {
              "type": "number"
            }
          }
        }
      }
    },
    {
      "id": "lamp.analytics",
      "type": "object",
      "properties": {
        "event_name": {
          "type": "string"
        },
        "event_payload": {
          "type": "object",
          "additionalProperties": true
        }
      }
    },
    {
      "id": "lamp.blood_pressure",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.bluetooth",
      "type": "object",
      "properties": {
        "device__id": {
          "type": "string"
        },
        "frequency": {
          "type": "number"
        },
        "rssi": {
          "type": "number"
        }
      }
    },
    {
      "id": "lamp.calls",
      "type": "object",
      "properties": {
        "phone_number": {
          "type": "string"
        },
        "duration": {
          "type": "number"
        },
        "call_type": {
          "type": "string",
          "enum": [
            "incoming",
            "outgoing",
            "missed",
            "busy"
          ]
        }
      }
    },
    {
      "id": "lamp.device_state",
      "type": "object",
      "properties": {
        "battery_level": {
          "type": "number"
        },
        "event_type": {
          "type": "string",
          "enum": [
            "locked",
            "unlocked",
            "plugged",
            "unplugged",
            "screen_on",
            "screen_off"
          ]
        }
      }
    },
    {
      "id": "lamp.distance",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.flights",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.gps",
      "type": "object",
      "description": "The location sensor records the device's current GPS coordinates. Depending on the device operating system and device battery level, the source of the data from this sensor may alternate between GPS antennae (high accuracy), cellular tower triangulation (moderate accuracy), WiFi triangulation (poor accuracy), or a combination of these.",
      "properties": {
        "latitude": {
          "type": "number",
          "description": "The coordinate's latitude in degrees."
        },
        "longitude": {
          "type": "number",
          "description": "The coordinate's longitude in degrees."
        },
        "altitude": {
          "type": "number",
          "description": "The coordinate's altitude in meters, relative to sea level. A value of zero implies that the altitude of the coordinate could not be determined."
        },
        "accuracy": {
          "type": "number",
          "description": "The coordinate's estimated accuracy representing the radius of a circle formed around the reported latitude/longitude pair, for which there is AT LEAST a 68% probability that the true coordinate is contained within (the 'Circular Error Probable'). A value of zero implies that the accuracy of the coordinate could not be determined."
        },
        "bearing": {
          "type": "number",
          "description": "(Currently unsupported.) The bearing is the horizontal direction of travel, in degrees, estimated by the GPS satellites to the device when requesting coordinates, thus this value is different than if calculated from accelerometer and magnetic field measurements."
        },
        "speed": {
          "type": "number",
          "description": "(Currently unsupported.) The current estimated speed of travel over ground, in meters/second."
        }
      },
      "required": [
        "latitude",
        "longitude",
        "altitude",
        "accuracy"
      ],
      "additionalProperties": false
    },
    {
      "id": "lamp.gps.contextual",
      "type": "object",
      "properties": {
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "accuracy": {
          "type": "number"
        },
        "social_context": {
          "type": "string",
          "enum": [
            "home",
            "school",
            "work",
            "hospital",
            "outs_ide",
            "transit"
          ]
        },
        "location_context": {
          "type": "string",
          "enum": [
            "alone",
            "friends",
            "family",
            "crowd"
          ]
        }
      }
    },
    {
      "id": "lamp.gyroscope",
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    },
    {
      "id": "lamp.heart_rate",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.height",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.magnetometer",
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    },
    {
      "id": "lamp.respiratory_rate",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.segment",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.sleep",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.sms",
      "type": "object",
      "properties": {
        "phone_number": {
          "type": "string"
        },
        "length": {
          "type": "integer",
          "format": "int64"
        },
        "sms_type": {
          "type": "string",
          "enum": [
            "sent",
            "received"
          ]
        }
      }
    },
    {
      "id": "lamp.steps",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.weight",
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "units": {
          "type": "string"
        }
      }
    },
    {
      "id": "lamp.wifi",
      "type": "object",
      "properties": {
        "device__id": {
          "type": "string"
        },
        "frequency": {
          "type": "number"
        },
        "rssi": {
          "type": "number"
        }
      }
    }
  ]
}
```

**Comment by sarithapillai8** [comment]
@avaidyam 
I tried using the code below : 
LAMP.Sensor.create(studyId, {
    name:sensorName, spec:sensorSpec
  })
This is creating activity not the sensors. Could you please help me on this?

**Comment by avaidyam** [comment]
@sarithapillai8 [I've fixed the issue in `LAMP-server` with this commit.](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/commit/904afcf8de0c2a43181a17fc624ffd75fa6841b1) This change will not be in production this week, so for now please implement it correctly on your end but do not test it yet.

**Comment by sarithapillai8** [comment]
@avaidyam 
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/0bf310b10177aef564c1b1503fa4d237871b704d/src/components/CareTeam.tsx
I am using this file as reference for credentials section. But I am not clear about listing the care team. Do we need to list the credentials listed in dialog with credentials manager? With the code in the commit, the list contains only one with the default "me" one.

**Comment by avaidyam** [comment]
@sarithapillai8 The list you are seeing is correct — the old code merged the idea of the Care Team with the credential management and was very confusing. We do not want that old behavior, so you are on the right track already. 👍

**Comment by sarithapillai8** [comment]
@avaidyam 
I don't understand that. 
Adding a credential will create a care team account? Can we use same the credential manager dialogue for add/edit option?

**Comment by avaidyam** [comment]
@sarithapillai8 I realize now your confusion, so let me add an explanation of all of the above: 

1. The `Credential` API is for managing login/access through email/password combinations. Credentials are NOT Resource types in the LAMP API, and thus cannot have Tags or other Credentials attached to them. (If you recall, Resource types in the API allow for both Credentials and Tags to be applied: only `Researcher, Study, Participant, Activity, Sensor`.)
2. The `lamp.dashboard.credential_roles` Tag is specifically configured to allow patients to add care team members like their trusted peers or family members. (i.e. Permissions are read/write by the clinician and the patient.)
3. The `lamp.dashboard.credential_roles.external` Tag is the exact same and follows the same data structure as the above, except it is read/write by the clinician and read-only for the patient. This is used to prevent patients from being able to change or remove care team members, and the clinician half of the care team would be physicians, psychiatrists, pharmacists, nurses, social workers, etc. 

Previously (1) and (2)/(3) were tied together to simplify the flow. By adding a person to a clinician account, it becomes implicit that they are part of the care team for all patients in that clinician account. By adding a person to a patient account, it is the same from the patients' perspective. 
* It should NEVER be the case that a person is registered in either Tags (2) or (3) but does not have a Credential (1). 
* If a Credential (1) does not have a matching entry in the Tags (2) or (3) then it is not a person. (i.e. This is a "service account" Credential, used for API access or something similar, not operated by an actual person.)

**Comment by sarithapillai8** [comment]
@avaidyam 
Thanks for the detailed explanation. 
So the reset password link should open the credentials manager dialog specifically with reset password option?

**Comment by sarithapillai8** [comment]
@avaidyam 
 let ext = ((await LAMP.Type.getAttachment(id, `${prefix}.external`)) as any).data
let int = ((await LAMP.Type.getAttachment(id, `${prefix}`)) as any).data
These are the data listed in care-team. I have updated code like on update check which api call should be made and updating corresponding. But it is causing duplicated in care team. Could you please review the code pushed in milestone-1 branch? Code has been pushed, but this functionality could not be implemented as expected.

https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/milestone-1/src/components/CredentialManager.tsx
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/milestone-1/src/components/PatientProfile.tsx

**Comment by avaidyam** [comment]
This item appears to be completed already so I'm closing this issue for now.
