### ISSUE TITLE
TypeError for Dashboard Activity Schedules

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#800]
**Describe the bug**
When selecting 'add' for an activity notification schedule, the page defaults to a TypeError. This occurs across multiple admin logins and multiple investigator accounts, on the web dashboard via chrome browser. 

**To Reproduce**
1. Go to a mindLAMP investigator account. 
2. Go to activities.
3. Click on the calendar icon for an activity (the notification schedule).
4. Click 'add' 
5. Observe error. 

**Screenshots**
<img width="1131" alt="Screen Shot 2024-01-16 at 2 18 21 PM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/d20f51f1-b300-43bd-b84b-06e593d08a40">

![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/47f3dc99-2c82-4a78-9573-502191c8f50b)

**Comment by ZCOEngineer** [comment]
@ertjlane we shall check this

**Comment by sarithapillai8** [comment]
@ertjlane Updated the fix in staging.

**Comment by ertjlane** [comment]
@sarithapillai8 thanks for the prompt response, this appears to be fixed in staging.
