### ISSUE TITLE
Total Level Display for Cognitive Games

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#802]
We would like cognitive games with levels to display level progression during gameplay, illustrating to the player which level they are on out of the total possible levels. This is specifically for the following games:
- Jewels A
- Jewels B
- Spatial Span
- Maze Game 
An example of what this might look like for Jewels B has been attached below. This applies for games that have a timed feature, so long as they have levels, ex: spatial span.
<img width="1410" alt="Screen Shot 2024-02-12 at 12 48 07 PM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/461ea434-2817-405f-8db8-57427fb688f8">

**Comment by ZCOEngineer** [comment]
We shall check this @ertjlane

**Comment by sarithapillai8** [comment]
@ertjlane Jewels game doesn't have total levels in the game settings? The maze game currently has no settings for total levels, instead we are using 12 as a static value. Do we need to add the total number of levels or just use this value?

**Comment by carlan1** [comment]
The hardcoded value of 12 is fine here, as it is for other games. If it is a value customized in the settings, then just use that.

**Comment by evinkalengaden** [comment]
Hi @carlan1 
 
   We have updated the changes to dashboard staging.

**Comment by ertjlane** [comment]
Thanks so much. These look great, I've just tested them out. 
- Jewels A: I noticed when testing that it does not change to level 2 until after completing 2 levels (I.e. after completing the first round it stays at level 1). 
- Jewels B: Appears to work great.
- I noticed on spatial span that when answers are answered incorrectly, after clicking 'next', it does not actually adjust a level up. However, the game does not extend the number of levels, it still ends at level 6, it simply does not show that the levels are progressing. 
- Maze game appears to work perfectly.
If you could adjust the Jewels A, and the Spatial Span issue I noted I think we will be in great shape. Thank you!

**Comment by sarithapillai8** [comment]
@ertjlane We have updated spatial span. 
For Jewels A, there is some calculation for bonus points. Based on that we are updating levels. So according to current logic, the level change is working fine now. The same logic is for Jewels B.

**Comment by sarithapillai8** [comment]
The logic of spatial span is like it exits after 2 failed attempts. 

The level update for jewels is different, you can go through the logic if you want. The level change depends on the time taken for the last bonus points.
https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/master/JewelsPro/src/components/jewels/Jewels.tsx#L213

**Comment by ertjlane** [comment]
Reviewing Jewels A, I think the parameters for the level change are confusing because even when not meeting parameters to move to the next level, the app provides a prompt after all jewels are selected asking 'do you wish to continue to the next level'. If we make this contigant on the user actually moving to the next level, I think it would be much more clear.

**Comment by sarithapillai8** [comment]
@ertjlane So the actual issue lies in the prompt I think. The calculations are there from the beginning stage. Can we change the prompt text to something meaningful?

**Comment by sarithapillai8** [comment]
@ertjlane The parameters used for level calculation include the time taken for completion, number of attempts, negative points, and bonus point settings (bonus points required for the next level).

**Comment by ertjlane** [comment]
@sarithapillai8 Thank you. I wonder if we could change the text prompt when they fail to move to the next level into something indicating what they need to do differently - if it is hard to be specific it can just be something Like 'Good work! See if you can tap the jewels a little faster, or a little more carefully to move on to the next level'.

**Comment by sarithapillai8** [comment]
@ertjlane With our calculation, I observed that the user could go to the next level after completing one level 2 times. Do you think this text is appropriate if that is the case?

**Comment by sarithapillai8** [comment]
@ertjlane Different values can be given to game settings which can help to update the level in one go. But it depends on the values. So we cannot make sure this text suits there for the popup. If you can suggest another text or can we try one?
We can update the levels as mentioned.

**Comment by ertjlane** [comment]
@sarithapillai8 I don't follow your point, I'm not understanding very well what you mean by 'different values given to game settings', and how that pertains to the text included. Is that the same as or different from changing the levels such that one only needs to progress one level to get to level 2?

**Comment by sarithapillai8** [comment]
@ertjlane If you set the 'Bonus level for next level' parameter for Jewel A game settings within the range of 1-34, the game will advance to the next level immediately. For Jewel B, you can try values between 1 and 37. This parameter controls the level advancement, with a default value of 50. 
The message you suggested implies that clicking the jewels quickly and carefully will automatically advance to the next level. However, level advancement actually depends on this value. That's why I said it's not appropriate in this case. Does this make sense now?

**Comment by sarithapillai8** [comment]
`const totalBonusCollected =  stepNumber === totalDiamonds ? duration - Math.abs(negativePoints) : 0;`
This is how bonus point is calculated for the current level

`const level =  Math.floor((bonusPoints + totalBonusCollected) / bonusPointForNextLevel);` 
This is the level value calculation

bonusPoints - already collected bonus points in previous levels ,  initially 0
bonusPointForNextLevel - This value is from game settings
duration - Time duration of the level

So all this depends on these calculations.

**Comment by ertjlane** [comment]
Hello Saritha, yes that is helpful. I think with this in mind then we are good to go on this issue. I will make a dashboard release for this, the picture pop up and the translations.

**Comment by sarithapillai8** [comment]
@ertjlane All the changes have been made in LAMP-activities. You can create the release now. Previous issues with the release process have been resolved, and we hope we won't encounter any more issues.
