### ISSUE TITLE
Integrate Images into Popup for Certain Activities

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#804]
We would like to attach images as part of a popup to particular activities, specifically several of the cognitive assessments. For each of the following games 
- Spin the Wheel
- Symbol Digit Substitution
- Jewels A & B
- Maze Game
- Spatial Span 

What we would like is that in addition to the streak pop up, there be an additional pop up, containing the corresponding image. Let me know your thoughts on how viable this is to integrate into the user interface for each of these activities. I've attached the images here.

[mindlamp-cognition.pptx](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/14666629/mindlamp-cognition.pptx)

**Comment by ZCOEngineer** [comment]
We shall check this @ertjlane

**Comment by sarithapillai8** [comment]
@ertjlane Do you want to include these images in the streak popup? Do we need any configuration settings to show/hide the images?

**Comment by ertjlane** [comment]
@sarithapillai8 1. I don't think we want these to be attached to the streak pop-up, I think it should be separate. There can be a simple toggle in the investigator dashboard when editing the activity to 'show additional visual pop-up', if that makes sense.

**Comment by evinkalengaden** [comment]
Hi @ertjlane, We have updated the changes in dashboard staging, Please review.

**Comment by ertjlane** [comment]
Hello, @evinkalengaden, thanks for this. I have reviewed the games, and noticed that in many instances, even when the toggle was turned on to have the visual appear at the end of the game, they did not actually show up, either upon completing the game, or leaving it. The only exception to this is the Symbol Digit Substitution Game. Can you please investigate this?

**Comment by michaelmenon** [comment]
Thanks @ertjlane let us check and will get back asap.

**Comment by sarithapillai8** [comment]
@ertjlane We have tried on two different machines to reproduce the issue, but we have not been successful so far. Could you please try clearing the cache and checking again to see if there is any scenario where the issue can be reproduced? Also, could you please confirm once again that the settings are being saved correctly?

**Comment by ertjlane** [comment]
@sarithapillai8 I just double checked, thank you for the follow up and for your work on this. This looks good now!
