### ISSUE TITLE
Updated Spatial Span Score Display

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#806]
We would like to instantiate a scoring system for several of the cognitive games, with the aim of creating a user interface showing the user their score in the 'portal' section, utilizing graphs much like those used for survey scoring. To explore the process of implementing this, we would like to start by implementing this feature for the Spatial Span game, and utilize that as a model for implementing future scoring systems. So, this feature involves two components. 

1. The scoring system. 
- For each level correctly completed in Spatial Span, the user receives 10 points. With 6 possible levels, this leaves the user the potential for a maximum of 60 points per game, and a minimum of 0 points (as would happen if they fail the first level twice and receive a game over). We would like the score to be recorded, and then documented in the users portal section, as discussed below. 
2. The UI Showing the Score
- We would like the user to be able to see their score for spatial span as a graph, much like the interface for surveys. An example is shown below, substituting the 'weekly survey' for 'Spatial Span'. 
<img width="532" alt="Screen Shot 2024-04-24 at 10 36 14 AM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/0eacdd40-2348-4c5f-a9ef-994fe2ff7968">

We would like this to be done without making any changes to the API. Thank you, and please let me know if, or what questions you have.

**Comment by ZCOEngineer** [comment]
@ertjlane We shall review this and get back.

**Comment by sarithapillai8** [comment]
@ertjlane Similar to surveys, we also display a graph in the portal section for games. Would you like us to replace that with this scoring system?

**Comment by ertjlane** [comment]
@sarithapillai8 That is a great point, yes we would like it to be replaced. The visualization should be exactly the same except that the number on the Y axis should be the score. Out of curiosity, what do the current numbers on the Y axis of Spatial Span represent/how are they calculated?

**Comment by sarithapillai8** [comment]
Current calculation is based on score value and it is similar in jewels and other games. Score calculation is done as (this.state.successStages / totalStages) * 100.
We can replace this with new one.

**Comment by ertjlane** [comment]
Hello Saritha, I didn't realize there WAS a scoring system in place for the spatial span game. So for the system you described, the minimum value would be 0, and the maximum would be 100? 

Regardless, if there is already a scoring system in place then it is fine to keep it. The more important thing is that we have a new system for visualizing the scoring system, presuming we have one in place. Particularly since we are using this to assess how we might visualize/best score other games. So does the value shown in the dashboard represent the score calculated by the current system?

**Comment by ertjlane** [comment]
Thank you for this. This is useful information. What I think we want to accomplish, is to communicate participant scores, and what they mean. Given the info you just shared, what I propose is 2 visual changes, one to the portal section, and one to the popup after the game is completed. 

1. For the portal visualization of the cognitive games, have the x axis cap not at the highest score the user has achieved, but the highest score POSSIBLE. For the time being, let's implement this for spatial span, then once we have worked it out move on to the other games. We will not implement this for surveys, simply to keep the scope focused. 
2. For the visualization that pops up at the end of spatial span, add a text box underneath, showing the user the score they received, underneath the maximum possible score, with text denoting such. 

Let me know if there is additional information I can provide that would be helpful.

**Comment by sarithapillai8** [comment]
@ertjlane The maximum possible score for spatial span is 100, and that's what we are currently displaying. We can add the score values in the popup as suggested.

**Comment by sarithapillai8** [comment]
@ertjlane Please see below: let us know if this works for you.
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/41001ee3-096b-44d8-975f-5ccdbe8ebea4)
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/eeee9351-7021-449b-9c78-dadc1e242d6b)

**Comment by ertjlane** [comment]
Hello Saritha, yes this is Exactly what I was thinking of, that's perfect! It's fine if the scale is different for the other games, I just wanted to test it on spatial span and get a system ironed out for that one then move on to the others. Please let me know when this is good and ready for testing!

**Comment by sarithapillai8** [comment]
@ertjlane All the games have a maximum score of 100. We have updated the change in staging. Could you review it?

**Comment by ertjlane** [comment]
This looks good, and ready for release! Thank you very much!
