### ISSUE TITLE
Multiple mindLAMP Users Logged Out Consistently

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#808]
**Describe the bug**
We have received numerous reports of mindLAMP users being logged out of their accounts, seemingly spontaneously. Further, the same users report not being able to use their last-used credentials to log in. In all instances, users have been given new credentials, which they are logged out of, and are able to log back in when they use their originally generated mindLAMP credentials. This issue has occurred largely on the mindlamp-api.pronet.med.yale.edu. I have below included an excel document with the device data of those users who experienced this issue, as it is a high number of users. It is not perfectly clear if this is a frontend issue, or a native core issue. 

I am working on obtaining screenshots & additional details from the users reporting this issue.

[Logged Out User Device Data.xlsx](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/15301556/Logged.Out.User.Device.Data.xlsx)

**Comment by sarithapillai8** [comment]
@ertjlane Can you confirm if these users are logged in with credentials of the same user? Is this anything related to deleting the account? We are working on this. If you have any more information, please let us know.

**Comment by carlan1** [comment]
Have them run LAMP.Type.list_attachments('id') to see if these participants have a lamp.is_deleted tag

**Comment by sarithapillai8** [comment]
@ertjlane When an account is deleted, all the credentials related to that participant are removed. I am not able to check that with the given list as it only contains device information.

**Comment by ertjlane** [comment]
I have run the appropriate report and it appears that the users accounts have not been deleted, per the screenshot here. This is an example, but I run the code on multiple participants experiencing the issue, all of which produced the same result. 

<img width="737" alt="Screen Shot 2024-05-15 at 4 38 07 PM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/104088715/03bd8d3b-1d77-4e39-a6fd-2573019e835e">

**Comment by sarithapillai8** [comment]
@ertjlane Sorry I could not understand. Are you saying delete account not deleting credentials?

**Comment by ertjlane** [comment]
@sarithapillai8 I am saying deleted credentials not deleted account, so the opposite!

**Comment by ertjlane** [comment]
@sarithapillai8 Does the information that the credentials not accounts are being deleted provide any more useful context?

**Comment by sarithapillai8** [comment]
@ertjlaneThe delete account functionality removes user credentials to prevent the user from logging back into their dashboard. However, we do not delete any other data related to the user, allowing you to refer to it in the future.

**Comment by sarithapillai8** [comment]
```
      await LAMP.Credential.list(participant.id).then((cred) => {

          cred = cred.filter((c) => c.hasOwnProperty("origin"))

          cred.map(async (each) => {

            await LAMP.Credential.delete(participant.id, each["access_key"])

          })

        })

        await LAMP.Type.setAttachment(participant.id, "me", "lamp.name", null)

        await LAMP.Participant.delete(participant.id) 
```

The above code snippet is related to user deletion when a researcher deletes participant(s) from the researcher dashboard, i.e., when one or more participants are selected and deleted.
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/b1292d44-0436-45b9-9cb5-86db8750792d)

In this case, both credentials and participants are deleted from the database. The 'is-deleted' tag is not used here.

 ```
await LAMP.Type.setAttachment(id, "me", "lamp.is_deleted", true)

    await LAMP.Credential.list(id).then((cred) => {

      cred = cred.filter((c) => c.hasOwnProperty("origin"))

      ;(cred || []).map(async (each) => {

        await LAMP.Credential.delete(id, each["access_key"])

      })

    })

    await LAMP.Type.setAttachment(id, "me", "lamp.name", null)
```

This is the code snippet for deleting an account from the participant dashboard.
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/d35da04b-d51c-489e-a92f-bc86b8c8161c)

The functionality for deleting an account from the participant dashboard is the same for both researchers and participants. The 'is_deleted' tag name is used for the delete account functionality from the participant dashboard. In this case, only credentials are deleted and the participant is marked with the 'is_deleted' tag.

**Comment by carlan1** [comment]
Logic makes sense and reflects what we discussed. Thank you

**Comment by ertjlane** [comment]
Hello all, per the code I shared previously we have reason to believe that the accounts have not actually been deleted, as the user previously reported had no 'is_deleted' tag, suggesting that this IS actually a bug.

**Comment by sarithapillai8** [comment]
@ertjlane We are not able to debug the issue. Can we get any logs?

**Comment by ertjlane** [comment]
@sarithapillai8 Thanks for the information, this is useful for frame of reference. When you say a database log, or server log, what exactly do you mean?

**Comment by ertjlane** [comment]
@sarithapillai8 Just following up on this!

**Comment by sarithapillai8** [comment]
@ertjlane Are there any logs that can help debug the issue, I am not sure which can be used in this case? We are not sure if someone accidentally deleted them. As I mentioned above, apart from the delete account feature, there were no other changes made to the credentials section. This happened on a different server, which is not accessible to us. We need a way to reproduce this since it happened for the first time. There are no other possibilities that could cause the deletion of credentials apart from deliberate or accidental actions by the admin or researcher.

**Comment by MattMatt27** [comment]
Would seem that the participant or researcher must have deleted the account by accident. We have not had any similar issues with other participants since.
