### ISSUE TITLE
Logged out of app when they exit and not receiving notifications

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#81]
**Describe the bug**
MindLAMP logs me out after I exit the app and hinders me from receiving notifications.

**Smartphone (please complete the following information):**
 - Device: Samsung S8, iPhone XR

**Comment by jijopulikkottil** [comment]
_"MindLAMP logs me out after I exit the app"_ - It means, the data (username, password, server and userid) is missing or not passing to native side when login. We can post logs in this case to track the issue. Or to test quickly, Do you have the domain(if explicitly specifying when login), username and password to validate the data pass through script message handler.
