### ISSUE TITLE
Customizing the list of emotions in the Emotion Recognition activity

### ISSUE THREAD

**Issue by kijote0** [BIDMCDigitalPsychiatry/LAMP-platform#810]
We would like to add customization to the Emotion Recognition activity. In particular, we would like for researchers to have the option of specifying a list of emotions when creating the activity, instead of being restricted to the default list of Happiness, Sadness, Fear, Anger, and Neutral.

Ideally, there should be an option to use the built-in list of emotions specified above, or to create a custom list of emotions appropriate to the set of images used by the researcher. Then, when adding images, the Emotion drop-down list would contain the emotions from the list chosen by the researcher.

**Comment by evinkalengaden** [comment]
Hi @kijote0, 
The changes are updated in the dashboard staging and Please let me know your comments.

Thanks,
Evin K Alengaden

**Comment by kijote0** [comment]
Hi @evinkalengaden, just to confirm, to test the changes in dashboard staging, I would go to dashboard-staging.lamp.digital, correct? I tried to add a new Emotion recognition activity for a participant on dashboard staging, but I did not see how to customize the list of emotions

**Comment by evinkalengaden** [comment]
Hi @kijote0, Thanks for the reply. I am attaching a document which explains how to setup the Emotion Recognition activity. Try using this detailed document and let me know your comments.
[Emotion Activity Settings in detail.docx](https://github.com/user-attachments/files/15880897/Emotion.Activity.Settings.in.detail.docx)

**Comment by kijote0** [comment]
Thanks for sharing this document. Based on the instructions provided, it seems as if the Emotion Recognition task is the same as before: I am still unable to see how to customize the list of emotions beyond the default list. When I click on "Emotions", I only see "Happiness", "Sadness", "Fear", "Anger", and "Neutral".
Is it possible to customize the list of emotions? I.e. to optionally specify a list of emotions instead of using the default list provided.

**Comment by sarithapillai8** [comment]
@kijote0 Currently, the staging environment is not reflecting the recent changes. We updated the master branch two weeks ago. I tried rebuilding, but the changes are still not appearing on the site. Has there been any change made to the staging image? Previously, updating the master branch would trigger the staging environment to update with the latest code. Can you check if there have been any changes? I suspect this issue might have started after the login fix made for staging.
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/11d8a7da-3a5d-47e0-a226-0f61561d3cbc)

**Comment by sarithapillai8** [comment]
These are the actual screens with changes. Somehow this is not visible in the staging.
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/0ff54841-2412-47a8-93ef-211ef6541a46)
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/54e5546a-8388-49ad-9e0e-0a3577b8eab5)
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/a80faaa7-2fe7-47ba-9071-a2df8adaeb08)
![image](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/749aeb3a-9ebc-4130-a15e-444aa6434b50)

**Comment by kijote0** [comment]
@sarithapillai8 I just checked on the staging dashboard again, and it now seems that the changes are reflected

**Comment by ZCOEngineer** [comment]
> @sarithapillai8 I just checked on the staging dashboard again, and it now seems that the changes are reflected

Also @kijote0 did you do anything to make the updates available in Staging?

**Comment by kijote0** [comment]
@sarithapillai8 Yes, the feature matches what we had in mind.

**Comment by kijote0** [comment]
@ZCOEngineer No, I did not do anything to make the updates available in Staging
