### ISSUE TITLE
Add matrix of fields as option for questions in survey instruments

### ISSUE THREAD

**Issue by kijote0** [BIDMCDigitalPsychiatry/LAMP-platform#817]
**Feature description**
When creating a survey instrument on mindLAMP, we would like the option of creating a _matrix of fields_ (i.e. a table that groups survey items together as rows), similar to what is possible with RedCAP , to facilitate making certain survey types.

**Desired solution** 
Ideally, we would like to be able to create something that resembles the following, in which we can (1) provide a description at the top of the diagram (i.e. where "Please read each of the statements..." is currently); (2) customize the entries of the first column to contain the survey items (i.e. where each of the numbered entries are); and (3) customize the entries of the remaining columns to contain appropriate responses, such as a Likert scale or a checkbox (i.e. where each of the columns with radio buttons are).
![matrix_of_fields](https://github.com/user-attachments/assets/7206a314-abbf-4a5f-8544-3cc4d33f8c32)

**Comment by sarithapillai8** [comment]
This seems to be a duplicate feature request.
please check this ticket -https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/442

**Comment by kijote0** [comment]
Issue #442 does describe the same feature; was it ever completed and pushed to production?
Currently, it does not seem possible to create a matrix when making a survey instrument on the dashboard.

**Comment by sarithapillai8** [comment]
Yes @kijote0 It is already updated in production in 2022. To create a matrix, you need to create a matrix question followed by the same type of multiple questions. When there is a change in question type, matrix section ends. This was the requirement we got from Aditya.

**Comment by kijote0** [comment]
@sarithapillai8 Are there instructions available on how to create a matrix that would resemble the example in the issue description? I am unsure if I am doing something incorrectly, but it seems that the first question always has a text box and that the answer choices for the various survey items are not necessarily shared and have to be set individually. Ideally, the set of options for the survey items would only have to be set once, and the first item could be customized to not necessarily have a text box.
I have attached the following screenshots for reference.
![matrix_1](https://github.com/user-attachments/assets/97d3e59e-04bc-4537-8b35-4b72f2b04326)
![matrix_2](https://github.com/user-attachments/assets/94f72208-8c14-4f58-9777-66cdcba1f168)

**Comment by sarithapillai8** [comment]
@kijote0 The steps to create matrix question I mentioned were wrong. I'm very sorry about that. I rechecked and found this : https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/442#issuecomment-1029703095. Please go through the detailed steps to create a matrix question. 

![image](https://github.com/user-attachments/assets/e2ca958d-4876-4faa-a2d0-d22370fc27b8)

**Comment by kijote0** [comment]
@sarithapillai8 Thank you! Following the instructions I was able to create a matrix question properly.
