### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#82]
**Is your feature request related to a problem? Please describe.**
There should be a "Welcome to mindLAMP" intro screen if a patient has logged in for the first time that guides them through which activities they can use and which ones will show up in the feed/send notifications, then which sensors are activated/enabled AND WHY THEY ARE being used. Maybe then an informed consent quiz/description of the study/etc and finally load up the Home Screen.

**Comment by sarithapillai8** [comment]
@avaidyam  @elenamrv 
Please provide the details to be shown on the welcome screen? or do we need to show the welcome screen where was there initially?

**Comment by avaidyam** [comment]
For now, please make it a very plain dialog saying “Welcome to mindLAMP” with a single “Continue” button. You can remove the original welcome screen code.
