### ISSUE TITLE
DBT Diary Card Updates

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#83]
> @elenamrv (on behalf of the client):
> 1. Optional comments do not show up in Prevent - they should be dated and the full note should be there
> 2. There is a "none" field in the emotions graph, and well as both the ineffective urges graph and effective urges graph
> 3. Not all emotions show up. I rated myself as a 5 with Joy and there is no Joy marker (the field is there but there are no Joy data points on the graph)
> 4. The Actions graph is wrong. Each urge / action gets its own graph at the bottom
> 5.  The feature to view graph by week reads "TEN, TWENTY, THIRTY." This should list weeks (ie 12/12 - 12/19)  - beginning with the date the first card was completed, and then weekly

**Comment by avaidyam** [comment]
@michaelmenon @sarithapillai8 This is an **urgent** priority to complete these items. Please let me or @elenamrv know if there are any questions.

**Comment by michaelmenon** [comment]
Hi @avaidyam we will look into it as soon as possible, just to let you know engineers have taken off for few days next week. So as soon as anyone is available we will check on it. I will check and see who is available next week to check on it.

**Comment by sarithapillai8** [comment]
@avaidyam @elenamrv 

1. Optional comments do not show up in Prevent - they should be dated and the full note should be there - _Will check on it_
2. There is a "none" field in the emotions graph, and well as both the ineffective urges graph and effective urges graph - @avaidyam We talked about this and it was planned to ask the developer to work on this. So please confirm.
3. Not all emotions show up. I rated myself as a 5 with Joy and there is no Joy marker (the field is there but there are no Joy data points on the graph) - _will check on it_
4. The Actions graph is wrong. Each urge / action gets its own graph at the bottom - Could you please provide more details?
5. The feature to view graph by week reads "TEN, TWENTY, THIRTY." This should list weeks (ie 12/12 - 12/19) - beginning with the date the first card was completed, and then weekly - Okay.

**Comment by sarithapillai8** [comment]
@avaidyam @elenamrv 

1. Optional comments do not show up in Prevent - they should be dated and the full note should be there - Updated in PR
2. There is a "none" field in the emotions graph, and well as both the ineffective urges graph and effective urges graph -  Updated in PR
3. Not all emotions show up. I rated myself as a 5 with Joy and there is no Joy marker (the field is there but there are no Joy data points on the graph) - _will check on it_
4. The Actions graph is wrong. Each urge / action gets its own graph at the bottom - Could you please provide more details?
5. The feature to view graph by week reads "TEN, TWENTY, THIRTY." This should list weeks (ie 12/12 - 12/19) - beginning with the date the first card was completed, and then weekly - Okay.

**Comment by avaidyam** [comment]
@sarithapillai8 For point #4 I think the issue is that the Vega graph spec isn't showing the legend like the other graphs are so it's not possible to view the actions timeline for each action specifically. 

@gabrieldev755 Is this something that can be fixed from the Vega side of things?

**Comment by sarithapillai8** [comment]
@avaidyam @elenamrv 
The feature to view graph by week reads "TEN, TWENTY, THIRTY." This should list weeks (ie 12/12 - 12/19) - beginning with the date the first card was completed, and then weekly  - This list will grow in future. so do we need some limit?

**Comment by avaidyam** [comment]
@sarithapillai8 
1. No need for a limit for the week selector for now. 
2. Do you have a screenshot of this that you could share?

**Comment by avaidyam** [comment]
@sarithapillai8 Please take a look at these recent comments from the client: 

**Bugs:**
- [Vega Graphs] Actions Timeline doesn't appear to be graphing correctly. The legend does not appear correctly.
![image](https://user-images.githubusercontent.com/1361003/103775404-fe7e2e80-4ffb-11eb-8cd9-c0b3975abfd9.png)

**UI Changes:**
- [DBT Activity and/or Dashboard] Make the font for the "Urge" and "Acted" headers bolder (Question 1)
- [Vega Graphs] Create labels for Y axis on graphs in Prevent.
    - For Urges, Y axis is " Intensity"
    - For Emotions, Y axis "Intensity"
    - For Actions, Y axis should be "Times" for the summary, and for the specific action graphs, the Y axis should be whichever label is selected (e.g. days, hours, times)
- [Vega Graphs] The legend for the graphs does not multi-select by default. To select multiple items in the legend you have to shift-click, and it would be ideal if the behavior was multi-select by default instead.

**Comment by sarithapillai8** [comment]
1) what is to be shown in actions legend? There is a total of type values of effective/ineffective values. So what to be shown else there? 
2) for urges the acted values can be mix of different measuring units. So how can we show that in y axis as it is like a total? Or will that measuring unit same for all always? 

I am not sure about multi-select option change. We will check and update.

**Comment by avaidyam** [comment]
@sarithapillai8 For the Actions (Timeline) legend, please show everything the same was as it shows for the Actions (Summary). We want this chart to be a stacked bar chart (which my team can update the Vega spec for). For the urges, it’s okay to mix units.

**Comment by sarithapillai8** [comment]
@avaidyam 

If Actions(Timeline) will be changed your team, i hope the legend will be managed also.

For urges, how can I show mixed units? If there are 2 units : times and hours, can we show the text times/hours in y axis? it will be more confusing I think. Please confirm.

**Comment by avaidyam** [comment]
@sarithapillai8 Please just mark the axis as "Units" then to avoid confusion. It is pretty clear that multiple unit types cannot easily be compared, as you've pointed out.
