### ISSUE TITLE
Spin the Wheel - Buttons not displaying correctly

### ISSUE THREAD

**Issue by kijote0** [BIDMCDigitalPsychiatry/LAMP-platform#831]
The buttons in the Spin the Wheel game are not displaying correctly, which makes it difficult for users to correctly play the game: instead of the 4 buttons at the bottom of the screen being colored in, they contain numbers.

This is how the buttons are currently displayed in the app:
![IMG_5397](https://github.com/user-attachments/assets/57204c04-6a33-4169-984e-94b84bec7afd)

This is how the buttons should be displayed:
![correct_spin_the_wheel](https://github.com/user-attachments/assets/06f9dc49-5fd6-4125-b8ec-00951e0b2d96)

**Comment by sarithapillai8** [comment]
@kijote0 We changed the buttons as per requirement in https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/782.
Please confirm.
