### ISSUE TITLE
Answer Text Not Displaying Occasionally 

### ISSUE THREAD

**Issue by MattMatt27** [BIDMCDigitalPsychiatry/LAMP-platform#836]
**Describe the bug**
A few participants have reported seeing missing answer option text when they are answering surveys. It will show ... rather than the expected text (eg. 'Always', 'Never')

**To Reproduce**
The issue appears a bit random and infrequent so we have been unable to determine exact steps to reproduce the issue. It has only been observed on participant devices thus far.

**Expected behavior**
All description text for Answers in surveys should appear

**Screenshots**
![Screenshot 2024-10-07 at 1 45 39 PM](https://github.com/user-attachments/assets/49749abc-2061-430d-9e01-41bad02fb808)
![Screenshot 2024-10-07 at 1 45 24 PM](https://github.com/user-attachments/assets/edf427aa-4e45-4d2e-818e-14eeaa169427)

**Smartphone (please complete the following information):**
 - Device: iPhone devices are the only reported ones so far
 
**Additional context**
Only 2-3 participants reporting this issues so far. Low priority. Will update priority and add comments if issue becomes more frequent.

**Comment by sarithapillai8** [comment]
@MattMatt27 There is an option to scroll down to view the rest of the survey question. It seems the text is beneath the current view. Could you please ask the user to check again?

**Comment by MattMatt27** [comment]
@sarithapillai8 The user claimed that they tried to scroll down to view the rest of the survey question but were not able to. From the screenshots I agree with your assessment that it does seem that the text is beneath the current view.
