### ISSUE TITLE
Saved survey data not appearing in Prevent tab

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#84]
**Describe the bug**
Multiple participants have reported that LAMP does not save surveys anymore. After investigating it seems like this could also instead be an issue where survey data is being saved correctly but the Prevent tab/Feed tab are not correctly reflecting that. 

**To Reproduce**
> **Patient:** "I've been taking morning and afternoon surveys through both the Feed and Assess tabs. Aside from the weekly summary, however, it does not appear to be logging my answers. It does not show the streak badge, or the streak badge does not update day-by-day, and the graphs on the Prevent tab aren't updating. I just want to make sure I'm not doing anything wrong, and that the data is properly being logged. “

Affected Participant IDs (for `api.lamp.digital` server):
* `U5021714125`
* `U6328536102`

**Expected behavior**
Survey data should be saved correctly and visible in the Prevent tab.

**Smartphone:**
 - Device: Unknown
 - OS: Android (Version Unknown)
 - App Version: “Latest”

**Comment by sarithapillai8** [comment]
Updated this bug fix the PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/166
