### ISSUE TITLE
Duplicate javascript files in LAMP-server

### ISSUE THREAD

**Issue by MattMatt27** [BIDMCDigitalPsychiatry/LAMP-platform#843]
I noticed that in LAMP-server a number of the folders contain duplicate javascript and typescript files. It is my understanding that the javascript would be generated dynamically and so we shouldn't need to have the javascript files saved off in the GitHub repository. 

If I understand correctly, it looks like this commit: https://github.com/BIDMCDigitalPsychiatry/LAMP-server/commit/c34819d4a7d00c2bd05c1691dfdfed0a0148115c generated all of the javascript files and that none of them have been edited since. 

Is there a reason that we want to keep these javascript files around? 

The folders that have both .ts and .js files are:
- LAMP-server/src/model
- LAMP-server/src/repository
- LAMP-server/src/repository/couch
- LAMP-server/src/repository/interface
- LAMP-server/src/repository/mongo

This is more of a housekeeping question/issue. The only potential negative impact would be if someone went and edited the javascript files without editing the typescript files, but from a quick pass that does not seem to have happened yet.

**Comment by sarithapillai8** [comment]
Removed the js files. @MattMatt27

**Comment by MattMatt27** [comment]
Looks good! Thank you
