### ISSUE TITLE
Survey text responses are displayed backwards in Prevent tab graphs

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#85]
**Describe the bug**
> **Collaborator:** “Words are displayed backwards in Prevent when a patient comments on their day via Daily Survey.”

**To Reproduce** 
1. Take a survey with a text field question.
2. Respond to the question. 
3. Submit the survey. 
4. Go to the Prevent tab.
5. Go to the survey’s graph.
6. See the error.

**Expected behavior**
The text response should not be flipped. 

**Screenshots**
<img width="525" alt="XyeJ2Lke_o" src="https://user-images.githubusercontent.com/1361003/103682691-30898500-4f57-11eb-817f-bac0dc392e64.png">

**Desktop:**
 - OS: macOS (Version Unknown)
 - Browser: Safari (Version Unknown)

**Comment by divyav2020** [comment]
@avaidyam We are unable to reproduce this issue
