### ISSUE TITLE
Survey screen going blank mid-way through for participant

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#86]
**Describe the bug**
Survey screen going blank mid-way through for participant. After Question 17, on 3 Grouped Assessments survey, the screen goes blank (white) and the participant can no longer complete the survey.

**Screenshots**
https://user-images.githubusercontent.com/1361003/103684171-249ec280-4f59-11eb-913f-60dd9f633c57.mp4

**Smartphone:**
 - Device: iPhone
 - OS: iOS 14.2
 - App Version: 8f5399f

**Comment by sarithapillai8** [comment]
This is fixed as a part of the PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/166
