### ISSUE TITLE
Offset error when creating emotion recognition

### ISSUE THREAD

**Issue by kijote0** [BIDMCDigitalPsychiatry/LAMP-platform#862]
When modifying an existing Emotion Recognition activity event with 20 images on the dashboard, I received an error that states "The value of 'offset' is out of range. It must be >=0 && <= 17825792. Received 17825795" after I tried to change 2 images. 
![Image](https://github.com/user-attachments/assets/d030b950-6ddd-4698-b9c0-e380ee6fb332)

If it would be helpful to have for testing, I can provide the json file for the activity event as well as the files for the images I was trying to add.

**Comment by sarithapillai8** [comment]
@kijote0 We could not reproduce the issue. Could you please provide the details?

**Comment by sarithapillai8** [comment]
@kijote0 The images should have a maximum size of 4MB. Some of the pictures are of size greater than 4MB. I think the size warning is not displaying correctly. We can fix that.

**Comment by sarithapillai8** [comment]
@kijote0 Yes. We are working on that.

**Comment by sarithapillai8** [comment]
@kijote0 We have updated the fix in https://lamp-dashboard.zcodemo.com. Please review.
