### ISSUE TITLE
Update the PUSH_API_GATEWAY environment variable

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#87]
@Linoy339 The `PUSH_API_GATEWAY` environment variable should be renamed to `APP_GATEWAY`. (The `PUSH_API_KEY` variable should stay the same.) Furthermore, the format of the `APP_GATEWAY` variable must be `app-gateway.lamp.digital` (i.e. `<domain name>`) instead of `https://app-gateway.lamp.digital/push` (i.e. `https://<domain name>/push`). If the `APP_GATEWAY` variable is not defined, then fallback to `PUSH_API_GATEWAY` for legacy support:

```js
const gatewayURL = !!process.env.APP_GATEWAY ? `https://{process.env.APP_GATEWAY}/push` : process.env.PUSH_API_GATEWAY
```

If neither variable is correctly declared, log an error to the console and disable the push notifications module.

**Comment by Linoy339** [comment]
@avaidyam . PUSH_GATEWAY_APIKEY and PUSH_GATEWAY are the environment variables which we ae using now.

Can you clarify :
1)An additional environment variable need to be kept inside env and the variable name should be APP_GATEWAY.
2)APP_GATEWAY should contain the value "app-gateway.lamp.digital" 
3) If APP_GATEWAY is not defined, PUSH_GATEWAY variable should be used which contain the value- https://app-gateway.lamp.digital/push.
eg: 
const gatewayURL = !!process.env.APP_GATEWAY ? `https://{process.env.APP_GATEWAY}/push` : process.env.PUSH_API_GATEWAY

**Comment by avaidyam** [comment]
@Linoy339 
1. Yes, `APP_GATEWAY` will replace `PUSH_GATEWAY` and will store only the DNS name (not a URL) such as `app-gateway.lamp.digital`.
2. Yes; see above.
3. Yes; this is fallback behavior. 

Furthermore, the `PUSH_GATEWAY_APIKEY` variable needs to be renamed to `PUSH_API_KEY`. If the `PUSH_API_KEY` variable is not defined, THEN fallback to using `PUSH_GATEWAY_APIKEY`.

**Comment by Linoy339** [comment]
@avaidyam .
Please find [https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/41](https://github.com/BIDMCDigitalPsychiatry/LAMP-server/pull/41)
