### ISSUE TITLE
"Activity" Clipping Issue (Windows 10 Firefox 84.0.1)

### ISSUE THREAD

**Issue by philhenson** [BIDMCDigitalPsychiatry/LAMP-platform#89]
**Describe the bug**
"Activity" in the "Prevent" tab is cut off

**To Reproduce**
Go to Prevent in the browser version of the dashboard

**Expected behavior**
No clipping of Activity. If the screen is resized to be more smartphone-shaped, the problem is fixed when things snap to realign to the new dimensions. But the problem persists when resizing back to the original window.

**Screenshots**
![image](https://user-images.githubusercontent.com/4040536/103843428-cf040c00-5065-11eb-9d48-488d7bd78ee3.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Firefox
 - Version 84.0.1

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by divyav2020** [comment]
@avaidyam We are unable to reproduce this issue. Hence kindly provide us with more details.

**Comment by avaidyam** [comment]
@divyav2020 Are you using Firefox v84 on Windows 10? That is what you should use to reproduce the issue.

**Comment by divyav2020** [comment]
@avaidyam We are unable to reproduce this issue with same configuration.  Hence kindly provide us with more details.
