### ISSUE TITLE
Major refactoring for LAMP-core-android

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#90]
@amaljofyzco Please make the following changes to the `LAMP-core-android` repository:

- [x] `.DS_Store`: every instance must be deleted; add this file to `.gitignore`
- [x] `.idea/`: delete and add to .gitignore
- [x] `app/.gitignore`: delete; there should only be ONE in the repository root
- [ ] `lamp-core/`: delete and move to `LAMP-kotlin` repository
- [ ] `sensor-core/`: delete and move to `LAMP-kotlin` repository
- [ ] `app/src/main/java/digital/lamp/mindlamp/sensor/`: delete and move to `LAMP-kotlin` repository
- [x] `prod/`: delete
- [x] `app/proguard-rules.pro`: delete
- [x] `app/key.jks`: delete **IMMEDIATELY**
- [x] `app/google-services.json`: delete **IMMEDIATELY**
- [x] `app/src/main/ic_launcher-web.png`: delete
- [x] `app/src/main/res/drawable-*/splash_bg.png`: delete
- [x] `app/src/main/res/drawable-*/ic_stat_autorenew.png`: delete
- [x] `app/src/main/res/drawable-*/ic_stat_notification_icon.png`: delete
- [ ] `app/src/main/res/drawable-*/ic_launcher.png`: delete and replace with single vector asset XML
- [x] `app/src/main/res/drawable-*/ic_launcher_foreground.png`: delete (use `ic_launcher.xml`)
- [ ] `app/src/main/res/drawable-*/ic_launcher_round.png`: delete (use `ic_launcher.xml`)
- [ ] `app/src/main/java/digital/lamp/mindlamp/*`: all sub-packages must be flattened into parent package (`app, appstate, database, model, notification, repository, utils`).

For the `LAMP-kotlin` repository:

- [x] `src/main/kotlin/digital/lamp/lamp-core/*`: there is a module nested within the module which is not appropriate; the contents of `src/main/kotlin/digital/lamp/lamp-core/src/main/java/digital/lamp/service` should be inside `src/main/kotlin/digital/lamp/lamp-core` and the other files should be deleted
- [x] `src/main/kotlin/digital/lamp/sensor-core/*`: there is a module nested within the module which is not appropriate; the contents of `src/main/kotlin/digital/lamp/sensor-core/src/main/java/digital/sensor` should be inside `src/main/kotlin/digital/lamp/sensor-core` and the other files should be deleted

**Comment by amaljofyzco** [comment]
> @amaljofyzco Please make the following changes to the `LAMP-core-android` repository:
> 
> * [ ]  `.DS_Store`: every instance must be deleted; add this file to `.gitignore`
> * [ ]  `.idea/`: delete and add to .gitignore
> * [ ]  `app/.gitignore`: delete; there should only be ONE in the repository root
> * [ ]  `lamp-core/`: delete and move to `LAMP-kotlin` repository
> * [ ]  `sensor-core/`: delete and move to `LAMP-kotlin` repository
> * [ ]  `app/src/main/java/digital/lamp/mindlamp/sensor/`: delete and move to `LAMP-kotlin` repository
> * [ ]  `prod/`: delete
> * [ ]  `app/proguard-rules.pro`: delete
> * [ ]  `app/key.jks`: delete **IMMEDIATELY**
> * [ ]  `app/google-services.json`: delete **IMMEDIATELY**
> * [ ]  `app/src/main/ic_launcher-web.png`: delete
> * [ ]  `app/src/main/res/drawable-*/splash_bg.png`: delete
> * [ ]  `app/src/main/res/drawable-*/ic_stat_autorenew.png`: delete
> * [ ]  `app/src/main/res/drawable-*/ic_stat_notification_icon.png`: delete
> * [ ]  `app/src/main/res/drawable-*/ic_launcher.png`: delete and replace with single vector asset XML
> * [ ]  `app/src/main/res/drawable-*/ic_launcher_foreground.png`: delete (use `ic_launcher.xml`)
> * [ ]  `app/src/main/res/drawable-*/ic_launcher_round.png`: delete (use `ic_launcher.xml`)
> * [ ]  `app/src/main/java/digital/lamp/mindlamp/*`: all sub-packages must be flattened into parent package (`app, appstate, database, model, notification, repository, utils`).
> 
> For the `LAMP-kotlin` repository:
> 
> * [ ]  `src/main/kotlin/digital/lamp/lamp-core/*`: there is a module nested within the module which is not appropriate; the contents of `src/main/kotlin/digital/lamp/lamp-core/src/main/java/digital/lamp/service` should be inside `src/main/kotlin/digital/lamp/lamp-core` and the other files should be deleted
> * [ ]  `src/main/kotlin/digital/lamp/sensor-core/*`: there is a module nested within the module which is not appropriate; the contents of `src/main/kotlin/digital/lamp/sensor-core/src/main/java/digital/sensor` should be inside `src/main/kotlin/digital/lamp/sensor-core` and the other files should be deleted

1. lamp-core/: delete and move to LAMP-kotlin repository - **If i delete this module the app cannot take build during CI/CD**
2. sensor-core/: delete and move to LAMP-kotlin repository - **If i delete this module the app cannot take build during CI/CD**
3. `app/src/main/java/digital/lamp/mindlamp/sensor/`: delete and move to `LAMP-kotlin` repository -  **This module caputure sensor values from sensor-core and trigger service using lamp-core**
4. `prod/`: delete - **This is just a folder to hold the produciton build.**
5. `app/proguard-rules.pro` - ** This is generated by android normally we don't take off this. This is usefull once we do the code obfuscation.**
6. `app/google-services.json`: delete **IMMEDIATELY** - **If we remove this we will not receive the notificaiton and analytics connection also will be affected. If i remove it from the repo when other devloper tried to clone this project then issues occur.**

**I will remove all other suggestions and do a PR again tomorrow.
On previous PR the ci/cd build failed due to the min sdk-version i have fixed it.**

**Comment by avaidyam** [comment]
@amaljofyzco 
> If i delete this module the app cannot take build during CI/CD

It has been mentioned before to convert `LAMP-kotlin` into a Kotlin library and then use [JitPack.io](https://jitpack.io) to import it within `LAMP-core-android`. It is fairly simple to do as well -- let me know if you encounter any issues here. 

> This module caputure sensor values from sensor-core and trigger service using lamp-core 

Then please flatten this sub-package into a single (very large) file and leave it in the main package instead. 

> This is just a folder to hold the produciton build.

It looks like it has other contents (`release/output-metadata.json`) which should **NOT** be checked into the GitHub repo. This folder should be created during CI/CD only. 

> This is generated by android normally we don't take off this. This is usefull once we do the code obfuscation.

We do not want to enable code obfuscation at all; normally it would be very useful but in this specific project we do not want it. If we need it later on we can add the file at that point in time. 

> If we remove this we will not receive the notificaiton and analytics connection also will be affected. If i remove it from the repo when other devloper tried to clone this project then issues occur.

This is because this file leaks private API credentials to Google/Firebase, it should never be the case that another developer/team has access to this. Upon forking the repository they must add their own `google-services.json` file with THEIR API credentials, not ours. We will need this file only for CI/CD, and [here is an example of how to use that](https://www.coletiv.com/blog/android-github-actions-setup/). I have created a GitHub secret called `GOOGLE_SERVICES_JSON` that contains the contents of this file.

**Comment by amaljofyzco** [comment]
[jitpack_log.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5796410/jitpack_log.txt)
Jitpack log
