### ISSUE TITLE
Use Sensor API to only collect data from specific sensors. 

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#92]
Currently all sensors collect data all the time if using the native app. We would like to use the `Sensor` API (i.e. `LAMP.Sensor.all_by_participant()`) and only enable sensor data collection for the specific sensors that are activated for the patient. All permissions dialogs will still be presented up-front when opening the app, however. This code change should be implemented in `LAMP-core-ios` and `LAMP-core-android` for iOS, Android, Apple Watch, and Google wearOS.

**Comment by jijopulikkottil** [comment]
Hi @avaidyam , can we expect all sensor names listed in the attached excel sheet and to handle each one ? Or Is there a plan to group 

[Sensors.xls.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5903973/Sensors.xls.zip)

**Comment by avaidyam** [comment]
@jijopulikkottil Please use this adapted list for now: 
- `lamp.gps`
	- latitude
	- longitude
	- altitude
	- accuracy
- `lamp.analytics` (should ALWAYS be enabled)
- `lamp.device_motion`
	- motion (x,y,z)
	- rotation (x,y,z)
	- gravity (x,y,z)
	- magnetic (x,y,z)
	- attitude (x,y,z; renamed from roll,pitch,yaw)
	- REMOVE: `lamp.watch.accelerometer`, `lamp.watch.magnetometer`, `lamp.watch.gyroscope`, `lamp.watch.accelerometer.motion`, `lamp.accelerometer`, `lamp.gyroscope`, `lamp.magnetometer`
- `lamp.steps`
	- value (i.e. count)
	- distance
	- floors_ascended
	- floors_descended
	- pace
	- cadence
	- active_pace
	- calories (only Google Fit)
	- REMOVE: `lamp.distance`, `lamp.floors_ascended`, `lamp.floors_descended`, `lamp.current_pace`, `lamp.current_cadence`, `lamp.avg_active_pace`, `lamp.active_minute`, `lamp.calories`, `lamp.calories_bmr`, `lamp.cycling_pedal_cadence`, `lamp.step_count_cadence`, `lamp.heart_minutes`, `lamp.power`, `lamp.speed`, `lamp.cycling_wheel_rpm`, `lamp.wheel_revolution_cumulative`, etc. (~15 others)
- `lamp.nearby_device`
	- type: "bluetooth" or "wifi"
	- address (bssid for wifi)
	- name (ssid for wifi)
	- strength (rssi)
	- REMOVE: `lamp.wifi`, `lamp.bluetooth`
- `lamp.telephony`
	- type (incoming, outgoing, missed, voicemail, rejected, blocked, external, sent_sms, received_sms)
	- duration (or message length if sent_sms or received_sms)
	- trace 
	- REMOVE: `lamp.calls`, `lamp.sms`
- `lamp.screen_state`
- `lamp.segment`
	- type
	- duration
- `lamp.sleep`
- `lamp.nutrition`
	- type (+ additional type "hydration" for Google Fit)
	- value
	- REMOVE: `lamp.dietary*` (~39 in total), `lamp.hydration`, `lamp.body_fat_percentage`, `lamp.uv_exposure`, `lamp.height`, `lamp.weight`, etc. (~5 others)
- `lamp.blood_glucose`
- `lamp.blood_pressure`
- `lamp.oxygen_saturation`
- `lamp.body_temperature`
- `lamp.heart_rate`
- `lamp.respiratory_rate`

**Comment by jijopulikkottil** [comment]
Updated the sheet. Removed sensors are marked as Red.
[Sensors.xls.zip](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5942990/Sensors.xls.zip)

**Comment by jijopulikkottil** [comment]
Hi @avaidyam , Could you please open the related server/web task of setting sensors in dashboard for a participant ? So that we can test it.

**Comment by avaidyam** [comment]
@jijopulikkottil This is already in the staging build so you can access it at `https://dashboard-staging.lamp.digital/` -- please check with @sarithapillai8 on how it works or if any issues come up.

**Comment by sarithapillai8** [comment]
@avaidyam
The sensors specific to participant are not tested as you said - https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/8#issuecomment-756109272. The code exist in the codebase. 
FYI @jijopulikkottil

**Comment by jijopulikkottil** [comment]
@Linoy339 Or @sarithapillai8  In staging dashboard, Could you please add the 'Sensor Spec'. Make sure that we only need specs which are listed [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/8#issuecomment-770976348)

**Comment by jijopulikkottil** [comment]
Can we use this in staging now ? 
[Sensors.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/5963889/Sensors.txt)

**Comment by avaidyam** [comment]
@jijopulikkottil Yes that should be okay! This document does look a little outdated but if you need to add any additional SensorSpecs, you can just add them as an empty JSON Schema with an `id` field.

**Comment by jijopulikkottil** [comment]
Currently we have handled the sensors which are listed [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/92#issuecomment-770976348). We have updated it in staging dashboard.
Please specify or [update the excel sheet of sensor name](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/92#issuecomment-775041544) if need to handle any other sensors..

**Comment by avaidyam** [comment]
@jijopulikkottil That sounds good - I will check in with my team about this list as well and confirm everything. Could you also restore the `lamp.accelerometer` sensor which will only be `x, y, z` accelerometer instead of the `lamp.device_motion` sensor which is much more comprehensive? This will be primarily for backwards compatibility.

**Comment by jijopulikkottil** [comment]
@avaidyam ok. we can handle both `lamp.accelerometer` and `lamp.device_motion`.

**Comment by jijopulikkottil** [comment]
@avaidyam when we post sensor event from watch, currently we are using like `lamp.watch.accelerometer`. Hope we can keep as it is. And we will add it to the dashboard sensor specs  to add sensors for a participant. right ?

**Comment by avaidyam** [comment]
@jijopulikkottil No - it should not be `lamp.watch.accelerometer`. The Watch apps should collect and post the exact same sensor data following the exact same sensor specs as the phone apps, regardless of device type.

**Comment by jijopulikkottil** [comment]
@avaidyam But can we identify the source of data if a participant installed app on both devices ?

**Comment by avaidyam** [comment]
That will be based on the security credentials used and the audit log. So not specific to the Sensor API changes here.
