### ISSUE TITLE
iOS notification bug with location services

### ISSUE THREAD

**Issue by kkadapa** [BIDMCDigitalPsychiatry/LAMP-platform#95]
@avaidyam I meticulously tested twice and found a bug in Push Notifications. The notifications are not being shown on the iPhones when Location Services is turned ON... The moment I turn off Location Services and then reschedule a different time using WebApp then I see them again on my iPhone.

_Originally posted by @kkadapa in https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/88#issuecomment-759838840_

**Comment by kkadapa** [comment]
Hello, Just following-up to see if there are any updates on this bug. Thanks!

**Comment by jijopulikkottil** [comment]
Hi @kkadapa 
Sorry, we couldn't reproduce this issue. Could you please try again by turning off location and make sure the internet connectivity is on.

To debug, 
Could you please give us the device token ? You can get it if you call the API https://api.lamp.digital/participant/{participant_id}/sensor_event?origin=lamp.analytics using Basic Authentication.  Replace 'participant_id' with your user id.
Or Could you share your credentials by email so we can get the device token by calling this API.
 
By using the device token, we can send push notification manually to check it is receiving or not.

**Comment by kkadapa** [comment]
@jijopulikkottil I just tried again on my iPhone just now by first turning off location services the Push Notification didn't occur but again when I turned location services on and rescheduled I received the notification... please let me know if you need additional details, the below are the logs and device_token

```
GET /type/a9zbfnbppszr5zc3qcfj/attachment/lamp.messaging 404 - 63.404 ms
{
  device_token: '9baaa9b31b309c37af10ed89d9546f09bbbba1687ef378816fe507316fbb7c48',
  device_type: 'ios',
  payload: {
    participant_id: 'U3395362177',
    activity_id: 'cvdm5mqebhwcyanzxcsr',
    message: 'You have a mindLAMP activity waiting for you: Breathe.',
    title: 'Breathe',
    url: '/participant/U3395362177/activity/cvdm5mqebhwcyanzxcsr'
  }
}
/participant/U3395362177/activity/cvdm5mqebhwcyanzxcsr
```

**Comment by jijopulikkottil** [comment]
hi @kkadapa did you get a 'test' notification which I sent manually.

**Comment by kkadapa** [comment]
No @jijopulikkottil Sorry I just reinstalled mindlamp app as I was testing different features... Could you please send it again now?

**Comment by jijopulikkottil** [comment]
@kkadapa  if you re-installed, the token might be changed. could you get the device token again.

**Comment by kkadapa** [comment]
No @jijopulikkottil, I checked the token is the same.

**Comment by jijopulikkottil** [comment]
@kkadapa  I have sent two notifications, please check.

**Comment by kkadapa** [comment]
Sorry @jijopulikkottil I didn't recieve it, My apologies that's not the right device token the following is the correct device token, could you kindly resend it?

```
GET /type/a9zbfnbppszr5zc3qcfj/attachment/lamp.messaging 404 - 43.670 ms
{
  device_token: '35c36b3c7a6efb07191bdd8e74001d471234e44acc65230e8f9e00f6eb919e56',
  device_type: 'ios',
  payload: {
    participant_id: 'U5248224818',
    activity_id: 'cvdm5mqebhwcyanzxcsr',
    message: 'You have a mindLAMP activity waiting for you: Breathe.',
    title: 'Breathe',
    url: '/participant/U5248224818/activity/cvdm5mqebhwcyanzxcsr'
  }
}
/participant/U5248224818/activity/cvdm5mqebhwcyanzxcsr
```

**Comment by kkadapa** [comment]
Yes I just received one Hello1... I think it's because I turned on location services and already tested a sample notification from the (https://dashboard.lamp.digital/)

**Comment by jijopulikkottil** [comment]
Please turn off location services Settings-> Privacy->Location Services -> turn off. I can send push after 5 mins

**Comment by kkadapa** [comment]
@jijopulikkottil The issue only occurs when someone installs the app for the first time and their location services are turned off... I reinstalled and the location services are turned off I didn't receive the Push Notification.  Will share the user login credentials in an email.

**Comment by jijopulikkottil** [comment]
jijo.pulikkottil@zcocorporation.com. Did you get the 'Hello3' push?.  
So the location services are turned off when you launch the app first time. right ? I will try this scenario.

**Comment by kkadapa** [comment]
I didn't get the Hello3 Push... Yes. In order to reproduce the issue you first turn off location services and then install mindlamp app and try sending a Push.

**Comment by jijopulikkottil** [comment]
I turned off location services (Settings-> Privacy->Location Services -> turn off). Installed mindLAMP 2 app, and logged in. Verified that the device token is sent to server by calling the API (https://api.lamp.digital/participant/{participant_id}/sensor_event?origin=lamp.analytics). I sent a custom push from my terminal and its work fine. Will test with same scenario by sending push from dashboard.

**Comment by jijopulikkottil** [comment]
hi @kkadapa , I have logged in my device with your credentials. Could you send me a notification plz ?

**Comment by kkadapa** [comment]
Hi @jijopulikkottil I made you an Admin emailed your credentials. Since I'm not aware of your TimeZone I thought It would be best if you could schedule a sample test activity notification that is convenient to you.

**Comment by jijopulikkottil** [comment]
Hi @kkadapa , I am getting notification for the participant created by me.
So to debug the issue, its better to try with the participant which you given to me.. I can login on my device with the participant given to me.. You just send a notification for the time 'current time + 5 minutes' and plz inform me when you schedule it.

**Comment by kkadapa** [comment]
Hi @jijopulikkottil  Please see below I scheduled for username: U8400982571@lamp.com. Please turn off location services and reinstall the app and sign in to reproduce the issue.

![image](https://user-images.githubusercontent.com/6679852/106162150-c75ff080-6155-11eb-87cf-7846fd6e8b92.png)

**Comment by jijopulikkottil** [comment]
I have turn off location service and reinstall app from App Store. And got a push notification now. Now the current time is 9:50 am?

**Comment by kkadapa** [comment]
I rescheduled for 11AM CST and 11:05AM CST again... Now the time here is 10:57AM CST

**Comment by kkadapa** [comment]
My apologies it's EST.... I'm currently in EST

**Comment by jijopulikkottil** [comment]
Didn't get notification at 11AM.

**Comment by kkadapa** [comment]
I logged in as a different user and I too didn't receive the 11AM Notification but just received the 11:05AM Notification

**Comment by jijopulikkottil** [comment]
for U84... please schedule again for next 5 minutes

**Comment by kkadapa** [comment]
Sure. Scheduled one for 11AM and 11:12AM and another activity for 11:15AM.. I reinstalled app turned off location services and logged in the app didn't receive the 11AM and 11:12AM ones...

**Comment by jijopulikkottil** [comment]
plz schedule again for next 5 mins

**Comment by jijopulikkottil** [comment]
I got both at 11:12 and 11:15

**Comment by kkadapa** [comment]
Sure. I just got 11:15AM Notification surprisingly Did you make any changes?
![image](https://user-images.githubusercontent.com/6679852/106166482-38090c00-615a-11eb-81b5-076abc80cb11.png)

**Comment by jijopulikkottil** [comment]
no changes done. Got 11:20 notification.. waiting for 11:25

**Comment by kkadapa** [comment]
I received the 11:20 and 11:25 as well... I opened the server console and checking the logs from 11:12AM since then the Notifications started coming... Can you reinstall the app and login again and test for one last time? This time I closed the server logs

**Comment by jijopulikkottil** [comment]
Ok, will update here after reinstall and login again (keeping the location services turned off)

**Comment by kkadapa** [comment]
Please close MindLamp App on your phone don't run the app in the background and I'm scheduling from 11:40AM till 11:55AM.

**Comment by jijopulikkottil** [comment]
"don't run the app in the background" - means , force-quit app from background ?

**Comment by kkadapa** [comment]
I too received 11:40, 11:45 and 11:50... Looks like this is an intermittent issue, I will try to reproduce again.

**Comment by jijopulikkottil** [comment]
Ok, we can continue testing to reproduce. I can test using the -admin- account which you gave me.  BTW got a notification 3 minutes ago

**Comment by kkadapa** [comment]
I just tested twice in our QA environment I didn't get Notifications but the moment when I turned on Location Services I started getting them but there is a delay by 1 min or so

![image](https://user-images.githubusercontent.com/6679852/106187262-5f200780-6173-11eb-98d2-17a540441744.png)

**Comment by kkadapa** [comment]
Hi @avaidyam I just scheduled another Notification in our QA Env for 2:14PM but instead i received at 2:15PM... Please see below..

![image](https://user-images.githubusercontent.com/6679852/106188291-c8544a80-6174-11eb-9b96-0f142086b0e3.png)

![image](https://user-images.githubusercontent.com/6679852/106188394-e8840980-6174-11eb-9916-9cc9cf79877f.png)

**Comment by jijopulikkottil** [comment]
@kkadapa the delivery time can vary few seconds sometimes.
