### ISSUE TITLE
Jewels are sometimes hidden underneath bottom bar

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#96]
> **Collaborator 1**: Some of the jewels are hidden in both the Jewels and Jewels Pro game. They are cut off at the bottom of the screen, so you can't see the number that is on the jewel. If you get the first two jewels right, the bottom white banner will disappear, but some of the jewels are still cut off (shown in one image). But in some games jewel 1 is hidden, so you can't even start the game.
> 
> **Collaborator 2**: One of our participants have noticed in the Jewels game that about half of the time they will reach a level where there will be a missing Jewel number, and thus they are unable to complete the level and would have to end that game.

**Comment by sarithapillai8** [comment]
@avaidyam 
The fix included in the PR - https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/pull/30
