### ISSUE TITLE
Notifications not being delivered at the correct time

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#97]
> **Collaborator**: notifications were set for 9 and 5 but was receiving them at 8 and 4

I believe this is a timezone issue. As part of the new Device API we should be saving not only the device token but also the local timezone; this should then be used to offset the cron schedule from GMT.

**Comment by Linoy339** [comment]
@avaidyam . We will make the device api  soon and include this.
