### ISSUE TITLE
Screen cuts off questions - you have to scroll around to see entire question

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#98]
> @kkadapa: The issue here is that the whole question is not visible, you have to touch the screen and sort of scroll around to see it all. I’m not sure someone who wasn’t familiar with the question would even realize part is obscured.
> ![image](https://user-images.githubusercontent.com/1361003/105361015-3d4ce080-5bc7-11eb-9628-134c6ee2e02c.png)
> ![image](https://user-images.githubusercontent.com/1361003/105361029-40e06780-5bc7-11eb-9707-dce4a29e46ab.png)

**Comment by kkadapa** [comment]
Just commenting to follow this issue and to also provide more context this screenshot is from iPhone SE. Hope this helps!

**Comment by kkadapa** [comment]
Hi I'm just following up to see if this is fixed?
